### ISSUE TITLE
TOC Conflict of interest statements on graduating projects

### ISSUE THREAD

**Issue by TheFoxAtWork** [cncf/toc#1007]
First, thanks to @anvega for bringing this to my attention.

Currently the [TOC process](https://github.com/cncf/toc/blob/b7ab5ab947249554def34118ac46dd626d210552/process/project_proposals.md) states:
> TOC members may not sponsor a project for which they have a clear conflict of interest (for example, originating primarily from their organization). This doesn't mean that they can't have any involvement at all - for example, contributing pull requests, or being an adopter of that project, can signal a healthy interest in and knowledge of a worthwhile project.

however this "clear conflict of interest" is highly subjective. The Security TAG has a [conflict of interest statement](https://github.com/cncf/tag-security/tree/main/assessments/guide#conflict-of-interest-statement-and-review) that defines hard and soft conflicts which has been crucial to their work in performing assessments and reviews.

Hard Conflicts | Y/N
-- | --
Reviewer is a currently a maintainer of the project |  
Reviewer is direct report of/to a current maintainer of the project |  
Reviewer is paid to work on the project |  
Reviewer has significant financial interest directly ties to the success of the project |  

Soft Conflicts | Y/N
-- | --
Reviewer belongs to the same company/organization of the project, but does not work on the project |  
Reviewer uses the project in their work |  
Reviewer has contributed to the project |  
Reviewer has a personal stake in the project (personal relationships, etc.) |  

**Does the community feel it would be worthwhile for TOC sponsors to provide COI statements if they sponsor a project to provide transparency to community members on the impartiality of the TOC reviewing projects for graduation?**

**Comment by craigbox** [comment]
"Reviewer uses the project in their work" feels like a good thing for a graduation sponsor, especially given projects that reach this stage are expected to have broad industry adoption.

**Comment by tpepper** [comment]
The current [TOC process](https://github.com/cncf/toc/blob/b7ab5ab947249554def34118ac46dd626d210552/process/project_proposals.md) doesn't have a concise section on the role/responsibility of the sponsor.  But across the text it feels their influence, and risk of bias, is much more significant in the incubation proposal phase, and there is a (small) mention of desire for non-conflicted sponsors in that phase which seems like it would benefit from the sample y/n form.  Is there a specific _graduation_ sponsor problem today?  Eg: is the TOC overwhelmed with graduation proposals and biasing to the ones they know/use unfairly leaving others without sponsors?  Or?

**Comment by tomkerkhove** [comment]
Good addition imo

**Comment by angellk** [comment]
+1 good addition to the process - former statement seemed to bias against
TOC members that could be associated with an organization but not involved
in a project

**Comment by tomkerkhove** [comment]
Another soft remark can be "Reviewer sponsors one or more maintainers"

**Comment by TheFoxAtWork** [comment]
@tomkerkhove can you clarify?  I think I know what you mean but I want to be sure, how would you define "sponsors" in regard to a TOC member and the maintainers of the project?  As a mentor, coach, something else?

**Comment by tomkerkhove** [comment]
No; a simple example is a "GitHub sponsor". I personally don't think it's a problem but it might be good to just point it out, in case

**Comment by TheFoxAtWork** [comment]
Gotcha, makes sense.  Sounds like soft conflict then?

**Comment by TheFoxAtWork** [comment]
> Is there a specific _graduation_ sponsor problem today?  Eg: is the TOC overwhelmed with graduation proposals and biasing to the ones they know/use unfairly leaving others without sponsors?  Or?


@tpepper it is not today, nor do I believe it to be an issue at this time.  We have traditionally discussed potential conflicts when deciding to sponsor and reach consensus on whether it's acceptable (to my knowledge these have been soft conflicts and are uncommon). However as more members become involved in multiple projects (as some are today) it is beneficial to document or formalize this for the community.

**Comment by tpepper** [comment]
I agree it is useful to formalize and it is a slightly strange gap the stronger listing of expectations for incubation versus graduation.  Could the COI and other sponsor role/responsibilities perhaps be pulled out into a generic section?

**Comment by tomkerkhove** [comment]
> Gotcha, makes sense.  Sounds like soft conflict then?

Agreed, it is more to inform others to take in to consideration. Actually the other way around is also good to know - Does any of the maintainers sponsor the TOC member?

**Comment by dims** [comment]
@tomkerkhove you can see the details in the TOC charter (how many seats, who elects them):
https://github.com/cncf/foundation/blob/main/charter.md#6-technical-oversight-committee-toc

Current roster list is here:
https://github.com/cncf/toc#members

(See the annotations next to each member for example, mine and Katie's say `[TOC-appointed]`

**Comment by tomkerkhove** [comment]
> No; a simple example is a "GitHub sponsor". I personally don't think it's a problem but it might be good to just point it out, in case

Thanks @dims, but as mentioned earlier by choice of words was not ideal :) Sponsor in my suggestion refers more to "GitHub Sponsors" and related efforts.

**Comment by dims** [comment]
no worries @tomkerkhove - All the TOC members have a day job for sure. I am not aware of any TOC members who receive remuneration by "GitHub Sponsors" / GoFundMe or other things like that.

I did get a t-shirt from kyverno folks when they gave it to everyone :)

**Comment by tomkerkhove** [comment]
That is actually not correct - For example, I'm one of the happy sponsors of @RichiH :)

**Comment by dims** [comment]
@tomkerkhove aha!

**Comment by anvega** [comment]
The motivation to call this out is that while we are a growing community, most of the community leadership is fairly tight-knit. 

For close to a decade, we have many moments and experiences that we've shared including organizing, traveling to, and attending conferences, coffees, lunches and dinners, giving joint talks, been colleagues, coauthored books, etc. We have gotten to know each other so well that some of us even choose to spend time with each other in our spare time. That's indeed a great thing. We care for and can vouch for others on how good they are and how hard they work. Naturally, we care and are invested in the success of all our cloud native friends. 

While I believe we are all professionals that can give another project that which we have a close relationship to its contributors an impartial due diligence review, the paramount onus in a due diligence review is that of a third-party auditor to convey reliable information to end users and the public so that they may make imperative decisions on whether to adopt a technology. For this obligation to be fulfilled, a quality due diligence must be performed in accordance with generally accepted assurance and audit standards which involves declaring  up front any ties to a project and its contributors. 

Just striving to keep things consistent for all projects.

**Comment by craigbox** [comment]
@anvega's comment helped me solidify some cognitive dissonance I have had about the CNCF for some time.

The [due diligence guidelines](https://github.com/cncf/toc/blob/main/process/due-diligence-guidelines.md) talk about the responsibility of each TOC member to validate that the project meets the defined criteria. I interpret that as meaning that the identity of the sponsor is theoretically irrelevant, as they are only one vote at the end of the day.  They don't give "a due diligence review", they assist the project in ensuring that the entire TOC can "form their own opinion". That would also imply that there's no real need to ensure neutrality.  Any TOC sponsor should be able to deliver a consistent service to a project, especially the case of a graduation.  

If the current model has an individual sponsor be responsible for validation against some _other_ set of criteria before a project is presented for the vote, then that is not what is currently documented as the [CNCF's principles](https://github.com/cncf/toc/blob/main/PRINCIPLES.md#projects-are-self-governing).  The only thing that sounds subjective is "alignment with CNCF’s role and values", and I am not aware of any case where this could be said to have regressed between incubation and an application for graduation.

I understand the relevance of only presenting a project for vote when it is reasonable that it will pass, but I do not, for example, understand why [a project](#300) which appears to [deserve recommendation to an early majority of enterprises](https://www.cncf.io/projects/#maturity-levels), and meets all the required criteria, can sit in limbo for _3 years_.  (I don't mean to derail this thread, so I recommend that any discussion about this paragraph be held elsewhere.)

**Comment by RichiH** [comment]
Good point, @tomkerkhove; I agree that this is not a level that's approaching conflict of interest, and as such should be made explicit either way.

For the avoidance of any doubt, I would happily shut down GH sponsors if it was against CNCF CoI guidance.

**Comment by tomkerkhove** [comment]
Oh I think that should not be a requirement and pointing out would be just a way of pointing it out indeed. (but who am I 🤷)

**Comment by TheFoxAtWork** [comment]
@nikhita asked about COIs for Sandbox as compared with items identified on this issue. As a matter of transparency and further information i'm providing my response here:

- The sandbox application process identifies  “Project Champions” - in the past, any TOC member that is associated with the project is usually identified as a Champion. However this is not a hard requirement and up to the applicant to express this value.
- the sandbox voting process removes any single member’s ability to dictate preference or favoritism on accepting a project
- for incubating and graduation - due to the limited number of sponsors for moving levels, COIs on incubation and graduation should be provided as a single sponsor could make assertions about the project without oversight as part of the DD process but within limits and always with an additional check (below).
- TOC members are expected to review one-another’s work for moving levels which is why we have the internal review, it assists in reducing biases regardless of what COIs are claimed.
- Ultimately voting is the final arbitration to reduce bias as a result of COI and when proceeded by the public comment period, it is anticipated sufficient reviewers have evaluated the content presented to the community for public record and informed decision making.

**Comment by TheFoxAtWork** [comment]
Providing another note on this (mulling over open issues and community feedback):

The presence of soft conflicts (one or more?) requires at least one other TOC sponsor who is not-conflicted to support the review of the project to increase impartiality in the review.
