### ISSUE TITLE
[Annual Review] notary

### ISSUE THREAD

**Issue by caniszczyk** [cncf/toc#1018]
The @cncf/cncf-toc has requested an annual review for the CNCF TOC based on the discussion in
https://github.com/cncf/toc/issues/981

Your annual review should answer the following questions:

[] Include a link to your project’s devstats page. We will be looking for signs of consistent or increasing contribution activity. Please feel free to add commentary to add colour to the numbers and graphs we will see on devstats.
[] How many maintainers do you have, and which organisations are they from? (Feel free to link to an existing MAINTAINERS file if appropriate.)
[] What do you know about adoption, and how has this changed since your last review / since you joined Sandbox? If you can list companies that are end users of your project, please do so. (Feel free to link to an existing ADOPTERS file if appropriate.)
[] How has the project performed against its goals since the last review? (We won't penalize you if your goals changed for good reasons.)
[] What are the current goals of the project? For example, are you working on major new features? Or are you concentrating on adoption or documentation?
[] How can the CNCF help you achieve your upcoming goals?
[] Do you think that your project meets the criteria for [incubation](https://github.com/cncf/toc/blob/main/process/graduation_criteria.md#incubating-stage)?

After you've submitted a pull request, please add the pull request URL and date to your project in the [landscape](https://github.com/cncf/landscape/), this is how we track annual reviews!

**Comment by amye** [comment]
Cc: @justincormack @stevelasker @niazfk @HuKeping @mnm678

**Comment by FeynmanZhou** [comment]
I am a Notary maintainer. I would like to work on this issue and prepare for the annual review with @toddysm and other Notary maintainers. We will raise a PR to this repo within a couple of weeks.

**Comment by caniszczyk** [comment]
FYI a security fuzzing audit was completed recently and should be added to the annual review report: https://www.cncf.io/blog/2023/03/21/the-notary-project-completes-fuzzing-security-audit/

**Comment by TheFoxAtWork** [comment]
@FeynmanZhou @toddysm Checking in on this, i know you all have made meaningful updates to Notary Project Org. May we expect an Annual Review PR (please leverage the sandbox Annual Review PR format for now) within the next two months?

**Comment by toddysm** [comment]
@TheFoxAtWork, apologies for missing this one. Will make sure that this is addressed ASAP.

**Comment by TheFoxAtWork** [comment]
Thank you. Please tag me when you submit so I can ensure we review it separately from sandbox

**Comment by toddysm** [comment]
We will target 10/10 to submit the PR

**Comment by FeynmanZhou** [comment]
@TheFoxAtWork We raised a PR to add the Notary Project annual review https://github.com/cncf/toc/pull/1187. PTAL when you are available. Thanks!
