### ISSUE TITLE
cannot delete upon TOC outreach

### ISSUE THREAD

**Issue by anoncam** [cncf/toc#1023]
is it dead yet. i have no desire to dance around an issue that creates confusion and unnecessary division of consensus on what is obvious: sigstore is our future. Who must be pestered to the point of a real debate to close this chapter @dlorenc 

_Originally posted by @anoncam in https://github.com/cncf/toc/issues/981#issuecomment-1382699142_

I am trying to delete this comment and one more down the page. The thread is locked and I cannot seem to delete the comment even at the request of the TOC. 

Apologies  for my anti productive discourse and you will not see the same type of unproductive content from me again.

**Comment by caniszczyk** [comment]
resolved, thanks for being responsive @anoncam
