### ISSUE TITLE
TOC Chair, 2023

### ISSUE THREAD

**Issue by amye** [cncf/toc#1026]
Now that we have a fully formed TOC, a TOC chair needs to be selected.

We will leave nominations open through next Tuesday, March 21th at noon Pacific.

Please comment here if you're interested in standing for chair.

**Comment by TheFoxAtWork** [comment]
I am interested in standing for chair

**Comment by raghu-007** [comment]
Interested!!!!

**Comment by dims** [comment]
@raghu-007 this is an selection/election internal/within the elected TOC members - https://github.com/cncf/toc/#members

**Comment by amye** [comment]
Welcome new TOC chair, @TheFoxAtWork

**Comment by alolita** [comment]
Woot! Welcome Emily!
Best,
Alolita

**Comment by onlydole** [comment]
Congratulations, @TheFoxAtWork!!! 🥳

**Comment by joshgav** [comment]
Good luck Emily!
