### ISSUE TITLE
License exception request for MPL v2.0

### ISSUE THREAD

**Issue by FeynmanZhou** [cncf/toc#1029]
Hi Team,

I am a Notary maintainer. I would like to request a license exception for MPL v2.0. Notary has a dependency [go-cose](https://github.com/veraison/go-cose) using this license. The following question list is copied from @amye 's PR: https://github.com/cncf/foundation/pull/313/files#diff-7897b3a73b083b1b230305e8772b88b5313d9ecbe8e32afe84c9b3cd9376878eR9

- What is the alternative license?
MPL v2.0

- If this is a newly created code, why can't it be under Apache-2.0?
The [go-cose](https://github.com/veraison/go-cose) project was initially forked from the upstream [mozilla-services/go-cose](http://github.com/mozilla-services/go-cose) project with MPL v2.0 license. [It was founded by Mozilla](https://github.com/veraison/go-cose#project-status) but the Veraison and Mozilla maintainers have agreed to retire it and focus on [veraison/go-cose](https://github.com/veraison/go-cose) as the active project.

- Is this an existing 3rd party open source project?
Yes. It is a 3rd party OSS project.

- How does this code integrate with or interact with, if at all, other components of CNCF?
The [go-cose](https://github.com/veraison/go-cose) project is a Golang library for the [COSE specification](https://datatracker.ietf.org/doc/rfc9052/). It is one of the dependencies in [notation-core-go](https://github.com/notaryproject/notation-core-go/blob/main/signature/cose/envelope.go) that supports the COSE signature envelop for Notation signing. 

- How will the code be maintained? Who is responsible for it?
The [go-cose](https://github.com/veraison/go-cose) project is maintained under the umbrella of [Veraison](https://github.com/veraison/docs/blob/main/project-overview.md) . Major contributors are from ARM, Mozilla, Microsoft, etc. go-cose reached the first stable release [v1.0.0](https://github.com/veraison/go-cose/releases/tag/v1.0.0) in Jan 2023 and which is a production-ready project. We have two Notary maintainers [who are also active maintainers](https://github.com/veraison/community/blob/main/OWNERS#L19-L28) in go-cose.

- How will the code be kept up to date with security patches?
The go-cose project undergoes periodic security reviews. The historical security review reports are located [here](https://github.com/veraison/go-cose/blob/main/reports). If there are any security issues detected, we will follow the [go-cose security policy](https://github.com/veraison/go-cose/security/policy) to patch the vulnerability, release an update, and publish vulnerability disclosure.

**Comment by amye** [comment]
This belongs in /foundation!
