### ISSUE TITLE
Request for Review: TAG App Delivery - WG Artifacts

### ISSUE THREAD

**Issue by joshgav** [cncf/toc#1070]
Hello TOC members :wave: 

**Background**: TAG App Delivery has been bringing together projects and individuals seeking to improve and simplify software artifact packaging, discovery and deployment as a proposed "WG Artifacts" within the TAG, starting in <https://github.com/cncf/tag-app-delivery/issues/368>. Together we've developed a charter, defined the initial work to be done, and informally started some of that work. Now we're ready to officially charter and inaugurate the group.

**Action requested**: Please provide your feedback and approval on the proposed group and its charter via this PR opened by @afflom: <https://github.com/cncf/tag-app-delivery/pull/409>.

A :+1: on that issue or in a reply there would be really helpful! Approval and merge of that PR will be the official inauguration of WG Artifacts. We'll follow that up by finalizing leadership of the group and formalizing meeting times and other logistics.

To speed your review here are direct links to the charter and appendix in the source repo for the PR (thanks again @afflom!): 
- Charter - <https://github.com/afflom/tag-app-delivery/blob/docs/add-artifacts-wg/artifacts-wg/charter/charter.md> 
- Appendix: Problem statements: <https://github.com/afflom/tag-app-delivery/blob/docs/add-artifacts-wg/artifacts-wg/charter/appendix.md>

**Comment by justincormack** [comment]
We had a working session last week, I think we are ready to go shortly.

**Comment by joshgav** [comment]
Hi everyone - following many discussions and reviews we believe we're ready to merge the new WG's charter in <https://github.com/cncf/tag-app-delivery/pull/409>.

If you'd like to review and contribute to it please do so today, we'll plan to merge tomorrow (Friday).

**Comment by joshgav** [comment]
Thank you everyone for your support! The WG has been officially chartered, see <https://github.com/cncf/tag-app-delivery/blob/main/artifacts-wg/charter/charter.md>. If you're interested in supporting our goals please join the [wg-artifacts Slack channel](https://cloud-native.slack.com/archives/C04UQDWS4M7) and future meetings.

**Comment by scottrigby** [comment]
I've been traveling and finally catching up. So excited about this. Will be diving back in. Great work, everyone! 👏
