### ISSUE TITLE
Present Harbor to TOC

### ISSUE THREAD

**Issue by clintkitson** [cncf/toc#109]
# Who, what, why?
Harbor is a enterprise-grade container registry project from VMware. The project includes a variety of important features including replication between disparate Harbor nodes, authentication via LDAP/AD, repository grouping by project with role-based access control, vulnerability scanning, audit logging, trusted content through image signing, and an HTML5 web interface. Harbor complies with the OCI Distribution Specification.

Harbor currently has a robust community with 70+ contributors from 15+ countries, 4000+ stars, 1.1k+ forks and 10k+ downloads.

GitHub: https://www.github.com/vmware/harbor
Website: http://vmware.github.io/harbor
License: Apache 2.0

# Cloud-Native & CNCF Alignment
The project's mission is to build a fully featured container registry for Kubernetes.
 
Harbor users tell us that image registries are a critical need for cloud native environments. Users include BeyondSoft, BingoCloud, Boco Inter-Telecom, Caicloud, Hydsoft, Pivotal, Rancher, Shanghai OnStar, TrendMicro, and many more.

# Donation Goals
Our primary goal of contributing Harbor to CNCF is to have the project in an environment supportive of collaboration to help grow the contributor and user communities. 

Now that the OCI Distribution specification has been finalized, the Harbor community can focus on building critical features for large-scale cloud-native deployments: clustering, lifecycle management, more robust multi-tenancy, more fine-grained RBAC functionality, storage and network quotas, etc.

We are looking forward to having a chance to discuss Harbor with the TOC.

**Comment by caniszczyk** [comment]
Thanks, if no one from the @cncf/toc has an issue, I will schedule this for June 19th

**Comment by caniszczyk** [comment]
RFC @cncf/toc

**Comment by bgrant0607** [comment]
I hear that the OCI distribution spec has NOT been finalized, that the effort basically just started.

Note the mention of "Docker" (rather than OCI) everywhere in the spec:
https://github.com/opencontainers/distribution-spec/blob/master/spec.md

**Comment by caniszczyk** [comment]
This is because the OCI just recently created the distribution spec project and ported the Docker registry API spec over, there still needs to be work before a first release is done but we expect backwards compatibility.

**Comment by caniszczyk** [comment]
scheduled for 19th
