### ISSUE TITLE
[REPO CREATION] Create wg-artifacts in cncf-tags

### ISSUE THREAD

**Issue by ncdc** [cncf/toc#1122]
### Requested name for new repository

wg-artifacts

### What should the repo description be?

Working group - Artifacts - CNCF TAG App Delivery

### What TAG/WG does this fall under?

TAG App Delivery

**Comment by nikhita** [comment]
Assigning to @justincormack and @kgamanji to approve as TAG App Delivery TOC Liaisons

**Comment by justincormack** [comment]
Approved.

**Comment by TheFoxAtWork** [comment]
@kgamanji could you review and provide your approval so this issue may be closed?  @justincormack  already provided his approval above.

**Comment by joshgav** [comment]
Hi @kgamanji, please take a look!

@TheFoxAtWork might we consider @justincormack's approval enough? Though admittedly, the [doc](https://github.com/cncf/toc/blob/main/tags/cncf-tags-github-org.md#creating-a-new-repo) implies all liaisons must approve.

**Comment by kgamanji** [comment]
Thank you all for your patience in my response. I am in favor of this initiative

**Comment by joshgav** [comment]
Thank you @kgamanji and no problem!

@nikhita would you like to create the repo?

Perhaps the process should be to set [TAG leaders](https://github.com/cncf/tag-app-delivery#leads) as admins and ask them to maintain a [CODEOWNERS file](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) delegating permissions to WG chairs and other TAG members.

**Comment by nikhita** [comment]
> @nikhita would you like to create the repo?

@joshgav please create a ServiceDesk ticket and the CNCF staff should be able to set it up for you 👍 
(this is called out in the [doc](https://github.com/cncf/toc/blob/main/tags/cncf-tags-github-org.md#creating-a-new-repo) to ensure that I'm not a blocker here)

> Perhaps the process should be to set [TAG leaders](https://github.com/cncf/tag-app-delivery#leads) as admins and ask them to maintain a [CODEOWNERS file](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) delegating permissions to WG chairs and other TAG members.

Process around access is defined here - https://github.com/cncf/toc/blob/main/tags/cncf-tags-github-org.md#access-for-each-repo

It's to be managed by `.github/settings.yaml` and can be delegated to other TAG members.

**Comment by joshgav** [comment]
I submitted a request to ServiceDesk, sorry for the delay folks!

**Comment by joshgav** [comment]
Repo has been created at <https://github.com/cncf-tags/wg-artifacts>. Thank you!

**Comment by nikhita** [comment]
Closing since the repo has been created.
