### ISSUE TITLE
Present TiKV to TOC

### ISSUE THREAD

**Issue by ceohockey60** [cncf/toc#113]
**Who, what, why?**

TiKV is an open-source distributed transactional key-value store written in Rust built by the company, PingCAP. It provides strong consistency, ACID compliance, and horizontal scalability. TiKV’s transaction model is based on Google’s Percolator model with a few optimizations, and it uses the Raft consensus protocol (with a Multi-Raft implementation) to execute data replication in order to provide High Availability. It has been deployed in production in more than 200 companies.

TiKV currently has a vibrant community with 60+ contributors from 9 countries, 3000+ stars, and almost 400 forks. It also receives institutional contribution from the following organizations:
- Samsung
- Mobike (world's biggest dockless bikesharing company; ~30 million rides per day)
- Toutiao (popular news aggregator app; 120 million DAUs)
- Ele.me (food delivery platform, 200 million users)
- Tencent Cloud (2nd largest public cloud provider in China)
- UCloud (3rd largest public cloud provider in China)

GitHub: https://github.com/pingcap/tikv
License: Apache 2.0

**Cloud-Native & CNCF Alignment**

TiKV is designed to be cloud-native since the project started two years ago, and it has already been made available for users via Kubernetes in Tencent Cloud. The PingCAP team is also working on an operator tool to more easily deploy, operate, and manage TiKV clusters via Kubernetes in any cloud environment--public, private or hybrid. 

**Donation Goals**

We conceived TiKV to be a standalone project that can serve as a building block for developers to build other systems on top of it. Contributing it to CNCF will take that vision one step closer to reality, by putting it in a neutral environment to foster more community activities, contribution, and adoption.

A stronger TiKV community supported by CNCF will accelerate its development to support more languages, more storage orientation like column family, and other useful features.

We look forward to having a chance to present and discuss TiKV with the TOC.

**Comment by caniszczyk** [comment]
Thanks, I'll wait to hear from the @cncf/toc if there are any objections but we can schedule you July 3rd or July 17th

**Comment by ceohockey60** [comment]
Sounds good! July 3rd works for us. Thanks!

**Comment by caniszczyk** [comment]
scheduled for July 3rd!
