### ISSUE TITLE
annual reviews: provide guidance for projects on what to expect during reviews

### ISSUE THREAD

**Issue by nikhita** [cncf/toc#1133]
As a part of https://github.com/cncf/toc/issues/1123, we should provide better guidance to projects on what to expect during a review. #1123 provides guidance to TAGs and the TOC but fails to provide an easy-to-consume doc for project maintainers on what timelines to expect, how the recommendation process works, what is looked at while performing a review, etc.

So as next steps:

- Gather feedback from project maintainers after annual reviews are conducted as per the process laid out in #1123 
- Evaluate feedback and update the annual review [process](https://github.com/cncf/toc/blob/main/process/sandbox-annual-review.md) to add a section for what project maintainers should expect.

**Comment by TheFoxAtWork** [comment]
Closing this issue as we've migrated away from the previous annual review process favoring automation when it is available
