### ISSUE TITLE
[REPO CREATION] Create container-device-interface in cncf-tags

### ISSUE THREAD

**Issue by elezar** [cncf/toc#1142]
### Requested name for new repository

container-device-interface

### What should the repo description be?

The Container Device Interface (CDI), is a specification, for container-runtimes, to support third-party devices. It allows device vendors to describe which entities (device nodes, mounts, environment variables, and container lifecycle hooks) are required to provided to access a device in a containerised environment. Each device in a set of CDI specification can be uniquely identified by its fully-qualified CDI device name (e.g. `vendor.com/class=device0`).

This repository contains the specification definition as well as a set of utilities for injecting CDI devices into a container as a set of modifications to a container's OCI Runtime Specification.

### What TAG/WG does this fall under?

TAG Runtime (COD WG)

### Additional context for request

Ideally we would want to transfer the existing repo from https://github.com/container-orchestrated-devices/container-device-interface from the `container-orchestrated-devices` org to the `cncf-tags` org.

Please let us know if this is not possible so that we can follow an alternative migration strategy.

Note that I have created https://github.com/container-orchestrated-devices/container-device-interface/pull/151 to add the remaining mandatory files to the repository before transfer.

**Comment by nikhita** [comment]
> Ideally we would want to transfer the existing repo from https://github.com/container-orchestrated-devices/container-device-interface from teh container-orchestrated-devices org to the cncf-tags org.

+1 to transfer existing repo vs creating a new one.

+1 with my TAG Runtime Liaison hat on.

**Comment by nikhita** [comment]
@cathyhongzhang @RichiH as TAG Runtime Liaisons, PTAL.

**Comment by cathyhongzhang** [comment]
+1

**Comment by nikhita** [comment]
@TheFoxAtWork given that @RichiH is on vacation, wdyt about updating the repo creation docs to require a majority approval from liaisons if the number of liaisons for a TAG is greater than 2?

Having 3 liaisons will make it harder to align across vacation schedules.

**Comment by TheFoxAtWork** [comment]
2 is fine when there is 3 IMO.

**Comment by nikhita** [comment]
> 2 is fine when there is 3 IMO.

created #1149 

@helayoty can you also approve as TAG Runtime chair?

**Comment by nikhita** [comment]
We have all required approvals now 🎉 

@helayoty as next steps, can you please create a service desk ticket to migrate the CDI repo to cncf-tags?

**Comment by kad** [comment]
Question, can infra team do repository move from old org under cncf-tags/ ? We would like to save issues/PRs tracking in that repo.

**Comment by nikhita** [comment]
> Question, can infra team do repository move from old org under cncf-tags/ ? We would like to save issues/PRs tracking in that repo.

@RobertKielty can we please ensure that we do a migration instead of creating a new repo?

**Comment by krook** [comment]
This is being tracked in the [CNCF Service Desk here](https://cncfservicedesk.atlassian.net/jira/servicedesk/projects/CNCFSD/queues/custom/22/CNCFSD-1913).

@RobertKielty is out of the office, but I have admin on the `cncf-tags` org, but in order to migrate the repo I'd also need rights to move it from `container-orchestrated-devices` to preserve the history.

**Comment by elezar** [comment]
@krook let me check if I can give you the required rights. @kad any objections?

**Comment by elezar** [comment]
@krook I have dropped you an invite.

**Comment by RobertKielty** [comment]
Hi @krook, @jeefy can assist with you with cncf-tag org access, I'm back Monday and will finish out CLOWarden deployment which we use for access control atop GitHub.

**Comment by helayoty** [comment]
The repository is transferred with history and issues. Many thanks @krook

**Comment by elezar** [comment]
Thanks all. 

One thing we've noted is that the devs no longer have merge permissions on this repository. What steps should be taken to address this?

Thanks @kad for calling this out.

**Comment by kad** [comment]
... or actually, if we get prow working automatically, we need way to setup approvers/reviewers, as well we need some pointer on HOWTO docs about making tags/releases in the repo.

**Comment by RobertKielty** [comment]
I'll set that up later today!

**Comment by elezar** [comment]
> @elezar @kad When I moved the repo I also created a new team that has the same Admin access as the corresponding team in the old organization. @kad your invite seems to still be pending your acceptance to this new team.

@krook where did you create the team you mention? I didn't get any specific invites and don't see any teams mentioned in the `cncf-tags` repo.

**Comment by krook** [comment]
@elezar The team created is called _COD Resource Management_ in the `cncf-tags` org. 

It mirrors the _Resource Management_ team in the `container-orchestrated-devices` org and it was created the same 6 Admin members (`egernst`, `zvonkok`, `marquiz`, `klihub`, `crosbymichael`, `kad`). 

You were not originally in the original team, but you had admin access in the old org as an Owner, so I added you as a member in the new team now.

There are 2 other Owners of the `container-orchestrated-devices` org that aren't in this new repo-scoped team, `klueska` and `mikebrow`. Now that you have Admin access to the repo, you can go ahead and add them if they need access.

**Comment by elezar** [comment]
Thanks @krook! I got the invite and will work with @kad to manage access to the repo.

**Comment by elezar** [comment]
> I'll set that up later today!

Hi @RobertKielty please let me know if there is anything that I need to do once this is set up.

Also dow we create a separate issue for something like prow integration?

**Comment by krook** [comment]
@elezar @RobertKielty Now that the repo is created, which was the scope of this issue, let's handle any customizations or refinements as [CNCF Service Desk](https://servicedesk.cncf.io/) tickets.

**Comment by nikhita** [comment]
> Now that the repo is created, which was the scope of this issue, let's handle any customizations or refinements as [CNCF Service Desk](https://servicedesk.cncf.io/) tickets.

Closing this issue. Thanks, @krook and @RobertKielty!
