### ISSUE TITLE
Add new "beginners" channel to CNCF Slack

### ISSUE THREAD

**Issue by Cali0707** [cncf/toc#1146]
## Background
There are currently a lot of questions about how to get started contributing, how to learn more about devops, how to do Y in Z, etc. in many channels such as [#random](https://cloud-native.slack.com/messages/random), [#hallway](https://cloud-native.slack.com/messages/hallway), and [#mentoring](https://cloud-native.slack.com/messages/mentoring). While there are currently people answering these questions in the channels I've mentioned, it shows that there isn't a good place for beginners/newcomers to go and ask all their questions. 

For more background, see the slack discussion [here](https://cloud-native.slack.com/archives/CT6CWS1JN/p1692113266748519)

## Proposal
We should add a #beginners channel to the CNCF slack and make it one of the default channels which everyone is added. This channel would be the default place to ask questions like "how can I get started contributing". It will also be a good place where we can direct people to other channels. For example, if someone asks about how to contribute a Knative feature, we can direct them to the [#knative-contributors](https://cloud-native.slack.com/messages/knative-contributors) channel, and if someone wants to learn more about ArgoCD we can direct them to [#argo-cd](https://cloud-native.slack.com/messages/argo-cd).

**Comment by aliok** [comment]
IMO this is a good idea.

#random is, well, random. 
#hallway is similar.

We receive lots of beginner questions in #mentoring, but they're mostly about contributing.

A good example I've recently seen as a #beginner channel is on CHAOSS Slack: [#newcomers](https://chaoss-workspace.slack.com/archives/C0207C3RETX), where people introduce themselves.

**Comment by nikhita** [comment]
+1

@amye what's the process for approving a new slack channel in the CNCF slack?

**Comment by aliok** [comment]
@nikhita Creating a new channel is easy. I can do it (not sure if I have special permissions).

What's proposed here is to make the new channel one of the default channels which everyone is added when they join. That would need some Slack admin permissions.

**Comment by amye** [comment]
So this should probably be over in /foundation as it's a bit broader than TOC, but we're evaluating this. 
We're looking into better automation that would make a channel like this useful. However, we're familiar with other channels that end up being less than welcoming. 
@krook for awareness.

**Comment by amye** [comment]
#651 in /foundation is the right place for this!
