### ISSUE TITLE
Vote for TAG App Delivery Chairs

### ISSUE THREAD

**Issue by amye** [cncf/toc#1151]
Nominations have closed for [TAG App Delivery Chairs](https://github.com/cncf/tag-app-delivery/issues/407), three candidates for co-chair are proposed:

The nominees are:
@AloisReitbauer - https://github.com/cncf/tag-app-delivery/issues/407#issuecomment-1677792217
@joshgav - https://github.com/cncf/tag-app-delivery/issues/407#issuecomment-1568847460
@thschue - https://github.com/cncf/tag-app-delivery/issues/407#issuecomment-1579279849

**Comment by amye** [comment]
Love the pending! Pings will go out tomorrow at 8am Pacific, no need to bug any of the pending votes. 
I will bug them for you.

**Comment by amye** [comment]
Huh. *kicks tires* Will try it again.

**Comment by amye** [comment]
Huh. @tegioz, something's gone awry here.

**Comment by tegioz** [comment]
Hi @amye! Everything looks good to me, what's the issue?

**Comment by tegioz** [comment]
If you were referring to the auto-close feature, please see https://github.com/cncf/gitvote/issues/335#issuecomment-1623606147.
