### ISSUE TITLE
Request for vanity URL to be used as the module prefix of go repos in the `cncf-tags` GitHub organization

### ISSUE THREAD

**Issue by tariq1890** [cncf/toc#1152]
Currently, we have custom module prefixes to represent go modules of repos in the kubernetes and kubernetes-sigs organization

i) k8s.io in [kubernetes](https://github.com/kubernetes) - 

- [k8s.io/kubernetes](https://github.com/kubernetes/kubernetes/blob/fb785f1f42183e26e2b9f042474391c4d58433bb/go.mod#L7C5-L7C5)

ii) sigs.k8s.io for [kubernetes-sigs](https://github.com/kubernetes-sigs)

- [sigs.k8s.io/kueue](https://github.com/kubernetes-sigs/kueue/blob/7e64317fd64edf726201b7408d48a863d15baf51/go.mod#L1)

I'd like to discuss if a similar convention for the [cncf-tags](https://github.com/cncf-tags) GH org makes sense. In this case:

The vanity URL would be `tags.cncf.io` and the module of the [container-device-interface](https://github.com/cncf-tags/container-device-interface) would be renamed to `tags.cncf.io/container-device-interface`

**Comment by nikhita** [comment]
+1, this would help with an easy way to `go get` and redirect to the repo.

cc @jeefy @RobertKielty

**Comment by elezar** [comment]
As a matter of interest, what would be required to move this along? I would like to hold off on renaming the CDI modules until this is done.

**Comment by jeefy** [comment]
Worked with @RobertKielty to come up with our punchdown list to move this forward. :) 

- [ ] Create `subdomain redirect` repo under `cncf`
- [ ] Update repo definition in CLOWarden (use `cncf-automation` team + populate)
- [ ] Populate with Dockerfile + nginx config (and all the usual suspect files)
- [ ] Spin up Cloud Run + Cloud Build instance pointing at repo (to auto-build/deploy) on merge
- [ ] Capture IP address of Cloud Run instance
- [ ] Point `tags.cncf.io` at Cloud Run IP

**Comment by RobertKielty** [comment]
I'm working on Dockerfile/nginx config atm
cc @jeefy

**Comment by RobertKielty** [comment]
Initial deployment of subdomain-redirector has been deployed to Cloud Run. 

@jeefy will do the needful on the last two steps on above checklist for domain/IP config.

Then we will do some acceptance testing and report back.

**Comment by RobertKielty** [comment]
@jeefy and I met with LF IT for domain management support on this yesterday.  Thank you Rudy from LF IT! ❤️ 

Once those changes were made and we merged a last config change we have the following redirects in place:

[https://tags.cncf.io/](https://tags.cncf.io/) will redirect to  https://github.com/cncf-tags/

Once they are published calls like `go install tags.cncf.io/wg-artifacts` will compile and install packages from  
https://github.com/cncf-tags/wg-artifacts 

**Implementation Notes**
The http server doing the redirects is defined here

https://github.com/cncf/subdomain-redirector

any new subdomain redirects can be added by submitting PRs to the the nginx confg file.

https://github.com/cncf/subdomain-redirector/blob/main/etc/nginx/default.conf

Deployment will be managed and supported by the CNCF Projects Team.

**Comment by RobertKielty** [comment]
@nikhita @tariq1890 please take a look when you get a chance.

If this is everything that you need for now we can close this off.

**Comment by elezar** [comment]
We have successfully converted our go module to `tags.cncf.io/container-device-interface`, so I think this could be closed off.

@tariq1890 did you have anything else in mind here?

**Comment by RobertKielty** [comment]
Thank you @elezar I'll close this off for now. If you need anything else, reopen this or log a new issue.

**Comment by tariq1890** [comment]
@elezar Nothing else. Thanks!
