### ISSUE TITLE
[REPO CREATION] Create green-reviews-tooling in cncf-tags

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/toc#1160]
### Requested name for new repository

green-reviews-tooling

### What should the repo description be?

Project Repository for the WG Green Reviews which is part of the CNCF TAG Environmental Sustainability

### What TAG/WG does this fall under?

WG Green Reviews

### Additional context for request

The TAG Environmental Sustainability recently launched the [WG Green Reviews](https://github.com/cncf/tag-env-sustainability/tree/main/working-groups/green-reviews) which aims to establish sustainability footprint reports for CNCF projects. To do so, we need to build some minimal tooling which we would like to source in the new dedicated cncf-tags org. Ref related issues https://github.com/cncf/tag-env-sustainability/issues/184 & https://github.com/cncf/tag-env-sustainability/issues/182 - 

cc @nikhita (AFAIK one of the owners of [cncf-tags](github.com/cncf-tags) org)

cc @guidemetothemoon @nikimanoledaki (wg green reviews)
cc @catblade @mkorbi (tag env)
cc @TheFoxAtWork @erinaboyd @mattfarina (tag env toc liaisons)

**Comment by TheFoxAtWork** [comment]
LGTM

**Comment by nikhita** [comment]
Not a TOC Liaison for TAG Env, but +1

**Comment by erinaboyd** [comment]
LGTM
