### ISSUE TITLE
[REPO CREATION] Create tag-env-tooling in cncf-tags

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/toc#1184]
### Requested name for new repository

tag-env-tooling

### What should the repo description be?

CNCF TAG Environmental Sustainability Tooling

### What TAG/WG does this fall under?

TAG Environmental Sustainability

### Additional context for request

We would like to create a new repository as part of TAG ENV which can be the home of smaller technical projects.

* **Scope**: tag-env-tooling would be the home for smaller projects or POCs that we would like to try out. This should reduce repository clutter and ease starting smaller projects without moving through a big process each time. If another bigger project may arise (similar to WG Green Reviews) we will push it to a new repository (like [green-reviews-tooling](https://github.com/cncf-tags/green-reviews-tooling)).
* **Background**: @Al-HusseinHameedJasim wrote a small script some time ago (see [repo](https://github.com/Al-HusseinHameedJasim/green-talks-scraper)) to scrape talks on environmental sustainability from conference websites (such as sched). We plan to post this information on our [events page website](https://tag-env-sustainability.cncf.io/events/) to make it easier to discover and browse talks & events.
@guidemetothemoon created this issue https://github.com/cncf/tag-env-sustainability/issues/214 to formulize the idea. @wrkode has also been working on a small program for this purpose, which can be found [here](https://github.com/wrkode/greenscraper). We would like to merge both approaches in a small project under the umbrella of cncf-tags GitHub org. Since this project is relatively small (for now) and there's a good chance that other similar small projects will pop up in the (near) future, a more general repo called "TAG ENV tooling" that captures this would be the approach suggested here.
* **Discussions**: We have been talking about creating this repo on the last [TAG ENV call (Oct.4 2023)](https://youtu.be/2SJaH2KsDIA) & on Slack tag-env-sustainability
* **Auth**: TAG ENV Leads would be the owner of the repo.

cc @guidemetothemoon @wrkode @Al-HusseinHameedJasim
cc @catblade @mkorbi (TAG ENV)
cc @TheFoxAtWork @erinaboyd @mattfarina (TAG ENV TOC liaisons)

**Comment by TheFoxAtWork** [comment]
Approved. I would love to see tests for projects here in the future as green reviews explores project evaluation of emissions.

**Comment by krook** [comment]
> Approved. I would love to see tests for projects here in the future as green reviews explores project evaluation of emissions.

@TheFoxAtWork do we need a second TAG liaison to add their +1 before we move ahead?

**Comment by TheFoxAtWork** [comment]
Correct.  Needs another liaison to approve

**Comment by erinaboyd** [comment]
lgtm

**Comment by krook** [comment]
Great, looks like we're good to go. I'll work with @RobertKielty on getting the repo created. Thank you all.

**Comment by mattfarina** [comment]
Approved.

**Comment by RobertKielty** [comment]
CLOWarden created the [tag-env-tooling repo](https://github.com/cncf-tags/tag-env-tooling) as part of the [CLOWarden cncf-tags deployment](https://github.com/cncf-tags/org-admin/pull/5)

The  [tag-env-leads team](https://github.com/cncf-tags/org-admin/blob/237ee29223e22b91ecb16618d544e51b57f7c0f3/access-control.yaml#L31C1-L39C15)  have admin privileges.

That team looks like
```
teams:
  - name: tag-env-leads
    displayName: CNCF TAG Environmental Sustainability Chairs and Tech Leads
    maintainers:
      - leonardpahlke
    members:
      - caradelia
      - catblade
      - mkorbi
 ```
Audit log here https://clowarden.io/audit/?organization=cncf-tags&page=1

If you need to grant other people access to the repo, visit  https://github.com/cncf-tags/org-admin

and submit a PR to change

https://github.com/cncf-tags/org-admin/blob/main/access-control.yaml

**Comment by leonardpahlke** [comment]
Thanks Rob🙏
