### ISSUE TITLE
[REPO CREATION] Create higher-ed in cncf-tags

### ISSUE THREAD

**Issue by castrojo** [cncf/toc#1186]
### Requested name for new repository

higher-ed

### What should the repo description be?

Higher Ed Initiative (Cloud Native Curriculum)

### What TAG/WG does this fall under?

Contributor Strategy?

### Additional context for request

This is a working group. Notes: https://docs.google.com/document/d/1zdHZ9E9Up3_2Z38G-xv_CM-lJjwTagfI0qQAb7Qy1uc/edit#heading=h.d1ot8vdv33ht

**Comment by TheFoxAtWork** [comment]
Approved. @dzolotusky ?

**Comment by dzolotusky** [comment]
Yeah, definitely approved by me.

**Comment by krook** [comment]
That's two TOC approvals 🎉 

@castrojo anything else needed before this can be closed as completed?

**Comment by castrojo** [comment]
This one is done, thanks!
