### ISSUE TITLE
Unable to add selection of events from CNCF calendar

### ISSUE THREAD

**Issue by aliok** [cncf/toc#1222]
[CNCF meeting calendar](https://tockify.com/cncf.public.events/monthly) is good:
- Public and transparent
- Central location

I can add the CNCF meeting calendar to my own calendar; this is also nice.

However it is not possible to add a selection of events. When I add the whole calendar, my calendar will be flooded.

To overcome this problem, I create copies of a selection of events in my own calendar. 
This creates additional issues where my events get out of sync.

I find this important to reduce the cognitive load of maintainers / community members / TAG members / WG members.

Note: Let me know if there's a better place to have this issue.

**Comment by aliok** [comment]
We were discussing this issue in a TAG Contributor Strategy meeting. Although, I am not sure about the technical feasibility, what would be super nice is if we can have these:
- Calendar events tied to a mailing list
- Mailing lists send invites to new members

This is what we usually do in a Google calendar and Google groups setup in various other places. We invite the Google group as a whole in the calendar event. When someone new joins to the group, they get an invite automatically.

I see that CNCF mailing lists use https://groups.io.

There are some features listed, but I can't see this kind of feature there: https://groups.io/static/features


An alternative idea might be creating subgroups of calendars. For example, I can subscribe to a TAG Contributor Strategy calendar personally, and the events under this one could be still shown in the broader calendar.

**Comment by Riaankl** [comment]
I like the auto-meeting invitations proposal. (I think the K8s community is using it.)

**Comment by aliok** [comment]
I don't have the permissions to transfer this issue to /foundation, so I will create a new ticket there and close this one.

**Comment by aliok** [comment]
/foundation issue: https://github.com/cncf/foundation/issues/693
