### ISSUE TITLE
[SANDBOX PROJECT ONBOARDING] KubeStellar

### ISSUE THREAD

**Issue by Cmierly** [cncf/toc#1227]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project.
We would like to complete onboarding within one month of acceptance.

From the project side, please ensure that you:

- [x] Understand the project proposal process and reqs: <https://github.com/cncf/toc/blob/main/process/project_proposals.md#introduction>
- [x] Understand the services available for your project at CNCF <https://www.cncf.io/services-for-projects/>
- [x] Ensure your project meets the CNCF IP Policy: <https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy>
- [x] Review the online programs guidelines: <https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md>
- [x] Understand the trademark guidelines: <https://www.linuxfoundation.org/en/trademark-usage/>
- [x] Understand the license allowlist: <https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist>
- [x] Is your project working on written, open governance? see <https://contribute.cncf.io/maintainers/governance/>
- [x] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? (see <https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another> for more details)
- [x] Is your project in its own separate neutral github organization?
- [x] Submitted a Pull request to add your project as a sandbox project to <https://landscape.cncf.io>
- [x] Create maintainer list + add to aggregated <https://maintainers.cncf.io> list by submitting a PR to it
- [x] Artwork: Submit a pull request to <https://github.com/cncf/artwork> with your artwork
- [x] Domain: transfer domain to the CNCF - <https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63>

Things that CNCF will need from the project:

- [x] Provide emails for the maintainers added to <https://maintainers.cncf.io> in order to get access to the maintainers mailing list and ServiceDesk - <project-onboarding@cncf.io> is the best email to send those to
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF - <https://github.com/cncf/foundation/tree/master/agreements> has agreements
- [x] GitHub: ensure `thelinuxfoundation`, `caniszczyk`, and `krook` are added as initial org owners, this helps us make sure we have continuity of GH ownership that we will onboard to our GitHub Enterprise instance: <https://github.com/enterprises/cncf>
- [x] GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [x] GitHub: ensure that that the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines to the README file of your project on GitHub).
- [x] Website: Analytics transferred to <projects@cncf.io>
- [x] OpenSSF Best Practices Badge: Start on an OpenSSF Best Practices Badge <https://bestpractices.coreinfrastructure.org/en>

Things that the CNCF will do or help the project to do:

- [x] Devstats: add to devstats <https://devstats.cncf.io/>
- [x] Insights: add to LFX Insights <https://insights.v3.lfx.linuxfoundation.org/>
- [x] Marketing: update relevant intro + slide decks
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read <https://www.cncf.io/services-for-projects/>
- [x] CNCF Welcome Email Sent to confirm maintainer list access
- [ ] Book time with the team with <http://project-meetings.cncf.io>
- [ ] Create space for meetings/events on <https://community.cncf.io>, e.g., <https://community.cncf.io/pravega-community/> - (<https://github.com/cncf/communitygroups/blob/main/README.md#cncf-projects>)
- [x] Adopt a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/)

**Comment by lukaszgryglicki** [comment]
DevStats [page](https://kubestellar.devstats.cncf.io) added - affiliations will be researched in January.

**Comment by lukaszgryglicki** [comment]
The project was added to [projects health](https://all.devstats.cncf.io/d/53/projects-health-table?orgId=1) dashboard.

**Comment by clubanderson** [comment]
@Cmierly would you please check off all items in the "From the project side, please ensure that you:" section (except for transferring the domain name) so that I can keep track of where I left off?  Thank you.

**Comment by clubanderson** [comment]
remaining items as of today:

From the project side, 
- [ ] Domain: transfer domain to the CNCF - https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63

Things that CNCF will need from the project:
- [ ] Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
- [ ] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines to the README file of your project on GitHub).
- [ ] Website: Analytics transferred to [projects@cncf.io](mailto:projects@cncf.io)

@lukaszgryglicki is there a page with instructions on how to transfer google analytics to [projects@cncf.io](mailto:projects@cncf.io)

**Comment by clubanderson** [comment]
@lukaszgryglicki I just opened domain transfer https://jira.linuxfoundation.org/plugins/servlet/desk/portal/2/IT-26345

**Comment by clubanderson** [comment]
opened issue with godaddy (original hosting service for kubestellar.io) to make sure files for web hosting will still work once domain is transferred.  Domain transfer is on hold for now.

**Comment by clubanderson** [comment]
@Cmierly can you advise on how to transfer google analytics to projects@cncf.io?

**Comment by clubanderson** [comment]
@amye @Cmierly - I have sent over the assignment of trademarks agreement.  Please sign and send back so that we can sign.  Sent it to project-onboarding@cncf.io

**Comment by clubanderson** [comment]
Domain Transfer is now complete.

Assignment of trademark is in process. Document signatures are pending. 

I need assistance with transferring google analytics to complete the onboarding process. Thank you

**Comment by amye** [comment]
> Domain Transfer is now complete.
> 
> Assignment of trademark is in process. Document signatures are pending.
> 
> I need assistance with transferring google analytics to complete the onboarding process. Thank you

You should be able to invite projects@ as an owner? Let me know if you have trouble.

**Comment by clubanderson** [comment]
@amye I added projects@ as administrator - no option to invite as owner.  I hope this is sufficient.

**Comment by amye** [comment]
> @amye I added projects@ as administrator - no option to invite as owner. I hope this is sufficient.

Oh interesting, we should be able to accept from there.

**Comment by amye** [comment]
Confirmed! Domain and trademarks look to be the last things!

**Comment by clubanderson** [comment]
Domain transfer was confirmed by Jonathan earlier this evening.

**Comment by clubanderson** [comment]
no problem - please proceed

**Comment by clubanderson** [comment]
@amye trademarks are transferred and FOSSA was integrated can you please check both of these off?

**Comment by krook** [comment]
The LFX Insights onboarding task is now marked complete on the CNCF side.

Once the initial data load finishes, I'll share a link to your project-specific dashboard where you can explore dashboards and reports. It should be ready for you by the end of the week.

**Comment by clubanderson** [comment]
thank you

**Comment by Cmierly** [comment]
@clubanderson 
There are two tasks left to finish up onboarding! Let me know once you complete them and we can finish up your onboarding.

**Comment by Cmierly** [comment]
KubeStellar has completed onboarding!
