### ISSUE TITLE
Guidance on Adding a Working Group Chair or Technical Lead

### ISSUE THREAD

**Issue by devigned** [cncf/toc#1237]
What is the standard operating procedure for adding a chair or a technical lead to a working group? [TAG elections are pretty clear](https://github.com/cncf/toc/blob/main/tags/README.md#elections), but not so clear for a Working Group within a TAG.

/cc @raravena80

**Comment by amye** [comment]
Typically, TOC liaisons give a quick approval for that as it comes up. That's probably why it's not documented super well.
@Riaankl - we should add this to the list of what we need to write down.

**Comment by Riaankl** [comment]
Yes, this is a point that need improvement. Some working groups have leads and tech leads, some just have a facilitator. 
I am currently working on clarifying TAG docs, but have a TODO list building up for WGs. I will add this to the list.

**Comment by endocrimes** [comment]
Cool! - So I guess for now @devigned and I should bring things up to @nikhita / @cathyhongzhang / @RichiH for approval going by https://github.com/cncf/tag-runtime/#toc-liaisons?

**Comment by Riaankl** [comment]
Yes, working through the liaisons for a +1 is how it is handle for now.

**Comment by endocrimes** [comment]
Perfect thank you!

**Comment by leonardpahlke** [comment]
(just passing by) In the TAG ENV we have a governance document to describe this process. https://github.com/cncf/tag-env-sustainability/blob/main/governance/lead-proposal-process.md#tag-chair-and-tl-election-process There is a PR open to add a version of this as a template to the toc/tags repo. See https://github.com/cncf/toc/pull/1195/
