### ISSUE TITLE
Project proposal review cadence

### ISSUE THREAD

**Issue by FeynmanZhou** [cncf/toc#1247]
Hi team,

From the [Project Proposal Process](https://github.com/cncf/toc/blob/main/process/README.md#sandbox-projects), it states that the proposal review cadence is every two months.

> To apply for inclusion into the Sandbox, projects should use apply at [sandbox.cncf.io](https://sandbox.cncf.io/). The TOC will review on a rotating basis, currently every two months as of June 2020.

We are preparing for a new project proposal submission. Is this review cadence still valid in 2024? Will the 3rd Tuesday of Feb be the next review meeting for Sandbox project proposal?

Thanks

**Comment by amye** [comment]
Next sandbox review is January 23rd, following will be April 9th. Sandbox.cncf.io has the dates listed on their project board.
