### ISSUE TITLE
[ARCHIVE] Krator

### ISSUE THREAD

**Issue by amye** [cncf/toc#1252]
- [x] TOC vote to archive passed
- [x] Move logo to archived on CNCF.io	
- [x] Remove from landscape		
- [x] Archive maintainers mailing list	
- [x] Remove ML from maintainers@ mailing group
- [x] Remove/Archive on maintainers.cncf.io (https://github.com/cncf/foundation/pull/825)
- [x] Remove logo from all slide decks	
- [x] Remove logo from event sites	
- [x] Move logo to archived in artwork (https://github.com/cncf/artwork/pull/484)
- [x] Archive DevStats (or archive?)	
- [x] Notify Speakers team to remove from CFPs	
- [x] Remove from service desk or archive	
- [x] Remove from CNCF store
- [x] Remove from [CLOMonitor data](https://raw.githubusercontent.com/cncf/clomonitor/main/data/cncf.yaml)

**Comment by angellk** [comment]
@jeefy @Cmierly has this been completed?

**Comment by mrbobbytables** [comment]
All tasks have been completed, going to go ahead and close this out :+1:
