### ISSUE TITLE
Create a TAG health check dashboard

### ISSUE THREAD

**Issue by jberkus** [cncf/toc#1255]
Starting a discussion from the Feb 6 TOC meeting.  Several TOC members suggested that we should have TAG metrics the same as we have them for projects.  This discussion is to resolve what metrics we would track, and how we would track them.

**Comment by linsun** [comment]
Was this closed by accident @jberkus ?

**Comment by krook** [comment]
@linsun the conversation [moved over to a discussion](https://github.com/cncf/toc/discussions/1256) rather than an issue.

**Comment by linsun** [comment]
Thanks for the linkage @krook!!
