### ISSUE TITLE
Present Rook graduation to Incubating stage to the TOC

### ISSUE THREAD

**Issue by jbw976** [cncf/toc#126]
The maintainers of the [Rook project](https://github.com/rook) would like to present to the TOC about graduation from Sandbox to Incubating stage.  Rook was initially accepted as a CNCF hosted project on [2018-01-29](https://www.cncf.io/blog/2018/01/29/cncf-host-rook-project-cloud-native-storage-capabilities/).

Since being accepted, Rook has continued to grow in accordance with the [Incubating stage graduation criteria](https://github.com/cncf/toc/blob/master/process/graduation_criteria.adoc#incubating-stage) in terms of size and quality of production deployments, number of contributors to the project and frequency of commits.

Does August 7th work with the TOC schedule? A full proposal and presentation will be put together in the coming weeks.

**Comment by caniszczyk** [comment]
@jbw976 August 7th seems fair. Can you also do a PR against the toc/reviews, i.e., https://github.com/cncf/toc/blob/master/reviews/incubation-coredns.md

**Comment by jbw976** [comment]
Yes @caniszczyk, we'll put a PR together for a toc/reviews entry.

**Comment by caniszczyk** [comment]
@jbw976 any idea when you plan to do this?

**Comment by jbw976** [comment]
my apologies @caniszczyk, I had made the assumption that a PR there needed to be opened just before the August 7th presentation.  I can put together something before the end of next week, the long pole is reaching out and syncing up with our production users. Does that sound good?

**Comment by jbw976** [comment]
PR #139 has been opened for the review, I am planning on presenting to the TOC on August 21st.

**Comment by caniszczyk** [comment]
This was presented to the TOC already and being voted upon, closing the backlog

**Comment by caniszczyk** [comment]
https://blog.rook.io/rook-moves-into-the-cncf-incubator-d25197a6bb14
