### ISSUE TITLE
TOC Chair + Vice Chair, 2024

### ISSUE THREAD

**Issue by amye** [cncf/toc#1261]
Now that we have a fully formed TOC, a TOC chair needs to be selected.
New this year: TOC has decided to experiment with a Vice Chair role to help distribute responsibilities. 

We will leave nominations open through next Friday, March 1st at noon Pacific.

Please comment here if you're interested in standing for chair or vice chair.

**Comment by TheFoxAtWork** [comment]
If the TOC is willing to continue to have me to serve in role, I will stand.  Alternatively, I am happy to support another TOC member in the Chairperson duties by serving as Vice Chair.

**Comment by kgamanji** [comment]
I am interested in standing for the Vice Chair role

**Comment by dzolotusky** [comment]
So, are we nominating here or only commenting here if interested in standing for chair or vice chair?
I want to nominate dims for either role.

**Comment by nikhita** [comment]
I'd like to run for the role of Vice Chair.

I have been working on refactoring the TOC repo, setting up the Annual Review Process for sandbox projects, improving the outreach for TAGs (TAG Runtime in particular), shepherding the process around TAG contributor recognition.

If selected as a Vice Chair, I would love to partner with the Chair and the TOC to work on:
* making the TOC meetings more efficient 
* make the TOC repo more accessible 
* ensure we have transparent processes
* the TOC project boards are upto date
* ensure that the moving levels process is seamless
* improve engagement between TAGs and the TOC, along with building a process to increase more contributors in TAGs
* improve engagement between projects and TAGs/TOC
* improve the processes to have sustainable governance in CNCF projects

**Comment by amye** [comment]
Vice chair election is now open! Election will close at noon pacific on Thursday, March 7th.

**Comment by amye** [comment]
Election is closed, Nikhita Raghunath is Vicechair for TOC!
