### ISSUE TITLE
Moving levels criteria are now hard to find

### ISSUE THREAD

**Issue by craigbox** [cncf/toc#1266]
#1263 moved the source of truth for criteria for moving levels into GitHub issue templates.  

A number of documents, in this repo and outside, refer to documents like [graduation_criteria.md](https://github.com/cncf/toc/blob/main/process/graduation_criteria.md) which have been removed.

Could we please ensure the criteria remain documented separately from the checklists, and that redirects from important URLs exist?

**Comment by kevin-wangzefeng** [comment]
Thanks for catching this, I'm going to fix it.
/assign

**Comment by craigbox** [comment]
I didn't mean just the one file - there are a few others that were removed that were well linked.
You might be able to commit a symlink to the old location if you want to redirect people to a new path.

What I had hoped was that the guidelines would clearly be written down somewhere, and the templates would just be a checklist that reflects them.  It is a bit strange that you can't see them without actually starting the application process.  

(Even better would be that the checklist is annotated with context regarding the what/why/how it will be measured, for each guideline).

**Comment by kevin-wangzefeng** [comment]
We can always iterate as needed.
Let me think about how we can improve it, maybe adding some indexes as well. I will try to avoid making it a document for document :-)
