### ISSUE TITLE
Update TOC TAG Liaisons for current TOC

### ISSUE THREAD

**Issue by angellk** [cncf/toc#1273]
Please update the TOC TAG Liaisons for the current TOC

> TOC Liaisons - updated as of 4/11/2023

[tags/cncf-tags.md](https://github.com/cncf/toc/blob/main/tags/cncf-tags.md)

**Comment by Riaankl** [comment]
Fixed by https://github.com/cncf/toc/pull/1282 & https://github.com/cncf/toc/pull/1286
