### ISSUE TITLE
DTR Working Group Proposal

### ISSUE THREAD

**Issue by angellk** [cncf/toc#1277]
I would like to help lead the new cross-TAG Domain Technical Reviews Working Group per the KubeCon EU TOC/TAG session, March 20. Thank you to @TheFoxAtWork for the notes on DTRs.

Note: This is intended to be a long term working group.

### Why a Domain Technical Review?

The primary objectives of a Domain Technical Review (DTR) are to ensure the overall quality and robustness of the project, identify any potential weaknesses or areas for improvement, and provide **actionable** feedback to the project maintainers. This process helps maintain the high standards of excellence associated with CNCF projects and fosters innovation and collaboration within the cloud native ecosystem.

### Who is involved in a Domain Technical Review
A Domain Technical Review (DTR) is a collaboration between a project, one or more CNCF Technical Advisory Groups (TAGs) and the CNCF Technical Oversight Committee (TOC).

The DTR Working Group should have a representative from each TAG to inform the DTR guidelines - as well as CNCF TOC represention.

### What is a Domain Technical Review

A Domain Technical Review is an engagement by the project and the TAG(s) to fully explore the project in the context of cloud native and the specific domain(s). The Domain Technical Review is to be a comprehensive assessment of a project aimed at evaluating, within the CNCF ecosystem:

- The domain specific technical merits of the project
- Cloud native design principles
- Adherence to domain specific best practices

### What are the goals the DTR Working Group

- Provide well structured guidance for the DTR that provides consistency across the TAGs
- Identify the domain specific best practices that inform the DTRs - in collaboration with the CNCF TAG(s) and CNCF TOC
- Avoid presentations by projects without active discussion or feedback from TAG expertise to improve and align the project with CNCF practices

### What are the non-goals of the DTR Working Group

- To be determined by the working group and approved by the TOC

cc: @TheFoxAtWork @amye @Riaankl @mrbobbytables

**Comment by TheFoxAtWork** [comment]
Thanks @angellk !  Would you write up the scope of the DTR effort so others interested in it understand what we're looking to cover here?

**Comment by TheFoxAtWork** [comment]
@angellk checking in here wrt updating this issue for the group?

**Comment by raravena80** [comment]
In relation with this issue https://github.com/cncf/toc/issues/1279  Should we also specify that this is intended to be a long lived Working Group?

**Comment by nicholasjackson** [comment]
Happy to help on behalf of TAG-Network.

**Comment by alolita** [comment]
Hi Folks - I am interested in contributing to the DTR working group from TAG Observability.

**Comment by angellk** [comment]
It looks like we have quorum! I'll set up the kick-off meeting and invite you all.

**Comment by leonardpahlke** [comment]
Happy to join too - TAG Environmental Sustainability

**Comment by angellk** [comment]
Please join the [#wg-dtr](https://cloud-native.slack.com/archives/C06UK3WDY3V) slack channel on CNCF slack - we'll coordinate the kick-off meeting there!

**Comment by bavarianbidi** [comment]
:wave: on behalf of End-User TAB

**Comment by angellk** [comment]
**Thank you** everyone for the continued momentum with the DTRs.

Please comment and review on the [General Technical Questions document](https://docs.google.com/document/d/1GQfeu4okLcdLnjvW8yHLnwygDeCBl6lKPm_1IiHxtP4/edit). 

Starting this week we have been going into deeper technical domain reviews: Storage and Security

Next week: Runtimes and TBD

Please check the slack channel for questions/updates/meeting times.

**Comment by anvega** [comment]
It would be great to highlight that DTRs help make the process timeline more predictable for projects moving through stages. In a certain way, this helps projects prepare a stronger case, and recruits people in the DTR as champions for the project.

**Comment by angellk** [comment]
Thank you everyone from the TAGs, TOC, LF Staff, Kubernetes SIG leads and Community members that contributed to and collaborated on the new [Domain Technical Review](https://github.com/cncf/toc/blob/main/tags/resources/toc-supporting-guides/README.md) process! 

As this was intended to be a working group for the work scoped - https://github.com/cncf/toc/pull/1441 officially closes the DTR Working Group.
