### ISSUE TITLE
Update KCCN freeze based on today's TOC meeting

### ISSUE THREAD

**Issue by linsun** [cncf/toc#1284]
we decided to continue with the freeze for kubecon EU and US,and drop the freeze from 6 weeks to 4 weeks.  We'll keep the 1 week post kubecon freeze as before.

Individual TOC member should continue to communicate to projects when they are not available while traveling on other events.

https://github.com/cncf/toc/tree/main/process#kubeconcloudnativecon-freeze

cc @TheFoxAtWork if I missed anything

**Comment by TheFoxAtWork** [comment]
Sounds good.
