### ISSUE TITLE
[SANDBOX PROJECT ONBOARDING] KubeSlice

### ISSUE THREAD

**Issue by jeefy** [cncf/toc#1298]
Welcome to CNCF Project Onboarding!

This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project into the Sandbox.

We would like to complete onboarding within one month of acceptance.

**From the project side, please ensure that:**

- [x] You understand the project proposal process and requirements: <https://github.com/cncf/toc/blob/main/process/README.md>
- [x] You understand the services available for your project at CNCF <https://www.cncf.io/services-for-projects/>
- [x] You ensure your project meets the CNCF IP Policy: <https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy>
- [x] You review the online programs guidelines: <https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md>
- [x] You understand the trademark guidelines: <https://www.linuxfoundation.org/en/trademark-usage/>
- [x] You understand the license allowlist: <https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist>
- [x] Your project is working on written, open governance. See <https://contribute.cncf.io/maintainers/governance/>
- [x] Your Slack channels are migrated to the Kubernetes or CNCF Slack workspace. See <https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another> for more details)
- [x] Your project in its own separate neutral GitHub organization. This will make it transferable to the CNCF's GitHub Enterprise account.
- [x] You submit a pull request to add your project as a Sandbox project to <https://landscape.cncf.io>
- [x] You create maintainer list + add to aggregated <https://maintainers.cncf.io> list by submitting a PR to it
- [x] You submit a pull request to <https://github.com/cncf/artwork> with your artwork
- [x] You transfer your domain to the CNCF - <https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63>

**Things that CNCF will need from the project:**

- [x] Provide emails for the maintainers added to <https://maintainers.cncf.io> in order to get access to the maintainers mailing list and Service Desk - <project-onboarding@cncf.io> is the best email to send those to
- [x] Transfer any trademark and logo assets over to the LF - <https://github.com/cncf/foundation/tree/master/agreements> has agreements
- [x] Accept the invite to join the CNCF GitHub Enterprise account. We'll then add `thelinuxfoundation` as an organization owner to ensure neutral hosting of your project
- [x] Ensure that [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [x] Ensure that that the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub
- [x] Ensure LF footer is on your website and [guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines for the README file of your project on GitHub).
- [x] Transfer website analytics to <projects@cncf.io>
- [x] Start on an OpenSSF Best Practices Badge <https://bestpractices.coreinfrastructure.org/en>

**Things that the CNCF will do or help the project to do:**

- [x] Add your project to DevStats <https://devstats.cncf.io/>
- [x] Add your project to LFX Insights <https://insights.v3.lfx.linuxfoundation.org/>. This is a read-only app added to the GitHub organization once your project is in the CNCF GitHub Enterprise account and we add `thelinuxfoundation` as an organization owner.
- [x] Update relevant marketing intros and slide decks
- [x] Update event call for papers, registration, and CFP area forms
- [x] Confirm maintainers have read about what's available through the Service Desk <https://www.cncf.io/services-for-projects/>
- [x] CNCF sends a welcome email to confirm maintainer list access
- [x] Book time with the team using <http://project-meetings.cncf.io>
- [x] Create space for meetings/events on <https://community.cncf.io>, e.g., <https://community.cncf.io/pravega-community/> - (<https://github.com/cncf/communitygroups/blob/main/README.md#cncf-projects>)
- [x] Adopt a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/)

**Comment by lukaszgryglicki** [comment]
Project added to `All CNCF` DevStats [instance](https://all.devstats.cncf.io), also included in projects health dashboards [here](https://all.devstats.cncf.io/d/54/project-health-table?orgId=1&var-repogroup_name=Kubeslice) and [there](https://all.devstats.cncf.io/d/53/projects-health-table?orgId=1).

**Comment by pnavali** [comment]
You create maintainer list + add to aggregated https://maintainers.cncf.io/ list by submitting a PR to it
>> https://github.com/cncf/foundation/pull/792

 You submit a pull request to https://github.com/cncf/artwork with your artwork
 >>https://github.com/cncf/artwork/pull/476

**Comment by pnavali** [comment]
- [x] Provide emails for the maintainers added to https://maintainers.cncf.io/ in order to get access to the maintainers mailing list and Service Desk - [project-onboarding@cncf.io](mailto:project-onboarding@cncf.io) is the best email to send those to

Imran Md imran@avesha.io
Richie Sebastian richie@avesha.io
Bharath Horatti bharath@avesha.io
Eric Peterson eric@avesha.io
Prabhu Navali prabhu@avesha.io

**Comment by pnavali** [comment]
@jeefy @amye - when you get a chance please add the above email-ids to the maintainers mailing list and Service Desk. Thanks!

**Comment by amye** [comment]
@Cmierly to resolve

**Comment by pnavali** [comment]
- [x] Ensure that [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project

> DCO enabled on all the repos

 - [x] Ensure that that the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub
> Code of conduct updated with CNCF reference https://github.com/kubeslice/kubeslice/blob/master/code_of_conduct.md 
 
 - [x] Ensure LF footer is on your website and [guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines for the README file of your project on GitHub).
 > kubeslice.io website updated with LF footer  https://kubeslice.io

**Comment by Cmierly** [comment]
thank you, @pnavali !
I have updated the checklist and it is current as of today!

**Comment by pnavali** [comment]
Thanks @Cmierly - there were few more tasks completed (in earlier comments) that needs to be resolved as well.

**Comment by pnavali** [comment]
@amye @jeefy @Cmierly - we need additional time to prepare a neutral git organization for the code.

**Comment by krook** [comment]
> @amye @jeefy @Cmierly - we need additional time to prepare a neutral git organization for the code.

Hi @pnavali isn't that already https://github.com/kubeslice? If so, I can invite that org to the CNCF GHE (which will add `thelinxufoundation` as an owner and prepare it to board LFX Insights)

**Comment by krook** [comment]
> Hi @pnavali isn't that already https://github.com/kubeslice? If so, I can invite that org to the CNCF GHE (which will add `thelinxufoundation` as an owner and prepare it to board LFX Insights)

Ah, I see this org is already associated to another GitHub Enterprise account. It will have to be released first so that it can be invited to the CNCF GHE account.

**Comment by pnavali** [comment]
Hi @krook - we are working on it,  there are a few tangled repos that we are migrating to get it ready for the takeover.

**Comment by pnavali** [comment]
Hi Daniel @krook -  kubeslice org  https://github.com/kubeslice  is ready for CNCF GHE takeover - please send the invite when you get a chance. Thanks.

Please add the following maintainers email-ids:
Imran Md [imran@avesha.io](mailto:imran@avesha.io)
Richie Sebastian [richie@avesha.io](mailto:richie@avesha.io)
Bharath Horatti [bharath@avesha.io](mailto:bharath@avesha.io)
Eric Peterson [eric@avesha.io](mailto:eric@avesha.io)
Prabhu Navali [prabhu@avesha.io](mailto:prabhu@avesha.io)

**Comment by pnavali** [comment]
Hi @jeefy @Cmierly - we have added governance doc to the repo.
https://github.com/kubeslice/kubeslice/blob/master/GOVERNANCE.md

When you get a chance please mark this one and few others ( update comment https://github.com/cncf/toc/issues/1298#issuecomment-2091965514) as done. Thanks.

**Comment by krook** [comment]
> Hi Daniel @krook - kubeslice org https://github.com/kubeslice is ready for CNCF GHE takeover - please send the invite when you get a chance. Thanks.

Hi @pnavali seems like something is still holding on. 

<img width="665" alt="image" src="https://github.com/cncf/toc/assets/1499840/b152e934-430a-4da5-b336-b1fb9138958f">

**Comment by pnavali** [comment]
Hi @krook - we have removed it from our GHE - please try again. Thanks.

**Comment by krook** [comment]
> Hi @krook - we have removed it from our GHE - please try again. Thanks.

Great, sent!

**Comment by pnavali** [comment]
Thanks Daniel @krook

**Comment by RobertKielty** [comment]
I have sent out invites to join the kubslice organization on the CNCF Group on Snyk. 

This is for the License Scanning onboarding task that ensures compliance with the CNCF's license policy.

Once one of the maintainers accepts the invite and scans the project code repos then we can call this done.

@pnavali please add the GH User accounts here also for our records of the maintainers, Bharath Horatti, Eric Petersonm, Imran Md, Prabhu Navali and Richie Sebastian.

**Comment by pnavali** [comment]
> I have sent out invites to join the kubslice organization on the CNCF Group on Snyk.
> 
> This is for the License Scanning onboarding task that ensures compliance with the CNCF's license policy.
> 
> Once one of the maintainers accepts the invite and scans the project code repos then we can call this done.
> 
> @pnavali please add the GH User accounts here also for our records of the maintainers, Bharath Horatti, Eric Petersonm, Imran Md, Prabhu Navali and Richie Sebastian.

Thanks @RobertKielty - will do.

**Comment by pnavali** [comment]
Hi @RobertKielty - here are GH user accounts for maintainers:
Eric Peterson - eric978
Bharath Horatti - bharath-avesha
Imran MD - narmidm
Richie Sebastian - richiesebastian
Prabhu Navali - pnavali

**Comment by RobertKielty** [comment]
@pnavali thank you so much, I have updated our internal records.

**Comment by pnavali** [comment]
@jeefy @Cmierly - we are planning kubeslice.io domain transfer - we need a LF stakeholder contact/email-id for transfer.  Thanks.
https://jira.linuxfoundation.org/plugins/servlet/desk/portal/2/create/63

**Comment by krook** [comment]
> @jeefy @Cmierly - we are planning kubeslice.io domain transfer - we need a LF stakeholder contact/email-id for transfer. Thanks. https://jira.linuxfoundation.org/plugins/servlet/desk/portal/2/create/63

You can use `projects@cncf.io` for that @pnavali

**Comment by pnavali** [comment]
ok thanks @krook

**Comment by richiesebastian** [comment]
@jeefy @Cmierly created a domain transfer request https://jira.linuxfoundation.org/plugins/servlet/desk/portal/2/IT-26845 - PTAL, Thanks.

**Comment by pnavali** [comment]
@jeefy @Cmierly - sent trademarks & accounts assignment executed doc to project-onbarding@cncf.io - PTAL. Thanks.

**Comment by pnavali** [comment]
@Cmierly - the following 2 open items have been addressed.

Transfer website analytics to [projects@cncf.io](mailto:projects@cncf.io)
  - we have configured the analytics engine to send reports to projects@cncf.io.  - PTAL

 Start on an OpenSSF Best Practices Badge https://bestpractices.coreinfrastructure.org/en  - we have added the project and are working on reviewing/updating project badge status.

**Comment by Cmierly** [comment]
That's fantastic!
With those tasks done, onboarding is complete for KubeSlice!
