### ISSUE TITLE
[SANDBOX PROJECT ONBOARDING] Connect

### ISSUE THREAD

**Issue by jeefy** [cncf/toc#1299]
Welcome to CNCF Project Onboarding!

This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project into the Sandbox.

We would like to complete onboarding within one month of acceptance.

**From the project side, please ensure that:**

- [x] You understand the project proposal process and requirements: <https://github.com/cncf/toc/blob/main/process/README.md>
- [x] You understand the services available for your project at CNCF <https://www.cncf.io/services-for-projects/>
- [x] You ensure your project meets the CNCF IP Policy: <https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy>
- [x] You review the online programs guidelines: <https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md>
- [x] You understand the trademark guidelines: <https://www.linuxfoundation.org/en/trademark-usage/>
- [x] You understand the license allowlist: <https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist>
- [x] Your project is working on written, open governance. See <https://contribute.cncf.io/maintainers/governance/>
- [x] Your Slack channels are migrated to the Kubernetes or CNCF Slack workspace. See <https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another> for more details)
- [x] Your project in its own separate neutral GitHub organization. This will make it transferable to the CNCF's GitHub Enterprise account.
- [x] You submit a pull request to add your project as a Sandbox project to <https://landscape.cncf.io>
- [x] You create maintainer list + add to aggregated <https://maintainers.cncf.io> list by submitting a PR to it
- [x] You submit a pull request to <https://github.com/cncf/artwork> with your artwork
- [x] You transfer your domain to the CNCF - <https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63>

**Things that CNCF will need from the project:**

- [x] Provide emails for the maintainers added to <https://maintainers.cncf.io> in order to get access to the maintainers mailing list and Service Desk - <project-onboarding@cncf.io> is the best email to send those to
- [x] Transfer any trademark and logo assets over to the LF - <https://github.com/cncf/foundation/tree/master/agreements> has agreements
- [x] Accept the invite to join the CNCF GitHub Enterprise account. We'll then add `thelinuxfoundation` as an organization owner to ensure neutral hosting of your project
- [x] Ensure that [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [x] Ensure that that the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub
- [x] Ensure LF footer is on your website and [guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines for the README file of your project on GitHub).
- [x] Transfer website analytics to <projects@cncf.io>
- [x] Start on an OpenSSF Best Practices Badge <https://bestpractices.coreinfrastructure.org/en>

**Things that the CNCF will do or help the project to do:**

- [x] Add your project to DevStats <https://devstats.cncf.io/>
- [x] Add your project to LFX Insights <https://insights.v3.lfx.linuxfoundation.org/>. This is a read-only app added to the GitHub organization once your project is in the CNCF GitHub Enterprise account and we add `thelinuxfoundation` as an organization owner.
- [x] Update relevant marketing intros and slide decks
- [x] Update event call for papers, registration, and CFP area forms
- [x] Confirm maintainers have read about what's available through the Service Desk <https://www.cncf.io/services-for-projects/>
- [x] CNCF sends a welcome email to confirm maintainer list access
- [x] Book time with the team using <http://project-meetings.cncf.io>
- [x] Create space for meetings/events on <https://community.cncf.io>, e.g., <https://community.cncf.io/pravega-community/> - (<https://github.com/cncf/communitygroups/blob/main/README.md#cncf-projects>)
- [x] Adopt a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/)

**Comment by lukaszgryglicki** [comment]
DevStats [instance](https://connect.devstats.cncf.io) added, adding to "All CNCF" [instance](https://all.devstats.cncf.io) in progress, researching affiliations in progress.

**Comment by lukaszgryglicki** [comment]
Project added to `All CNCF` DevStats [instance](https://all.devstats.cncf.io), also included in projects health dashboards [here](https://all.devstats.cncf.io/d/54/project-health-table?orgId=1&var-repogroup_name=Connect) and [there](https://all.devstats.cncf.io/d/53/projects-health-table?orgId=1).

**Comment by krook** [comment]
https://github.com/connectrpc has been invited to the CNCF GHE. Once the invite is accepted and onboarded, we can then add `thelinuxfoundation` id as an org Owner and begin the LFX Insights onboarding step.

**Comment by akshayjshah** [comment]
> @akshayjshah there are multiple items remaining to complete the onboarding process. Anything we can help you with?

Apologies! Nothing except finding me a time-turner :) We'll get on this right away - @bufdev, @perezd, and I are picking up various pieces of this. We'll coordinate here with any questions.

> Your Slack channels are migrated to the Kubernetes or CNCF Slack workspace. See https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another for more details)

We've got a `#connectrpc` channel in the CNCF Slack, but it's currently private. Can an admin make it public?

**Comment by krook** [comment]
> We've got a `#connectrpc` channel in the CNCF Slack, but it's currently private. Can an admin make it public?

I can do that. Just invite me to it.

**Comment by krook** [comment]
Connect is now in GHE with `thelinuxfoundation` as an owner, and it's onboarded to Insights.

**Comment by krook** [comment]
@perezd We highly recommend just using the [DCO and bot](https://github.com/dcoapp/app) instead of a CLA.

**Comment by RobertKielty** [comment]
I have sent out invites to join FOSSA to @eseay @akshayjshah @emcfarlane @jhump @mattrobenolt @rebello95 @bufdev @pkwarren @smaye81 @timostamm @srikrsna-buf

When the invites are accepted I will add the maintainers as new CNCF FOSSA users to the Connect team there.

**Comment by RobertKielty** [comment]
I have sent out CNCF Snyk invites to @eseay @akshayjshah @emcfarlane @jhump @mattrobenolt @rebello95 @bufdev @pkwarren @smaye81 @timostamm @srikrsna-buf to joint the Connect Org I setup on Snyk.

**Comment by perezd** [comment]
>  Transfer any trademark and logo assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements

This is now done (docusigned)

**Comment by perezd** [comment]
> Transfer website analytics to [projects@cncf.io](mailto:projects@cncf.io)

This is now done (Google Analytics)

**Comment by RobertKielty** [comment]
The Connect maintainers have accepted the CNCF Snyk invites and are members of the Connect Org there. No code imported yet though? Looks like the FOSSA invites has expired, that's fine. 

@perezd let me know when one of the maintainer team have added a repo in Snyk for license scanning.

Any issues you can update me here or DM me on CNCF Slack.

**Comment by RobertKielty** [comment]
Of @eseay @akshayjshah @emcfarlane @jhump @mattrobenolt @rebello95 @bufdev @pkwarren @smaye81 @timostamm @srikrsna-buf, eight of you have acccepted an invite to join the Connect Organziation on Snyk. Thank you!

When one of you have imported the code repos for scanning we can call this task done.

The reports that we are interested in here will be found 

https://app.snyk.io/org/radius-mAGJJGJ7yUvT2TEgmL2vML/reports/licenses

**Comment by bufdev** [comment]
Hey @RobertKielty apologies for the massive delay here. Could you resend me an invite for Snyk? The invitation expired - appreciate it, and sorry for the bother.

**Comment by krook** [comment]
Great to meet with you Connect team!

Since we held the meeting and you're on to Synk we can close out those two checklist items can call you officially onboarded to the Sandbox 🎉 

@RobertKielty now that they are on Snyk, they did have some additional questions that they will follow up with you on.

**Comment by Cmierly** [comment]
Congrats on completing onboarding!
