### ISSUE TITLE
[VOTE] TAG Environmental Sustainability TL - Saiyam Pathak

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/toc#1322]
Hello TOC,

On behalf of the TAG Environmental Sustainability co-chairs, would like to nominate [Saiyam Pathak](https://github.com/saiyam1814) as a Tech Lead for TAG Environmental Sustainability.

Saiyam has been a dedicated member of TAG ENV since its inception. He actively promotes sustainability in technology across his social networks and conducts in-depth [YouTube](https://www.youtube.com/@kubesimplify) explorations of cloud native sustainability initiatives. Through interviews with fellow technology experts, Saiyam shares diverse perspectives on cloud native technologies and sustainability. As CNCF Ambassador, he is engaged with both the global community and local community, driving conversations about technological advancements in sustainability. Saiyam's passion for technology, sustainability, extensive experience, and proven leadership as a CNCF Ambassador, TAG ENV contributor, and Field CTO at CIVO position him as an invaluable asset to the TAG ENV leadership team.

@saiyam1814 could you comment if you accept the nomination - thanks!

@riaankleinhans how would you like to facilitate the voting? - i know you are in the process of documenting this. gitvote automation https://github.com/cncf/gitvote (not sure if I should call for a vote)

Thanks,
Leo

**Comment by saiyam1814** [comment]
Thanks @leonardpahlke I gladly accept the nomination :)

**Comment by JacobValdemar** [comment]
Whoops sorry I changed the status. Thought I was just filtering items on the board for my own view 😆

**Comment by riaankleinhans** [comment]
Congratulation  Saiyam Pathak, @saiyam1814  you nomination as Tech Lead for TAG Environmental Sustainability have passed the TOC vote.

Please submit the the nessisery updates to the TOC and TAG Env. repos.
