### ISSUE TITLE
[VOTE]: Roberth Strand as a Tech Lead for the TAG App Delivery

### ISSUE THREAD

**Issue by thschue** [cncf/toc#1332]
### Select your TAG

TAG App Delivery

### Position

Tech Lead

### Name

Roberth Strand (@roberthstrand)

### Motivation & Additional Information

On behalf of the TAG App Delivery, I propose @roberthstrand as a new Tech Lead for the TAG App Delivery as discussed in https://github.com/cncf/tag-app-delivery/issues/642.

Roberth was a founding member of the Cooperative Delivery (now Platforms) Working Group and maintainer of OpenGitOps. He has been an active member of the TAG for many years, and with his broad knowledge and technical leadership capability, he would definitely be a valuable addition to the TAG Leadership Team.

Bio
Roberth is a self-proclaimed "cloud automator", and works at Sopra Steria as Principal Cloud Native Architect. He has several honorary titles, like Microsoft MVP in the Azure category, CNCF Ambassador, and was previously a HashiCorp Ambassador. Roberth has been involved with TAG App Delivery for years, since he joined the GitOps WG and helped create the GitOps Principles. He currently serves as maintainer on the OpenGitOps project and is one of the co-chairs of the Platforms WG.

Action requested: This issue is to ask the TOC for approval of Roberth as a Tech Lead for our TAG.

**Comment by riaankleinhans** [comment]
@roberthstrand congratulation with the appointment, please make PRs to add yourself to all the right places.
