### ISSUE TITLE
Change "engineer" requirement to be on the TOC

### ISSUE THREAD

**Issue by xmulligan** [cncf/toc#1351]
The current CNCF charter states that:

"(d) Criteria for Nomination. Nominees for the TOC shall:
ii. demonstrate an advanced level of professional experience as engineers in the scope of CNCF"

I think the term should be changed from "engineers" to "technical leaders" for three reasons.

First, in practice this is what the TOC is already doing. Everyone currently sitting on the TOC is a strong technical leader within the community, however not every member is an engineer. This change would help remediate this deviation between process and practice.

Second, (and I would argue more importantly) this change would better meet the demands of the current community. I wasn't here when the charter was originally written, but in the beginning CNCF had only a handful of projects and being an engineer was probably a good requirement. CNCF now encompassed almost 200 projects and there is a growing realization within the community that to make projects sustainable for the next decade, we need to focus on more than just the code. The people, process, and community around the projects are just as important as the code itself. Moving from just engineers to technical leaders would open the TOC to people who can bring their experience on everything that a projects needs to be successful beyond just the code.

Finally, the work of the TOC itself has also changed. Oversight of TAGs and project moving levels are just two examples of work that the TOC carries out that were not around when the charter was originally written. The additional responsibilities of the TOC can also be filled out by people that are not engineers. I think opening to technical leaders broaden the skillsets and experience of the TOC to carry out their expanded role.

**Comment by monadic** [comment]
+1

I don't recall this "engineer" ask and would certainly have rejected it back in the day

**Comment by jeefy** [comment]
Spitballing, "leaders with demonstrated technical expertise"? 

I generally agree with the sentiment, but we do need ensure that TOC members are expected to have technical chops since they're ultimately evaluating and accepting projects. Yes, certain responsibilities are delegated out to TAGs but the final say lands at the TOC so it's still a requirement IMO.

**Comment by krook** [comment]
Looks like you did reject it back in the day @monadic :) 

Related: https://github.com/cncf/foundation/issues/71

**Comment by monadic** [comment]
@krook ha! there you go

**Comment by dims** [comment]
> I don't recall this "engineer" ask and would certainly have rejected it back in the day

+1 from me as well

**Comment by cathyhongzhang** [comment]
Agree with @jeefy on "leaders with demonstrated technical expertise". TOC is a technical committee and technical expertise and leadership are important for evaluating projects, guiding CNCF technical direction, building community interest in cutting-edge technologies, etc.

**Comment by xmulligan** [comment]
Sure, I don't have a strong preference "technical leaders" vs "leaders with demonstrated technical expertise"

**Comment by TheFoxAtWork** [comment]
Since this is under the purview of the Governing Board to make changes to the Charter, and this has several TOC members supporting it, we will propose this change to the GB.

**Comment by xmulligan** [comment]
@TheFoxAtWork what is actually being proposed to the GB? Is there anything I should update in the PR?

**Comment by TheFoxAtWork** [comment]
the proposed change to the GB i believe is:

(subject to GB input on language change)

6(d) ii.
> ii. demonstrate an advanced level of professional experience as leaders with demonstrated technical expertise in the scope of CNCF,

**Comment by xmulligan** [comment]
Fixed with https://github.com/cncf/foundation/pull/861
