### ISSUE TITLE
DTR WG: New General Technical Review Questions for Projects

### ISSUE THREAD

**Issue by angellk** [cncf/toc#1357]
The [DTR Working Group](https://github.com/cncf/toc/issues/1277) presented [initial findings and update](https://docs.google.com/presentation/d/1g_vDyVQ1uUusisb8A_uNLXgIxczottGR_ih5zjAqlqs/edit?usp=sharing) in the June 18, 2024 TOC meeting.

### Initial Findings
- During deep dives with Domain experts, the WG determined many questions can be asked of all projects.
- The working group proposes to start with [General Technical Review Questions](https://docs.google.com/document/d/1mzhEoa-S5zno6JQvHklntpHGrEdHkhyEjEkfWrqMIGk/edit#heading=h.n46kvyo47341) of all projects
- Follow-on Domain Technical Review questions will provide further insight into domain specific projects and “Why” the questions are being asked
- Questions are broken out into:
   - General Technical Review
       - Day 0 / Day 1 / Day 2
   - Domain Technical Review
       - TAG Domain
       - Working Groups
       - Scopes

### General Technical Review Questions
During a general technical review, the intent is to understand and validate the cloud native software lifecycle of the project and whether it is in line with the CNCF Maturation process and levels. For the purposes of the general technical review and further domain reviews, the questions follow the cloud native software lifecycle day schemas:

**Day 0 - Planning Phase.** This phase covers design and architecture of the cloud native project.

**Day 1 - Installation and Deployment Phase.** This phase covers initial installation and deployment of the design developed during Day 0 - Planning Phase.

**Day 2 - Day-to-Day Operations Phase.** This phase covers post-deployment operations including monitoring, maintenance, auditing and troubleshooting.

_Note: Following the General Technical Review questions will be Domain Technical Review questions in phase 2 of the working group._

### Phase 1 WG Proposal to TOC
- Please review the [GTR questions](https://docs.google.com/document/d/1mzhEoa-S5zno6JQvHklntpHGrEdHkhyEjEkfWrqMIGk/edit#heading=h.n46kvyo47341)

Sandbox Applications:
- Approve adding the GTR questions to the Sandbox application template
    - Approve the Day 0 questions as mandatory
    - Approve the Day 1 / 2 questions as recommended
- Approve asking current Sandbox applications the GTR questions via manual comments on Sandbox applications in preparation for August review
- After August Sandbox review, look at progress and feedback

Incubation and Graduation Applications:
- Approve adding the GTR questions to the Incubation/Graduation templates as mandatory
- Manually ask _current_ Incubation and Graduation applicants to answer Day 0 / 1 / 2 questions
- In August, review progress and feedback

This issue is open for 2 weeks for TOC comment/approval.

**Comment by TheFoxAtWork** [comment]
@cncf/cncf-toc please take a look at the GTR and provide your feedback/comments.

**Comment by angellk** [comment]
#1441 has been merged to incorporate the General Technical Review Questions into the Domain Technical Review and Moving Levels process. Thank you to all TOC, TAB, TAG and additional community members who participated.
