### ISSUE TITLE
[ARCHIVE] (Migrate) OpenMetrics

### ISSUE THREAD

**Issue by mrbobbytables** [cncf/toc#1364]
Follow up actions from the thread regarding [OpenMetrics folding into Prometheus](https://github.com/cncf/toc/issues/1242). 
The project will be treated as ["archived"](https://github.com/cncf/toc/issues/1242#issuecomment-1954226998) but migrated into Prometheus.

- [x] TOC vote to archive passed (N/A - desire to merge from projects themselves)
- [x] Move logo to archived on CNCF.io	
- [x] Remove from landscape https://github.com/cncf/landscape/pull/3943
- [x] Archive maintainers mailing list	
- [x] Remove ML from maintainers@ mailing group
- [x] Remove/Archive on maintainers.cncf.io (https://github.com/cncf/foundation/pull/825)
- [x] Remove logo from all slide decks	
- [x] Remove logo from event sites	
- [x] Move logo to archived in artwork https://github.com/cncf/artwork/pull/484
- [x] Archive DevStats (or archive?)	
- [x] Notify Speakers team to remove from CFPs	
- [x] Remove from service desk or archive (holding off till domain transfer)
- [x] Remove from CNCF store
- [x] Remove from [CLOMonitor data](https://raw.githubusercontent.com/cncf/clomonitor/main/data/cncf.yaml) (https://github.com/cncf/clomonitor/pull/1532)

**Comment by krook** [comment]
Related: https://github.com/cncf/toc/issues/1242

**Comment by mrbobbytables** [comment]
All tasks have been completed, going to go ahead and close this out :+1:
