### ISSUE TITLE
[SANDBOX PROJECT ONBOARDING] Score

### ISSUE THREAD

**Issue by Cmierly** [cncf/toc#1374]
# Welcome to CNCF Project Onboarding!

This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project into the Sandbox.

We would like your project to complete onboarding within one month of acceptance.

Please track your progress by using "Quote reply" to create your own copy of this checklist in an issue, so that you can update the status as you finish items.

## Review and understand

- [x] The [project proposal process and requirements](https://github.com/cncf/toc/blob/main/process/README.md).
- [x] The [services available for your project at the CNCF](https://contribute.cncf.io/resources/project-services/).
- [x] The [CNCF IP Policy](https://github.com/cncf/foundation/blob/main/charter.md#11-ip-policy).
- [x] The [trademark guidelines](https://www.linuxfoundation.org/legal/trademark-usage).
- [x] The [license allowlist](https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md#approved-licenses-for-allowlist).
- [x] The [online program guidelines](https://github.com/cncf/foundation/blob/main/online-programs-guidelines.md).
- [x] Optional: [Book time with CNCF staff](http://project-meetings.cncf.io) for any onboarding questions.

## Contribute and transfer

- [x] Move your project to its own separate neutral GitHub organization. This will make it transferable to the CNCF's GitHub Enterprise account. If it's already in a GHE account, you will need to remove it from that first.
- [x] Accept the invite to join the CNCF GitHub Enterprise account. We'll then add `thelinuxfoundation` as an organization owner to ensure neutral hosting of your project.
- [x] Migrate your Slack channels (if any) to the [Kubernetes or CNCF Slack workspace](https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another). CNCF staff can help.
- [x] Submit a [pull request](https://github.com/cncf/landscape/pulls) to add your project as a Sandbox project to the [Cloud Native Landscape](https://landscape.cncf.io) by updating [landscape.yml](https://github.com/cncf/landscape/blob/master/landscape.yml) following these [instructions](https://github.com/cncf/landscape2/blob/main/docs/config/data.yml).
- [x] Transfer [your domain to the CNCF](https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63). The "LF Stakeholder email" is <projects@cncf.io>.
- [x] Transfer any [trademark and logo assets to the Linux Foundation](https://github.com/cncf/foundation/tree/main/agreements).
- [x] Submit a [pull request](https://github.com/cncf/artwork) with your artwork.
- [x] Transfer website analytics to <projects@cncf.io>. CNCF staff can help.

## Update and document

- [x] Ensure that [DCO](https://github.com/apps/dco) (preferred) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project.
- [x] Ensure that that the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's `README` on GitHub.
- [x] Ensure LF footer is on your website and [guidelines](https://github.com/cncf/foundation/blob/main/website-guidelines.md) are followed (if your project doesn't have a dedicated website, please adopt those guidelines for the `README` file).
- [x] Create a maintainer list and add it to the [aggregated CNCF maintainer list](https://maintainers.cncf.io) via pull request.
- [x] Provide emails for the maintainers to get access to the maintainers mailing list and Service Desk. Email them to <project-onboarding@cncf.io>.
- [x] Start working on [written, open governance](https://contribute.cncf.io/maintainers/governance/).
- [x] Start on an [OpenSSF Best Practices Badge](https://www.bestpractices.dev/en).

## CNCF staff tasks

- [x] Add the project to [DevStats](https://devstats.cncf.io/).
- [x] Add the project to [LFX Insights](https://insights.lfx.linuxfoundation.org/). This is done by adding a read-only app to your GitHub organization once it's in CNCF GHE.
- [x] Add a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/).
- [x] Send a welcome email to confirm maintainer list access.

**Comment by lukaszgryglicki** [comment]
DevStats [instance](https://score.devstats.cncf.io) added, project also added to [All CNCF projects health](https://all.devstats.cncf.io/d/53/projects-health-table?orgId=1).

**Comment by RobertKielty** [comment]
FOSSA Team for score-spec, is setup. @astromechza is setup as a Team Admin

**Comment by sujaya-sys** [comment]
Hi @Cmierly, just letting you know that we completed the onboarding requirements. Thank you to everyone for your support on this! 🎉

I added references to PRs or similar next to the checked items below:

> # Welcome to CNCF Project Onboarding!
> This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project into the Sandbox.
> 
> We would like your project to complete onboarding within one month of acceptance.
> 
> Please track your progress by using "Quote reply" to create your own copy of this checklist in an issue, so that you can update the status as you finish items.
> 
> ## Review and understand
> * [x]  The [project proposal process and requirements](https://github.com/cncf/toc/blob/main/process/README.md).
> * [x]  The [services available for your project at the CNCF](https://contribute.cncf.io/resources/project-services/).
> * [x]  The [CNCF IP Policy](https://github.com/cncf/foundation/blob/main/charter.md#11-ip-policy).
> * [x]  The [trademark guidelines](https://www.linuxfoundation.org/legal/trademark-usage).
> * [x]  The [license allowlist](https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md#approved-licenses-for-allowlist).
> * [x]  The [online program guidelines](https://github.com/cncf/foundation/blob/main/online-programs-guidelines.md).
> * [x]  Optional: [Book time with CNCF staff](http://project-meetings.cncf.io) for any onboarding questions.
> 
> ## Contribute and transfer
> * [x]  Move your project to its own separate neutral GitHub organization. This will make it transferable to the CNCF's GitHub Enterprise account. If it's already in a GHE account, you will need to remove it from that first.
> * [x]  Accept the invite to join the CNCF GitHub Enterprise account. We'll then add `thelinuxfoundation` as an organization owner to ensure neutral hosting of your project.
> * [x]  Migrate your Slack channels (if any) to the [Kubernetes or CNCF Slack workspace](https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another). CNCF staff can help.
> * [x]  Submit a [pull request](https://github.com/cncf/landscape/pulls) to add your project as a Sandbox project to the [Cloud Native Landscape](https://landscape.cncf.io) by updating [landscape.yml](https://github.com/cncf/landscape/blob/master/landscape.yml) following these [instructions](https://github.com/cncf/landscape2/blob/main/docs/config/data.yml). (See [#3956](https://github.com/cncf/landscape/pull/3956) for reference).
> * [x]  Transfer [your domain to the CNCF](https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63). The "LF Stakeholder email" is [projects@cncf.io](mailto:projects@cncf.io). (See [IT-27054](https://jira.linuxfoundation.org/plugins/servlet/desk/portal/2/IT-27054) for reference).
> * [x]  Transfer any [trademark and logo assets to the Linux Foundation](https://github.com/cncf/foundation/tree/main/agreements).
> * [x]  Submit a [pull request](https://github.com/cncf/artwork) with your artwork. (See [#490](https://github.com/cncf/artwork/pull/490) for reference).
> * [x]  Transfer website analytics to [projects@cncf.io](mailto:projects@cncf.io). CNCF staff can help.
> 
> ## Update and document
> * [x]  Ensure that [DCO](https://github.com/apps/dco) (preferred) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project.
> * [x]  Ensure that that the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's `README` on GitHub.
> * [x]  Ensure LF footer is on your website and [guidelines](https://github.com/cncf/foundation/blob/main/website-guidelines.md) are followed (if your project doesn't have a dedicated website, please adopt those guidelines for the `README` file).
> * [x]  Create a maintainer list and add it to the [aggregated CNCF maintainer list](https://maintainers.cncf.io) via pull request. (See [#829](https://github.com/cncf/foundation/pull/829) for reference).
> * [x]  Provide emails for the maintainers to get access to the maintainers mailing list and Service Desk. Email them to [project-onboarding@cncf.io](mailto:project-onboarding@cncf.io).
> * [x]  Start working on [written, open governance](https://contribute.cncf.io/maintainers/governance/). (see [GOVERNANCE.md](https://github.com/score-spec/spec/blob/main/GOVERNANCE.md) for reference).
> * [x]  Start on an [OpenSSF Best Practices Badge](https://www.bestpractices.dev/en). (Work in progress, we're currently at 31%)
> 
> ## CNCF staff tasks
> * [x]  Add the project to [DevStats](https://devstats.cncf.io/).
> * [x]  Add the project to [LFX Insights](https://insights.lfx.linuxfoundation.org/). This is done by adding a read-only app to your GitHub organization once it's in CNCF GHE.
> * [x]  Add a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/).
> * [ ]  Send a welcome email to confirm maintainer list access.

**Comment by Cmierly** [comment]
@sujaya-sys 
Thank you so much and congrats on completing onboarding!
