### ISSUE TITLE
[VOTE]: Roberth Strand as TAG App Delivery Chair

### ISSUE THREAD

**Issue by lianmakesthings** [cncf/toc#1381]
### Select your TAG

TAG App Delivery

### Position

TAG Chair / Co-Chair

### Name

Roberth Strand @roberthstrand

### Motivation & Additional Information

Roberth has been serving the TAG as a Co-Chair of the Platforms Working Group for a long time, was a very active member of the GitOps Working Group and stepped up as a Tech Lead recently. His industry insights, technical expertise and leadership capabilities are very valuable to the TAG Leadership Team.

**Bio**
Roberth is a self-proclaimed "cloud automator", and works at Sopra Steria as Principal Cloud Native Architect. He has several honorary titles, like Microsoft MVP in the Azure category, CNCF Ambassador, and was previously a HashiCorp Ambassador. Roberth has been involved with TAG App Delivery for years, since he joined the GitOps WG and helped create the GitOps Principles. He currently serves as maintainer on the OpenGitOps project and is one of the co-chairs of the Platforms WG.

**Comment by linsun** [comment]
Thanks Lian for opening the vote.

+1 way to go Roberth!

**Comment by riaankleinhans** [comment]
> Thanks Lian for opening the vote.
> 
> +1 way to go Roberth!

@linsun you were to quick for my :smiley: 
Can you please :+1:  on the vote, as the first +1 
comment would not be counted.

**Comment by linsun** [comment]
> > Thanks Lian for opening the vote.
> > +1 way to go Roberth!
> 
> @linsun you were to quick for my 😃 Can you please 👍 on the vote, as the first +1 comment would not be counted.

Done! :)

**Comment by riaankleinhans** [comment]
Congratulations :tada: @roberthstrand !
https://github.com/cncf/toc/discussions/1390

Please make a PR to update the [leadership page](https://github.com/cncf/toc/blob/main/tags/cncf-tags.md) and add yourself to the [people/config.yaml](https://github.com/cncf/people/blob/main/config.yaml
) and update the[ emeritus-leaders](https://github.com/cncf/toc/blob/main/tags/emeritus_leaders.md) file if needed.
