### ISSUE TITLE
Request for Review: TAG App Delivery - WG Infrastructure Lifecycle

### ISSUE THREAD

**Issue by roberthstrand** [cncf/toc#1383]
Hello TOC, another working group in the making from TAG App Delivery 😎

## Background

One key concern of those who run applications in cloud native environments is to develop and orchestrate infrastructure. This is a very extensive topic, and is out of scope for the other working groups. For this reason, members of the TAG want to start the Infrastructure Lifecycle Working Group.

## Action Request

Please provide your feedback and approval on the proposed group and its charter in this [PR](https://github.com/cncf/tag-app-delivery/pull/691).

We would also like the TOC to approve @rynowak, @bschaatsbergen, and @elft3r as WG Co-Chairs. 

Thank you!

**Comment by rchincha** [comment]
Would https://cluster-api.sigs.k8s.io/ etc fall under this WG?

**Comment by GenPage** [comment]
@rchincha Yes, it would fall under this WG.

**Comment by lianmakesthings** [comment]
To address the concerns raised by TOC members regarding the number of WG chairs, @GenPage has agreed to withdraw his nomination for WG Chair. We hope this will address those concerns sufficiently
