### ISSUE TITLE
[VOTE]: Matthew Flannery for TAG Security Technical Leader

### ISSUE THREAD

**Issue by anvega** [cncf/toc#1393]
### Select your TAG

TAG Security

### Position

Tech Lead

### Name

 Matthew Flannery @matthewflannery

### Motivation & Additional Information

Over the years, Matt has consistently demonstrated technical leadership and fulfilled many aspects of the TL role through his dedicated contributions to the TAG.

Matt has organized TAG Security meetings for the Asia Pacific region and worked on several key initiatives, including the Security Map, Supply Chain Best Practices, Software Factory Reference, the Access WG, and more recently, Automated Governance. Additionally, he organizes KCD Australia, showcasing his commitment to community engagement and cloud native security.

Matt is a strong advocate of cloud native security and compliance in regulated industries, particularly in the public sector. As the founder of Threat Cannary and Principal Advisor to the Australian Digital Service (Services NSW), he has led significant cloud native initiatives for the Australian Government.

Matt has continuously demonstrated his ability to provide unbiased and objective technical guidance, driving understanding and bringing people together in discussions. He is a proven technical and people leader who readily shares his knowledge with others.

**Comment by dzolotusky** [comment]
Thanks for this nomination. It looks Matt is a great candidate. Though, I think that we're a little early to call for a TOC vote as this nomination didn't follow our publicly documented governance for these roles. I'd like to understand why this nomination didn't follow our stated governance, and to follow what we publicly documented governance before we hold a vote.

I believe that the official governance that we have for these roles (https://github.com/cncf/toc/tree/main/tags#elections) states "The TOC and Chairs nominate Tech leads".

I see that TAG Security's guidance has a section on nominees by community (https://github.com/cncf/tag-security/blob/main/governance/tech-lead-proposal-process.md#nominees-by-community) which states that "Nominations are to be submitted to Security TAG Co-Chairs email alias" and not to the TOC.

Have the TAG chairs been involved here and have endorsed Matt already?

**Comment by riaankleinhans** [comment]
Thank you @dzolotusky , I missed that. Removed the vote for the moment.

**Comment by tegioz** [comment]
Hi @riaankleinhans 👋

To cancel a vote in progress it's best to use the [/cancel-vote](https://github.com/cncf/gitvote#cancelling-votes) command 😇

Thanks!

**Comment by riaankleinhans** [comment]
/cancel-vote
 
 Thank you @tegioz

**Comment by riaankleinhans** [comment]
close in favor of #1407
