### ISSUE TITLE
[VOTE]: Brandt Keller for TAG Security Technical Leader

### ISSUE THREAD

**Issue by mnm678** [cncf/toc#1405]
### Select your TAG

TAG Security

### Position

Tech Lead

### Name

Brandt Keller @brandtkeller 

### Motivation & Additional Information

Brandt has been an invaluable member of our community, consistently showing up as a dedicated leader through his work with the Automated Governance and Compliance Working Groups. His contributions in these areas have been vital to the development and implementation of key initiatives, always ensuring that we're on the right track with best practices.
Beyond his work in the groups, Brandt has been a familiar and steady presence in international community meetings. His ability to bridge different workstreams has been a real asset, helping to keep everyone connected and moving forward together. His knack for bringing people and ideas together has made a lasting impact on our collective efforts.

At Defense Unicorns, where he serves as a Software Engineer, Brandt continues to apply his deep expertise in automation and governance, which shines through in his community work. His efforts in revising and automating our website have not only improved its functionality but have also made it more user-friendly for everyone involved.

Brandt's dedication to the community, combined with his professional experience and his natural ability to connect and drive diverse teams, makes him a perfect fit for the Tech Lead role.

**Comment by eddie-knight** [comment]
Brandt has been a core contributor in the past several months, and many of us have come to rely on him for technical and strategic guidance. That doesn't even mention his comprehensive note-taking skills, which are a unique bonus he adds to keep our NA and EMEA community calls harmonized 😁 

Very happy to endorse this nomination.

**Comment by jkjell** [comment]
I strongly support this! @brandtkeller has been a great contributor to the community bringing his unique perspective from his experiences and work.

**Comment by MohawkMattDenny** [comment]
Brandt is a stellar human and I support this position for him. He is incredibly knowledgeable and knows his things better than anyone I know. I would would go into battle with Brandt and highly recommend him for this role and believe he will crush it.

**Comment by TheFoxAtWork** [comment]
Closing as completed

**Comment by riaankleinhans** [comment]
@TheFoxAtWork would you OK with a further automation closing the issue once the vote passed and the announcement was posted in the GH Discussion?

**Comment by TheFoxAtWork** [comment]
Yep, one less thing to do, but we need to ensure we update the repo when these changes happen.
