### ISSUE TITLE
[VOTE]: Marco De Benedictis for TAG Security Technical Leader

### ISSUE THREAD

**Issue by mnm678** [cncf/toc#1406]
### Select your TAG

TAG Security

### Position

Tech Lead

### Name

Marco De Benedictis @mrcdb

### Motivation & Additional Information

Marco has consistently demonstrated technical leadership within the community through his dedicated contributions to the TAG. In addition to his contributions to the Italian translation of the Cloud Native Security Whitepaper, project security reviews, and the Baseline WG, he has been a reliable facilitator for TAG community meetings in the EMEA region.

Marco routinely identifies operational challenges from documentation to website issues, and proactively proposes precise solutions that are ready to merge. His technical expertise is further demonstrated through his support in issue triaging, where he helps identify obstacles and helps the community move work forward. His work at ControlPlane, particularly in threat modeling, Kubernetes security, and DevSecOps maturity assessments, underscores his deep technical knowledge that make him an exemplary candidate for the Tech Lead role.

**Comment by eddie-knight** [comment]
Marco is a stable pillar of the EMEA community, and at times he has been the central reason that STAG work has continued in that region. In addition to the aforementioned ways he has contributed in the past, I believe that bringing on Marco as a Tech Lead is _essential_ to furthering the groups goals in EMEA.

**Comment by brandtkeller** [comment]
Wanted to add further support for Marco as TL. His leadership extends beyond the EMEA community and greatly improves the cohesion of teams across the globe.

**Comment by TheFoxAtWork** [comment]
Closing as completed.
