### ISSUE TITLE
[VOTE]: Matthew Flannery for TAG Security Technical Leader

### ISSUE THREAD

**Issue by mnm678** [cncf/toc#1407]
### Select your TAG

TAG Security

### Position

Tech Lead

### Name

Matthew Flannery @matthewflannery

### Motivation & Additional Information

Over the years, Matt has consistently demonstrated technical leadership and fulfilled many aspects of the TL role through his dedicated contributions to the TAG. He has organized TAG Security meetings for the Asia Pacific region and worked on several key initiatives, including the Security Map, Supply Chain Best Practices, Software Factory Reference, the Access WG, and more recently, Automated Governance. Additionally, he organizes KCD Australia, showcasing his commitment to community engagement and cloud native security.

Matt is a strong advocate of cloud native security and compliance in regulated industries, particularly in the public sector. As the founder of Threat Cannary and Principal Advisor to the Australian Digital Service (Services NSW), he has led significant cloud native initiatives for the Australian Government.

Matt has continuously demonstrated his ability to provide unbiased and objective technical guidance, driving understanding and bringing people together in discussions. He is a proven technical and people leader who readily shares his knowledge with others

**Comment by eddie-knight** [comment]
I can affirm and support all of the statements in this nomination!

With the recent launch of the APAC community efforts, having Matt join as a Tech Lead to support the community will open up new doors for the TAG to operate globally.

**Comment by TheFoxAtWork** [comment]
Closing as completed
