### ISSUE TITLE
[TOC Meeting][Closed] 2024-10-08 - Sandbox Review 

### ISSUE THREAD

**Issue by mrbobbytables** [cncf/toc#1427]
**Host:** @rochaporto 
**Note Taker:**

Agenda:
- [Sandbox Applications](https://github.com/orgs/cncf/projects/14/views/1)

**Comment by castrojo** [comment]
Results from meeting:

Reloader: Move to vote 
Sermant: Move to vote
Youki: Move to vote
OpenEBS: Move to vote
Kmesh: Move to vote
OVN-Kubernetes: Move to vote
KAITO: Move to vote

syngit: Talk to app delivery and open gitops, Karena to closeKubeVPN: Emily to close, not ready
SlateDB: Waiting state until presentation, leave for next time. Alex C. to ask follow up questions
Threeport: Bob check on status, postponed then close
