### ISSUE TITLE
404 link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by MetzinAround** [cncf/toc#1437]
When I navigate to CONTRIBUTING.md, the first link with a proposal for a new project leads to a 404 error. 

broken link: https://github.com/cncf/toc/blob/main/process/project_proposals.md

inside `/process` there is no file called `project_proposals.md`. I wasn't able to locate it in the repo elsewhere. Is there a location for this process for others to follow in the future or is this no longer a formal process CNCF follows. 

Thanks, happy to help if needed.

**Comment by angellk** [comment]
Thanks for bringing this up @MetzinAround ! The correct link is https://github.com/cncf/toc/blob/main/process/README.md if you'd like to open a PR.

**Comment by riaankleinhans** [comment]
This would be fixed by #1438
