### ISSUE TITLE
[VOTE]: TAG ENV Chair Nomination Kristina Devochko

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/toc#1457]
* **TAG**: TAG Environmental Sustainability
* **Role**: Chair
* **Name**: Kristina Devochko (@guidemetothemoon)

### Motivation & Additional Information

Hello TOC,

I would like to nominate Kristina Devochko (@guidemetothemoon) as TAG Environmental Sustainability Chair to replace Max Körbächer who moved to emeritus chair end of September 2024.
Kristina is a passionate community leader that is active in the TAG for close to two years now. Her contribution majorly impacted our initiatives in the last two years. She co-founded the TAG ENV WG Green Reviews, moved to TAG Tech Lead and started several efforts. She is also an CNCF Ambassador, community group meetup organizer and podcast host. We are glad to have Kristina in our team.

Having discussed the nomination with Kristina, she has expressed her willingness to step into this role officially.

Thank you for considering her nomination.

Thanks everyone and especially to Kristina!

Leo

cc @catblade 
cc @TheFoxAtWork @angellk @kevin-wangzefeng

**Comment by riaankleinhans** [comment]
@leonardpahlke can you please format to match the [leadership nomination template](https://github.com/cncf/toc/issues/new?template=tag-leadership-nomination.yaml)

**Comment by ADiTuri** [comment]
+1 NB

**Comment by AntonioDiTuri** [comment]
+1 NB

**Comment by catblade** [comment]
+1B

WELL DESERVED!

**Comment by vallss** [comment]
+1 but for me would be  `+infinity`! Super well deserved for everything you do for the TAG 💚

**Comment by Nancy-Chauhan** [comment]
+1

**Comment by TheFoxAtWork** [comment]
@riaankleinhans  is this ready for TOC voting?

CC @mrbobbytables

**Comment by thelooter** [comment]
+1NB
