### ISSUE TITLE
[VOTE]: TAG ENV TL Nomination Alessandro Vozza

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/toc#1458]
* **TAG**: TAG Environmental Sustainability
* **Role**: Tech Lead
* **Name**: Alessandro Vozza (@ams0)

### Motivation & Additional Information

Hello TOC,

I would like to nominate Alessandro Vozza (@ams0) as TAG Environmental Sustainability Tech Lead (TAG ENV TL).
Alessandro is a passionate community leader, CNCF Ambassador and Cloud Native Advocate. He has been leading initiatives in the TAG for over a year now. His long time engagement in various CNCF projects and community groups bundled with his drive to make an impact building more sustainable cloud infrastructure makes him an excellent candidate for the TAG ENV TL role. His technical knowledge and advocacy experience are supporting. We are glad to have Alesandro in our team.

Having discussed the nomination with Alessandro, he has expressed his willingness to step into this role officially.

Thank you for considering his nomination.

Thanks everyone and especially to Alessandro!

Leo

cc @catblade 
cc @TheFoxAtWork @angellk @kevin-wangzefeng

**Comment by lucab85** [comment]
I advocate for Alessandro Vozza

**Comment by ADiTuri** [comment]
+1 NB

**Comment by AntonioDiTuri** [comment]
+1 NB

**Comment by catblade** [comment]
+1B

**Comment by guidemetothemoon** [comment]
+1NB 😺

**Comment by Nancy-Chauhan** [comment]
+1

**Comment by rohitg00** [comment]
+1

**Comment by linsun** [comment]
+1, way to go @ams0

**Comment by rohitg00** [comment]
+1 🎉
