### ISSUE TITLE
Sandbox Application - Project Champions section needs update

### ISSUE THREAD

**Issue by edrob999** [cncf/toc#1461]
Attn @TheFoxAtWork  (this is the issue discussed in Slack)

- The Sandbox application has a section "Project champions"
- The tooltip is "Please list any people who are part of CNCF leadership (TOC, TAGS, etc.) who can endorse or answer questions about your project."

**The problem is:**
The tooltip encourages applicants to list any CNCF leaders who are familiar with the project. The leaders may be informed, but may not consider themselves a "Project champion".

**Recommendation**
Change the section title to: "CNCF Contacts"
Change tooltip to: "Please list any people within CNCF leadership (TOC, TAGS, etc.) who are familiar with, and can answer questions about your project."

I believe this more closely aligns with the intention of the section, and encourages CNCF people to give balanced feedback to TOC.

**Comment by TheFoxAtWork** [comment]
Thanks @edrob999 !

TOC & Community - we've had other suggested changes to the Sandbox application form
* updating which fields should be required but currently are not
* improving clarity of fields

Are there others?

**Comment by angellk** [comment]
Thank you @edrob999 - that's a great recommendation. 

@TheFoxAtWork - agree with the other the suggestions. It will help to ensure completeness of the application by updating the required fields.

**Comment by edrob999** [comment]
@angellk @TheFoxAtWork Typo alert:
in the live version: 
"can questions about your project"
should be
"can answer questions about your project"

**Comment by angellk** [comment]
Closing per https://github.com/cncf/sandbox/pull/305

Thanks @edrob999 !
