### ISSUE TITLE
Present ORY Hydra to TOC

### ISSUE THREAD

**Issue by aeneasr** [cncf/toc#147]
## Project Description

ORY Hydra is an OpenID Certified OAuth 2.0 and OpenID Connect open source server. It implements best practices for access control security and builds on top of open standards and protocols. Contrary to existing projects in this space, ORY Hydra defines a clear boundary around OAuth 2.0 and OpenID Connect and does not aim to solve all authentication, authorization, and access control issues in one stack.

[ORY](http://github.com/ory/) builds a range of open source services that individually tackle these issues within a clear defined boundary. Each service, including ORY Hydra, solves the task at hand stand-alone. The services can also be combined with other ORY projects or other CNCF projects, such as OPA, to build a hardened, enterprise-grade access control system.

ORY Hydra is written in Go and compiles to a static ~12 MB size binary without dependencies that runs on any operating system with a minimal CPU & memory footprint. Its twelve-factor architecture allows horizontal (auto-)scaling and makes it natively compatible with application platforms such as Kubernetes, CloudFoundry, Heroku, and others.

In contrast to existing projects, this software focuses on interoperability with any authentication system by implementing a redirection-based flow (“user login and consent flow”). Popular “full-stack” auth* solutions provide strongly opinionated customization logic including template engines, plugin systems, and scripting languages that are often hard to test and require specific domain-knowledge of the system and language in place.

Instead, ORY Hydra relies on Layer 7 protocols (HTTP/HTTPS) so developers can plan, develop, test, and operate custom business logic and UIs in the language, frameworks, and with development processes they prefer.

Preferred Maturity Level: Sandbox
License:  Apache License 2.0

## Community

ORY Hydra has evolved, over the course of three years, to a trusted project for developers looking to solve API access control and delegation of authorization (OAuth 2.0) as well as authentication (OpenID Connect).

| **metric** | **snapshot** |
| --- | --- |
| Stars | 4500 |
| Watchers | 151 |
| Forks | 350 |
| Contributors | 48 |
| Docker Hub Pulls | ~500k |
| Chat Members | ~330 |

Community and adoption is growing fast. We are open and willing to share detailed telemetry data insights with the TOC. Telemetry data *has voluntarily been submitted to us*.

## Source control

GitHub: https://github.com/ory/hydra

## External Dependencies

```
$ licenses github.com/ory/hydra
github.com/ory/hydra                                                                 Apache License 2.0
github.com/ory/hydra/vendor/github.com/asaskevich/govalidator                        MIT License
github.com/ory/hydra/vendor/github.com/beorn7/perks/quantile                         MIT License (98%)
github.com/ory/hydra/vendor/github.com/davecgh/go-spew/spew                          ISC License (98%)
github.com/ory/hydra/vendor/github.com/dgrijalva/jwt-go                              MIT License (98%)
github.com/ory/hydra/vendor/github.com/fsnotify/fsnotify                             BSD 3-clause "New" or "Revised" License (96%)
github.com/ory/hydra/vendor/github.com/go-resty/resty                                MIT License
github.com/ory/hydra/vendor/github.com/go-sql-driver/mysql                           Mozilla Public License 2.0
github.com/ory/hydra/vendor/github.com/golang/gddo/httputil/header                   BSD 3-clause "New" or "Revised" License (96%)
github.com/ory/hydra/vendor/github.com/golang/protobuf/proto                         BSD 3-clause "New" or "Revised" License (92%)
github.com/ory/hydra/vendor/github.com/gorilla/context                               BSD 3-clause "New" or "Revised" License (96%)
github.com/ory/hydra/vendor/github.com/gorilla/securecookie                          BSD 3-clause "New" or "Revised" License (96%)
github.com/ory/hydra/vendor/github.com/gorilla/sessions                              BSD 3-clause "New" or "Revised" License (96%)
github.com/ory/hydra/vendor/github.com/gtank/cryptopasta                             Creative Commons Zero v1.0 Universal (96%)
github.com/ory/hydra/vendor/github.com/hashicorp/golang-lru/simplelru                Mozilla Public License 2.0
github.com/ory/hydra/vendor/github.com/hashicorp/hcl                                 Mozilla Public License 2.0
github.com/ory/hydra/vendor/github.com/imdario/mergo                                 BSD 3-clause "New" or "Revised" License (96%)
github.com/ory/hydra/vendor/github.com/jmoiron/sqlx/reflectx                         MIT License (98%)
github.com/ory/hydra/vendor/github.com/julienschmidt/httprouter                      BSD 3-clause "New" or "Revised" License (95%)
github.com/ory/hydra/vendor/github.com/lib/pq/oid                                    MIT License (98%)
github.com/ory/hydra/vendor/github.com/magiconair/properties                         BSD 2-clause "Simplified" License (95%)
github.com/ory/hydra/vendor/github.com/matttproud/golang_protobuf_extensions/pbutil  Apache License 2.0
github.com/ory/hydra/vendor/github.com/mendsley/gojwk                                BSD 2-clause "Simplified" License (96%)
github.com/ory/hydra/vendor/github.com/mitchellh/mapstructure                        MIT License
github.com/ory/hydra/vendor/github.com/mohae/deepcopy                                MIT License
github.com/ory/hydra/vendor/github.com/oleiade/reflections                           MIT License
github.com/ory/hydra/vendor/github.com/ory/fosite                                    Apache License 2.0
github.com/ory/hydra/vendor/github.com/ory/go-convenience                            MIT License
github.com/ory/hydra/vendor/github.com/ory/herodot                                   Apache License 2.0
github.com/ory/hydra/vendor/github.com/ory/ladon                                     Apache License 2.0
github.com/ory/hydra/vendor/github.com/ory/pagination                                Apache License 2.0
github.com/ory/hydra/vendor/github.com/pborman/uuid                                  BSD 3-clause "New" or "Revised" License (96%)
github.com/ory/hydra/vendor/github.com/pelletier/go-toml                             MIT License
github.com/ory/hydra/vendor/github.com/pkg/errors                                    BSD 2-clause "Simplified" License
github.com/ory/hydra/vendor/github.com/pkg/profile                                   BSD 2-clause "Simplified" License (97%)
github.com/ory/hydra/vendor/github.com/pmezard/go-difflib/difflib                    BSD 3-clause "New" or "Revised" License (98%)
github.com/ory/hydra/vendor/github.com/prometheus/client_golang/prometheus/promhttp  Apache License 2.0
github.com/ory/hydra/vendor/github.com/prometheus/client_model/go                    Apache License 2.0
github.com/ory/hydra/vendor/github.com/prometheus/common                             Apache License 2.0
github.com/ory/hydra/vendor/github.com/prometheus/procfs                             Apache License 2.0
github.com/ory/hydra/vendor/github.com/rubenv/sql-migrate                            MIT License
github.com/ory/hydra/vendor/github.com/rubenv/sql-migrate/sqlparse                   MIT License
github.com/ory/hydra/vendor/github.com/sirupsen/logrus                               MIT License
github.com/ory/hydra/vendor/github.com/spf13/afero/mem                               Apache License 2.0 (95%)
github.com/ory/hydra/vendor/github.com/spf13/cast                                    MIT License
github.com/ory/hydra/vendor/github.com/spf13/cobra                                   Apache License 2.0 (95%)
github.com/ory/hydra/vendor/github.com/spf13/jwalterweatherman                       MIT License
github.com/ory/hydra/vendor/github.com/spf13/pflag                                   BSD 3-clause "New" or "Revised" License (96%)
github.com/ory/hydra/vendor/github.com/spf13/viper                                   MIT License
github.com/ory/hydra/vendor/github.com/stretchr/testify                              MIT License (94%)
github.com/ory/hydra/vendor/github.com/toqueteos/webbrowser                          MIT License
github.com/ory/hydra/vendor/golang.org/x/crypto                                      BSD 3-clause "New" or "Revised" License (96%)
github.com/ory/hydra/vendor/golang.org/x/net                                         BSD 3-clause "New" or "Revised" License (96%)
github.com/ory/hydra/vendor/golang.org/x/oauth2                                      BSD 3-clause "New" or "Revised" License (96%)
github.com/ory/hydra/vendor/golang.org/x/sys/unix                                    BSD 3-clause "New" or "Revised" License (96%)
github.com/ory/hydra/vendor/golang.org/x/text                                        BSD 3-clause "New" or "Revised" License (96%)
github.com/ory/hydra/vendor/gopkg.in/gorp.v1                                         MIT License (97%)
github.com/ory/hydra/vendor/gopkg.in/square/go-jose.v2/cipher                        Apache License 2.0
github.com/ory/hydra/vendor/gopkg.in/square/go-jose.v2/json                          BSD 3-clause "New" or "Revised" License (96%)
github.com/ory/hydra/vendor/gopkg.in/yaml.v2                                         Apache License 2.0
```

## Release methodology

We use [semver](https://semver.org/) semantics for version tags and trigger automated test and build pipelines for [binaries](https://github.com/ory/hydra/releases), [Docker Images](https://hub.docker.com/r/oryd/hydra/tags/), SDKs (swagger-codegen currently for Node, PHP, Go), docs, and changelogs.

Releases happen often and breaking changes are [documented extensively](https://github.com/ory/hydra/blob/master/UPGRADE.md).

Releases are announced via the [ORY Security Newsletter](http://eepurl.com/di390P).

## Community Size and any Existing Sponsorship

Unfortunately, most companies do not wish to be identified publicly. They fear that disclosed vulnerabilities leave them open to attackers. We are allowed to disclose them privately with the TOC on request. The adopters whose decision makers have agreed to be identified publicly include:

- Gruppe Deutsche Börse AG (German Stock Exchange operating EUREX and the Frankfurt Exchange)
- Raspberry PI Foundation
- Arduino

We are currently working with existing adopters on publicly disclosing their use case.

## Communication channels

* [GitHub](https://github.com/ory/hydra/issues)
* [Discord](https://discord.gg/PAMQWkr)
* [Discourse](https://community.ory.am/)

## Documentation

* [Developer Guide](https://www.ory.sh/docs/guides/master/)
* [REST API](https://www.ory.sh/docs/api/hydra/)

## Statement on alignment with CNCF mission

Access Control is a topic that every developer has to solve. In the past, one had to rely on libraries and middleware e.g. [rbac](https://github.com/seeden/rbac) for the language at hand. With k8s and the service mesh, this landscape is quickly changing due to CNCF projects like OPA, Istio Auth* patterns, Kubernetes RBAC, and other systems.

ORY's commitment is to build an open source platform that solves easy and hard access control scenarios while providing maximum security and reliability. Access control should not be a "least effort" solution, rather something that is focused, open source, peer-review, and relies on open standards.

With this vision in mind we believe that ORY Hydra fits the CNCF's mission. Apart from technological decision we are confident that the concept of a lean, API-first OAuth 2.0 / OpenID Connect solution fits the vision and the idea of the CNCF mission.

We believe strongly that the ORY ecosystem, including existing and future projects, greatly improves cloud native offerings for developers and companies alike.

Thank you for reviewing this application!

**Comment by caniszczyk** [comment]
Thanks, we will get back to you in a couple of weeks to see if we can slot you in

RFC @cncf/toc

**Comment by aeneasr** [comment]
Hi there, no pressure or anything but I wanted to check if there has been any progress here?

**Comment by caniszczyk** [comment]
Sorry for the delay, the @cncf/toc is still working to schedule presentations and make decisions, there's a bit of a backlog, give us a couple more weeks.

**Comment by aeneasr** [comment]
No problem, thank you for the update!

**Comment by glerchundi** [comment]
toc toc!

Now that it seems the new TOC was settled, do you have a timeframe on when is going to start the evaluation? No hurries just to know if it fits on our plan as we're currently evaluating between ORY Hydra, dex & Keycloak and this will be a point in favor of ORY Hyra.

Thanks in advance and keep up the good work @aeneasr!

**Comment by caniszczyk** [comment]
@glerchundi we're going to actively rebooting project evaluation but focusing on the backlog of graduation requests first. The TOC is also reworking the way projects are organized at a high level to help scale CNCF: https://docs.google.com/document/d/1mt1LH1QJgwA91A6x-DEdjg4ZOXrOnxxc1d2xhq4Hq3I/edit#heading=h.sgr75xakh1k6

**Comment by glerchundi** [comment]
Thanks for the update and tip! Will keep my eyes open then 👀!

**Comment by MatthewJamesBoyle** [comment]
Just a quick comment to say that here at Curve we are looking to move ORY Hydra into production in the coming weeks and have been very happy with it.

**Comment by glerchundi** [comment]
Same here in our company, we'll be putting into production by the end of this year.

**Comment by caniszczyk** [comment]
can you make a formal project proposal and send us a PR? we will then schedule you for a presentation (e.g., https://github.com/cncf/toc/pull/256)

Thanks!

**Comment by aeneasr** [comment]
Ok, will do! Is the plan to present this to the SIG still open?

**Comment by lopezator** [comment]
We also are going to put this into production shortly! Great product @aeneasr !

**Comment by glerchundi** [comment]
Hei @aeneasr, does the proposal PR exist or where could I subscribe in order to see how is this going? Thanks!

**Comment by aeneasr** [comment]
Sorry, we didn't have time to follow up with this.

**Comment by glerchundi** [comment]
Don't worry, thanks for the update and keep up the good work!

**Comment by lizrice** [comment]
Nice to see there are folks commenting in support of this project. Now that SIG Security is in place it would make sense to schedule a presentation with them first for their thoughts. 

Also we have recently added that we would like to see projects tell us how they compare and contrast to other similar projects and products (eg Keycloak)

**Comment by glerchundi** [comment]
> Now that SIG Security is in place it would make sense to schedule a presentation with them first for their thoughts.

Happy to contribute and help in case it needed.

Reasons why we've chosen Hydra:
* Simple: It does one thing and it does it well
* Extensible: How they designed the flows allowed us to create a custom login page with our custom authentication mechanisms which make our whole app much simple with less attack surface making in the end much more easy to manage, operate & protect.
* We feel comfortable with projects written in Go as they're, in general, very reliable.
* It's not a monster like Keycloak
