### ISSUE TITLE
[VOTE]: Dylan Page as Tech Lead for the TAG App Delivery

### ISSUE THREAD

**Issue by lianmakesthings** [cncf/toc#1498]
### Select your TAG

TAG App Delivery

### Position

Tech Lead

### Name

Dylan Page @GenPage

### Motivation & Additional Information

Dylan has been doing fantastic work during his trial run which started end of August. As interim TL he has taken the lead on delivering a [paper on the state of the ecosystem](https://docs.google.com/document/d/17wYKFHSdtRRPQPW-FXBS94RqOjRcBLKxq6urZTxT_R8/edit?usp=sharing) and helped coordinate the TAG's presence at KubeCon NA 2024.
A majority of the TAG's leadership team have [voted favorably](https://github.com/cncf/tag-app-delivery/issues/780) on Dylan's nomination.

**Bio**
Dylan Page is the Manager of the Core Infrastructure team at Lambda and a maintainer of Atlantis, a CNCF sandbox project. He is currently focused on scaling bare-metal Kubernetes for AI/ML workloads across cloud and on-premises environments. Prior to Lambda, Dylan spent four years at Autodesk, supporting an internal developer platform, and five years at DigitalOcean, contributing to their global cloud platform.

**Comment by kgamanji** [comment]
+1 binding

**Comment by mrbobbytables** [comment]
(removed the gitvote label, that should only be applied when a vote is called with gitvote itself)

**Comment by linsun** [comment]
+1 binding

**Comment by riaankleinhans** [comment]
Sorry for being slow on  setting the vote. Please feel free add me to any new voting issue (we might want to add that to the automation)
@linsun & @kgamanji can you please add your votes to the Gitvote?
