### ISSUE TITLE
Present Virtual Kubelet to TOC 

### ISSUE THREAD

**Issue by rbitia** [cncf/toc#154]
**What is Virtual Kubelet?** 
Virtual Kubelet is an open source Kubernetes kubelet implementation that masquerades as a kubelet for the purposes of connecting Kubernetes to other APIs.  Using Virtual Kubelet users can connect their Kubernetes cluster to multiple providers like IoT Edge, Service Fabric Mesh, AWS Fargate, VIC, CRI, Azure Container Instances, and many more. Thus benefiting from Kubernetes alongside the benefits that the provider offers. Within the Virtual Kubelet interface we've enabled bring your own private VNet, monitoring, volumes, port-forwarding, exec and more. 

**Through these features Virtual Kubelet enables:** 
Limited operational overhead to scale up applications in Kubernetes
Extending Kubernetes to any technology with an API

 **GitHub:** https://github.com/virtual-kubelet/virtual-kubelet
**License:** Apache 2.0  

**Cloud-Native and CNCF Alignment**
Virtual Kubelet works within the ecosystem of Kubernetes rather than being a replacement architecture but we also are a standalone component that can be easily installed or deleted. Virtual Kubelet truly enables people to extend beyond the lines of a traditional node. The VK community is growing with over 50 contributors from Microsoft, VMWare, Amazon, and more. Release 1.0 is expected in December.

**Donation Goals**  
By open sourcing an interface to enable any kind of provider to build an abstraction into Kubernetes has been proven very powerful. Kubernetes becomes a default interface backed by multiple services, technologies and providers. 

Virtual Kubelet needs a home where the ecosystem around it can grow beyond just a couple of use cases. We are excited to inspire programmers to build into the interface even if it's just a "silly" provider. We also want to leverage the CNCF's expertise and knowledge about running an open source component in an inclusive way.

**Comment by jovizhangwei** [comment]
Great to see this move for virtual kubelet community.

As a early user of virtual kubelet, we choose it as core component in Alibaba Cloud's Serverless Kubernetes service. It's a fully managed kubernetes service, allows user to quickly create kubernetes container applications without having to manage and maintain clusters and servers, this gives cluster "unlimited" capability to scale container applications. (https://www.alibabacloud.com/help/doc-detail/71479.htm)

Besides of Serverless Kubernetes, we also open source our ECI(Elastic Container Instance) provider for virtual kubelet(https://github.com/virtual-kubelet/virtual-kubelet/tree/master/providers/alicloud), users can simply add virtual node to existing kuberenetes cluster. By deploying pod into the virtual node, it make application scaling more easier than ever, with limited operational overhead, and "unlimited" capacity.

We strongly believe the benefits that virtual kubelet can bring to us and whole kubernetes community, we hope it can get better under CNCF umbrella. :)

**Comment by caniszczyk** [comment]
no need to present, VK is proposed in #153
