### ISSUE TITLE
TOC chair election March 2019

### ISSUE THREAD

**Issue by caniszczyk** [cncf/toc#209]
Now that we have a fully formed TOC, a TOC chair needs to be selected.

We will leave nominations open by end of this week, Fri 5pm PT time.

**Comment by lizrice** [comment]
I'll put myself forward

**Comment by jbeda** [comment]
I'd also like to put myself forward.

**Comment by caniszczyk** [comment]
thanks, we now have enough to at least hold an election ;)

cc: @cncf/toc

**Comment by moderation** [comment]
Would be great to see one or both or our end-user TOC members @mattklein123 and @brewer531 nominate.

**Comment by caniszczyk** [comment]
Liz Rice has been elected as TOC Chair, thanks!

https://civs.cs.cornell.edu/cgi-bin/results.pl?num_winners=1&id=E_cf1dfc636429c32a&rkey=394dd8647cdcd5f8&algorithm=runoff

FYI: @cncf/toc

**Comment by pragashj** [comment]
Congrats Liz! ♥️
