### ISSUE TITLE
Should graduation criteria be refined for spec projects?

### ISSUE THREAD

**Issue by caniszczyk** [cncf/toc#218]
Some projects under CNCF operate essentially as specification only, should we refine the graduation requirements to be different for these types of projects?

cc: @michelleN

**Comment by duglin** [comment]
I'd be very interested in hearing the ideas around this given our work in CloudEvents. As of now, the biggest hurdle to move from sandbox to incubator (IMO) is this:
- - -
Document that it is being used successfully in production by at least three independent end users which, in the TOC’s judgement, are of adequate quality and scope.
- - - 
And that seemed like a reasonable request of a project regardless of whether it's code-based or spec-based. The only open question for me is how to define "end users". For example, if I can document that CloudEvents is being used by at least 3 Cloud Providers is that sufficient? Or do I have to document 3 users of those Cloud Providers?

**Comment by JustinCappos** [comment]
In a similar vein the TUF project was asked in the past for a lot of
detailed documentation about use metrics as part of our Graduation
proposal.  We can point to things like blog posts from major adopters, but
don't have the sort of relationship where we can ask for data.  Sometimes
we only find out about an adoption after someone blogs about having used it
in production for some time...

**Comment by yurishkuro** [comment]
Tracking users / adopters is my number 1 pain point. I raised it to @mattklein123 when he solicited feedback from project maintainers:

> **End-user tracking**: Who uses the project is a critical aspect of project success. A handful of well-recognized names on the adopters / production users list can be the difference between someone deciding to use the project vs. trying a competitor. Yet there is no “register to download” button for OSS projects, and tracking the actual users is quite difficult (and is a time consuming, non-engineering task). CNCF processes like incubation/graduation ask for documented users however there is no CNCF documentation on how to use a company name / logo in the project’s documentation. 
> **Proposal**: can it be a requirement of a company joining the CNCF to publicly state which CNCF projects they are using? Is there something else that CNCF can do to help in this area?

**Comment by duglin** [comment]
@caniszczyk would it be possible to get some clarity from the TOC on this point during the next call? I'd be happy to open a PR but I'd like to first get a sense from the TOC on what direction they would like to go.  To be clear... for me, I'd like more guidance around what "end users" means at least w.r.t. specifications. Does it mean implementers of the spec, or users of implementations of the spec?

**Comment by lizrice** [comment]
Yes, I would like to have this on the agenda for discussion on the next call

**Comment by caniszczyk** [comment]
added to the agenda for May https://docs.google.com/document/d/1jpoKT12jf2jTf-2EJSAl4iTdA7Aoj_uiI19qIaECNFc/edit#

**Comment by xiang90** [comment]
> And that seemed like a reasonable request of a project regardless of whether it's code-based or spec-based. The only open question for me is how to define "end users". For example, if I can document that CloudEvents is being used by at least 3 Cloud Providers is that sufficient? Or do I have to document 3 users of those Cloud Providers?

For specifications, a better measurement is probably the number of successful implementations. I would interpret end users as the actual consumer, not the service provider or broker.

**Comment by JustinCappos** [comment]
One complicating factor we've seen is that if a spec is fairly easy to
implement, then integrators tend to re-implement it rather than integrate a
common implementation.  This happens even more in my experience if the
languages popular tools are in differ.

So TUF, which is very widely used (automotive, cloud native, OS, language
package managers, etc.), has about as many implementations as in-toto (with
only 4 large scale adoptions).

Just something to ponder...

**Comment by michelleN** [comment]
I think the TOC needs to figure out what we're looking for from a spec in the first place and then define metrics. 

- I'd like to see that the spec is stable and unambiguous. So, having/requiring some specific versioning scheme and a reference implementation would help me with understanding that.
- I'd also like to see that the spec is holding up in different scenarios. So, requiring information around at least some number of other implementations would let me know what kinds of scenarios/use cases the spec is being used for 
- I'd also like to know that the spec is being widely adopted meaning people in the end (end users of the implementations) are making use of it so some information on that roughly

**Comment by lizrice** [comment]
I think this was covered by #277 - @michelleN @caniszczyk please reopen if you disagree
