### ISSUE TITLE
Add FAQ to clarify topics/process for projects

### ISSUE THREAD

**Issue by caniszczyk** [cncf/toc#248]
The roles of sponsor have been very different for Incubation & Sandbox.
1) Incubation: the sponsor acts as a champion for the end-end process
and may get very deeply involved in technical DD and user interviews.
2) Sandbox: the sponsor is part of a quorum of N (=2 today). That is
all. There are no down-votes or deep DD docs.

The processes are also very different:
1) Incubation. Needs filling out lots of docs. Needs user
interviews. DD should be a high bar. TOC vote is by majority (6/9)
2) Sandbox. There is no formal technical DD. The process is
deliberately minimal.

--

1. project present a pitch for TOC to consider it worthy of applying
for Incubation
2. if one TOC member volunteers to act as "sponsor" then the
Incubation process begins
3. a questionnaire is completed (it has LOTS of qns eg history of the project)
4. using docs and github, a formal DD takes place (this got documented
in a lot of detail later on)
5. chris gets LF to do their own DD
6. when the DD teams are happy, everyone presents results to TOC for
review, discussion, vote.
7. the TOC sponsor is involved at all stages especially vouching for 6
being done right

**Comment by lizrice** [comment]
Cc @brendandburns @mattklein123, some input to the process flow chart idea

**Comment by caniszczyk** [comment]
https://github.com/cncf/toc/blob/main/FAQ.md
