### ISSUE TITLE
revisit the idea of needing 3 TOC Sponsors for Sandbox

### ISSUE THREAD

**Issue by caniszczyk** [cncf/toc#249]

**Comment by lizrice** [comment]
TOC had some discussion on this and didn’t reach consensus, on the basis that it’s unclear what problem we are trying to solve and therefore whether three sponsors would solve that problem

**Comment by ultrasaurus** [comment]
would be good to address open question about the responsibility of sponsors here: https://github.com/cncf/toc/issues/195

**Comment by amye** [comment]
Closing as this changed when the TOC increased to 11.
