### ISSUE TITLE
establish conflict of interest guidelines

### ISSUE THREAD

**Issue by ultrasaurus** [cncf/toc#270]
Clear conflict of interest guidelines can mitigate the risk that there is real or perceived bias and accelerate the work of the SIGs, supporting TOC ["No Kingmakers" principle](https://github.com/cncf/toc/blob/master/PRINCIPLES.md#no-kingmakers--one-size-does-not-fit-all).

The CNCF TOC relies on [TOC Contributors](https://github.com/cncf/toc/blob/master/CONTRIBUTORS.md) and [SIG](https://github.com/cncf/toc/tree/master/sigs) (previously Working Groups) for technical analysis and project review that informs decisions.  Almost all of the individuals who do the work are employees by a company who benefits from the Cloud Native ecosystem, and TOC decisions can positively or negatively affect business outcomes.  This creates potential issues:

1. individuals could intentionally or unintentionally promote their own company's project
2. CNCF decision-makers could intentionally or unintentionally limit the participation of an individual unfairly by asserting conflict of interest
3. projects can get stalled while groups discuss whether this person or that person should be allowed to participate

This would help SIG members to comply with the responsibility to be unbiased:

"It is of utmost importance that the information and proposals provided to the TOC by SIGs be highly accurate and unbiased, driven by the goal to improve the CNCF as a whole, rather than benefit one project or company over another. We believe that the rising tide lifts all boats, and that is our goal." -- [SIG Responsibilities](https://github.com/cncf/toc/blob/master/sigs/cncf-sigs.md#responsibilities--empowerment-of-sigs)

**Comment by jbeda** [comment]
Sounds good to me.  There is always gray here but this sounds like a good start. Regardless we want to make sure that there are outside eyes on any projects/info/evaluation.

**Comment by dims** [comment]
IEEE seems to distinguish between Employment and Affiliation ( https://standards.ieee.org/faqs/affiliation.html ) probably too much for us..

**Comment by ultrasaurus** [comment]
FYI: SIG-Security has established [conflict of interest guidelines for security reviewers](https://github.com/cncf/sig-security/blob/master/assessments/guide/security-reviewer.md#conflict-of-interest) (with discussion in PR https://github.com/cncf/sig-security/pull/125)

Writing something down helps streamline our process.  We're happy to adjust anything, as needed, whenever CNCF TOC decides to move forward with more general guidance.

**Comment by amye** [comment]
Closing, this can be reopened if there's still outstanding issues.
