### ISSUE TITLE
Is it possible to contribute an open source project of k8s distribution to CNCF sandbox?

### ISSUE THREAD

**Issue by FeynmanZhou** [cncf/toc#273]
Hi, @lizrice @caniszczyk ,  is it possible to contribute an open source project of k8s distribution (e.g. Rancher 2.0) to CNCF sandbox?

**Comment by dims** [comment]
@FeynmanZhou interesting question. I am guessing you meant - "something that looks like Rancher 2.0" (and not Rancher 2.0 itself!). It would be interesting to explore that idea. 

Just in terms of "platforms / distributions" that claim conformance - there are several open source (and under CNCF) projects:
https://github.com/cncf/k8s-conformance/tree/master/v1.14
(kubeadm, kubespray, kind etc)

**Comment by dankohn** [comment]
Here are the 5 conformant Kubernetes installers that are part of the K8s project: https://landscape.cncf.io/category=certified-kubernetes-installer&format=card-mode&grouping=category&organization=cloud-native-computing-foundation-cncf

**Comment by caniszczyk** [comment]
Anything is possible per discretion of the @cncf/toc ;)

Where does the code currently live? @FeynmanZhou 

You'd have to put forth a formal project proposal and then it will be discussed.

**Comment by timothysc** [comment]
I would heavily vote against this just due to the potential conflicts around this, and I firmly believe @kubernetes/steering-committee should have a say on this.

**Comment by jbeda** [comment]
As someone that is on both the TOC and the k8s SC, this isn't something I'd support. We have enough confusion as it stands.  If there is a gap to be filled here I'd suggest we do it within the k8s project itself.

Is there a specific project being proposed here or is this a hypothetical?

**Comment by caniszczyk** [comment]
closing, old issue

also https://github.com/cncf/toc/blob/main/proposals/sandbox/k3s.md ended up in CNCF
