### ISSUE TITLE
[SIG-Security] recommendation for in-toto evaluation for supply chain security improvements

### ISSUE THREAD

**Issue by ultrasaurus** [cncf/toc#287]
Supply chain attacks on are on the rise.  SIG-Security's [in-toto assessment](https://github.com/cncf/sig-security/tree/master/assessments/projects/in-toto) includes a set of recommendations, including one that identifies a way that CNCF can help this project increase the security of the ecosystem:

* Identify UX Researcher to engage 2-3 companies or projects to evaluate the time and effort required to integrate in-toto and recommend improvements

To further elaborate on this, we felt that increased adoption of in-toto would be beneficial, yet it wasn't clear whether companies / organizations should adopt in-toto directly or whether adoption would be driven by more integrations or perhaps a combination of both.  We felt that such a study could be executed fairly quickly at relatively low cost and create positive impact for the project and the ecosystem.

**Comment by JustinCappos** [comment]
Oh, that would be great!  We'll be looking forward to it!

**Comment by michelleN** [comment]
@ultrasaurus does SIG Security recommend in-toto for incubation status or is this study a blocking requirement for moving to incubation?

**Comment by ultrasaurus** [comment]
Hi @michelleN -- thanks for checking in.  This came out of the part of the security assessment when we think about if there are ways the CNCF could help the project.  I think this would be helpful to in-toto, and might relate to how much we evangelize vs encourage folks to use it, but shouldn't be considered a blocking issue at all. 

I kicked off a conversation with @oicheryl last year, but got a bit stuck on how to engage with CNCF staff on this.  I was thinking this might make more sense as a "service desk" request.

I'll take a look at the incubation criteria and respond separately on that!

**Comment by michelleN** [comment]
The CNCF usually provides minimal services to sandbox projects since sandbox simply is used as a neutral space to collaborate. I wonder if this investment makes more sense at the incubation level. Although I am for investing in this kind of space since software supply chain is becoming an increasingly important area and could also end up helping our own projects in the CNCF as well. @lizrice @amye @justincormack - what do ya'll think?

**Comment by amye** [comment]
Closing as this is happening as part of incubation review.
