### ISSUE TITLE
Develop a process for Working Group formation

### ISSUE THREAD

**Issue by caniszczyk** [cncf/toc#3]
There is an interest to form Working Groups around specific topics.

We should have a simple formal process to establish these.

**Comment by jonboulle** [comment]
Can you give some examples of topics for which there's been interest in
creating working groups?

**Comment by chriswright** [comment]
@jonboulle some topics that came up:
- Service Broker
- Storage
- Networking
- OpenStack collaboration

**Comment by jonboulle** [comment]
Thanks - and what's the thinking in terms of how these working groups
interact with CNCF projects? I'm just trying to understand what the
implications are

**Comment by caniszczyk** [comment]
drafted a proposal here in google doc form for comment tomorrow:
https://docs.google.com/document/d/1rs13t8oTTyYgnm_0bGF_K38rRzG7WtYa0ztbD2K8T8E/edit#

If people are happy with it, I can turn it into proposal where we can vote on it.

**Comment by bcantrill** [comment]
It remains unclear to me what problem is being solved here: if people wish to meet and discuss, CNCF doesn't prevent that -- but if some sort of implicit endorsement is being sought to be given by the TOC and/or CNCF, we should be much more clear about what is being done here and why.  Why not let an informal group form and then come to the TOC when they feel that the association with the CNCF would be helpful to them?

**Comment by caniszczyk** [comment]
@bcantrill they are already discussing this and want a place to do it in a formal fashion as the end result may be a CNCF project proposal (these are CNCF members wanting to do this). We should provide it for them along with some simple rules (transparent meetings, short lived charter, etc)

The purpose is clearly laid out here, feel free to comment on the PR:
https://github.com/cncf/toc/blob/add-working-group-process/process/working_groups.adoc
https://github.com/cncf/toc/pull/6/files

**Comment by caniszczyk** [comment]
This is finally done: https://github.com/cncf/toc#working-groups
