### ISSUE TITLE
Add graduated table

### ISSUE THREAD

**Issue by caniszczyk** [cncf/toc#314]
We need a table for "graduated" projects with date + announcement

Add: https://github.com/cncf/toc/blob/master/docs/projects.md

**Comment by lukaszgryglicki** [comment]
Data for this is available here: https://github.com/cncf/devstats-docker-images/blob/master/devstats-helm/projects.yaml, for each project that graduated just search for `graduated_date` field.

**Comment by caniszczyk** [comment]
@amye to update
