### ISSUE TITLE
Service Mesh Interface (SMI) proposal

### ISSUE THREAD

**Issue by lachie83** [cncf/toc#337]
We would like to propose [Service Mesh Interface (SMI)](https://smi-spec.io/) specification for donation as a sandbox project in the CNCF.

The SMI proposal was presented during the CNCF sig-network, January 16, 2020. The proposal deck can be found [here](https://docs.google.com/presentation/d/1Pn6PvdaCnKf-MRhATWDFgKGmM7Z6tycumb07xYSev5U/edit?ts=5e179825#slide=id.g4054009e6b_5_0).

Please find associated proposal PR - #336

**Comment by mattklein123** [comment]
+1 from me. Happy to be one of the TOC sponsors.

**Comment by leecalcote** [comment]
+1 here. I support SMI's entrance.

**Comment by grampelberg** [comment]
I'm so excited about this proposal!

**Comment by olix0r** [comment]
Big +1 from me as well.

**Comment by mhausenblas** [comment]
+1

Cheers,
Michael

**Comment by caniszczyk** [comment]
thanks @mattklein123, any other @cncf/toc members want to sponsor this project for the sandbox?

**Comment by alexellis** [comment]
👏🐳

**Comment by michelleN** [comment]
I'm also happy to sponsor @caniszczyk

**Comment by lachie83** [comment]
@monadic would you be interested in sponsoring?

**Comment by monadic** [comment]
Potentially but would need to know more.  Is any other TOC member keen?

**Comment by brendandburns** [comment]
I'm willing to sponsor, but I'm not sure if I can given that @michelleN is already sponsoring?

**Comment by lizrice** [comment]
@brendandburns I don’t think there is any reason you & Michelle can’t both sponsor now that we’re looking for three of 11 TOC members (@caniszczyk please shout if I’m missing something). With @mattklein123 that would make three.

**Comment by caniszczyk** [comment]
@lizrice there is nothing against the rules, we did have an unspoken policy that if you were a maintainer or strongly associated with the project you would let other people sponsor

**Comment by xiang90** [comment]
> we did have an unspoken policy that if you were a maintainer or strongly associated with the project you would let other people sponsor

@lizrice @caniszczyk 

We probably should make this an explicit rule if we agree on this.

**Comment by lachie83** [comment]
Thanks for the clarification. In the interest of getting this sponsored to comply with these rules would either of you (@xiang90 @lizrice) be interested in sponsoring?

**Comment by lachie83** [comment]
Thank you all. The TOC sponsors have been updated as follows in the proposal:
 - mattklein123
 - brendandburns
 - brewer531

**Comment by amye** [comment]
Closing this as [SMI](https://github.com/cncf/toc/pull/336) is on the [project board](https://github.com/cncf/toc/projects/4).
