### ISSUE TITLE
Sandbox Project Proposal Template 

### ISSUE THREAD

**Issue by erinaboyd** [cncf/toc#344]
# CNCF SIG Sandbox Project Request Template & Promotion Template

# <Project> 

## <Promotion/Acceptance> to CNCF <Incubation/Sandbox>

**Primary aim: This template helps a project to prepare for a presentation to the SIG, and then helps the SIG share the collated information with the TOC.**

**Authors:**

# Background

**_Link to TOC PR_**

**_Link to Presentation_**

**_Link to GitHub project_**

## Future Plans

# Project Scope

## Clear project definition

**_Does the project have a clear and well defined scope_**

## Value-add to the CNCF ecosystem

**_Does the project have a clear value add to the current project ecosystem. How does it relate to other projects with overlapping capabilities._**

## Alignment with other CNCF projects

**_Does the project align and actively collaborate with other CNCF projects?_**

**_Does the project require any specific versions of projects (or APIs) to interoperate?  (e.g. K8s API, CSI, CNI, CRI)?_**

**_Does the project augment or benefit other CNCF projects?_**

## Anticipated use cases

**_What problems does the project solve?_**

## Alignment with SIG Reference Model

**_Does the project align with the SIG CNCF reference model and which capabilities does it require/provide at each level of the reference model._**

## High level architecture

**_Describe the overall architecture of the project. Feel free to add diagrams._**

# Formal Requirements

**_Document that the project fulfills the requirements as documented in the [CNCF graduation criteria for sandbox](https://github.com/cncf/toc/blob/master/process/graduation_criteria.adoc#sandbox-stage)_**

**_Are there any anticipated issues with any of the criteria ?_**

**_Has the TOC been approached for sponsorship?   If yes, which TOC members have agreed to sponsor the project?_**

# CNCF IP Policy

**_Becoming a sandbox project requires adoption of the CNCF IP Policy: [https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy](https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy)_**

**_Note: there is a grace period after becoming a sandbox period to enable projects to adopt the policy, however, some prep is required to ensure there are no major blockers._**

**_Has the IP policy been reviewed?_**

**_List the repos for the project and their current license_**

**_List any dependent repos (upstream/downstream) that are required to build the project  (including but not limited to  libraries, commercial tools, plugins)_**

**_What actions are required to be compliant with the IP policy?_**

# Other Considerations

## **_Please note, these are not gating criteria but rather to:_**

*   **_Collect a standard set of information for each project_**
*   **_Provides a point in time capture of the state of the project which makes it easier to track progress at future reviews and / or promotion_**
*   **_Help projects to prepare for SIG and TOC presentation_**
*   **_Allow the SIG to review the project and perform due diligence for incubation_**
*   **_Provide the TOC with the information required to accept sponsorship of a project and/or votes_**
*   **_Identify and rectify any significant issues / blockers prior to presenting to the TOC and acceptance as a CNCF project_**

## Cloud Native

**_Does the project meet the definition of Cloud Native?  The CNCF charter states:_**

    “Cloud native technologies empower organizations to build and run scalable applications in modern, dynamic environments such as public, private, and hybrid clouds. Containers, service meshes, microservices, immutable infrastructure, and declarative APIs exemplify this approach.

    “These techniques enable loosely coupled systems that are resilient, manageable, and observable. Combined with robust automation, they allow engineers to make high-impact changes frequently and predictably with minimal toil.”

## Project and Code Quality

**_Are there any metrics around code quality?  Are there good examples of code reviews? Are there enforced coding standards?_**

**_What are the performance goals and results? What performance tradeoffs have been made?  What is the resource cost?_**

**_What is the CI/CD system?  Are there code coverage metrics?  What types of tests exist?_**

**_Is there documentation?_**

**_How is it deployed?_**

**_How is it orchestrated?_**

**_How will the project benefit from acceptance into the CNCF?_**

**_Has a security assessment by the security SIG been done? If not, what is the status/progress of the assessment?_**

# Promotion to Incubation 

## Open Governance

**_How are committers chosen?_**

**_How are architectural and roadmap decisions made?_**

**_How many decision makers are outside the sponsoring organization._**

## Adoption

**_Who are the current maintainers?_**

**_How long has the project been developed for?_**

**_Is there a commercial version of the project or a primary commercial sponsor ?_**

**_Is the project used in production? If so, please list some of the accounts._**

**_Does the project participate in a CNCF User Group?_**

## Vendor Independence

**_Is the project reasonably independent from the sponsoring vendor?_**

**_Are all communication channels and project resources hosted just for this project or with other CNCF projects/resources?_**

**_Is all code that is part of the project hosted and part of the CNCF managed orgs and repos?_**

**_Are all defaults for upstream reporting either unset or community hosted infrastructure (i.e. doesn’t point to vendor hosted SaaS control plane or analytics server for usage data)? Is all project naming independent of vendors?_**

**_Relevant Assets regarding vendor independence_**

**Comment by ultrasaurus** [comment]
It might be helpful to move the content to a PR and update the issue to reflect the problem that we're attempting to solve with the template (for folks who haven't been directly involved).  From my perspective, having a template will 
- reduce the work for individuals who are volunteering to help with the process (SIG Chairs/Tech leads, TOC members/contributors, etc)
- increase transparency in the process

Thanks @erinaboyd for your work on this!

**Comment by xiang90** [comment]
@erinaboyd 

Thanks for putting this up.

A few comments:

Some of the general questions are duplicate with the initial toc proposal here: https://github.com/cncf/toc/blob/master/process/project_proposals.adoc#cncf-project-proposal-process-v12. I suggest to remove the duplicated questions from this template and link to the proposal one. 

> Has the TOC been approached for sponsorship? If yes, which TOC members have agreed to sponsor the project?

The intention is to sponsor projects after the SIG assessment. And we shall discourage projects to reach out TOC members individually before that is done.

**Comment by AloisReitbauer** [comment]
LGTM.

I also added a section at the end for review summary and recommendation to the project for things they should address going forward.

**Comment by lizrice** [comment]
I would be very supportive of having a first version of the template published quickly, which we can iterate on

**Comment by raravena80** [comment]
+1 to move this to a PR and getting it published so we can iterate.

**Comment by xiang90** [comment]
@erinaboyd @lizrice 

as #335 gets merged. shall we create a PR for adding this template?

**Comment by erinaboyd** [comment]
@xiang90 yes I will remove the TOC sponsor solicitation blurb...good idea

**Comment by resouer** [comment]
@erinaboyd Just check if you will move this to a PR?

We have several on-going sandbox level candidates need to change to this template.

**Comment by erinaboyd** [comment]
@resouer already did https://github.com/cncf/toc/pull/361 :)

**Comment by erinaboyd** [comment]
@lizrice do we need to revisit this?

**Comment by michelleN** [comment]
@amye - should we close this in favor of the new sandbox form process?

**Comment by amye** [comment]
Yes, sounds like a plan.
