### ISSUE TITLE
Invalide link of kubernetes's pause

### ISSUE THREAD

**Issue by warmchang** [cncf/toc#35]
The kubernetes repo's directory structure has been adjusted, and should update  the pause's info:
https://github.com/cncf/toc/blob/master/proposals/kubernetes.adoc
![image](https://cloud.githubusercontent.com/assets/13084624/25264786/c8a0a2da-269b-11e7-8f12-48e91bb5b225.png)
The link "https://github.com/kubernetes/kubernetes/blob/master/third_party/pause/LICENSE" get the 404 error.

**Comment by idvoretskyi** [comment]
@warmchang the "pause" is still here https://github.com/kubernetes/kubernetes/tree/master/build/pause, but without a LICENSE file.
Do you have an idea where it can be located now?

**Comment by warmchang** [comment]
@idvoretskyi , as part of kubernetes, the pause use the Apache v2.0 license ([pause.c](https://github.com/kubernetes/kubernetes/blob/master/build/pause/pause.c)).
Can we just use the kubernetes' [LICENSE](https://github.com/kubernetes/kubernetes/blob/master/LICENSE)?
