### ISSUE TITLE
Proposal to donate Dex as a Sandbox project 

### ISSUE THREAD

**Issue by timothysc** [cncf/toc#363]
Hello TOC, 

Per request for the Dex maintainers, they would like to donate Dex to the CNCF. 
xref: https://github.com/dexidp/dex/issues/1379 

## Proposal
**Name of project:** Dex

**Description:** 
Dex is an identity service that uses OpenID Connect to drive authentication for other apps.

Dex acts as a portal to other identity providers through "connectors." This lets dex defer authentication to LDAP servers, SAML providers, or established identity providers like GitHub, Google, and Active Directory. Clients write their authentication logic once to talk to dex, then dex handles the protocols for a given backend.

**Statement on alignment with CNCF mission:**
Dex's main production use is as an auth-N addon in for Kubernetes. Dex runs natively on top of any Kubernetes cluster and can drive API server authentication through the OpenID Connect plugin. Clients, such as kubectl, can act on behalf users who can login to the cluster through any identity provider dex supports.

Dex has been used by numerous companies who would like for it to find a neutral home where they can actively contribute to the long term viability of the project.  

**Sponsors from TOC:** 
TODO

**Preferred maturity level:** Sandbox

**License:** Apache2 + DCO

**Source control:** Github (https://github.com/dexidp/dex)

**Initial Committers:**

Founding Maintainers:
- Joel Speed (Red Hat) 
- Nándor Krácser (Banzai Cloud) 
- Márk Sági-Kazár (Banzai Cloud) 
- Janos Matyas (Banzai Cloud) 
- Rithu John (Lyft) 
- Vijay Katam (VMware) 
- Mo Khan (VMware) 

**Infrastructure requests (CI / CNCF Cluster):**

GitHub Actions for CI/CD
Docker images are stored on Docker Hub

Communication Channels:

IM/Slack: TODO-Request
Issue tracker: https://github.com/dexidp/dex
Mailing List: None
Website: None

**Existing sponsorship:**  

Not at this time, which is the reason for the request 

**Community size:** 
The community around Dex has been fairly large over time, but has struggled recently due to its abandonment when CoreOS was acquired.  However there is a very active user community and developers have requested that it find a neutral home so others can actively engage.   

- 4.2k Github Stars 
- 890 Forks 
- 123 Unique contributors

/cc @cncf/sig-security-triage

**Comment by amye** [comment]
Holding off on adding a SIG to this until TOC review.

**Comment by justaugustus** [comment]
Let us know if you need additional info on the dex side, Amye! :)

**Comment by amye** [comment]
So yes! And this should be a PR so that it can be [tracked](https://github.com/cncf/toc/projects/4).
Closing in favor of a PR to follow.

**Comment by justaugustus** [comment]
Sounds good, @amye. I'll get a PR opened for this!

**Comment by justaugustus** [comment]
PR opened here: https://github.com/cncf/toc/pull/379
