### ISSUE TITLE
Propose Chaos Mesh as a Sandbox project

### ISSUE THREAD

**Issue by dcalvin** [cncf/toc#364]
Hey, we would like to propose Chaos Mesh, a versatile Chaos Engineering platform that orchestrates chaos experiments on Kubernetes environments. The detailed  proposal can be seen here: 

https://github.com/cncf/sig-app-delivery/issues/23

Thanks.

**Comment by amye** [comment]
Excellent! 
However, process note: these should be in pull requests so that I can track them in the [project board](https://github.com/cncf/toc/projects/4). 
Closing, will watch for PR to add to our queue.
