### ISSUE TITLE
Proposal - Cloud Custodian

### ISSUE THREAD

**Issue by kapilt** [cncf/toc#368]
We would like to propose the Cloud Custodian project (https://github.com/cloud-custodian/cloud-custodian) for donation as an incubating project in the CNCF.

The Cloud Custodian project was presented during the CNCF sig-security, December 11, 2019.
https://www.youtube.com/watch?v=gHV1pHX2S7k

We're still working through due diligence with cncf sig security for their threat model assessment.
background issue - https://github.com/cncf/sig-security/issues/307

**Comment by monadic** [comment]
Fwiw, I'm supportive!

**Comment by caniszczyk** [comment]
awesome, can you send a PR with the full proposal? e.g., https://github.com/cncf/toc/pull/367

**Comment by ultrasaurus** [comment]
FYI: there's a related open question (https://github.com/cncf/toc/issues/369) about new process docs -- when PR happens seems to have been accidentally left out of the steps!  

Thanks @caniszczyk for chiming in to get this on track!  

Thinking that might be good to write down a bit about how security assessment related to project proposal / on-boarding process and can probably tag some parts of the assessment that overlap with proposal template and can be just copy/pasted or linked.

**Comment by kapilt** [comment]
post-sandbox related #478
