### ISSUE TITLE
guidance on submitting SIG recommendation

### ISSUE THREAD

**Issue by michelleN** [cncf/toc#369]
We've defined in the[ project process doc](https://github.com/cncf/toc/blob/master/process/project_proposals.adoc) that a project should open a GitHub issue in the TOC repo as the initial step. That's when triage happens then SIG review. What is unclear is where the SIG should submit their recommendation, the GitHub issue or the proposal PR. I saw for one project, the SIG recommendation was confirmed on the proposal PR. 

It is nice to have all the convo around the project in the proposal PR so I'd recommend we go that route and add it to the process doc. Thoughts?

**Comment by mattfarina** [comment]
At what step does the PR happen? For example, if we look at the current [sandbox process](https://github.com/cncf/toc/blob/132bccd4199870653b11aa46f0b371ffe521441a/process/project_proposals.adoc) there is no step listing a PR as part of it. From the documented process it appears a project can go through the whole process and be accepted as a sandbox project without a PR. If this is the case I would suggest everything happen on the issue.

If a PR is to be part of the process I would ask the TOC to document this step in the various processes along with what should be in the pull request.

When the issue closes or a PR with certain information closes does that equal acceptance at a certain level? I would like to have the details on the PR if what the PR contains is the root source of the discussion and merging it equals an accepted at a certain level decision.

**Comment by gerred** [comment]
@guenter Do you remember where you got this PR template from? #261. We opened a PR for sandbox, but in retrospect and looking at the docs, I'm not sure _why_ this is. I'm working on the due diligence now for SIG recommendation and having clarity on this will be great - do we need to open an issue instead?

**Comment by guenter** [comment]
@gerred IIRC there used to be a template in this repo somewhere but I can't find it anymore. Or I may have used a different project proposal as a starting point. The PR requirement was not documented but KUDO was asked in private to open a PR before presenting to the TOC.

**Comment by amye** [comment]
Closing as we've updated processes since this was opened.
