### ISSUE TITLE
Proposing Gluu as a Sandbox project

### ISSUE THREAD

**Issue by nynymike** [cncf/toc#371]
We've been working on the Gluu Server for ten years. It's currently one of the most comprehensive OpenID Connect implementations, according to the [published self-certification results](https://openid.net/certification/). We are the only implementation to self-certify four times. We are passing all OP test, the FAPI OP tests, and very soon, we'll submit the CIBA tests as well. The Gluu Server is also the most comprehensive implementation of Kantara's User Managed Access protocol (UMA). 

We've made a huge investment in making Gluu cloud native. Our ability to auto-scale using Kubernetes has enabled us to algorithmically scale performance. This is an important feature for an identity federation platform, which is by definition subject to "bursty" usage patterns. 

Commercially, we are committed to keeping Gluu open source. We believe open source is the best methodology to write the software, that transparency is the best way to build trust in security software, and that a strong community will drive innovation.

We are looking for home to improve the governance of the Gluu project, and to make it clear to everyone that Gluu will be open forever.  We think CNCF can be that home.

**Comment by justincormack** [comment]
For the sandbox process you should present to SIG Security first, open an issue on https://github.com/cncf/sig-security/issues

**Comment by amye** [comment]
So yes on the SIG Security, except -- issues are not tracked on the project board, PRs are. 
I am closing this and will look for a PR to add to the board.

**Comment by caniszczyk** [comment]
Hey @nynymike, since you're in Austin, please try to grab time with me this Friday if you're around, happy to do coffee and walk you through the CNCF/LF process https://calendly.com/caniszczyk
