### ISSUE TITLE
KUDO proposal for sandbox

### ISSUE THREAD

**Issue by michelleN** [cncf/toc#380]
KUDO has submitted a proposal for sandbox in PR #261 and has done a presentation to SIG App Delivery (recording [here](https://youtu.be/noXA70bNdzg?t=401)).

There was some talk of KUDO moving into Operator Framework as a subproject [here](https://github.com/operator-framework/community/pull/1#issuecomment-560126054). That ended up not happening but @gerred, a KUDO maintainer, is now involved in the governance of operator framework which is a great step forward. The outcome of that discussion is posted [here](https://github.com/operator-framework/community/pull/1#issuecomment-594678708).

Given that, we'll move forward with the sandbox process for KUDO, and the next step for this project is for the SIG App Delivery folks to send over their recommendation for the project as outlined in the [sandbox process](https://github.com/cncf/toc/blob/master/process/project_proposals.adoc#sandbox-process).

**Comment by resouer** [comment]
Thanks @michelleN , it's much clearer for the SIG to continue the process now.

**Comment by gerred** [comment]
Thanks @michelleN. I was given a document by @bryanl for due diligence. This document is here: https://docs.google.com/document/d/1QOumLAXaET8nkZinsok8oIUfnmPyHQsvpsDvERUW_N0/edit I've made a copy while I work on it.

@michelleN, @resouer, What are the expectations currently on me to help SIG App Delivery provide a recommendation?

**Comment by resouer** [comment]
Should work on this one: https://github.com/cncf/toc/issues/344

**Comment by caniszczyk** [comment]
re: sig recommendation, I'd do something that just puts the rec in the repo like SIG Network is doing for SMI, e.g., https://github.com/cncf/sig-network/pull/3

**Comment by gerred** [comment]
Working on that PR now.
