### ISSUE TITLE
Presentation of gluster-kubernetes to the CNCF TOC

### ISSUE THREAD

**Issue by wattsteve** [cncf/toc#39]
Hi Folks

We'd like to introduce the TOC to [gluster-kubernetes](https://github.com/gluster/gluster-kubernetes/) and would appreciate it if we could get a slot on the next CNCF TOC meeting to present the project as a candidate project to join the CNCF. Gluster-Kubernetes is an Apache licensed storage platform that deploys and runs [Gluster](https://www.gluster.org/) in kubernetes. It has native support in K8s for volume plugins and provisioners and was built by members of the Kubernetes Storage SIG. Downstream, Red Hat offers gluster-kubernetes as a product called Container Native Storage (CNS). CNS has been a GA product since July 2016.

**Comment by caniszczyk** [comment]
Thanks @wattsteve, does anyone oppose to have @wattsteve present the project at an upcoming meeting, most likely the second TOC meeting in August?

**Comment by caniszczyk** [comment]
I have you tentatively scheduled for Aug 15th, we currently have Envoy and the CI WG so the schedule is fairly packed and we may ask you to delay presenting until the Sept 5th meeting.

cc: @monadic

**Comment by caniszczyk** [comment]
You're official set for 9/5/17 @wattsteve
