### ISSUE TITLE
TOC chair election March 2020

### ISSUE THREAD

**Issue by amye** [cncf/toc#398]
Now that we have a fully formed TOC, a TOC chair needs to be selected.

We will leave nominations open by end of next week, Fri March 27,  5pm PT time.

Please comment here if you're interested in standing for chair.

**Comment by lizrice** [comment]
I’d like to stand again

**Comment by justincormack** [comment]
Happy to nominate Liz!

**Comment by caniszczyk** [comment]
Since @lizrice ran unopposed she continues to be @cncf/toc chair, thank you for your continued service Liz :)

**Comment by kenowens12** [comment]
Congrats Liz and thanks for your continued leadership.
