### ISSUE TITLE
Update email information for TOC Contributor

### ISSUE THREAD

**Issue by archyufa** [cncf/toc#399]
Please update TOC Contributor information for Ayrat Khayretdinov.
Would be able to change my email as i've changed the company?
From: 
akhayretdinov@cloudops.com 
To:
ayratk@google.com

I've stopped receiving updates and invitations to TOC meeting and would like to resume my participation. Also can this information be propagated to the website page: https://www.cncf.io/people/technical-oversight-committee/

Thank you,
Ayrat

**Comment by amye** [comment]
https://github.com/cncf/toc/pull/445 resolves

**Comment by archyufa** [comment]
Thank you @amye !
