### ISSUE TITLE
Proposal: Artifact Hub as Sandbox project

### ISSUE THREAD

**Issue by mattfarina** [cncf/toc#401]
The [current process](https://github.com/cncf/toc/blob/de7446cd7d9fcb2b9516b675a5b061c9eeea69ac/process/project_proposals.adoc) notes creating an issue to propose a project for sandbox. This issue serves as that step.

A pull request with more details will be coming soon that includes the usual information and more detail on the proposal.

This is for https://artifacthub.io/ whose code is at https://github.com/artifacthub

**Comment by michelleN** [comment]
Did we get a decision on whether this would go under SIG-Runtime or SIG App Delivery? @lizrice

**Comment by quinton-hoole** [comment]
I think realistically both of those sigs will want to take a close look.  Also, is that GitHub repo still empty?

**Comment by mattfarina** [comment]
@michelleN I'm curious why SIG Runtime. SIG App Delivery I can see because of operators and Helm. SIG Security I could see because of Falco and OPA (which have been discussed). I'm curious of the reason for SIG Runtime.

**Comment by quinton-hoole** [comment]
There seems to be a fair amount of overlap with container registries, which fall within SIG Runtime.    See also https://github.com/cncf/toc/blob/master/sigs/runtime-charter.md#interfaces-with-other-related-groups

**Comment by raravena80** [comment]
I believe the repo is https://github.com/artifacthub/hub. There also seems to be a DB component that might fall within SIG-Storage: https://github.com/artifacthub/hub/tree/master/database.

I think from the SIG-Runtime pov: Helm Generates YAML template -> Template contains pods -> Pod definition contains container definitions -> container points to container registry -> Images are pulled from container registry -> Containers created/started. My guess is that this would not apply to OPA policies and Falco rules.

Another aspect would also be checking the validity of the container images that Helm charts refer to.

**Comment by xiang90** [comment]
@michelleN 

I think the main SIG responsible for this should be SIG App Delivery. SIG App Delivery should decide which other SIGs need to be involved and coordinate the review process accordingly.

I am going to assign this to SIG App Delivery if I hear no objection.

**Comment by xiang90** [comment]
@mattfarina I assigned to SIG App Delivery for the initial review. Note that the Sandbox proposal still needs to be added. The template is TBD as it is now (the old one looks like [this](https://github.com/cncf/toc/blob/de7446cd7d9fcb2b9516b675a5b061c9eeea69ac/process/project_proposals.adoc#project-proposal-requirements)). I assume it should be ready in the next couple of weeks.

**Comment by mattfarina** [comment]
@xiang90 The proposal is now at #409.
