### ISSUE TITLE
Presentation of CNCF CI Cross-cloud project on Aug 15 TOC Meeting

### ISSUE THREAD

**Issue by dlx** [cncf/toc#41]
Our CI Working Group has been tasked with demonstrating best practices for integrating, testing, and deploying projects within the CNCF ecosystem across multiple cloud providers. The Cross-Cloud CI uses multiple project CI pipelines (cross-project) driving multi-cloud deployments (cross-cloud) with e2e tests. 

We have 3 projects on Cross-Cloud CI now, Prometheus, CoreDNS and Kubernetes.

The ii coop demo, presented by @dlx and @hh, is 10 minutes long and we would love to gather the TOC's feedback. 

Thank you for your consideration.
@caniszczyk @dankohn

**Comment by caniszczyk** [comment]
Thanks @dlx, I'll slot you in!

You can add your presentation to the deck here + run a demo at the 8/15 TOC meeting:
https://docs.google.com/presentation/d/1Gl6oZb--jB6BPWJOoQdFk9PyHYIn_Hvl9kG3VovT0LQ/edit?usp=sharing

Thanks!
