### ISSUE TITLE
consistency in security related processes for cncf projects

### ISSUE THREAD

**Issue by michelleN** [cncf/toc#410]
Drawing from personal experience on Helm, it would benefit projects to have a template for best practices around reporting a security vulnerability. A template would be helpful for projects to copy. Helm, for example, has a private mailing list to report issues and a documented process for how these issues are handled. We should draw on best practices from other projects, the LF, and any recommendations from CNCF SIG Security.

**Comment by justincormack** [comment]
See also discussion in https://github.com/cncf/sig-security/issues/183

There are parts related to this in the CII badges, and the SIG Security assessment process covers the existence of this, but at present we do not have templates or guidelines.

**Comment by amye** [comment]
Closing as TAG Security has much more processes now, can revisit in 2022 for improvements.
