### ISSUE TITLE
Promote CommunityBridge internship opportunities to projects

### ISSUE THREAD

**Issue by michelleN** [cncf/toc#412]
Contributors can request interns through Google Summer of Code AND through CNCF via Community Bridge. Maybe CNCF SIG Contributor strategy should be looped in here.

cc/ @caniszczyk

**Comment by caniszczyk** [comment]
Thanks @michelleN, @idvoretskyi can you describe what has been done so far?

https://github.com/cncf/soc#current-year

We send emails to all of our maintainers + project lists but happy to see how we can do more. 

We also do blog posts usually before/after each term:
https://www.cncf.io/blog/2019/12/05/cncf-to-participate-in-the-community-bridge-mentorship-program/
https://www.cncf.io/blog/2019/08/23/cncf-joins-google-summer-of-code-2019-with-17-interns-projects-for-containerd-coredns-kubernetes-opa-prometheus-rook-and-more/

**Comment by idvoretskyi** [comment]
@michelleN 

+1 to what @caniszczyk said. We send the notification to the maintainer's mailing list on the Community Bridge opportunities, and our recent cycle has started in December (https://www.cncf.io/blog/2019/12/05/cncf-to-participate-in-the-community-bridge-mentorship-program/).

This cycle ends today (April 1st) - https://github.com/cncf/soc/blob/bbcd4d9f13c4c9f3965b37b413924b9c3fc8b538/communitybridge/README.md#timeline; and we will announce the results together with the blog post shortly.

In addition, this opportunity is promoted here - https://github.com/cncf/contribute#mentorship-programs.

I'll put this on agenda for the next CNCF SIG Contributor strategy meeting, but happy to hear other thoughts here.

**Comment by caniszczyk** [comment]
I haven't figured out what else to do here outside of sending more communications out, we do the most mentorships in the LF family of foundations: https://mentorship.lfx.linuxfoundation.org/#projects_all and https://www.cncf.io/blog/2021/02/03/cncf-lfx-projects-are-open-for-spring-term-2021-apply-now-for-a-mentorship-opportunity/
