### ISSUE TITLE
Clear definition of "End Users" and criteria for Incubation level projects

### ISSUE THREAD

**Issue by resouer** [cncf/toc#438]
So basically there're two issues:

We have a **MUST criteria** of "3 independent end users" for incubation level project: https://github.com/cncf/toc/blob/master/process/graduation_criteria.adoc#incubating-stage. 

The definition of "End Users", according to [CNCF End User Community](https://www.cncf.io/wp-content/uploads/2019/08/cncf-end-user-benefits-2.pdf), is: _companies
that use cloud native technologies internally, but do not sell any cloud native services externally_.

So **the first issue** is we don't have a clear definition of "End Users" in the graduation criteria doc.

**The second issue** is, there are many projects whose adopters are mostly vendors instead of "End Users" based on the definition above.

Most examples are **spec projects**, e.g. [CloudEvents](https://cloudevents.io/) which is already a CNCF incubation level project. Another example is [Cloud Native Buildpack](https://buildpacks.io/)which is [currently under review](https://docs.google.com/document/d/1tb3mK5cJmaQLO8xR__9NaH2GMrdn3WPjAZFBJYsXrxY/edit) in SIG App Delivery.

So I would like to bring the discussion to TOC and wider community to revisit this criteria and discuss how we honor it during daily review practice.

**Comment by jberkus** [comment]
Howdy!  

This issue seems to come under the purvue of the newly formed Governance WG of SIG-Contributor Strategy.

Would you be willing to discuss it in an issue there?
https://github.com/cncf/sig-contributor-strategy/issues/30

**Comment by KimMcMahon** [comment]
Hello @resouer 
The definition of an end user was added to:
https://github.com/cncf/toc/blob/master/process/graduation_criteria.adoc
https://github.com/cncf/toc/blob/master/FAQ.md
https://www.cncf.io/about/faq/#What-is-the-definition-of-an-end-user-specifically-for-graduation-criteria-from-sandbox-to-incubation?

**Comment by fabiand** [comment]
Btw  - another issue with the definition is: They can consume one cloud-naitve technology and provide another one.
I.e. we see KubeVirt adopters (which we consider end-users) which use KubeVirt to build VM based applications, and offer these VMs as a cloud service to end-users. IOW they are not selling kubevirt, but a cloud (-native) service running on top of it.

**Comment by fabiand** [comment]
Another note: I'd appreciat eif the end user definition would be easier to find and not "somehwere" in End users are organizations that use cloud native technologies internally and do not sell any cloud native services externally. This excludes vendors, consultancies, training partners, telcos.

**Comment by amye** [comment]
Closing, can be reopened for 2022 if still relevant

**Comment by fabiand** [comment]
@amye I'd appreciate if we can re-open it right away :)

**Comment by amye** [comment]
> @amye I'd appreciate if we can re-open it right away :) 
Keeping closed in favor of the open TAG discussion. 

I will let https://github.com/cncf/tag-contributor-strategy/issues/30 come back with recommendations, the TAG is the proper working group for this discussion.
