### ISSUE TITLE
Broken links in /cncf/toc

### ISSUE THREAD

**Issue by dholbach** [cncf/toc#444]
The docs in this repository have partly become a bit stale, so some links are broken. In #416 I fixed the few I came across already, but there's more.

I used [markdown-link-check](https://github.com/tcort/markdown-link-check) and [asciidoc-link-check](https://www.npmjs.com/package/asciidoc-link-check)¹ to figure out which are broken and listed them in this [spreadsheet](https://docs.google.com/spreadsheets/d/1nA2mNg44Zp-m5V24i_GoSLmLdkuvecrKCW5M3ZLBB_I/edit#gid=0)².

Originally I thought we could add automatic link checking, but it turned out you get quite a few false positives and sites like github.com start rate-limiting you quite quickly, so all you get is 429s.

I'd suggest we just iterate over the spreadsheet and fix links and post subsequent PRs to make sure things are nice and tidy again.

Adding a CI job would be a separate piece of work. Potentially moving adoc files to markdown another.

¹ asciidoc-link-check crashed one or two times - probably not the most reliable.
² Let me know if you need write access.

cc @sdake with whom I discussed this.

**Comment by sdake** [comment]
This is our [comprehensive plan](https://docs.google.com/document/d/13q09yB-Uy6lpDZSqgN7m7OO98ImncAVWEpeEbFLDdUw/edit?usp=sharing). The rate-limiting can be overcome (retry on 529).

I agree we should phase the work and the existing plan does not account for a phased approach.

There is little value in improving the state of the broken windows if we do not then enforce that further windows shall not be broken. We can enforce this periodically, or per commit. Every engineer prefers per-commit, although periodic is a possible middle ground.

Would you mind adding the stats from the spreadsheet to the comprehensive plan and links to the spreadsheet within the plan where appropriate?

Cheers
-steve

**Comment by amye** [comment]
This will need @cncf/toc review

**Comment by jberkus** [comment]
This seems like a very elaborate plan for fixing a few broken links.  Why can't we just fix the broken links as we find them? @dholbach seems to have done a fine job of that in #416. It's not like anything in this repo is mission-critical.

**Comment by sdake** [comment]
Thank you for the compliment on the plan. I am glad that you have witnessed that both @dholbach and I have thought about this small project in detail.

For historical context, the first fix that led to @dholbach and I joining forces was PR https://github.com/cncf/toc/pull/443 which has merged. After Fixing #443, I looked in the issue queue and PR queue for linting work, and found a PR (the one you reference) was blocked for months. After it was mentioned in a crosslink to issue #443 and slack #toc channel, someone nicely reviewed the PR #443 and said it LGTM although they weren't an expert in CI.

It doesn't make sense to send hundreds of PRs to the queue without a coordinated effort, as @amye rightly points out. The TOC is responsible for reviewing the work, and that should be delivered in a way the TOC can review and approve without significant editorial work on their part.

I had also hoped to recruit others to help execute the plan and drive engagement in the TOC contributors, of which I am a member. If others were unwilling to do the work with a distributed plan, then I and @dholbach) had committed to doing the work, when the TOC has.approved this plan. @dholbach had indicated he didn't wish to enter a long engagement. When I mentioned the hour estimate, he indicated that was fine.

I was hopeful that the TOC would take up this issue on what I estimate to be 60-80 hours of work. The TOC repository has enough volume that a permanent linting project makes perfect sense. This repository is critical to the mission of the CNCF Technical Oversight Committee. This repository helps the TOC define the mission. If this repository doesn't scale, the mission itself runs into capacity constraints around a lack of scalability.

If the TOC disagrees with my position, I can accept that, and I'll abandon the work. That is why I have written a detailed proposal.

Cheers
-steve

**Comment by dholbach** [comment]
I think that it should suffice if people review the spreadsheet, pick a couple of links, fix them in a PR and update the spreadsheet. Approving a PR for the fixed link should be straight-forward as well - if there's not enough reviewers right now, maybe that should be fixed as well?

As I said above: adding a CI job and moving to markdown consistently can be optional. Not sure if this is going to turn into a project of 60 or 80 hours.

**Comment by sdake** [comment]
@dholbach that would be fine, although I have been told by @amye to hold off this work as the TOC is focusing on other work at the moment. This is why a plan was produced. A plan generates the least amount of wasted effort if we are pushing a rope, which it seems like, in this case, we may be doing. I have no lost sleep over that. If the TOC wishes to address this further and take it up for a vote, we can start executing. Or you can execute independently and your PRs may stall.

Cheers,
-steve

**Comment by jberkus** [comment]
@dholbach so I checked your spreadsheet to see if I could move things along, and all of the "broken links" I checked were false positives.

**Comment by dholbach** [comment]
I went through the "Broken Review and Proposal links" tab and ~~striked through~~ the false positives.
