### ISSUE TITLE
Propose Pravega.io for incubation as a CNCF project

### ISSUE THREAD

**Issue by derekm** [cncf/toc#457]
PR #456 proposes Pravega.io for incubation as a CNCF project.

Pravega is a new storage system from Dell EMC targeting streaming analytics and modern data platforms.

Pravega is built to provide consistent semantics around the concept of a stream, in order to reduce the complexity that developers have to tackle when dealing with continuous data in cloud-native applications and environments.

**Comment by caniszczyk** [comment]
Thanks @derekm, the PR is all we need :)
