### ISSUE TITLE
[PROJECT ONBOARDING] crossplane

### ISSUE THREAD

**Issue by caniszczyk** [cncf/toc#466]
Welcome to CNCF Project Onboarding!

Please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/master/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Has your project adopted open governance already? see http://opengovernance.dev

Formal onboarding:
- [x] Domain: transfer domain to CNCF/LF (ITx)
- [ ] Trademarks: transfer any trademark and logo mark assets over to the LF
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners
- [x] Artwork: Ensure logos present on https://github.com/cncf/artwork
- [x] Website: ensure LF footer is there and website guidelines followed, analytics transferred
- [x] Create maintainer list + added to aggregated https://maintainers.cncf.io list - OWNERS file needed
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Trail Map: update CNCF trail map if relevant (incubating projects and above)
- [x] Update https://landscape.cncf.io
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access
- [x] Schedule monthly project sync with CNCF staff

**Comment by amye** [comment]
@jbw976: if I can trouble you for a logo (and the things from the project above), that would be swell. 
Happy to have you onboard!

**Comment by jbw976** [comment]
@amye you can find the main logo in the artwork repo at https://raw.githubusercontent.com/crossplane/artwork/master/logo/logo-horizontal-bluetext.svg.

artwork repo: https://github.com/crossplane/artwork

Will the [crossplane sandbox proposal](https://github.com/cncf/toc/pull/454), that [covers some of this information](https://github.com/jbw976/toc/blob/crossplane-proposal/proposals/sandbox/crossplane.md#project-logo-in-svg-format), be merged soon? :)
https://github.com/cncf/toc/pull/454

**Comment by amye** [comment]
@jbw976: website footer guidelines can be found here: https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices, thanks!

**Comment by amye** [comment]
@jbw976: checking on that LF footer, we're so close to done here!

**Comment by jbw976** [comment]
@amye thanks for the reminder.  I've opened https://github.com/crossplane/crossplane.github.io/issues/54 to get this added to crossplane.io in the very near future.  We should be able to follow up very soon.

**Comment by jbw976** [comment]
@amye https://crossplane.io/ has been updated with the LF footer, thanks to @rathpc, we can check that item off now :)

**Comment by amye** [comment]
Done! Any trademarks to transfer?

**Comment by jbw976** [comment]
@amye following up now to check on the status of the trademark assignment paperwork, i'll update with more info soon

**Comment by jbw976** [comment]
Also just sent an invite to `caniszczyk` and `thelinuxfoundation` to be organization owners for the crossplane org

**Comment by amye** [comment]
Last thing: If you drop me an email at amye@linuxfoundation.org, I can get the domains connected with LFIT.

**Comment by jbw976** [comment]
quick status update:

* trademark transfer paperwork and legal work is on going via email thread
*  https://github.com/crossplane/crossplane/pull/1663 and https://github.com/crossplane/crossplane.github.io/issues/57 are opened to track adding the CNCF sandbox project mention to crossplane.io website and main readme
* sent mail to amye to start process of crossplane.io domain transfer to LFIT
* following up on getting admin access to google analytics for crossplane.io

**Comment by amye** [comment]
Domain transfer in progress, closing as the transfer paperwork is ongoing.
