### ISSUE TITLE
[PROJECT ONBOARDING] kuma

### ISSUE THREAD

**Issue by caniszczyk** [cncf/toc#467]
Welcome to CNCF Project Onboarding!

Please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/master/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Has your project adopted open governance already? see http://opengovernance.dev

Formal onboarding:
- [x] Domain: transfer domain to CNCF/LF (ITx)
- [ ] Trademarks: transfer any trademark and logo mark assets over to the LF
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners
- [x] Artwork: Ensure logos present on https://github.com/cncf/artwork
- [x] Website: ensure LF footer is there and website guidelines followed, analytics transferred
- [x] Create maintainer list + added to aggregated https://maintainers.cncf.io list - OWNERS file needed
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Trail Map: update CNCF trail map if relevant (incubating projects and above)
- [x] Update https://landscape.cncf.io
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access
- [x] Schedule monthly project sync with CNCF staff

**Comment by amye** [comment]
When you move over to the new kumahq repo, can we update the CODEOWNERS file?

**Comment by amye** [comment]
Added to https://www.cncf.io/sandbox-projects/ with a placeholder logo, happy to update!

**Comment by amye** [comment]
@subnetmarco: checking in here on the move to the new repo, thanks!

**Comment by lukaszgryglicki** [comment]
Yeah, would be great to have a separate org, can you also please ping me when the repo is moved? I'll update [DevStats](https://kuma.devstats.cncf.io/d/8/dashboards?orgId=1&refresh=15m) config then.

**Comment by subnetmarco** [comment]
@lukaszgryglicki @amye we have already registered the org `kumahq` on GitHub. I am going to start transferring the repository this week and making sure that doesn't break our automation tooling.

I estimate the entire transfer to CNCF to complete within a couple of weeks: kuma trademark (under legal review), website, etc. but we will focus on the GitHub repository at first.

**Comment by lukaszgryglicki** [comment]
Ok, I'll update Devstats to track `kumahq` org, it doesn't matter if org is already created or not, it will just know to track this org.

**Comment by subnetmarco** [comment]
* All the repositories have been transferred to `https://github.com/kumahq/`. There may be some leftover work to do to make sure everything is correct.
* `thelinuxfoundation` and `caniszczyk` are ORG owners.

**Comment by lukaszgryglicki** [comment]
Will update DevStats main repo tomorrow, `kumahq` GH org is already tracked.

**Comment by amye** [comment]
https://github.com/kumahq/kuma/blob/master/CODEOWNERS doesn't list anyone, @subnetmarco - can you update?

**Comment by subnetmarco** [comment]
@amye in the linked file, we listed the following owners at the end.

```
*       @kumahq/kuma-maintainers
```

But I'd be happy to hear feedback if the expectation is different.

**Comment by amye** [comment]
Crossplane is a good example, we need to know who to add to our public maintainers file: http://maintainers.cncf.io/ 
https://github.com/crossplane/crossplane/blob/master/OWNERS.md

**Comment by amye** [comment]
@subnetmarco: https://github.com/kumahq/kuma/blob/master/OWNERS.md is correct? I can get you all added into the systems today.

**Comment by amye** [comment]
@subnetmarco: I've also cleaned up the landscape with your new logo, see https://github.com/cncf/landscape/pull/1777

**Comment by subnetmarco** [comment]
@amye yes the OWNERS.md is correct. Thanks for updating the logo in the landscape.

**Comment by amye** [comment]
Last remaining: website footer, transferring the domain and any trademarks that need to be transferred!

**Comment by amye** [comment]
Website footer guidelines: https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices, thanks!

**Comment by subnetmarco** [comment]
@amye the footer has been updated: https://kuma.io/

**Comment by amye** [comment]
Super! Marked off. Domains and trademarks are the last out there, is there a registered trademark? https://github.com/cncf/foundation/tree/master/agreements

**Comment by subnetmarco** [comment]
@amye as per email thread, the domain has also been transferred.

**Comment by amye** [comment]
Trademarks are just our last thing here, and that always takes a bit.
