### ISSUE TITLE
[PROJECT ONBOARDING] LitmusChaos

### ISSUE THREAD

**Issue by caniszczyk** [cncf/toc#468]
Welcome to CNCF Project Onboarding!

Please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/master/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Has your project adopted open governance already? see http://opengovernance.dev

Formal onboarding:
- [x] Domain: transfer domain to CNCF/LF (ITx)
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners
- [x] Artwork: Ensure logos present on https://github.com/cncf/artwork
- [x] Website: ensure LF footer is there and website guidelines followed, analytics transferred
- [x] Create maintainer list + added to aggregated https://maintainers.cncf.io list - OWNERS file needed
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Trail Map: update CNCF trail map if relevant (incubating projects and above)
- [x] Update https://landscape.cncf.io
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access
- [x] Schedule monthly project sync with CNCF staff

**Comment by amye** [comment]
Adding @umamukkara from the project side.

**Comment by umamukkara** [comment]
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners

**Comment by ksatchit** [comment]
@amye , here are the maintainers list & logo: 

Maintainers List: https://github.com/litmuschaos/litmus/blob/master/MAINTAINERS
Logo: https://github.com/litmuschaos/litmus/blob/master/images/litmus-logo-white-bg-stacked.svg

**Comment by amye** [comment]
Maintainers.cncf.io has been updated with https://github.com/litmuschaos/litmus/blob/master/MAINTAINERS

**Comment by amye** [comment]
You're up on https://www.cncf.io/sandbox-projects/ with a placeholder logo, we need the icon only without the name.

**Comment by ksatchit** [comment]
Thanks @amye ! Here is the logo w/ just the icon: https://github.com/litmuschaos/litmus/blob/master/images/litmus-logo-white-bg-icon.svg

**Comment by umamukkara** [comment]
@amye , the icon only logo is at
https://github.com/litmuschaos/litmus/blob/master/images/litmus-logo-white-bg-icon.svg
(or)
https://raw.githubusercontent.com/litmuschaos/litmus/master/images/litmus-logo-white-bg-icon.svg

**Comment by amye** [comment]
Replaced! 
Let me know what other links you'd like.

**Comment by umamukkara** [comment]
Thanks @amye . Can you please help with these additional links?

Website - https://litmuschaos.io
Slack - https://kubernetes.slack.com/messages/CNXNB0ZTN
Twitter - https://twitter.com/LitmusChaos
GitHub - https://github.com/litmuschaos/
Youtube - https://www.youtube.com/channel/UCa57PMqmz_j0wnteRa9nCaw

DevStats link will be added later on by you I think.

**Comment by amye** [comment]
Updated!

**Comment by lukaszgryglicki** [comment]
https://litmuschaos.devstats.cncf.io

**Comment by amye** [comment]
@umamukkara: Last piece is any logo assets to transfer to the LF, we have a PDF here: 
https://github.com/cncf/foundation/blob/master/agreements/CNCF%20Trademark%20and%20Account%20Assignment%20Agreement%20(2020%20-%20no%20reg%20trademarks).pdf

**Comment by amye** [comment]
Closing, we are complete here!
