### ISSUE TITLE
[PROJECT ONBOARDING] ArtifactHub

### ISSUE THREAD

**Issue by caniszczyk** [cncf/toc#470]
Welcome to CNCF Project Onboarding!

Please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/master/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [ ] Has your project adopted open governance already? see http://opengovernance.dev

Formal onboarding:
- [x] Domain: transfer domain to CNCF/LF (ITx)
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners
- [x] Artwork: Ensure logos present on https://github.com/cncf/artwork
- [x] Website: ensure LF footer is there and website guidelines followed, analytics transferred
- [x] Create maintainer list + added to aggregated https://maintainers.cncf.io list - OWNERS file needed
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Trail Map: update CNCF trail map if relevant (incubating projects and above)
- [x] Update https://landscape.cncf.io
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access
- [x] Schedule monthly project sync with CNCF staff

**Comment by amye** [comment]
Adding @mattfarina from the project side.

**Comment by amye** [comment]
Added to https://www.cncf.io/sandbox-projects/ with a placeholder logo, let me know if you'd like something different and more links.
