### ISSUE TITLE
[PROJECT ONBOARDING] BFE

### ISSUE THREAD

**Issue by caniszczyk** [cncf/toc#471]
Welcome to CNCF Project Onboarding!

Please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/master/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Has your project adopted open governance already? see http://opengovernance.dev

Formal onboarding:
- [x] Domain: transfer domain to CNCF/LF (ITx)
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners
- [x] Artwork: Ensure logos present on https://github.com/cncf/artwork
- [x] Website: ensure LF footer is there and website guidelines followed, analytics transferred
- [x] Create maintainer list + added to aggregated https://maintainers.cncf.io list - OWNERS file needed
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Trail Map: update CNCF trail map if relevant (incubating projects and above)
- [x] Update https://landscape.cncf.io
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access
- [x] Schedule monthly project sync with CNCF staff

**Comment by amye** [comment]
@iyangsj: Please provide a link for your maintainers file and we'll get you into the Public Maintainers list. 
Thanks!

**Comment by iyangsj** [comment]
@amye The maintainers file for BFE is: https://github.com/bfenetworks/bfe/blob/develop/MAINTAINERS.md

**Comment by amye** [comment]
You've been added to https://www.cncf.io/sandbox-projects/ with a placeholder, I'm having trouble getting your icon to work! Can you send that to me directly?

**Comment by iyangsj** [comment]
@amye  'thelinuxfoundation' and 'caniszczyk' have been added as initial org owners. (https://github.com/bfenetworks)

**Comment by caniszczyk** [comment]
@iyangsj thanks, let me know when you want to do the domain transfer, you have to unlock the domain + send us an auth code: caniszczyk@linuxfoundation.org

**Comment by amye** [comment]
@iyangsj Just checking in on the domain transfer, that seems to be the last outstanding thing here.

**Comment by amye** [comment]
Domain is transferred, marking this as closed.
