### ISSUE TITLE
[PROJECT ONBOARDING] Dex

### ISSUE THREAD

**Issue by caniszczyk** [cncf/toc#472]
Welcome to CNCF Project Onboarding!

Please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/master/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Has your project adopted open governance already? see http://opengovernance.dev

Formal onboarding:
- [x] Domain: transfer domain to CNCF/LF (ITx)
- [ ] Trademarks: transfer any trademark and logo mark assets over to the LF
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners
- [x] Artwork: Ensure logos present on https://github.com/cncf/artwork
- [x] Website: ensure LF footer is there and website guidelines followed, analytics transferred
- [x] Create maintainer list + added to aggregated https://maintainers.cncf.io list - OWNERS file needed
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Trail Map: update CNCF trail map if relevant (incubating projects and above)
- [x] Update https://landscape.cncf.io
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access
- [x] Schedule monthly project sync with CNCF staff

**Comment by amye** [comment]
Adding @justaugustus from the project side.

**Comment by sagikazarmark** [comment]
Hello!

I'm a dex maintainer. How can I help, to move things forward. What are the tasks from the list above that we can clear?

Thanks,
Mark

**Comment by JoelSpeed** [comment]
I was just typing something very similar as that message popped up @sagikazarmark! I'll make mine simpler

Also a maintainer, let me know if there's anything I can help with

**Comment by bonifaido** [comment]
Another maintainer here, ready to help!

**Comment by justaugustus** [comment]
@sagikazarmark @JoelSpeed @bonifaido -- I'll help coordinate. Email to follow later today.

**Comment by justaugustus** [comment]
I've invited both @caniszczyk and @thelinuxfoundation as owners to https://github.com/dexidp.

**Comment by justaugustus** [comment]
Sent @amye the [maintainers list](https://github.com/dexidp/dex/blob/master/MAINTAINERS) with current affiliations, which has been reflected in the [Maintainers List](https://docs.google.com/spreadsheets/d/1Pr8cyp8RLrNGx9WBAgQvBzUUmqyOv69R7QAFKhacJEM/edit?usp=sharing).

Cross-tracking this on the project level at https://github.com/dexidp/dex/issues/1739.

**Comment by amye** [comment]
If the project can take care of the top checklist and check off the 'services for project', that would be super. 
Other things: 
any logo files?

**Comment by amye** [comment]
You have been added to https://www.cncf.io/sandbox-projects/ with the CNCF logo, we can replace and edit with the logos when we have those.

**Comment by bonifaido** [comment]
The dexidp repository contains these logo files: https://github.com/dexidp/dex/tree/master/Documentation/logos I think we can use these for now.

**Comment by caniszczyk** [comment]
@amye is Dex almost set?

**Comment by amye** [comment]
Trademark/asset transfer is our last thing!

**Comment by amye** [comment]
Closing as trademark is proceeding offline.
