### ISSUE TITLE
[PROJECT ONBOARDING] KUDO

### ISSUE THREAD

**Issue by caniszczyk** [cncf/toc#473]
Welcome to CNCF Project Onboarding!

Please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/master/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Has your project adopted open governance already? see http://opengovernance.dev

Formal onboarding:
- [x] Domain: transfer domain to CNCF/LF (ITx)
- [ ] Trademarks: transfer any trademark and logo mark assets over to the LF
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners
- [x] Artwork: Ensure logos present on https://github.com/cncf/artwork
- [ ] Website: ensure LF footer is there and website guidelines followed, analytics transferred
- [x] Create maintainer list + added to aggregated https://maintainers.cncf.io list - OWNERS file needed
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Trail Map: update CNCF trail map if relevant (incubating projects and above)
- [x] Update https://landscape.cncf.io
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access
- [x] Schedule monthly project sync with CNCF staff

**Comment by amye** [comment]
Adding @guenter for onboarding from the project side.

**Comment by gerred** [comment]
@amye will you assign this to me? Thank you!

**Comment by amye** [comment]
@gerred: The project gets the checklist on top, CNCF staff gets the other checklist. 
If you can give me your maintainers file (just a link) and your logo, we can get you onboarded.

**Comment by gerred** [comment]
:+1:

Maintainers: https://github.com/kudobuilder/kudo/blob/main/OWNERS
Logo assets as attached. 

[KUDO logo variations - CNCF.zip](https://github.com/cncf/toc/files/4833253/KUDO.logo.variations.-.CNCF.zip)

**Comment by gerred** [comment]
We are open governance as far as process but now putting that together with our seed leadership group as far as continued open governance goes. Otherwise, I understand the requirements and process as the current chair of KUDO.

**Comment by amye** [comment]
Maintainers.cncf.io has been updated, let me know if anyone's missing.

**Comment by amye** [comment]
Added to https://www.cncf.io/sandbox-projects/ with the logo that was sent over. Let me know if you have more links to add!

**Comment by gerred** [comment]
> Welcome to CNCF Project Onboarding!
> 
> Please ensure that you:
> 
> * [x]  Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/master/process/project_proposals.adoc#introduction
> * [x]  Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
> * [x]  Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
> * [x]  Has your project adopted open governance already? see http://opengovernance.dev
> 
> Formal onboarding:
> 
> * [ ]  Domain: transfer domain to CNCF/LF (ITx)
> * [ ]  Trademarks: transfer any trademark and logo mark assets over to the LF
> * [x]  GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners
> * [ ]  Artwork: Ensure logos present on https://github.com/cncf/artwork
> * [ ]  Website: ensure LF footer is there and website guidelines followed, analytics transferred
> * [x]  Create maintainer list + added to aggregated https://maintainers.cncf.io list - OWNERS file needed
> * [ ]  Devstats: add to devstats https://devstats.cncf.io/
> * [ ]  Marketing: update relevant intro + slide decks
> * [ ]  Trail Map: update CNCF trail map if relevant (incubating projects and above)
> * [ ]  Update https://landscape.cncf.io
> * [ ]  Events: update CFP + Registration + CFP Area forms
> * [ ]  ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
> * [ ]  CNCF Welcome Email Sent to confirm maintainer list access
> * [ ]  Schedule monthly project sync with CNCF staff

**Comment by gerred** [comment]
@caniszczyk and @thelinuxfoundation have been invited as owners to kudobuilder

**Comment by amye** [comment]
@gerred: Looks like the footer needs to be updated, guidelines are here - https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices

**Comment by gerred** [comment]
Yep, that slipped through. On it for both kuttl.dev and kudo.dev

**Comment by amye** [comment]
Oh super, thanks! Trademarks (if any) and domain look to be the only things left.

**Comment by gerred** [comment]
What do we need for that? I think we're ready to go on those two things, just need the info to proceed.

**Comment by amye** [comment]
Checking in on the footer change, @gerred. Thanks!

**Comment by amye** [comment]
Footer change is dependent on the transfer paperwork, but I will mark this as closed as that's in progress in email.
