### ISSUE TITLE
[PROJECT ONBOARDING] Checkov

### ISSUE THREAD

**Issue by schosterbarak** [cncf/toc#475]
Welcome to CNCF Project Onboarding!

Please ensure that you:
- [ ] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/master/process/project_proposals.adoc#introduction
- [ ] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [ ] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [ ] Has your project adopted open governance already? see http://opengovernance.dev

Formal onboarding:
- [ ] Domain: transfer domain to CNCF/LF (ITx)
- [ ] Trademarks: transfer any trademark and logo mark assets over to the LF
- [ ] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners
- [ ] Artwork: Ensure logos present on https://github.com/cncf/artwork
- [ ] Website: ensure LF footer is there and website guidelines followed, analytics transferred
- [ ] Create maintainer list + added to aggregated https://maintainers.cncf.io list - OWNERS file needed
- [ ] Devstats: add to devstats https://devstats.cncf.io/
- [ ] Marketing: update relevant intro + slide decks
- [ ] Trail Map: update CNCF trail map if relevant (incubating projects and above)
- [ ] Update https://landscape.cncf.io
- [ ] Events: update CFP + Registration + CFP Area forms
- [ ] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [ ] CNCF Welcome Email Sent to confirm maintainer list access
- [ ] Schedule monthly project sync with CNCF staff

**Comment by amye** [comment]
Hey there! This is for projects that have been accepted into the CNCF Sandbox. 
You're looking for https://docs.google.com/forms/u/2/d/1bJhG1MuM981uQXcnBMv4Mj9yfV5_q5Kwk3qhBCLa_5A/ which is where you can apply for inclusion.
