### ISSUE TITLE
[PROJECT ONBOARDING]  CNI-Genie

### ISSUE THREAD

**Issue by amye** [cncf/toc#477]
Welcome to CNCF Project Onboarding!

Please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/master/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Has your project adopted open governance already? see http://opengovernance.dev

Formal onboarding:
- [x] Domain: transfer domain to CNCF/LF (ITx)
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners
- [x] Artwork: Ensure logos present on https://github.com/cncf/artwork
- [x] Website: ensure LF footer is there and website guidelines followed, analytics transferred
- [x] Create maintainer list + added to aggregated https://maintainers.cncf.io list - OWNERS file needed
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Trail Map: update CNCF trail map if relevant (incubating projects and above)
- [x] Update https://landscape.cncf.io
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access
- [x] Schedule monthly project sync with CNCF staff

**Comment by amye** [comment]
Adding @sushanthakumar for project onboarding.

**Comment by amye** [comment]
You've been added to the https://www.cncf.io/sandbox-projects/ page with a placeholder logo. Once I get that logo, I can replace the placeholder with the real one.

**Comment by sushanthakumar** [comment]
Mentioning @kevin-wangzefeng

**Comment by amye** [comment]
Lovely! Logo is probably the biggest thing right now.

**Comment by kevin-wangzefeng** [comment]
@amye
CNI-Genie doesn't have logo yet, there is a draft design, not yet finished.
BTW, there's no websit nor domain name for CNI-Genie yet, I guess they are optional for a project, are they?

**Comment by amye** [comment]
That's perfectly fine, they are optional. Marking domain + website as complete because there aren't any.

**Comment by amye** [comment]
Just to confirm, no trademarks to transfer? Last piece is adding to the GH repo as owners.

**Comment by amye** [comment]
@kevin-wangzefeng: can you confirm that there's no trademarks to come across and 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners?

**Comment by kevin-wangzefeng** [comment]
@amye 
Invitations sent to 'thelinuxfoundation' and 'caniszczyk'.
And there's no trademarks

**Comment by amye** [comment]
Closing this, we are set here!
