### ISSUE TITLE
set expectations about response time to issues and PRs

### ISSUE THREAD

**Issue by michelleN** [cncf/toc#489]
Sometimes issues/PRs linger in this queue without being addressed. This causes confusion for maintainers. We should work towards setting expectations around when and who (TOC or CNCF staff) should respond to each type of issue.

**Comment by RichiH** [comment]
As anecdata, this issue has been sitting for 20 days without action or response.

With both my maintainer and my chair hats on, I wholeheartedly agree; relatedly, votes on the TOC mailing list can also turn into a little bit of a waiting game and the process to get things moving can be somewhat opaque.

A mechanism I have seen work quite well for other, similar roles is a two-prong approach.
1. On the one hand, tasks have pre-announced deadlines and reminders.
2. On the other hand, time commitment and ongoing availability is made a quantitative, not a qualitative, requirement during election phases.

https://github.com/cncf/foundation/blob/master/charter.md#6-technical-oversight-committee-toc already states that
> (d) Criteria for Nomination. Nominees for the TOC shall:
>  i. commit that they have the available bandwidth to make the time to invest in the CNCF TOC,

having a quantitative requirement would make it easier to negotiate time budgets into everyone's OKRs & quarterly planning with their respective managers.
