### ISSUE TITLE
Presentation of SPIFFE to the CNCF TOC

### ISSUE THREAD

**Issue by ajessup** [cncf/toc#49]
Hi folks,

We'd like to introduce the TOC to [SPIFFE](https://github.com/spiffe/spiffe) and [SPIRE](https://github.com/spiffe/spire) an Apache 2.0 licensed platform originally proposed by @jbeda for issuing identities to software systems in heterogenous environments. It is particularly well suited for elastic or ephemeral cloud workloads and container schedulers such as Kubernetes. The goal of the project is to provide this API on a wide range of platforms.

In presenting this to the TOC, we will demonstrate how SPIRE can be used to securely issue identities to workloads running in a Kubernetes cluster, and workloads running outside of that cluster, and discuss the ways in which those identities can be used. We also hope to discuss the ways that SPIFFE and SPIRE support the CNCF mission, and a path forward to CNCF acceptance.

Ideally we'd like to present the first week of November.

**Comment by caniszczyk** [comment]
You're set for Nov 7th: https://github.com/cncf/toc/blob/master/README.md#scheduled-community-presentations

Does that work @ajessup

**Comment by ajessup** [comment]
Perfect, thanks!

**Comment by caniszczyk** [comment]
@monadic @bgrant0607 are you OK with this since you have spoken with the SPIFFE team before on behalf of the @cncf/toc

**Comment by sebgoa** [comment]
On Wed, Sep 20, 2017 at 10:51 PM, Andrew J <notifications@github.com> wrote:

> Hi folks,
>
> We'd like to introduce the TOC to SPIFFE
> <https://github.com/spiffe/spiffe> and SPIRE
> <https://github.com/spiffe/spire>
>

That SPIRE link does not work

**Comment by ajessup** [comment]
Hey @sebgoa - the SPIRE repository is currently private (we're planning to open it up next week). I've invited you in the meantime. If there are others who would like access, just let me know.

**Comment by caniszczyk** [comment]
@ajessup feel free to invite me

**Comment by ajessup** [comment]
@caniszczyk done

**Comment by monadic** [comment]
@caniszczyk yes let's move to presentation phase

**Comment by caniszczyk** [comment]
Perfect thanks!

**Comment by bgrant0607** [comment]
+1

**Comment by suniljames** [comment]
@caniszczyk what time are you proposing we conduct this meeting? I'd like to get things on the calendar ASAP for my team.

**Comment by suniljames** [comment]
Ignore. I see the designated meeting times.
