### ISSUE TITLE
further clarify annual review process

### ISSUE THREAD

**Issue by michelleN** [cncf/toc#490]
Currently what is documented is the submission process and review outcomes. There needs to be more documentation on the process itself (what happens after submission) so that maintainers have a clear understanding of what to expect.

**Comment by amye** [comment]
This should be resolved as of the August 11th meeting, we're now moving to annual reviews pass with a simple majority vote by the TOC in a closed TOC meeting that is recorded and made public. 
Will be updating the annual review documentation today.
