### ISSUE TITLE
Clarify CNCF project acceptance criteria

### ISSUE THREAD

**Issue by caniszczyk** [cncf/toc#5]
It's great that we now have a formal project proposal process, one thing we haven't done yet is to clarify acceptance criteria for new technologies to include in CNCF (outside of what is specified in the charter: https://cncf.io/governance). We can choose to do this as an amendment section to the project proposal process or include in another document.

**Comment by idvoretskyi** [comment]
@caniszczyk it should be already defined here https://github.com/cncf/toc/blob/master/process/graduation_criteria.adoc

**Comment by caniszczyk** [comment]
closing this old issue, but the TOC principles will help cover this
