### ISSUE TITLE
Presentation of the Open Policy Agent project to the CNCF TOC

### ISSUE THREAD

**Issue by tsandall** [cncf/toc#51]
Hello!

We would like to introduce [the Open Policy Agent (OPA) project](http://www.openpolicyagent.org) to the TOC. OPA is an Apache 2.0 licensed, general-purpose policy engine. OPA can be applied to any system, at any layer of the stack. OPA’s goal is to enable policy-based control throughout the cloud native ecosystem.

As part of the presentation, we can provide an overview of how OPA works as well examples of integrations with projects such as Kubernetes, Istio, and Docker. In addition, we will provide an overview of future work planned with our design partners at Google.

The goal of the discussion would be to figure out how OPA can be accepted into the CNCF.

**Comment by caniszczyk** [comment]
@tsandall we can make Nov 21st work

@cncf/toc are you OK with OPA being presented? It is licensed under the ALv2

**Comment by tsandall** [comment]
Nov 21st would be great!

**Comment by bgrant0607** [comment]
That's the week of Thanksgiving in the US. A number of people may be on vacation, including me. I suggest we cancel or move that week's meeting.

**Comment by bgrant0607** [comment]
@caniszczyk Yes, @kenowens12 and I asked for a presentation.

**Comment by bgrant0607** [comment]
cc @alfus

**Comment by caniszczyk** [comment]
@bgrant0607 what are your thoughts about bumping up the meeting a week? Nov 14th?

cc: @monadic 

Anyways, we can discuss this on the TOC call next week.

**Comment by bgrant0607** [comment]
@caniszczyk The 14th would work for me.

**Comment by tsandall** [comment]
Nov 14th is fine on this side.

**Comment by caniszczyk** [comment]
@tsandall you're all set for Nov 14th

cc: @cncf/toc
