### ISSUE TITLE
[PROJECT ONBOARDING] Open Service Mesh

### ISSUE THREAD

**Issue by amye** [cncf/toc#535]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project. 

From the project side, please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/master/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Has your project adopted open governance already? see http://opengovernance.dev

Formal onboarding:
- [x] Owners file: Please add a link to your owners file to this issue, this is used to be able to create your maintainers mailing list. 
- [x] Create maintainer list + added to aggregated https://maintainers.cncf.io list
- [x] Domain: transfer domain to CNCF/LF (ITx)
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] Artwork: Ensure logos present on https://github.com/cncf/artwork
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices) followed
- [x] Website: Analytics transferred
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Trail Map: update CNCF trail map if relevant (incubating projects and above)
- [x] Update https://landscape.cncf.io
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access
- [x] Schedule monthly project sync with CNCF staff

**Comment by amye** [comment]
@lachie83, @bridgetkromhout, we'll be tracking onboarding in here.
If I can get a link to your OWNERS file and your artwork, I should be able to get most things done on our end. 
We'd like to have onboarding complete by September 22nd.

**Comment by lachie83** [comment]
Fantastic! Thanks @amye. I will provide

**Comment by lachie83** [comment]
Current OWNERS can be found here - https://github.com/openservicemesh/osm/blob/main/CODEOWNERS. Artwork here - https://github.com/openservicemesh/osm/tree/main/community/logos

**Comment by lachie83** [comment]
We have a mailing list here and will need to migrate to the new one once available - https://groups.google.com/g/openservicemesh

**Comment by amye** [comment]
Ah, looks like you'll need cncf-openservicemesh-users@lists.cncf.io?

**Comment by amye** [comment]
So on the OWNERS file, this gives us a list of who all should be on the maintainers.cncf.io page. 
Crossplane is a good example: https://github.com/crossplane/crossplane/blob/master/OWNERS.md

**Comment by lachie83** [comment]
Okay. I will gather and get back to you

**Comment by lachie83** [comment]
OWNERS list will land in the following PR - https://github.com/openservicemesh/osm/pull/1677

**Comment by lachie83** [comment]
Could we also request the creation of cncf-openservicemesh-security@lists.cncf.io with the maintainers list please?

**Comment by lukaszgryglicki** [comment]
DevStats page [added](https://openservicemesh.devstats.cncf.io).

**Comment by bridgetkromhout** [comment]
Hi, @amye! I'm back from vacation and super-excited to work on this with you! 

> Could we also request the creation of cncf-openservicemesh-security@lists.cncf.io with the maintainers list please?

What do you need from us to set this up? Thanks!

**Comment by amye** [comment]
Invites are away for both lists.

**Comment by amye** [comment]
Big stuff remaining: 
Domain: transfer domain to CNCF/LF (ITx)
 Trademarks: transfer any trademark and logo mark assets over to the LF
 GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
 Website: ensure LF footer is there and website guidelines followed
 Website: Analytics transferred

@bridgetkromhout, let me know if you need more help from me on any of this.

**Comment by bridgetkromhout** [comment]
> GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership

Both invites have now been sent.

**Comment by amye** [comment]
Confirmed on the GH, landscape updates are in a PR: https://github.com/cncf/landscape/pull/1834

**Comment by bridgetkromhout** [comment]
Hi, @amye - here is the current status.

> Domain: transfer domain to CNCF/LF (ITx)

In progress (current status: inside Microsoft)

> Trademarks: transfer any trademark and logo mark assets over to the LF

We did not apply to register “Open Service Mesh” as a trademark on any of the registries, so there’s nothing else to be done. There are no trademark rights to transfer to the CNCF.

> Website: ensure LF footer is there and website guidelines followed

https://openservicemesh.io/ now has CNCF footer. Thanks, @flynnduism!

>Website: Analytics transferred

Appropriate invite sent to LF account.

**Comment by amye** [comment]
If there's no registered trademark, then the non-registered agreement is the appropriate one:
https://github.com/cncf/foundation/blob/master/agreements/CNCF%20Trademark%20and%20Account%20Assignment%20Agreement%20(2020%20-%20no%20reg%20trademarks).pdf

**Comment by bridgetkromhout** [comment]
Waiting to hear back internally as to who signs the non-registered agreement.
Domain transfer in progress.

**Comment by bridgetkromhout** [comment]
I noticed that we aren't using the OSM logo yet at https://www.cncf.io/sandbox-projects/ - logos are in https://github.com/openservicemesh/osm/tree/main/community/logos and I put in a PR to fix the listing in the CNCF artwork repo (https://github.com/cncf/artwork/pull/193). What else do we need to do to make the logo show up on the sandbox page?

**Comment by amye** [comment]
Resolved on the logo!

**Comment by bridgetkromhout** [comment]
Put in a PR to fix the logo on the landscape: https://github.com/cncf/landscape/pull/1851

**Comment by bridgetkromhout** [comment]
Worked with @amye to update social icons on  https://www.cncf.io/sandbox-projects/

Waiting for Microsoft people on the trademark forms.

**Comment by bridgetkromhout** [comment]
Hi @amye, I see that `openservicemesh.io` has transferred; can you check on the progress for `openserviceme.sh`?

**Comment by bridgetkromhout** [comment]
From CNCF Slack:
```
Chris Aniszczyk  1:20 PM
It's up to the OSM maintainers but they need to choose between the CLA / DCO
```
https://github.com/openservicemesh/osm/blob/main/CONTRIBUTING.md#contributor-license-agreement
Update needed - I'll follow up.
