### ISSUE TITLE
SIG charters should live in TOC repo

### ISSUE THREAD

**Issue by michelleN** [cncf/toc#538]
There was a conversation about where a CNCF SIG's charter should - the TOC repo (this one) or the SIG's own GitHub repo.
I believe the conclusion was SIG charters should live in this repo because:
- the TOC votes on charters
- the TOC should be informed of (and potentially vote on) any charter changes
The charter should be linked in the SIG's repo.

Do we still want to do this? If so, we should document this policy and update the reference to [SIG security's charter](https://github.com/cncf/toc/blob/master/sigs/security.md) in this repo. Does anyone have any objections? I just checked and it looks like everyone's charter except SIG security's is indeed in this repo. cc/ @amye @lizrice @cncf/toc

**Comment by lizrice** [comment]
Yes, I completely agree
