### ISSUE TITLE
Rename CNCF SIGs to avoid confusion with other types of SIG

### ISSUE THREAD

**Issue by lizrice** [cncf/toc#549]
It's increasingly confusing that we have groups called Special Interest Groups (SIGs) some of which operate at the CNCF-wide level, and others that are project-specific in Kubernetes. Since the Kubernetes project adopted the term first, I propose they should keep the term SIG and we could rename the CNCF-wide ones that report in to the TOC. For similar reasons let's not use Working Group (WG) since some of those exist already. 

Some initial ideas:
* Special Working Group (SWG)
* TOC Sub Committee (TSC)
* TOC Specialist Group (TSG) 

Thoughts?

**Comment by nikhita** [comment]
cc @parispittman -- I believe Paris has been working on alternate names as a part of SIG Contributor Strategy

**Comment by parispittman** [comment]
i never finished it but it's here https://hackmd.io/UWWVsKkrTsuZ7W2x3qxTzA

i highly recommend the rename.

**Comment by raravena80** [comment]
Renaming sounds like a good idea to me. 

I like "TOC <> Council" or "<> TOC Council" (TOCC)
Instead of working groups what about "<> Workstream" (WS)?

It might also be a good idea to come up with a list of choices and hold a vote.

My two cents.

**Comment by tomkerkhove** [comment]
How about TOC Advisory Council (TAC)?

**Comment by amye** [comment]
@chira001 has proposed renaming for 'Technical Advisory Group' in the Feb 16 TOC meeting.

**Comment by lizrice** [comment]
I'm calling for a vote on the proposal to change the names of CNCF SIGs to CNCF TAGs (technical advisory group).

This will also constitute an experiment in TOC voting by GitHub. Please cast your vote by adding a comment in the form +1/-1 [binding].

+1 binding

**Comment by dims** [comment]
+1 (non binding)

**Comment by chira001** [comment]
+1 (non-binding)

**Comment by mrbobbytables** [comment]
+1 (non-binding)

**Comment by raravena80** [comment]
+1 (nb)

**Comment by nikhita** [comment]
+1 (non-binding)

**Comment by qnetter** [comment]
+1 nb

**Comment by gerred** [comment]
+1 nb

**Comment by chasemp** [comment]
+1 non-binding

**Comment by kgamanji** [comment]
+1 non-binding

**Comment by xing-yang** [comment]
+1 (non-binding)

**Comment by kmova** [comment]
+1 (non-binding)

**Comment by chris-short** [comment]
+1 non-binding

**Comment by alena1108** [comment]
+1 binding

**Comment by RandyAbernethy** [comment]
+1 nb

**Comment by vfiftyfive** [comment]
+1 nb

**Comment by saad-ali** [comment]
I was never a fan of overloading the meaning of SIG. This seems like a step in the right direction.
+1 binding

**Comment by RichiH** [comment]
+/- 0 non-binding

I agree that "CNCF SIG" is confusing next to "K8s SIG".

With my SIG O11y chair hat on, I feel our mode of operation is aligned with how Working Groups in RIPE and IETF work; which is what I model my actions as chair upon.

While there are plenty of hits for "Technical Advisory Group" on Google, Wikipedia does not list "TAG" as such and I feel as if uncommon naming might increase confusion.

As such, I would personally lean towards "WG" as a strong opinion loosely held. What matters in the end is the work done within the groups.

**Comment by ultrasaurus** [comment]
-1 non-binding

Originally, I disliked the name SIG and felt WG (Working Group) was fine, but TOC drove rename/redefinition, including strongly advocating for using exact name as K8s uses.  I was never involved in Kubernetes SIGs, but had good experiences with ACM SIGGraph and thought of that as a great model -- a large group of members, where a subset would be more active and contribute to defining programs and activities (where one activity is advising the TOC).  

Agree that the work is what matters and don't expect that name change will affect the operation of any of the groups.  If y'all decided to change the name, I think it will make outreach outside of CNCF require a bit more explanation of the inner workings of CNCF/TOC to explain TAG-Security, maybe we should consider short-hand abbreviated of cn-security, CNSecurity, or cncf/security.

Sarah Allen, SIG-Security co-chair

**Comment by justincormack** [comment]
@RichiH we also have WGs though, as part of the SIGs....

**Comment by danmikita** [comment]
+1 binding

**Comment by saad-ali** [comment]
> As such, I would personally lean towards "WG" as a strong opinion loosely held. What matters in the end is the work done within the groups.

I do like "Workgroup" > "technical advisory group". But both > "SIG".

**Comment by RichiH** [comment]
@justincormack That is a good point. In my nomenclature, the SIGs would be part of the WGs, but that would be too confusing of a flip and not solve the naming dominance of K8s.

Renaming the current SIGs to WGs, and the current WGs to something else would make more sense to me coming from an ISP & networking background, but that is a minority position, which is fine.

For the avoidance of bikeshedding I +/-0 on purpose.

**Comment by thschue** [comment]
+1 non-binding

**Comment by grissomsh** [comment]
+1 non-binding

**Comment by dshaw** [comment]
+1 non-binding

**Comment by SamDelamarter** [comment]
+1

**Comment by magnologan** [comment]
+1 nb

**Comment by jrsapi** [comment]
+1 nb

**Comment by freddyfernando** [comment]
+1 binding

**Comment by cdavisafc** [comment]
+1 binding

with SIGs(TAGs) already having working groups within them, I like that this proposal doesn’t have those potential cascading effects. Plus, I just like TAG.

**Comment by resouer** [comment]
+1 Binding

**Comment by anvega** [comment]
It used to create confusion until we starting referring to the groups as "CNCF SIG-X" or "Kubernetes SIG-Y". I hardly hear a mention of any SIG without a preface of the organization it is affiliated with in case the context is not already clear. 

Semantics matter. Established recognized names also matter. 

For SIG-Security, the exercise to rename would be exceedingly onerous as it would require:

* Updates to use of the name and link to the GitHub repository across a number of publications such as white papers, project assessments, and other collateral.
* Changes to repository name, comms channels, youtube channel. 
* Logo redesign

So here are other solutions to consider:

1. We could just call C-SIGs all of the CNCF level SIGs. 

2. If the confusion exists only where names overlap as in the case of Network, Security, and Storage. We could look at calling Security, Trust and Safety for Security, Connectivity for Network, and Data Storage for Storage. 

3. Just leave it as is. We've gotten along just fine for a now seemingly long time.

**Comment by lizrice** [comment]
There is _undoubtedly_ confusion - on an almost daily basis I speak with people who are confused between the two forms of SIG. CNCF staff will help support the change.

**Comment by fkautz** [comment]
@lizrice there is definitely some term overloading, but is there enough to disaggregate them at this point? I don't tend to see people being confused and if there is confusion, people tend to ask which one they are discussing. I worry that there will be significant work to modify existing resources which may cause additional confusion when they point at something that has been renamed.

K8s has working groups in addition to SIGs. Many CNCF projects have their own SIGs. The term SIG also predates both K8s and CNCF. Perhaps we can raise awareness around the naming convention, say CNCF SIG or K8s SIG (or SPIRE SIG or NSM SIG) instead of just SIG.

**Comment by tonit** [comment]
+1 non-binding for SIG -> TAG renaming.

Initially i found SIGs confusing since it was an unfamiliar term. Its a thing one needs to google once.
Then indeed there was confusion about Kubernetes SIGs and CNCF SIGs and the fact that there are different things.

So, renaming SIG to TAG inside CNCF will not fix the former issue, but at least the latter.
Also, i feel Workinggroups/WGs still exists inside TAGs, there are more "lightweight", thats why you don't just want to created (nested?) TAGs I guess.

**Comment by JimStLeger** [comment]
+1 non-binding

(and I'm looking forward to the day where SIGs -> K8s and TAGs -> CNCF)

**Comment by cblecker** [comment]
+1 non-binding for SIG -> TAG rename

**Comment by rochaporto** [comment]
+1 binding

**Comment by dzolotusky** [comment]
+1 binding

**Comment by dims** [comment]
+1 binding

**Comment by tabbysable** [comment]
K8s SIG Security says "thanks" -- this is indeed a source of confusion!

**Comment by justaugustus** [comment]
Retroactive +1 nb!

**Comment by amye** [comment]
The proposal to rename Special Interest Groups to Technical Advisory Groups (https://github.com/cncf/toc/issues/549) has been approved.

8/11
+1 Binding:
Liz Rice: https://github.com/cncf/toc/issues/549#issuecomment-780042038
Alena Prokharchyk : https://github.com/cncf/toc/issues/549#issuecomment-780761290
Saad Ali: https://github.com/cncf/toc/issues/549#issuecomment-780795486
Cornelia Davis: https://github.com/cncf/toc/issues/549#issuecomment-781705738
Lei Zhang: https://github.com/cncf/toc/issues/549#issuecomment-781710347
Ricardo Rocha: https://github.com/cncf/toc/issues/549#issuecomment-802719496
Dave Zolotusky: https://github.com/cncf/toc/issues/549#issuecomment-802952655
Davanum Srinivas: https://github.com/cncf/toc/issues/549#issuecomment-802988151

+1 NB
Alex Chircop: https://github.com/cncf/toc/issues/549#issuecomment-780191708
Bob Killen: https://github.com/cncf/toc/issues/549#issuecomment-780197766
Ricardo Aravena: https://github.com/cncf/toc/issues/549#issuecomment-780226224
Nikhita Raghunath: https://github.com/cncf/toc/issues/549#issuecomment-780261178
Roger Klorese: https://github.com/cncf/toc/issues/549#issuecomment-780263282
Gerred Dillon: https://github.com/cncf/toc/issues/549#issuecomment-780696438
Chase Pettet: https://github.com/cncf/toc/issues/549#issuecomment-780700787
Katie Gamanji: https://github.com/cncf/toc/issues/549#issuecomment-780702413
Xing Yang: https://github.com/cncf/toc/issues/549#issuecomment-780703403
Kiran Mova: https://github.com/cncf/toc/issues/549#issuecomment-780726704
Chris Short: https://github.com/cncf/toc/issues/549#issuecomment-780734687
Randy Abernathy: https://github.com/cncf/toc/issues/549#issuecomment-780763203
Nicholas Vermande: https://github.com/cncf/toc/issues/549#issuecomment-780794049
Dan Mikita: https://github.com/cncf/toc/issues/549#issuecomment-780826936
Thomas Schuetz: https://github.com/cncf/toc/issues/549#issuecomment-780837567
Grissom Wang: https://github.com/cncf/toc/issues/549#issuecomment-780978092
Dan Shaw: https://github.com/cncf/toc/issues/549#issuecomment-781047233
Sam Delamarter: https://github.com/cncf/toc/issues/549#issuecomment-781316334
Magno Logan: https://github.com/cncf/toc/issues/549#issuecomment-781445798
Joseph Sandoval: https://github.com/cncf/toc/issues/549#issuecomment-781455666
Freddy Fernando: https://github.com/cncf/toc/issues/549#issuecomment-781518289
Toni Menzel: https://github.com/cncf/toc/issues/549#issuecomment-799755814
Jim St Leger: https://github.com/cncf/toc/issues/549#issuecomment-801215770
Christoper Blecker: https://github.com/cncf/toc/issues/549#issuecomment-802505317

0:
Richard Hartmann: https://github.com/cncf/toc/issues/549#issuecomment-780799967

-1
Sarah Allen: https://github.com/cncf/toc/issues/549#issuecomment-780810240
