### ISSUE TITLE
Istio presenting to the TOC

### ISSUE THREAD

**Issue by caniszczyk** [cncf/toc#55]
The Istio team would like to request presenting to the TOC on Nov 7th: https://istio.io/

Are you OK with this @cncf/toc cc: @monadic @bgrant0607

**Comment by bgrant0607** [comment]
Works for me

**Comment by monadic** [comment]
Yes, let's invite them, Nov 7th is a good date.

**Comment by caniszczyk** [comment]
Thanks, all set!

https://github.com/cncf/toc/commit/b299bca5b5cbf592e1dfaf2ed2c88e85310b9122
