### ISSUE TITLE
TODO: develop maturation requirements authoritative process

### ISSUE THREAD

**Issue by jberkus** [cncf/toc#554]
Per discussion in #551, we have an issue that we don't have anywhere there is a complete, comprehensive list of requirements for all projects at each maturation level.   As an example, the list in graduation_criteria.adoc doesn't match the list of required form blanks on the Sandbox application form, and it's unclear to applicants which list is correct.  This is largely because there isn't a centralized process for updating the requirements, and a single source of truth.

Putting this year as a TODO to develop such a process.  The idea would be to have a comprehensive, authoritative list in one place that would be used to generate the various other documents, such as a shorter summary version of level requirements, the Sandbox form, the due dilligence documentation, etc.

**Comment by dims** [comment]
@jberkus do we still need to do this?

**Comment by amye** [comment]
We actually did some of this in 2021, closing out for end of year clean.

**Comment by jberkus** [comment]
We did not do it, or even any major part of it.  So yeah, it's still open.
