### ISSUE TITLE
[PROJECT ONBOARDING] SchemaHero 

### ISSUE THREAD

**Issue by amye** [cncf/toc#555]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project. 

From the project side, please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/master/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Has your project adopted open governance already? see http://opengovernance.dev

Formal onboarding:
- [x] Owners file: Please add a link to your owners file to this issue, this is used to be able to create your maintainers mailing list. 
- [x] Create maintainer list + added to aggregated https://maintainers.cncf.io list
- [x] Domain: transfer domain to CNCF/LF (ITx)
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] Artwork: Ensure logos present on https://github.com/cncf/artwork
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices) followed
- [x] Website: Analytics transferred
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Trail Map: update CNCF trail map if relevant (incubating projects and above)
- [x] Update https://landscape.cncf.io
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access
- [x] Schedule monthly project sync with CNCF staff

**Comment by amye** [comment]
https://github.com/schemahero/schemahero/blob/master/OWNERS.md looks to be owners file, @marccampbell. Any artwork repos?

**Comment by marccampbell** [comment]
@amye We don't have a separate repo for the artwork, but there are logos in svg and png formats in this and the docs repo.  Adding @graysonnull to help here also to help track it down and make sure you have the formats needed.

**Comment by GraysonNull** [comment]
Hi @amye I can add an artwork directory in the schemahero repo with png and svg assets. Based on what I see in the cncf/artwork repo I need a color, black, and white version is that correct?

**Comment by amye** [comment]
That would be splendid, thank you!

**Comment by GraysonNull** [comment]
@amye No problem! Here is the new directory: https://github.com/schemahero/schemahero/tree/master/artwork

Let me know if you need any other variants or file types for the logos and I can get them in there. 

Thanks!

**Comment by lukaszgryglicki** [comment]
Artworks are usually provided by creating a PR against: https://github.com/cncf/artwork

**Comment by GraysonNull** [comment]
No problem, here is the PR for the schemahero artwork https://github.com/cncf/artwork/pull/203

**Comment by amye** [comment]
@GraysonNull: Great! 
Next big things: 
 Domain: transfer domain to CNCF/LF (ITx)
 Trademarks: transfer any trademark and logo mark assets over to the LF
 GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
 Website: ensure LF footer is there and website guidelines followed
 Website: Analytics transferred
Where would you like to be on the landscape?

**Comment by lukaszgryglicki** [comment]
Test DevStats [page](https://schemahero.teststats.cncf.io) added, not added to [All CNCF](https://all.devstats.cncf.io) yet.

**Comment by marccampbell** [comment]
@amye GitHub owner invites sent!

Can you provide any guidance on the domain transfer, how to do it securely?

**Comment by amye** [comment]
Drop me an email with the transfer code and any details about zone files to amye@linuxfoundation.org

**Comment by lukaszgryglicki** [comment]
Prod [page](https://schemahero.devstats.cncf.io) added too, also added Projects health summary [report](https://all.teststats.cncf.io/d/53/projects-health-table?orgId=1) (on the test), prod `All CNCF` is pending.

**Comment by marccampbell** [comment]
@amye We think that SchemaHero best fits in the "Database" category on the landscape. It's not a database engine, but SchemaHero only works to operate and manage databases, there's no use outside of databases.

**Comment by amye** [comment]
@marccampbell:  Checking back in here: 

Trademarks: transfer any trademark and logo mark assets over to the LF  - https://github.com/cncf/foundation/tree/master/agreements has the agreements 
Website: ensure LF footer is there and website guidelines followed   - https://envoyproxy.io/ is a good example
Website: Analytics transferred

**Comment by marccampbell** [comment]
@amye we don't have any Trade/Logo marks on SchemaHero.
Who should I transfer the website Google Analytics to? (also can follow up via email if needed here)

**Comment by marccampbell** [comment]
@amye the LF footer has been deployed to https://schemahero.io

**Comment by breezybaldwin** [comment]
@amye Can you check the updated footer and let me know if it meets the requirements? Thanks!

**Comment by amye** [comment]
That works, marking that off! 
If you can send me an email for the analytics, I can work on getting those transferred. amye@linuxfoundation.org is fine.

**Comment by breezybaldwin** [comment]
Let me know if you got the analytics invite :)

**Comment by amye** [comment]
> @amye we don't have any Trade/Logo marks on SchemaHero.
> Who should I transfer the website Google Analytics to? (also can follow up via email if needed here)

You'll want the non-registered trademark version at https://github.com/cncf/foundation/tree/master/agreements

**Comment by amye** [comment]
> > @amye we don't have any Trade/Logo marks on SchemaHero.
> > Who should I transfer the website Google Analytics to? (also can follow up via email if needed here)
> 
> You'll want the non-registered trademark version at https://github.com/cncf/foundation/tree/master/agreements

@marccampbell - anything I can do to help here?

**Comment by amye** [comment]
@marccampbell: Just checking in here on the non-registered trademark agreement. Thanks!

**Comment by amye** [comment]
Trademark agreement is in, marking issue as closed!
