### ISSUE TITLE
[PROJECT ONBOARDING] OpenKruise

### ISSUE THREAD

**Issue by amye** [cncf/toc#558]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project. 

From the project side, please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/master/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Has your project adopted open governance already? see http://opengovernance.dev

Formal onboarding:
- [x] Owners file: Please add a link to your owners file to this issue, this is used to be able to create your maintainers mailing list. 
- [x] Create maintainer list + added to aggregated https://maintainers.cncf.io list
- [x] Domain: transfer domain to CNCF/LF (ITx)
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] Artwork: Ensure logos present on https://github.com/cncf/artwork
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices) followed
- [x] Website: Analytics transferred
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Trail Map: update CNCF trail map if relevant (incubating projects and above)
- [x] Update https://landscape.cncf.io
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access
- [x] Schedule monthly project sync with CNCF staff

**Comment by amye** [comment]
Owners file: https://github.com/openkruise/kruise/blob/master/MAINTAINERS.md -- @szihai, is there artwork running around?

**Comment by szihai** [comment]
Yes, logos are here: https://github.com/openkruise/kruise/tree/master/docs/img

**Comment by amye** [comment]
Super! 
Other things: 
Where on the landscape would you like to be? 

Project specific items: 
 Website: ensure LF footer is there and website guidelines followed
 Website: Analytics transferred
 Domain: transfer domain to CNCF/LF (ITx)
 Trademarks: transfer any trademark and logo mark assets over to the LF
 GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership


Thanks!

**Comment by szihai** [comment]
I think it belongs to App Definition and Development - Continuous Integration & Delivery
Thanks
-Andy

**Comment by amye** [comment]
@szihai: any chance we can find a .svg file? Thanks!

**Comment by szihai** [comment]
Does the .ico file work? https://raw.githubusercontent.com/openkruise/website/master/img/kruise.ico
Thanks
Andy

**Comment by lukaszgryglicki** [comment]
Test DevStats [page](https://openkruise.teststats.cncf.io) added, not added to [All CNCF](https://all.devstats.cncf.io) yet. I'll add the prod page once I add all new projects on the test (including All CNCF) and see all is fine.

**Comment by lukaszgryglicki** [comment]
Prod [page](https://openkruise.devstats.cncf.io) added too, also added Projects health summary [report](https://all.teststats.cncf.io/d/53/projects-health-table?orgId=1) (on the test), prod `All CNCF` is pending.

**Comment by amye** [comment]
@szihai: No, we'll need an .svg file, see the sandbox examples: https://github.com/cncf/artwork/blob/master/examples/sandbox.md

**Comment by amye** [comment]
@szihai: Just checking back in here, we'll need your artwork in a .svg file. 
Also: 
* Website: ensure LF footer is there and website guidelines followed
* Website: Analytics transferred
* Domain: transfer domain to CNCF/LF (ITx)
* Trademarks: transfer any trademark and logo mark assets over to the LF
* GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership

Thanks!

**Comment by amye** [comment]
@szihai: Checking back in on the above, thanks!

**Comment by amye** [comment]
@szihai: We've still got some items outstanding: 

 - Domain: transfer domain to CNCF/LF (ITx)
 - Trademarks: transfer any trademark and logo mark assets over to the LF
 - GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
-  Artwork: Ensure logos present on https://github.com/cncf/artwork
 - Website: ensure LF footer is there and website guidelines followed
 - Website: Analytics transferred

**Comment by resouer** [comment]
@amye I will sync with Alibaba team and take over this effort from here! It's hopeful we could tackle this faster than OpenYurt.

**Comment by amye** [comment]
Works for me!

**Comment by BinaryHB0916** [comment]
Hi @amye 

Wei again, and I'm assigned to follow up on this. I dropped an email to you seeking for help. Please kindly check it when you're available. Thanks.

**Comment by amye** [comment]
Checking in here again: 

- Domain: transfer domain to CNCF/LF (ITx)
- Trademarks: transfer any trademark and logo mark assets over to the LF
- GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- Artwork: Ensure logos present on https://github.com/cncf/artwork
- Website: ensure LF footer is there and website guidelines followed
- Website: Analytics transferred 

Thanks!

**Comment by BinaryHB0916** [comment]
Thanks for the notification, Amye.

Occupied on IP transferring paper works with our legal colleague, I'll follow up on these Todos once it's done.

**Comment by amye** [comment]
@BinaryHB0916: Any updates on the following: 
Domain: transfer domain to CNCF/LF (ITx)
GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
Artwork: Ensure logos present on https://github.com/cncf/artwork
Website: ensure LF footer is there and website guidelines followed
Website: Analytics transferred

**Comment by BinaryHB0916** [comment]
hi amye:

- Domain: transfer domain to CNCF/LF (ITx)
_ requesting transfer code from Alibaba legal_
- GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
_have sent invitation emails to  'thelinuxfoundation' and 'caniszczyk'  as requested, please have a look_
- Artwork: Ensure logos present on https://github.com/cncf/artwork
_preparing Logos as needed_
- Website: ensure LF footer is there and website guidelines followed
_this better be started after trademarks transfer finished_
- Website: Analytics transferred
_double checked, we haven't set up Anylytics for https://openkruise.io/en-us/ _

**Comment by amye** [comment]
@BinaryHB0916: Checking back in here!

**Comment by BinaryHB0916** [comment]
@amye transferring agreement just sent to you via email. Please have a look when you're available. Thanks.

**Comment by BinaryHB0916** [comment]
hi @amye all remained actions had been performed as needed. Please check and let me know if there's any problem. Thanks very much.

**Comment by amye** [comment]
Marking artwork in.
Domain transfer is in progress.
I have trademark paperwork in flight on our end but that might take a little bit with KubeCon coming in! 
We can make new analytics codes for you!

**Comment by BinaryHB0916** [comment]
Great! I'll follow up if there's anything coming up on our end, Good Day!

**Comment by lukaszgryglicki** [comment]
Hi, I can only see `black` [here](https://github.com/cncf/artwork/tree/master/projects/openkruise/icon/color) so [DevStats](https://openkruise.devstats.cncf.io/d/8/dashboards?orgId=1&refresh=15m) must use it and it is not looking good IMHO... can you please add `color` artwork as well?

**Comment by BinaryHB0916** [comment]
Sure made a mistake. Updated it and please go ahead to have a look with the PRs.

**Comment by amye** [comment]
@BinaryHB0916, separately, any change of getting .svg artwork? Thanks!

**Comment by BinaryHB0916** [comment]
@amye yep, there is one change related to the file named as openkruise-icon-color.svg, replacing the wrong file named as openkruise-icon-black.svg.

(located by root: artwork/projects/openkruise/icon/color/openkruise-icon-color.svg)

Please check https://github.com/cncf/artwork/pull/239 to see whether I need to do anything more.

**Comment by poconnor1** [comment]
Hi @BinaryHB0916 
Hope you are well. Checkin in here on the trademarks, GitHub ownership and website analytics. Thanks!

**Comment by BinaryHB0916** [comment]
hi @poconnor1 
Agreements for trademarks is in progress through email threads with Amye.

As for the latter two actions, please check history above:

- GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
_have sent invitation emails to 'thelinuxfoundation' and 'caniszczyk' as requested, please have a look_
- Website: Analytics transferred
_double checked, we haven't set up Anylytics for https://openkruise.io/en-us/

**Comment by amye** [comment]
@BinaryHB0916: updating here, our legal team has reached out through email. 
I'm keeping this issue open to make sure we're tracking.

**Comment by amye** [comment]
Marking Trademarks off and closing as I know that's with Legal now.
