### ISSUE TITLE
[PROJECT ONBOARDING] Tinkerbell 

### ISSUE THREAD

**Issue by amye** [cncf/toc#559]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project. 

From the project side, please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/master/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Has your project adopted open governance already? see http://opengovernance.dev

Formal onboarding:
- [x] Owners file: Please add a link to your owners file to this issue, this is used to be able to create your maintainers mailing list. 
- [x] Create maintainer list + added to aggregated https://maintainers.cncf.io list
- [x] Domain: transfer domain to CNCF/LF (ITx)
- [ ] Trademarks: transfer any trademark and logo mark assets over to the LF
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] Artwork: Ensure logos present on https://github.com/cncf/artwork
- [ ] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices) followed
- [x] Website: Analytics transferred
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Trail Map: update CNCF trail map if relevant (incubating projects and above)
- [x] Update https://landscape.cncf.io
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access
- [x] Schedule monthly project sync with CNCF staff

**Comment by vielmetti** [comment]
attn @mrmrcoleman

**Comment by amye** [comment]
@vielmetti: Thanks for tagging yourself here! Maintainers and artwork are the early important things.

**Comment by gianarb** [comment]
@amye we have a repository here https://github.com/tinkerbell/artwork is it enough or you need more? :)

**Comment by amye** [comment]
Nope, that looks great @gianarb. I will let our designers know. 
I don't see y'all on the CNCF Landscape, which category should you be added in?

**Comment by vielmetti** [comment]
@amye - For the landscape it should go into Provisioning / Automation and Configuration - alongside metal3, MAAS, Airship etc.

**Comment by amye** [comment]
Awesome. 
Next big things: 
Domain: transfer domain to CNCF/LF (ITx)
 Trademarks: transfer any trademark and logo mark assets over to the LF
 GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership 
 Website: ensure LF footer is there and website guidelines followed
 Website: Analytics transferred

**Comment by lukaszgryglicki** [comment]
Test DevStats [page](https://tinkerbell.teststats.cncf.io) added, not added to [All CNCF](https://all.devstats.cncf.io) yet. I'll add the prod page once I add all new projects on the test (including All CNCF) and see all is fine.

**Comment by gianarb** [comment]
Thanks @lukaszgryglicki !

**Comment by lukaszgryglicki** [comment]
Prod [page](https://tinkerbell.devstats.cncf.io) added too, also added Projects health summary [report](https://all.teststats.cncf.io/d/53/projects-health-table?orgId=1) (on the test), prod `All CNCF` is pending.

**Comment by amye** [comment]
@vielmetti: Checking in here!
Outstanding: 
Domain: transfer domain to CNCF/LF (ITx)  - you can email me a transfer code at amye@linuxfoundation.org
Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements have both registered and non-registered 
GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
Website: ensure LF footer is there and website guidelines followed
Website: Analytics transferred 

Thanks!

**Comment by vielmetti** [comment]
Thanks @amye ! I have asked @jacobsmith928 regarding the domain transfer and the web site changes.

**Comment by amye** [comment]
@vielmetti: Excellent. Is the OWNERS file supposed to link to a member list?https://github.com/tinkerbell/tink/blob/master/OWNERS.md

**Comment by gianarb** [comment]
@amye the list of people that are part of the GitHub organisation are currently considered maintainers. We are doing some refactoring of roles and members at this point. So, no OWNERS.md is the definition of ownership for us.

I am not sure if we want to proceed with an "extract' of email from the GitHub org or if we want to do something else here. I will reach out to @mrmrcoleman to figure it out.

@amye I have added @caniszczyk and @thelinuxfoundation as admin on GitHub 👍

**Comment by amye** [comment]
@gianarb: Just checking in on Owners file, thanks!

**Comment by vielmetti** [comment]
@amye the Owners file work is in progress, will update when it's ready. Mostly a people thing not a technical thing.

**Comment by amye** [comment]
@vielmetti: Just checking in here, any status update on the owners file? Thanks!

**Comment by gianarb** [comment]
@amye here we are with the MAITNAINERS.md file https://github.com/tinkerbell/.github/blob/master/MAINTAINERS.md !

**Comment by amye** [comment]
You are awesome! @gianarb, can you drop me an email with people's emails?

**Comment by amye** [comment]
@gianarb: Checking back in on the website footer, thanks!

**Comment by amye** [comment]
One missing piece here! @gianarb: "We are a Cloud Native Computing Foundation sandbox project."

**Comment by vielmetti** [comment]
Trademark assignment is in process, pending review by legal.

**Comment by amye** [comment]
> One missing piece here! @gianarb: "We are a Cloud Native Computing Foundation sandbox project."

Checking in on this!

**Comment by amye** [comment]
Two things still outstanding: @gianarb, @vielmetti -- 
Website: ensure LF footer is there and website guidelines followed
Trademarks: transfer any trademark and logo mark assets over to the LF

**Comment by amye** [comment]
@gianarb, @vielmetti: checking back in here, thanks!

**Comment by vielmetti** [comment]
@amye Regarding "trademark and logo mark assets", all I see is

https://github.com/tinkerbell/artwork

which has been assigned already and which looks complete.

**Comment by amye** [comment]
@vielmetti: We're missing the paperwork, found in https://github.com/cncf/foundation/tree/master/agreements

**Comment by poconnor1** [comment]
Hi @vielmetti,  
I've recently joined CNCF to help with project onboarding. Nice to meet you!
I wanted to check where we stand with the missing paperwork regarding the trademark and logo mark assets over to LF - https://github.com/cncf/foundation/tree/master/agreements

Thank you for the help! Reach out with any questions.

**Comment by poconnor1** [comment]
Hi @vielmetti 
checking in again, on the status of trademark and logo mark assets over to LF - https://github.com/cncf/foundation/tree/master/agreements

Thank you!

**Comment by caniszczyk** [comment]
followed up with @vielmetti
