### ISSUE TITLE
[PROJECT ONBOARDING] Pravega

### ISSUE THREAD

**Issue by amye** [cncf/toc#560]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project. 

From the project side, please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/master/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Has your project adopted open governance already? see http://opengovernance.dev

Formal onboarding:
- [x] Owners file: Please add a link to your owners file to this issue, this is used to be able to create your maintainers mailing list. 
- [x] Create maintainer list + added to aggregated https://maintainers.cncf.io list
- [x] Domain: transfer domain to CNCF/LF (ITx)
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] Artwork: Ensure logos present on https://github.com/cncf/artwork
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices) followed
- [x] Website: Analytics transferred
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Trail Map: update CNCF trail map if relevant (incubating projects and above)
- [x] Update https://landscape.cncf.io
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access
- [x] Schedule monthly project sync with CNCF staff

**Comment by amye** [comment]
@derekm, we'll be tracking work in here. 
First things, (1) Owners file and (2) artwork.

**Comment by lukaszgryglicki** [comment]
Test DevStats [page](https://pravega.teststats.cncf.io) added, not added to [All CNCF](https://all.devstats.cncf.io) yet. I'll add the prod page once I add all new projects on the test (including All CNCF) and see all is fine.

**Comment by derekm** [comment]
@amye -- You can start with the list of initial committers from our Incubation proposal as we sort out the owners/maintainers files in our various repos: https://github.com/cncf/toc/pull/456/files#diff-755b6388fdb45d6d7a281ede6afdad4774dbbdddc82df03bd4e96999d1484628R137

Thanks!

**Comment by lukaszgryglicki** [comment]
Prod [page](https://pravega.devstats.cncf.io) added too, also added Projects health summary [report](https://all.teststats.cncf.io/d/53/projects-health-table?orgId=1) (on the test), prod `All CNCF` is pending.

**Comment by amye** [comment]
@derekm: Any artwork that we should look for? Thanks!

**Comment by amye** [comment]
No worries, I didn't see the link in here directly! Marking that off. 

Things I could use (no particular order!): 
(1) Owners file (I have to link to it from maintainers.cncf.io)
(2)  Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has registered and non-registered trademarks 
(3) GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
(4) Website: ensure LF footer is there and website guidelines followed
(5)  Website: Analytics transferred 
(6)  Domain: transfer domain to CNCF/LF (ITx)

**Comment by derekm** [comment]
@amye -- I'll get (1) committed ASAP.

I'll contact legal today about (2). We have 19 trademarks in various countries, IIRC.

Re: (3), I am wrapping up the cleanup of potentially-proprietary private repos in our public github org (we had over 70 repos in our org). I should have our org fully cleaned up in the next few days, at which point I can add the new owners.

(4) and (5) are in progress, should have those delivered shortly.

Re: (6), the domain was transferred from SafeNames to 1API on Nov. 25th (as according to whois).

**Comment by derekm** [comment]
@amye -- [DONE] Website: ensure LF footer is there and website guidelines followed
[pravega.io](https://pravega.io/)
https://github.com/pravega/www.pravega.io/commit/e0501f0e6d142e1a41c4e740c3c5bddbdc3db4f2#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051

**Comment by amye** [comment]
@derekm: Checking back in here, the owners file would be really helpful!

**Comment by derekm** [comment]
@amye: that's next on my list! Today I invited @thelinuxfoundation and @caniszczyk as owners of the github.com/pravega org.

**Comment by derekm** [comment]
@amye: We have our CII Best Practices badge in our README: https://github.com/pravega/pravega#user-content-pravega-----

CII Best Practices survey ID: https://bestpractices.coreinfrastructure.org/en/projects/4178

**Comment by amye** [comment]
@derekm: Checking back in on owners file, thanks!

**Comment by amye** [comment]
@derekm: Checking back in on owners file, again.

**Comment by amye** [comment]
> @derekm: Checking back in on owners file, again.

Owners file ping, thanks!

**Comment by amye** [comment]
@derekm: 
Currently outstanding -- 
Owners file: Please add a link to your owners file to this issue, this is used to be able to create your maintainers mailing list.
Trademarks: transfer any trademark and logo mark assets over to the LF
GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
Website: Analytics transferred

**Comment by derekm** [comment]
@amye,

We're looking to have owners file by May 3rd.

Re: Trademarks -- Dell's deed was sent by you to LF Legal on Dec. 11th, 2020, for review/acceptance. Awaiting response from LF Legal to get both legal depts together for signatures.

Re: GitHub -- 'thelinuxfoundation' and 'caniszczyk' were added as org owners on Jan. 20th, 2021: 
![image](https://user-images.githubusercontent.com/379469/115774411-29a44800-a377-11eb-86fe-c018c16271fc.png)

Re: Website -- Analytics was incorrectly transferred to Chris' gmail. Analytics invite re-sent to Chris' LF email today.

Thank you!

**Comment by poconnor1** [comment]
Hi @derekm 
I've recently joined CNCF to help with project onboarding. Nice to meet you!
I wanted to check where we stand on these items below:

- Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- Has your project adopted open governance already? see http://opengovernance.dev
- Owners File

Thank you for the help! Reach out with any questions.

**Comment by amye** [comment]
Hey, @derekm: any movement on owners file? Thanks!

**Comment by poconnor1** [comment]
Hi @derekm 
Checking in again on the status of the following:

- Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- Has your project adopted open governance already? see http://opengovernance.dev
- Owners File

Thank you!

**Comment by derekm** [comment]
@amye & @poconnor1 --

We have committed a seed MAINTAINERS file for the Pravega org. We will quickly expand the maintainers list with 3 more names, but this should get us going in the meantime: https://github.com/pravega/.github/blob/main/MAINTAINERS

I will confirm all maintainers have read "Services for Projects." (I have.)

We comply with the CNCF IP Policy. Trademark transfer is underway. We do not use CLA. We already use DCO. All code in all repos is licensed Apache-2.0. Our docs were already licensed under Apache-2.0.

We are adopting open governance policies. We are modeling our governance on Apache ZooKeeper bylaws. PR for governance is here: https://github.com/pravega/community/pull/2

Thanks!

**Comment by amye** [comment]
This is super! Expect a bunch of invites shortly. 👍

**Comment by amye** [comment]
Welcome email (and several other emails!) out, marking those off

**Comment by amye** [comment]
Trademarks are complete, closing!
