### ISSUE TITLE
[PROJECT ONBOARDING] Kyverno

### ISSUE THREAD

**Issue by amye** [cncf/toc#561]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project. 

From the project side, please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/master/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Has your project adopted open governance already? see http://opengovernance.dev

Formal onboarding:
- [x] Owners file: Please add a link to your owners file to this issue, this is used to be able to create your maintainers mailing list. 
- [x] Create maintainer list + added to aggregated https://maintainers.cncf.io list
- [x] Domain: transfer domain to CNCF/LF (ITx)
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] Artwork: Ensure logos present on https://github.com/cncf/artwork
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices) followed
- [x] Website: Analytics transferred
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Trail Map: update CNCF trail map if relevant (incubating projects and above)
- [x] Update https://landscape.cncf.io
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access
- [x] Schedule monthly project sync with CNCF staff

**Comment by amye** [comment]
@JimBugwadia, we're tracking work in here. 
First things: (1) Owners file, (2) artwork (3) where you'd like to be on the CNCF landscape (area) 
Thanks!

**Comment by JimBugwadia** [comment]
Hi @amye, here you go: 

1. **Owners file:** https://raw.githubusercontent.com/kyverno/kyverno/main/OWNERS.md
2. **Artwork**: https://github.com/kyverno/artwork
3. **CNCF landscape**:  category `security-compliance`

**Comment by amye** [comment]
This is super! 
Next steps: 
[ ] Domain: transfer domain to CNCF/LF (ITx) - let me know when you have a transfer code! 
[ ] Trademarks: transfer any trademark and logo mark assets over to the LF -https://github.com/cncf/foundation/tree/master/agreements have both registered and non-registered
[ ] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
[ ] Website: ensure LF footer is there and website guidelines followed
[ ] Website: Analytics transferred

**Comment by JimBugwadia** [comment]
Hi @amye - I have the transfer code for kyverno.io and have sent to your email address.

**Comment by JimBugwadia** [comment]
There are no registered trademarks for Kyverno. If I understood correctly, we still will need to complete this agreement:

https://github.com/cncf/foundation/blob/master/agreements/CNCF%20Trademark%20and%20Account%20Assignment%20Agreement%20(2020%20-%20no%20reg%20trademarks).pdf

Is there an editable version?

Thanks!

**Comment by JimBugwadia** [comment]
> [ ] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership

Invited Chris and The Linux Foundation as https://github.com/orgs/kyverno owners!

**Comment by JimBugwadia** [comment]
Added LF to footer: https://kyverno.io/

**Comment by lukaszgryglicki** [comment]
Test DevStats [page](https://kyverno.teststats.cncf.io) added, not added to [All CNCF](https://all.devstats.cncf.io) yet. I'll add the prod page once I add all new projects on the test (including All CNCF) and see all is fine.

**Comment by lukaszgryglicki** [comment]
Prod [page](https://kyverno.devstatsstats.cncf.io) added too, also added Projects health summary [report](https://all.teststats.cncf.io/d/53/projects-health-table?orgId=1) (on the test), prod `All CNCF` is pending.

**Comment by amye** [comment]
@JimBugwadia: You should have a .docx for the trademark agreement.

**Comment by JimBugwadia** [comment]
Thanks @amye! Signed and sent back.

**Comment by amye** [comment]
Marking as closed here!
