### ISSUE TITLE
TOC Elections for 2021

### ISSUE THREAD

**Issue by amye** [cncf/toc#578]
This issue is for tracking timelines for the TOC elections for 2021. 

Nominations open December 14- January 11
Qualification Period: Jan 11 - Jan 25
Election opens: Jan 25
Election closes Feb 1, announced at noon 

Seats Available: 
TOC Seats up for Election in 2021:
Brendan Burns (1/29/21, GB-appointed)
Matt Klein (1/29/21, GB-appointed)
Xiang Li (1/29/21, GB-appointed)
Katie Gamanji (will be seated with 1/29/21 group, End User-appointed)
Dave Zolotusky (1/29/21, End User-appointed) 
Michelle Noorali (3/18/2021, TOC-appointed)

**Comment by caniszczyk** [comment]
Thanks @amye, I'd like to consider us opening the nomination period early, say starting next Monday!

**Comment by amye** [comment]
No issues there, will edit to reflect a nomination period of December 14 - Jan 11.

**Comment by amye** [comment]
Nominations for these seats are for the GB and End User community, the TOC appointed seat will be a separate election in Feb-March.

**Comment by amye** [comment]
Qualification vote is complete, sending out votes today. 
Congratulations to our candidates for TOC seats in this cycle:

Ricardo Aravena
John Belamaric
Erin Boyd
Cornelia Davis
Bridget Kromhout
Edward Lee
Michael Lieberman
Paul Morie
Ricardo Rocha
Davanum Srinivas
Carolyn Van Slyck
Kevin (Zefeng) Wang
Lei Zhang
Dave Zolotusky

**Comment by amye** [comment]
We are complete here!
**End User selected seats:** 
Dave Zolotusky
Ricardo Rocha (term ends 2022) 

**GB appointed seats:** 
Erin Boyd
Cornelia Davis
Lei Zhang
