### ISSUE TITLE
[PROJECT ONBOARDING] Piraeus-Datastore

### ISSUE THREAD

**Issue by amye** [cncf/toc#593]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project. 

From the project side, please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/master/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
- [x] Has your project adopted open governance already? see http://opengovernance.dev

Things that CNCF will need from the project: 
- [x] Owners file: Please add a link to your owners file to this issue, this is used to be able to create your maintainers mailing list. 
- [x] Create maintainer list + added to aggregated https://maintainers.cncf.io list
- [x] Domain: transfer domain to CNCF/LF (ITx)
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF - https://www.linuxfoundation.org/en/trademark-usage/ has guidelines 
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] Artwork: Ensure logos present on https://github.com/cncf/artwork
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices) followed
- [x] Website: Analytics transferred

Things that the CNCF will do or help the project to do: 
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Trail Map: update CNCF trail map if relevant (incubating projects and above)
- [x] Update https://landscape.cncf.io
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access
- [x] Schedule monthly project sync with CNCF staff

**Comment by amye** [comment]
Welcome!  @Philipp-Reisner, as I look at https://github.com/piraeusdatastore, it doesn't appear that you have a maintainers file? That's the key piece to get started with.

**Comment by lukaszgryglicki** [comment]
DevStats pages added: [test](https://piraeus.teststats.cncf.io), [prod](https://piraeus.devstats.cncf.io).

**Comment by WanzenBug** [comment]
@amye We've added a maintainers file here: https://github.com/piraeusdatastore/piraeus/blob/master/MAINTAINERS.md

**Comment by amye** [comment]
Excellent!
@WanzenBug: 
Next steps:  
Artwork: Ensure logos present on https://github.com/cncf/artwork
Domain: transfer domain to CNCF/LF (ITx)
 Trademarks: transfer any trademark and logo mark assets over to the LF - https://www.linuxfoundation.org/en/trademark-usage/ has guidelines
 GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
Website: Analytics transferred

**Comment by WanzenBug** [comment]
>  GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership

done

>  Trademarks: transfer any trademark and logo mark assets over to the LF - https://www.linuxfoundation.org/en/trademark-usage/ has guidelines

We haven't registered any trademarks. Is there anything we need to do in this case?

**Comment by amye** [comment]
> > GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
> 
> done
> 
> > Trademarks: transfer any trademark and logo mark assets over to the LF - https://www.linuxfoundation.org/en/trademark-usage/ has guidelines
> 
> We haven't registered any trademarks. Is there anything we need to do in this case?

All the agreements live in here, you'll want the nonregistered trademark: https://github.com/cncf/foundation/tree/master/agreements

**Comment by amye** [comment]
@WanzenBug: Checking back in here, artwork would be helpful!

**Comment by WanzenBug** [comment]
> Checking back in here, artwork would be helpful!

@alexzhc are you also on this? Or should I work on it?

**Comment by amye** [comment]
Checking back in on the above: 
Domain: transfer domain to CNCF/LF (ITx)
 Trademarks: transfer any trademark and logo mark assets over to the LF - https://www.linuxfoundation.org/en/trademark-usage/ has guidelines
 GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
 Artwork: Ensure logos present on https://github.com/cncf/artwork
 Website: ensure LF footer is there and website guidelines followed
 Website: Analytics transferred

**Comment by WanzenBug** [comment]
* Github ownership is done
* Artwork: PR is here https://github.com/cncf/artwork/pull/231

Regarding domain transfer, trademarks and the website: @alexzhc should have sent a message with the signed trademark transfer and an update on the domain transfer (basically the domain was recently transferred so the transfer can happen in may at the earliest). Did you receive that @amye ?

**Comment by amye** [comment]
Marking off artwork and GH ownership. 
No domain transfer on my end, email to amye@linuxfoundation.org

**Comment by poconnor1** [comment]
Hi @WanzenBug!
I've recently joined CNCF to help with project onboarding. Nice to meet you!
I wanted to check where we stand on these items below:

- Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- Has your project adopted open governance already? see http://opengovernance.dev

As well as the items Amye mentioned above, where do we stand here?
Domain: transfer domain to CNCF/LF (ITx)
Trademarks: transfer any trademark and logo mark assets over to the LF

Thank you for the help! Reach out with any questions.

**Comment by WanzenBug** [comment]
Hi @poconnor1!

> Understand the services available for your project at CNCF

We should be good to go on that part.

> Ensure your project meets the CNCF IP Policy

Trademarks, logo, etc should be transferred already (thanks to @alexzhc), all code is licensed under Apache 2.0 so I think we are good to go here, too.

> Has your project adopted open governance already

Done: https://github.com/piraeusdatastore/piraeus/blob/master/GOVERNANCE.md

>  Domain: transfer domain to CNCF/LF (ITx)

Done on our side, just needs the confirmation from CNCF

>  Trademarks: transfer any trademark and logo mark assets over to the LF

See above, @alexzhc did that a while back

**Comment by Philipp-Reisner** [comment]
@poconnor1, The domain got transfered to CNCF,
The website https://piraeus.io/ has the CNCF footer now.
Can you check these two items off the TODO list?

**Comment by caniszczyk** [comment]
done, you should be good to go now
