### ISSUE TITLE
[PROJECT ONBOARDING] Kube-OVN

### ISSUE THREAD

**Issue by amye** [cncf/toc#596]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project. 

From the project side, please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/master/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
- [x] Has your project adopted open governance already? see http://opengovernance.dev

Things that CNCF will need from the project: 
- [x] Owners file: Please add a link to your owners file to this issue, this is used to be able to create your maintainers mailing list. 
- [x] Create maintainer list + added to aggregated https://maintainers.cncf.io list
- [x] Domain: transfer domain to CNCF/LF (ITx)
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF - https://www.linuxfoundation.org/en/trademark-usage/ has guidelines 
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] Artwork: Ensure logos present on https://github.com/cncf/artwork
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices) followed
- [x] Website: Analytics transferred

Things that the CNCF will do or help the project to do: 
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Trail Map: update CNCF trail map if relevant (incubating projects and above)
- [x] Update https://landscape.cncf.io
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access
- [x] Schedule monthly project sync with CNCF staff

**Comment by amye** [comment]
Welcome! We'll be tracking work in here. 
@oilbeater, it looks like https://github.com/alauda/kube-ovn doesn't have a maintainers file. Help?

**Comment by oilbeater** [comment]
> Welcome! We'll be tracking work in here.
> @oilbeater, it looks like https://github.com/alauda/kube-ovn doesn't have a maintainers file. Help?

Thanks! We will add the maintainers file soon

**Comment by oilbeater** [comment]
@amye maintainers file is here https://github.com/alauda/kube-ovn/blob/master/MAINTAINERS

**Comment by lukaszgryglicki** [comment]
Hi, any plans to move to a separate org?
For now, DevStats will track https://github.com/alauda/kube-ovn

**Comment by oilbeater** [comment]
> Hi, any plans to move to a separate org?
> For now, DevStats will track https://github.com/alauda/kube-ovn

@lukaszgryglicki we are preparing to move to https://github.com/kubeovn/kube-ovn. But some projects already relies on the url exists now, we need to notify them to change before we migrate to the new org

**Comment by lukaszgryglicki** [comment]
OK, s I'll just set up DevStats to track `kubeovn` org, so if anything appears under that org - it will automatically be tracked.

**Comment by lukaszgryglicki** [comment]
DevStats pages added: [test](https://kubeovn.teststats.cncf.io), [prod](https://kubeovn.devstats.cncf.io).

**Comment by oilbeater** [comment]
we have migrate repo to https://github.com/kubeovn/kube-ovn

**Comment by amye** [comment]
@oilbeater: any updates on artwork? Thanks!

**Comment by amye** [comment]
@oilbeater: checking in here on: 
Domain: transfer domain to CNCF/LF (ITx)
 Trademarks: transfer any trademark and logo mark assets over to the LF - https://www.linuxfoundation.org/en/trademark-usage/ has guidelines
 GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
 Artwork: Ensure logos present on https://github.com/cncf/artwork
 Website: ensure LF footer is there and website guidelines followed
 Website: Analytics transferred

**Comment by oilbeater** [comment]
> @oilbeater: checking in here on:
> Domain: transfer domain to CNCF/LF (ITx)
> Trademarks: transfer any trademark and logo mark assets over to the LF - https://www.linuxfoundation.org/en/trademark-usage/ has guidelines
> GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
> Artwork: Ensure logos present on https://github.com/cncf/artwork
> Website: ensure LF footer is there and website guidelines followed
> Website: Analytics transferred
We  haven't apply any trademarks and website analytics as for now
 
 'thelinuxfoundation' and  'caniszczyk' have been added as the owner of the `kubeovn` org.

I will discuss with my company about domain, artwrok and websit footer work this week

**Comment by oilbeater** [comment]
@amye Some questions about the domain transfer

1. Is there any guides about how to transfer the domain?
2. We are planning a new version of website and might relocate it other host. How can we change the dns resolve if we transfer the domain to CNCF/LF

**Comment by oilbeater** [comment]
Artwork have been uploaded and website footer is added

**Comment by amye** [comment]
Replaced your artwork on the project page! 
For domains, you can still manage your DNS, I just need the transfer code to amye@linuxfoundation.org

**Comment by oilbeater** [comment]
@amye the artwork has been replaced and the transfer code has been send to your email.

**Comment by amye** [comment]
Transfer is in progress.

**Comment by amye** [comment]
Marking transfer complete! 
Remaining: 
 Trademarks: transfer any trademark and logo mark assets over to the LF - https://www.linuxfoundation.org/en/trademark-usage/ has guidelines
 GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership 
Website: Analytics transferred --  invite amye@linuxfoundation.org to your Google analytics, please!

**Comment by amye** [comment]
Landscape: https://github.com/cncf/landscape/pull/2038 is in

**Comment by amye** [comment]
Marking off analytics (none to transfer), GH ownership and landscape.
Outstanding: 
Trademarks: transfer any trademark and logo mark assets over to the LF - https://www.linuxfoundation.org/en/trademark-usage/ has guidelines -- if no registered trademarks, use the non-registered trademark agreement in https://github.com/cncf/foundation/tree/master/agreements

**Comment by oilbeater** [comment]
> Marking off analytics (none to transfer), GH ownership and landscape.
> Outstanding:
> Trademarks: transfer any trademark and logo mark assets over to the LF - https://www.linuxfoundation.org/en/trademark-usage/ has guidelines -- if no registered trademarks, use the non-registered trademark agreement in https://github.com/cncf/foundation/tree/master/agreements

@amye do we need to send the signed agreement pdf to you email?

**Comment by amye** [comment]
> > Marking off analytics (none to transfer), GH ownership and landscape.
> > Outstanding:
> > Trademarks: transfer any trademark and logo mark assets over to the LF - https://www.linuxfoundation.org/en/trademark-usage/ has guidelines -- if no registered trademarks, use the non-registered trademark agreement in https://github.com/cncf/foundation/tree/master/agreements
> 
> @amye do we need to send the signed agreement pdf to you email?
That will work! I can get it signed on our end.

**Comment by poconnor1** [comment]
Hi @oilbeater 
I've recently joined CNCF to help with project onboarding. Nice to meet you!
I wanted to check where we stand on Trademarks: transfer any trademark and logo mark assets over to the LF

Thank you for the help! Reach out with any questions.

**Comment by amye** [comment]
My fault! We are complete here, marking as closed!
