### ISSUE TITLE
[PROJECT ONBOARDING] Distribution

### ISSUE THREAD

**Issue by amye** [cncf/toc#598]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project. 

From the project side, please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/master/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
- [x] Has your project adopted open governance already? see http://opengovernance.dev

Things that CNCF will need from the project: 
- [x] Owners file: Please add a link to your owners file to this issue, this is used to be able to create your maintainers mailing list. 
- [x] Create maintainer list + added to aggregated https://maintainers.cncf.io list
- [x] Domain: transfer domain to CNCF/LF (ITx)
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF - https://www.linuxfoundation.org/en/trademark-usage/ has guidelines 
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] Artwork: Ensure logos present on https://github.com/cncf/artwork
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices) followed
- [x] Website: Analytics transferred

Things that the CNCF will do or help the project to do: 
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Trail Map: update CNCF trail map if relevant (incubating projects and above)
- [x] Update https://landscape.cncf.io
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access
- [x] Schedule monthly project sync with CNCF staff

**Comment by todogroup-packages** [comment]
@justincormack lmk what new org you plan to use

**Comment by amye** [comment]
Welcome! @justincormack, I see your maintainers file is https://github.com/docker/distribution/blob/master/MAINTAINERS, which helps get me started. 
If I was going to look for artwork, where would I start?

**Comment by justincormack** [comment]
We moved to an org https://github.com/distribution/distribution

**Comment by amye** [comment]
Edited on the sandbox project page, and marking maintainers file off.

**Comment by justincormack** [comment]
Added owners to org. There isn't a website at present. I am investigating the existence of trademark (I believe there is not one), and checking about artwork - the logo at https://camo.githubusercontent.com/3f0e8eeb989a431168db50524198fddd4b31c25dbc88f8a3d66090bd0b6096b4/68747470733a2f2f7777772e646f636b65722e636f6d2f73697465732f64656661756c742f66696c65732f6f79737465722d72656769737472792d332e706e67 is cute but very much of the "Docker animal family", for Compose spec we re-drew a related version that was not in that style, but kept the same idea as its a nice design...

**Comment by justincormack** [comment]
Note added one more maintainer yesterday as agreed on our call.

**Comment by caniszczyk** [comment]
DCO checks enabled: https://github.com/distribution/distribution/issues/3340

**Comment by caniszczyk** [comment]
looks like distribution may need an updated logo @justincormack ? 

https://camo.githubusercontent.com/3f0e8eeb989a431168db50524198fddd4b31c25dbc88f8a3d66090bd0b6096b4/68747470733a2f2f7777772e646f636b65722e636f6d2f73697465732f64656661756c742f66696c65732f6f79737465722d72656769737472792d332e706e67

We can improve on that if desired given that those containers are generally Docker specific artwork imho, but open to what you and the maintainers think over there. Let us know and we can have our designers work on it!

**Comment by thaJeztah** [comment]
I don't see it listed at a glance, but will there be a security mailinglist for the project? Currently the project points to `security@docker.com`, which should likely be updated; https://github.com/distribution/distribution/blob/main/CONTRIBUTING.md#reporting-security-issues

**Comment by lukaszgryglicki** [comment]
DevStats pages added: [test](https://distribution.teststats.cncf.io), [prod](https://distribution.devstats.cncf.io).

**Comment by justincormack** [comment]
There are no trademarks or website to transfer. I think an updated logo would be good @caniszczyk maybe we could make something somewhat derived for continuity? The oyster is quite cool, maybe as its not just containers in registries it could have pearls or Helm charts too?

**Comment by caniszczyk** [comment]
@amye kicked off a new logo design process https://jira.linuxfoundation.org/browse/LP-7100

**Comment by SteveLasker** [comment]
We had a Distribution Icon made as part of the OCI Icon set: https://github.com/opencontainers/artwork/blob/master/icons/oci_icon_distribution.svg

![](https://github.com/opencontainers/artwork/blob/master/icons/oci_icon_distribution.svg)

But, I also like the Oyster as special things you find in a registry.

**Comment by amye** [comment]
Currently in progress: artwork! 
However, the non-registered trademark paperwork is in https://github.com/cncf/foundation/tree/master/agreements and will need to be completed.

**Comment by amye** [comment]
Update from project: logo in revisions, feedback by Friday.

**Comment by amye** [comment]
@SteveLasker, @justincormack -- any logo feedback?

**Comment by amye** [comment]
Adding https://github.com/distribution/distribution/issues/3351 to keep track of discussion

**Comment by amye** [comment]
Round 2 of design is in!

**Comment by poconnor1** [comment]
Hi @SteveLasker 
I've recently joined CNCF to help with project onboarding. Nice to meet you!
I wanted to check where we stand on Trademarks: transfer any trademark and logo mark assets over to the LF

Thank you for the help! Reach out with any questions.

**Comment by SteveLasker** [comment]
Hi @poconnor1, nice to meet you as well. For the transfer, @justincormack should respond as he's the Docker Inc representative to transfer the logos and trademark. 
I'm involved to help with some logo selection, but the broader work I believe is driven by Justin.

**Comment by poconnor1** [comment]
Awesome. Thank you @SteveLasker 

Hi @justincormack 
Just checking in here on the status of the trademarks transfer and logo mark assets over to the LF. 

Thank you!

**Comment by justincormack** [comment]
Hi!

There is no trademark, we never took one out.

The redesign was because the logo mark was in the Docker house style so
transfer seemed inappropriate.
It looks like we are pretty close to agreement on the issue
https://github.com/distribution/distribution/issues/3351
and we should finalize.

Justin

**Comment by caniszczyk** [comment]
logo + landscape updates are in:
https://github.com/cncf/landscape/pull/2153
https://github.com/cncf/artwork/pull/264

**Comment by amye** [comment]
Excellent, with that logo, we are complete! Welcome letters are out!
