### ISSUE TITLE
Provide guidance for code signing binary artefacts

### ISSUE THREAD

**Issue by joshuagl** [cncf/toc#612]
Hello toc,

Increasingly many CNCF projects provide binaries for releases which are intended to be run on Windows and macOS hosts. Both Windows and macOS have security features which authenticate a binary's code signature on first run. If the binary is not code signed the user must take extra steps to run it, bypassing warnings from their operating system about potentially insecure files from unknown publishers.

I think it would be good for the CNCF to develop guidance for projects on the use of code signing. Furthermore I think it should be recommended for all CNCF projects producing binaries to code sign their binaries, particularly those targeting macOS and Windows, and that for graduated projects we should do something stronger than a recommendation.

I'd love to start a discussion about signing release artefacts more generally (source code archives, etc) but that would be scope creep for this issue and may be a better topic for SIG Security.

Note: I wasn't entirely sure where to post this suggestion, but ultimately couldn't think of a more suitable place.

**Comment by caniszczyk** [comment]
This is a nuanced topic as when we start doing binary artifact distribution there's legal ramifications.  Also, you can make an argument that binary artifact distribution should be left for the vendors to do.

I would love to see CNCF SIG Security discuss this first with some recommendations, then bring it back to the TOC and wider community for input.

**Comment by kfox1111** [comment]
-1.

Its very useful to just fetch kubectl from Kubernetes. Same with kubeadm, minikube, etc.

Preventing binaries can eliminate reference implementations and deincentivize common plumbing that help the vendors produce better distributions. We should be raising the boats of all IMO. I honestly think the lack of some reference implementations was one of the large dragging factors on OpenStack for example.

I think encouraging best practices around code signing for those that choose to produce binaries would be much better then trying to block binaries all together.

Thanks,
Kevin

________________________________________

**Comment by joshuagl** [comment]
> This is a nuanced topic as when we start doing binary artifact distribution there's legal ramifications. Also, you can make an argument that binary artifact distribution should be left for the vendors to do.

Is it fair to assume your concern wrt legal ramifications is specifically related to _signed_ binaries (i.e. export compliance restrictions)? I assume this is a relatively solved problem, because code signing is pervasive across borders in ecosystems like the macOS, iOS, and Windows stores; and in Linux distributions like Fedora. However, I am very much not a lawyer. In fact, I think the legal aspects are a strong argument for CNCF/LF developing and publishing guidance.

> I would love to see CNCF SIG Security discuss this first with some recommendations, then bring it back to the TOC and wider community for input.

I've filed an issue in the SIG security repository: https://github.com/cncf/sig-security/issues/558

**Comment by kfox1111** [comment]
Looks like the Linux Foundation just announced something that could help:
https://www.darkreading.com/application-security/linux-foundation-debuts-sigstore-project-for-software-signing/d/d-id/1340360

**Comment by dims** [comment]
Closing this in favor of https://github.com/cncf/tag-security/issues/558 please reopen if needed
