### ISSUE TITLE
Proposing OpenTelemetry for incubation

### ISSUE THREAD

**Issue by sarahnovotny** [cncf/toc#614]
This issue is to track the Sandbox -> Incubation proposal for the OpenTelemetry project.

@ccaraman has documents to attached.

@cncf/cncf-sig-observability has been holding discussions about the project's maturity.

**Comment by amye** [comment]
Oh, sharks, I missed that this was an Issue and not a PR.
PR is preferred because then I have something to merge into the incubated folder upon successful graduation.

**Comment by sarahnovotny** [comment]
[document for DD](https://docs.google.com/document/d/1f4WQR6K84giyOCKjCsqcoVA8YUIzBhWZDVo3CwM1wuk/edit#bookmark=id.tsd579u79lx2) to incubation.

**Comment by sarahnovotny** [comment]
> Oh, sharks, I missed that this was an Issue and not a PR.
> PR is preferred because then I have something to merge into the incubated folder upon successful voting for incubation.

we can convert to a PR at somepoint.  is this enough to start, @amye ?

**Comment by amye** [comment]
> > Oh, sharks, I missed that this was an Issue and not a PR.
> > PR is preferred because then I have something to merge into the incubated folder upon successful voting for incubation.
> 
> we can convert to a PR at somepoint. is this enough to start, @amye ?

Yep, that's why I left it on the board. It's fine to have this as a starting point.

**Comment by lizthegrey** [comment]
Sorry, I've been out on PTO for a few weeks, have we entered public comment period yet?

**Comment by lizthegrey** [comment]
https://share.getcloudapp.com/E0uALQxg -- aha, yes, it doesn't note changes in the Board on the Issue history.
