### ISSUE TITLE
Update incubation process to use pull request, instead of issue

### ISSUE THREAD

**Issue by tomkerkhove** [cncf/toc#623]
Currently the incubation process defines that it needs to be triggered by an issue ([docs](https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#incubation-process)) but after opening https://github.com/cncf/toc/issues/621 and talking to @amye it turns out that it should have been a PR instead.

The process should be updated so that:
- It mentions that a PR is required, instead of an issue
- It mentions what the initial PR should contain, since DD is only done later in the process

**Comment by amye** [comment]
Self-assigning because I could have sworn this got updated before
