### ISSUE TITLE
[PROJECT ONBOARDING] Kuberhealthy 

### ISSUE THREAD

**Issue by amye** [cncf/toc#627]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project. 

From the project side, please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
- [x] Has your project adopted open governance already? see http://opengovernance.dev

Things that CNCF will need from the project: 
- [x] Owners file: Please add a link to your owners file to this issue, this is used to be able to create your maintainers mailing list. 
- [x] Create maintainer list + added to aggregated https://maintainers.cncf.io list
- [x] Domain: transfer domain to CNCF/LF (ITx)
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF - https://www.linuxfoundation.org/en/trademark-usage/ has guidelines 
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [x] Artwork: Ensure logos present on https://github.com/cncf/artwork
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices) followed
- [x] Website: Analytics transferred

Things that the CNCF will do or help the project to do: 
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Trail Map: update CNCF trail map if relevant (incubating projects and above)
- [x] Update https://landscape.cncf.io
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access
- [x] Schedule monthly project sync with CNCF staff

**Comment by integrii** [comment]
This is awesome.  Thanks!  We are going to review this list internally and take any steps we can.

**Comment by lukaszgryglicki** [comment]
DevStats [page](https://kuberhealthy.devstats.cncf.io) ready, it lacks artwork and affiliations data, but this will be updated when ready (artwork merged into `cncf/artwork` and affiliations data processed).

**Comment by integrii** [comment]
'thelinuxfoundation' and 'caniszczyk' have been invited to our `kuberhealthy` organization.

**Comment by amye** [comment]
@integrii: Thank you! 
Next steps: 
 Owners file: Please add a link to your owners file to this issue, this is used to be able to create your maintainers mailing list.
 Create maintainer list + added to aggregated https://maintainers.cncf.io list
 Domain: transfer domain to CNCF/LF (ITx)
 Trademarks: transfer any trademark and logo mark assets over to the LF - https://www.linuxfoundation.org/en/trademark-usage/ has guidelines
 GitHub: ensure DCO or CLA are enabled for all GitHub repositories of the project
 Artwork: Ensure logos present on https://github.com/cncf/artwork
 Website: ensure LF footer is there and website guidelines followed
 Website: Analytics transferred

**Comment by joshulyne** [comment]
Team has reviewed: 
- `Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md` ✅ 
- ` Understand the services available for your project at CNCF: https://www.cncf.io/services-for-projects/` ✅  
- `Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy` -- WIP with Comcast legal
- `Has your project adopted open governance already? see http://opengovernance.dev` - Our team has not adopted open governance yet. 

Owners file: https://github.com/Comcast/kuberhealthy/blob/master/OWNERS

Create maintainer list + added to aggregated: commented:
```
Maintainers - Company - Github Name
Eric Greer - Comcast - integrii
Joshulyne Park - Comcast - joshulyne
Jonathan Phan - Comcast - jonnydawg
```

**Comment by shillasaebi** [comment]
Hello! I e-mailed the signed trademark transfer form for Kuberhealthy to @amye  & @caniszczyk on Monday, April 19, 2021 at 2:50 PM ET as a part of the onboarding step above. Thanks!

**Comment by shillasaebi** [comment]
Got the signed copy (both sides) back from Amye. We are all set on the trademark transfer step. Thank you!

**Comment by amye** [comment]
Marking off trademarks, can you confirm on: 
 Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
 Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
 Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
 Has your project adopted open governance already? see http://opengovernance.dev

**Comment by shillasaebi** [comment]
Yes, you can check off the following too:

- Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md

For the question about governance: 

- Has your project adopted open governance already? -  Our team has not adopted open governance yet. Do we need to? Would love your guidance on this one. 

Thank you!

**Comment by amye** [comment]
> Yes, you can check off the following too:
> 
> * Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
> * Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
> 
> For the question about governance:
> 
> * Has your project adopted open governance already? -  Our team has not adopted open governance yet. Do we need to? Would love your guidance on this one.

For a sandbox project, having the awareness and intention to adopt open governance is what we're looking for, you will definitely need this to move to incubation. 
> 
> Thank you!

**Comment by shillasaebi** [comment]
Fantastic, thank you @amye 

Please feel free to check off all of the below items please: 

- Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
- Has your project adopted open governance already?

Appreciate your help! 

Shilla

**Comment by amye** [comment]
@joshulyne: Your owners file doesn't have emails attached to it, do you mind giving me the addresses privately? amye@linuxfoundation.org will work.

**Comment by amye** [comment]
Last things remaining: 
* GitHub: ensure DCO or CLA are enabled for all GitHub repositories of the project
* Artwork: Ensure logos present on https://github.com/cncf/artwork
* Website: ensure LF footer is there and website guidelines followed
* Website: Analytics transferred
* Landscape: where should this be on the landscape?

**Comment by joshulyne** [comment]
> GitHub: ensure DCO or CLA are enabled for all GitHub repositories of the project 

How do we enable this? We're also planning to migrate our project from `comcast/kuberhealthy` to `kuberhealthy/kuberhealthy`
> Landscape: where should this be on the landscape? 

Observability and Analysis, Monitoring

For the remaining items, it would be great to have a quick meeting to discuss as we'd appreciate CNCF help on these items -- I believe @shillasaebi will email you for this!
```
- Artwork: Ensure logos present on https://github.com/cncf/artwork
- Website: ensure LF footer is there and website guidelines followed
- Website: Analytics transferred
```

**Comment by amye** [comment]
> > GitHub: ensure DCO or CLA are enabled for all GitHub repositories of the project
> 
> How do we enable this? We're also planning to migrate our project from `comcast/kuberhealthy` to `kuberhealthy/kuberhealthy`
@idvoretskyi can help answer 
> 
> > Landscape: where should this be on the landscape?
> 
> Observability and Analysis, Monitoring
> 
> For the remaining items, it would be great to have a quick meeting to discuss as we'd appreciate CNCF help on these items -- I believe @shillasaebi will email you for this!
> 
> ```
> - Artwork: Ensure logos present on https://github.com/cncf/artwork
Do you have a logo currently available? I can get our design team to add that. 

> - Website: ensure LF footer is there and website guidelines followed
Pretty straightforward: https://www.envoyproxy.io/ is a good example of what the LF footer looks like! 

> - Website: Analytics transferred
Invite amye@linuxfoundation.org as an owner! 
> ```

**Comment by joshulyne** [comment]
> Do you have a logo currently available? I can get our design team to add that.

We do have a logo available, but we're really open to better ideas for it!
- https://github.com/Comcast/kuberhealthy/blob/master/images/kuberhealthy.png
-  https://github.com/Comcast/kuberhealthy/blob/master/images/logo-square.png

**Comment by amye** [comment]
> > Do you have a logo currently available? I can get our design team to add that.
> 
> We do have a logo available, but we're really open to better ideas for it!
> 
> * https://github.com/Comcast/kuberhealthy/blob/master/images/kuberhealthy.png
> * https://github.com/Comcast/kuberhealthy/blob/master/images/logo-square.png

Oh, I can definitely work with this! We can revise in future, this just helps you close out onboarding. :)

**Comment by lukaszgryglicki** [comment]
Can you please ping me when main repo moves to a new GitHub org? I'll update DevStats then.

**Comment by joshulyne** [comment]
> Can you please ping me when main repo moves to a new GitHub org? I'll update DevStats then.

Yes, will do!

**Comment by idvoretskyi** [comment]
> GitHub: ensure DCO or CLA are enabled for all GitHub repositories of the project

@joshulyne if DCO is sufficient for you, please enable this - https://github.com/apps/dco

**Comment by poconnor1** [comment]
Hi @idvoretskyi and @joshulyne 
I've recently joined CNCF to help with project onboarding. Nice to meet you!
I wanted to check where we stand on these items below:

- Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- Domain: transfer domain to CNCF/LF (ITx)
- GitHub: ensure DCO or CLA are enabled for all GitHub repositories of the project

Thank you for the help! Reach out with any questions.

**Comment by integrii** [comment]
Quick update on onboarding here.

- This week were able to migrate our code from `Comcast/kuberhealthy` to `kuberhealthy/kuberhealthy` on Github. @lukaszgryglicki
- I just enabled the DCO bot on all repositories in the `kuberhealthy` Github organization.
- I would like to see us switch to using a `CLA` bot instead of the `DCO` bot.  What would be the right way to enable the `CLA` bot for CNCF?
- I am ready to transfer `kuberhealthy.com` to the CNCF.  I already own this domain personally so I just need a point of contact to work with for the migration.  I will ask @shillasaebi from our side who the trusted point of contact is on the CNCF side.  I am assuming it will be @amye

**Comment by amye** [comment]
Super! https://github.com/cncf/landscape/pull/2076 is updated with the new repo, I will mark off the DCO piece. 
Suggest staying with a DCO as it's a little less management than a CLA, but we can look at that in the future? 
Domain transfer: email a transfer code to amye@linuxfoundation.org and we'll get started.

**Comment by integrii** [comment]
Done: 
- We just looked through the IP policy as a team and we believe we meet all the requirements
- We don't currently have an official website or documentation website, so the items about a footer do not apply to us (yet!)

In progress:
- Domain transfer is in progress (we emailed Amye just moments ago!)
- We will work on enabling the CLA bot.  It looks like [this guide](https://github.com/kubernetes/community/blob/master/github-management/setting-up-cla-check.md) is the setup guide we need to follow.

**Comment by caniszczyk** [comment]
@integrii FYI you can just use DCO, you don't need a CLA unless you really want one

**Comment by caniszczyk** [comment]
@integrii it's a one click enable here https://github.com/apps/dco

**Comment by integrii** [comment]
I think it has been harder to get people signing every commit than it has for people to do a one time acknowledgement through the CLA bot in my experience.  We also had some issues where our github action bots weren't properly signing commits, even though they were configured to...

**Comment by amye** [comment]
Domain transfer is complete, definitely recommend the DCO as a good option. 
So close!

**Comment by caniszczyk** [comment]
it's up to you @integrii - I find CLA's a higher bar since it's a legal agreement to sign by someone authorized

can you also update all the documentation here https://github.com/kuberhealthy/kuberhealthy/blob/master/CONTRIBUTING.md to no longer mention the Comcast CLA :)?

**Comment by integrii** [comment]
I think for now we're going to stick with the CLA because we've seen that nearly everyone gets their commit signing wrong.  It also seems to mess with some of the github actions we use (because they aren't signing commits properly).

In the future, we can always switch over to a DCO bot, right?

I sent an email to @caniszczyk to request the CLA bot secret.  I also can confirm that the kuberhealthy.com domain was successfully transfered.  Nice!

**Comment by integrii** [comment]
Just merged a PR to remove mentions of Comcast from the `CONTRIBUTING.md` file as requested.

**Comment by amye** [comment]
Marking as closed, welcome in!

**Comment by integrii** [comment]
FYI we did decide to go with the DCO bot instead of the CLA bot ultimately!
