### ISSUE TITLE
[PROJECT ONBOARDING] Trickster

### ISSUE THREAD

**Issue by amye** [cncf/toc#629]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project. 

From the project side, please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
- [x] Has your project adopted open governance already? see http://opengovernance.dev

Things that CNCF will need from the project: 
- [x] Owners file: Please add a link to your owners file to this issue, this is used to be able to create your maintainers mailing list. 
- [x] Create maintainer list + added to aggregated https://maintainers.cncf.io list
- [x] Domain: transfer domain to CNCF/LF (ITx)
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF - https://www.linuxfoundation.org/en/trademark-usage/ has guidelines 
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [ ] Artwork: Ensure logos present on https://github.com/cncf/artwork
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices) followed
- [x] Website: Analytics transferred

Things that the CNCF will do or help the project to do: 
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Trail Map: update CNCF trail map if relevant (incubating projects and above)
- [x] Update https://landscape.cncf.io
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access
- [x] Schedule monthly project sync with CNCF staff

**Comment by amye** [comment]
@jranson, welcome in! We'll be tracking work in here.

**Comment by lukaszgryglicki** [comment]
DevStats [page](https://trickster.devstats.cncf.io) ready, it lacks artwork and affiliations data, but this will be updated when ready (artwork merged into `cncf/artwork` and affiliations data processed).

**Comment by jranson** [comment]
We have initiated the domain transfer process for tricksterproxy.io; this currently just redirects to our main github repo. So we do not have any analytics to transfer. Would you like for us to add the LF footer onto the readme there?

Separately, we have added LF and Chris as owners to the GH Organization.

You can find our logos here: https://github.com/tricksterproxy/trickster/tree/main/docs/images/logos   do we need to do anything, like create the logo variants, ourself?

Our github projects are currently connected to the Comcast CLA for PR's; is there any guidance or documentation for changing to the CNCF CLA?

Thank you!

**Comment by caniszczyk** [comment]
@jranson re: CLA, we can move to the CNCF CLA or you can drop it and just use DCO which almost all CNCF projects use except k8s https://github.com/apps/dco

You essentially do 'git commit -s <commit info>' to sign off your commits versus having to sign legal documents for all contributors which can be a higher barrier

**Comment by jranson** [comment]
Great, thanks! I've removed the Comcast CLA app and installed the DCO app.

**Comment by amye** [comment]
Request for logo edits is in with the design team!

**Comment by amye** [comment]
> We have initiated the domain transfer process for tricksterproxy.io; 
Still pending. 
this currently just redirects to our main github repo. So we do not have any analytics to transfer. Would you like for us to add the LF footer onto the readme there?
> 
Yes please! 
> Separately, we have added LF and Chris as owners to the GH Organization.
> 
> You can find our logos here: https://github.com/tricksterproxy/trickster/tree/main/docs/images/logos do we need to do anything, like create the logo variants, ourself?
> 
> Our github projects are currently connected to the Comcast CLA for PR's; is there any guidance or documentation for changing to the CNCF CLA?
> 
> Thank you!

**Comment by shillasaebi** [comment]
Hello! I e-mailed the signed trademark transfer form for Trickster to @amye & @caniszczyk on Monday, April 19, 2021 at 2:50 PM ET as a part of the onboarding step above.

**Comment by shillasaebi** [comment]
Got the signed copy (both sides) back from Amye. We are all set on the trademark transfer step. Thank you!

**Comment by amye** [comment]
Marking off trademarks!

**Comment by amye** [comment]
@shillasaebi, can you confirm on the following?
 Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
 Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
 Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
 Has your project adopted open governance already? see http://opengovernance.dev

**Comment by jranson** [comment]
Hi Amye, I will go through those items for you and let you know when they
can be checked off. I have been focusing on the more technical aspects
first (swapping out the license, setting up the DCO), and and ready to get
on those for you.

**Comment by poconnor1** [comment]
Hi @jranson, 
I've recently joined CNCF to help with project onboarding. Nice to meet you!
I wanted to check where we stand on these items below:

- Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- Has your project adopted open governance already? see http://opengovernance.dev

- As well as:
- Domain: transfer domain to CNCF/LF (ITx)
- GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- GitHub: ensure DCO or CLA are enabled for all GitHub repositories of the project
-  Artwork: Ensure logos present on https://github.com/cncf/artwork
-  Website: ensure LF footer is there and website guidelines followed
-  Website: Analytics transferred

Thank you for the help! Reach out with any questions.

**Comment by jranson** [comment]
@poconnor1 thanks for checking in.  We have already communicated several of these items as completed or not applicable, above in the prior comments. It would be a good idea to read through those and tick those off for us. We will have updates on the remaining items early next week.

**Comment by amye** [comment]
Actually, last thing that I see is artwork! Is there a folder out in the wild that has that and can be moved into the cncf artwork repo?

**Comment by jranson** [comment]
Thanks @amye! 

On the artwork, we previously provided the URL to https://github.com/tricksterproxy/trickster/tree/main/docs/images/logos in a comment on this issue, and in a later comment you stated that edits are in to the design team. Is that activity separate from something else we need to provide around artwork?

Open Governance is also still unchecked; we will be publishing a GOVERNANCE.md document to the project in the next couple of days.

I noticed the "Schedule monthly project sync with CNCF staff" item was checked off, but should not have been as we have not coordinated that with you yet.

**Comment by amye** [comment]
We have a monthly project sync that went out to the maintainers, it is also on the CNCF public calendar. 
I will check with the design team to see where that stalled out, thanks!

**Comment by jranson** [comment]
We're good to go on Open Governance @ https://github.com/tricksterproxy/trickster/blob/main/GOVERNANCE.md

**Comment by amye** [comment]
Excellent! Artwork is on us, I will update as that completes.

**Comment by amye** [comment]
https://github.com/cncf/artwork/blob/master/examples/sandbox.md#trickster-logos is up, let me know if anything is in error.
With this, we are complete!

**Comment by caniszczyk** [comment]
wohoo!
