### ISSUE TITLE
TOC Leadership to take "Inclusive Open Source Community Orientation"

### ISSUE THREAD

**Issue by caniszczyk** [cncf/toc#638]
The CNCF TOC wants to take the new LFC 102 to provide feedback on the course before making any decisions regarding how it should be rolled out across the CNCF community:

- [x] Alena Prokharchyk
- [ ] Erin Boyd
- [x] Dave Zolotusky
- [x] Justin Cormack
- [x] Ricardo Rocha
- [x] Liz Rice
- [ ] Cornelia Davis
- [x] Davanum Srinivas
- [x] Saad Ali
- [ ] Sheng Liang
- [ ] Lei Zhang

https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/

**Comment by dims** [comment]
Folks, i have completed the LFC102 course. thanks!

**Comment by lizrice** [comment]
Done!

**Comment by saad-ali** [comment]
[Completed](https://ti-user-certificates.s3.amazonaws.com/e0df7fbf-a057-42af-8a1f-590912be5460/c6320537-967c-4b5b-bfdf-cd63bee8de00-saad-ali-inclusive-open-source-community-orientation-lfc102-certificate.pdf)
