### ISSUE TITLE
[PROJECT ONBOARDING] Emissary-ingress

### ISSUE THREAD

**Issue by amye** [cncf/toc#639]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project. 

From the project side, please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
- [x] Has your project adopted open governance already? see http://opengovernance.dev

Things that CNCF will need from the project: 
- [x] Owners file: Please add a link to your owners file to this issue, this is used to be able to create your maintainers mailing list. 
- [x] Create maintainer list + added to aggregated https://maintainers.cncf.io list
- [x] Domain: transfer domain to CNCF/LF (ITx)
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF - https://www.linuxfoundation.org/en/trademark-usage/ has guidelines 
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [x] Artwork: Ensure logos present on https://github.com/cncf/artwork
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices) followed
- [x] Website: Analytics transferred

Things that the CNCF will do or help the project to do: 
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Trail Map: update CNCF trail map if relevant (incubating projects and above)
- [x] Update https://landscape.cncf.io
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access
- [x] Schedule monthly project sync with CNCF staff

**Comment by lukaszgryglicki** [comment]
DevStats [test](https://emissaryingress.teststats.cncf.io) page added, will add a `prod` one tomorrow.

**Comment by lukaszgryglicki** [comment]
Devstats [prod](https://emissaryingress.devstats.cncf.io) page added, also added in projects health tables [here](https://all.devstats.cncf.io/d/53/projects-health-table) and [there](https://all.devstats.cncf.io/d/54/project-health-table?orgId=1&var-repogroup_name=Emissary-ingress).

Now adding this new project in [All CNCF](https://all.devstats.cncf.io) DevStats instance, creating affiliations research task and will update artwork from CNCF-stub once an artwork for this project is added in [cncf/artowrk](https://github.com/cncf/artwork).

**Comment by amye** [comment]
Grabbing maintainers file from: https://github.com/emissary-ingress/community/blob/main/MAINTAINERS.md

**Comment by amye** [comment]
@richarddli: Checking in here, we'll be spending more time focusing on onboarding in the next few weeks to help get you all over the line. 
Important things for next steps: 
Domain: transfer domain to CNCF/LF (ITx)
 Trademarks: transfer any trademark and logo mark assets over to the LF - https://www.linuxfoundation.org/en/trademark-usage/ has guidelines
 GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
 GitHub: ensure DCO or CLA are enabled for all GitHub repositories of the project
 Artwork: Ensure logos present on https://github.com/cncf/artwork
 Website: ensure LF footer is there and website guidelines followed
 Website: Analytics transferred

**Comment by richarddli** [comment]
Thanks. We don't have a domain/website (due to the rename), LF registered the TM for us, and Chris A created the GitHub org. So I think other than the artwork and DCO we are all set.

We estimate moving the code is a 6 week effort for our entire engineering team, which is tentatively scheduled to start after KubeCon EU.

**Comment by amye** [comment]
Marking off domain + website things, and 6 weeks is a reasonable expectation. I'll keep this open to track work. 
Separately, and this isn't on this list - artwork is also a dependency for getting your swag in the CNCF store. :)

**Comment by poconnor1** [comment]
Hi @richarddli 
Checking in here on the status of some of these items:

- Trademarks: transfer any trademark and logo mark assets over to the LF - https://www.linuxfoundation.org/en/trademark-usage/ has guidelines
- GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- GitHub: ensure DCO or CLA are enabled for all GitHub repositories of the project
- Artwork: Ensure logos present on https://github.com/cncf/artwork

Thank you!

**Comment by richarddli** [comment]
@poconnor1 See my comment previously: https://github.com/cncf/toc/issues/639#issuecomment-828804694

**Comment by poconnor1** [comment]
Thank you!

**Comment by richarddli** [comment]
Update: The GitHub code has been moved. https://github.com/emissary-ingress/emissary

**Comment by caniszczyk** [comment]
awesome! @richarddli do we have the logo updated yet?

**Comment by lukaszgryglicki** [comment]
DevStats updated accordingly.

**Comment by brianfleming** [comment]
@caniszczyk I have the versions of the emissary logo collected. If there is a better way for me to deliver them please let me know:

[logos-emissary.zip](https://github.com/cncf/toc/files/6616862/logos-emissary.zip)

**Comment by lukaszgryglicki** [comment]
Please create a PR against [cncf/artwork](https://github.com/cncf/artwork) - something like [this](https://github.com/cncf/artwork/pull/252) for example.

**Comment by amye** [comment]
Welcome letters are out, DCO is the last thing outstanding.

**Comment by richarddli** [comment]
DCO is done

**Comment by amye** [comment]
Marking this as closed!
