### ISSUE TITLE
[SANDBOX PROJECT ONBOARDING] WasmEdge Runtime

### ISSUE THREAD

**Issue by amye** [cncf/toc#646]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project. 
We would like to complete onboarding within one month of acceptance. 

From the project side, please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
- [x] Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/ 
- [x] Has your project adopted open governance already? see http://opengovernance.dev
- [x] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? 
- [x] Is your project in its own separate neutral github organization? 
- [x] Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io

Things that CNCF will need from the project: 
- [x] Owners file: Please add a link to your owners file to this issue, this is used to be able to create your maintainers mailing list. 
- [x] Create maintainer list + added to aggregated https://maintainers.cncf.io list
- [x] Domain: transfer domain to the CNCF - please send a transfer code to amye@linuxfoundation.org
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [x] Artwork: Ensure logos present on https://github.com/cncf/artwork
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices) followed
- [x] Website: Analytics transferred to amye@linuxfoundation.org
- [x] Adopt a license scanning tool, like FOSSA or Snyk
- [x] CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en

Things that the CNCF will do or help the project to do: 
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access, welcome email has monthly project sync details
- [x] Create space for meetings/events on community.cncf.io, e.g., https://community.cncf.io/pravega-community/

**Comment by lukaszgryglicki** [comment]
Is this `https://wasmer.io` and the main GH repo is: https://github.com/wasmerio ?

**Comment by lukaszgryglicki** [comment]
OK thanks, I wasn't sure about this one. maybe we should require those `onboarding` tickets to at least have a reference to the main repo?

**Comment by lukaszgryglicki** [comment]
Yeah, usually I'm able to find the main repo, and then I have a bunch of scripts to detect or/repo renames via BigQuery, etc. In this case, I wasn't even sure about the main repo. Anyway, thanks for the info.

**Comment by lukaszgryglicki** [comment]
DevStats [test](https://wasmedge.teststats.cncf.io) page added, will add `prod` one soon.

**Comment by lukaszgryglicki** [comment]
The [prod](https://wasmedge.devstats.cncf.io) page added as well.

**Comment by lukaszgryglicki** [comment]
All new 6 Sandbox projects added to [All CNCF](https://all.devstats.cncf.io) page, also added all of them in [Projects health](https://all.devstats.cncf.io/d/53/projects-health-table?orgId=1).

**Comment by syrusakbary** [comment]
Important note for everyone that might be interested.

Wasmer is already the owner of wasmedge.com (since December 2020) and we are already in the process of trademarking the name.
I would suggest choosing other name to not conflict with our existing project, as other issues might arise from that.

cc @caniszczyk  @lukaszgryglicki @thelinuxfoundation @amye

**Comment by caniszczyk** [comment]
@syrusakbary we did a due diligence search when coming up with the name, happy to have a discussion, but the github repo wasn't claim nor was a product name nor trademark when searched

Happy to chat https://calendly.com/caniszczyk to see if we can come to a reason resolution

**Comment by syrusakbary** [comment]
Happy to chat, as always. But it's not likely we will drop the name and trademark request.
As such I would recommend you to approach with a different name, since not doing so will likely cause other issues for your project down the line.

**Comment by alabulei1** [comment]
Hi Amye,
Please see the owner file link. Thanks.
https://github.com/WasmEdge/WasmEdge/blob/master/doc/OWNER.md

**Comment by alabulei1** [comment]
Hi Amye,

Just want you to know we have done most of the items on our to-do list except for the logo and trademark.

Pending issues:
1. Artwork: Ensure logos present on https://github.com/cncf/artwork -- Will do after we decide on a logo
2. Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io - Will do after we decide on a logo
3. CII: Start on a CII best practices badge -- We are working on this
4. Trademark related

Thanks.

**Comment by poconnor1** [comment]
Hi @alabulei1 
Thank you for the update!

**Comment by amye** [comment]
Tracking logo progress internally in LP-7497, will report back!

**Comment by alabulei1** [comment]
> Tracking logo progress internally in LP-7497, will report back!

Hi Amye, May I ask how is the logo design for WasmEdge progressing? Thanks.

**Comment by amye** [comment]
Here's a first round of design options to choose from: 
[WasmEdgeRuntime-logos.pdf](https://github.com/cncf/toc/files/6633070/WasmEdgeRuntime-logos.pdf)
Any stand out?

**Comment by alabulei1** [comment]
> Here's a first round of design options to choose from:
> [WasmEdgeRuntime-logos.pdf](https://github.com/cncf/toc/files/6633070/WasmEdgeRuntime-logos.pdf)
> Any stand out?

Thanks for your work. The one at bottom right is good!

**Comment by alabulei1** [comment]
Hi Amye,

I have submitted a pull request to add WasmEdge Runtime as a sandbox project to https://landscape.cncf.io and the PR has been merged. https://github.com/cncf/landscape/pull/2170

**Comment by amye** [comment]
Excellent! 
Welcome letters are out!
Who should be invited to a space on community.cncf.io to help host project meetings, etc? 

- Website: ensure LF footer is there and website guidelines followed
-  Website: Analytics transferred to amye@linuxfoundation.org
-  Adopt a license scanning tool, like FOSSA or Snyk
-  CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en

**Comment by alabulei1** [comment]
Thanks, Amye!
Please invite michael@secondstate.io, hydai@secondstate.io, and mistermac2008@gmail.com to the WasmEdge Space.
* Website: ensure LF footer is there and website guidelines followed - https://wasmedge.org/
* Website: Analytics transferred to amye@linuxfoundation.org - Done. Please check out your email.
* Adopt a license scanning tool, like FOSSA or Snyk - We have adopted FOSSA.
* CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en - We are working on this.

**Comment by amye** [comment]
Last piece: CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en 
Thanks!

**Comment by amye** [comment]
> Last piece: CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en
> Thanks!

Quick ping here!

**Comment by alabulei1** [comment]
> > Last piece: CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en
> > Thanks!
> 
> Quick ping here!

Hi Amye, 

A quick update, the WasmEdge project has gotten a CII best practices badge. Check out the details here. https://bestpractices.coreinfrastructure.org/en/projects/5059

One more thing, could you also add vivian@secondstate.io to the CNCF WasmEdge Space? Thanks.

**Comment by amye** [comment]
Complete! Welcome in!
