### ISSUE TITLE
[SANDBOX PROJECT ONBOARDING] Fluid

### ISSUE THREAD

**Issue by amye** [cncf/toc#648]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project. 
We would like to complete onboarding within one month of acceptance. 

From the project side, please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
- [x] Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/ 
- [x] Has your project adopted open governance already? see http://opengovernance.dev
- [x] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? 
- [x] Is your project in its own separate neutral github organization? 
- [x] Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io

Things that CNCF will need from the project: 
- [x] Owners file: Please add a link to your owners file to this issue, this is used to be able to create your maintainers mailing list. 
- [x] Create maintainer list + added to aggregated https://maintainers.cncf.io list
- [x] Domain: transfer domain to the CNCF - please send a transfer code to amye@linuxfoundation.org
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [x] Artwork: Ensure logos present on https://github.com/cncf/artwork
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices) followed
- [x] Website: Analytics transferred to amye@linuxfoundation.org
- [x] Adopt a license scanning tool, like FOSSA or Snyk
- [x] CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en

Things that the CNCF will do or help the project to do: 
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access, welcome email has monthly project sync details
- [x] Create space for meetings/events on community.cncf.io, e.g., https://community.cncf.io/pravega-community/

**Comment by amye** [comment]
Welcome! @ronggu, we'll be tracking work here. I already have your owners file, https://github.com/fluid-cloudnative/fluid/blob/master/MAINTAINERS.md, so marking that off.

**Comment by RongGu** [comment]
Thank you for the message and starting to helping us getting on onboard @amye . We are so thrilled to hear the news! We will completed the items in the checklist in these days, thanks!

**Comment by lukaszgryglicki** [comment]
DevStats [test](https://fluid.teststats.cncf.io) page added, will add `prod` one soon.

**Comment by lukaszgryglicki** [comment]
The [prod](https://fluid.devstats.cncf.io) page added as well.

**Comment by lukaszgryglicki** [comment]
All new 6 Sandbox projects added to [All CNCF](https://all.devstats.cncf.io) page, also added all of them in [Projects health](https://all.devstats.cncf.io/d/53/projects-health-table?orgId=1).

**Comment by amye** [comment]
@RongGu: checking in here!
Items outstanding:  
Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction
 Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
 Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
 Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
 Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/
 Has your project adopted open governance already? see http://opengovernance.dev
 Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack?
 Is your project in its own separate neutral github organization?
 Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io

 Domain: transfer domain to the CNCF - please send a transfer code to amye@linuxfoundation.org
 Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
 GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
 GitHub: ensure DCO or CLA are enabled for all GitHub repositories of the project
 Artwork: Ensure logos present on https://github.com/cncf/artwork
 Website: ensure LF footer is there and website guidelines followed
 Website: Analytics transferred to amye@linuxfoundation.org
 Adopt a license scanning tool, like FOSSA or Snyk
 CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en

**Comment by amye** [comment]
So in https://github.com/cncf/foundation/tree/master/agreements, we have a registered and non-registered trademark agreement. Here, the non-registered is likely what you need, and you can send a signed copy to me at amye@linuxfoundation.org.

**Comment by RongGu** [comment]
Thanks @amye! Here are another batch of tasks that we have finished. Please check it.
> 
> Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction

Yes. We have understood that.

> Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/

Yes. Got it!

> Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy

Yes. Our project aligns with the CNCF IP policy.

> Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md

Yes. We have read the online programs guidelines

> Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/

Yes. We understand the trademark guidelines.

> Has your project adopted open governance already? see http://opengovernance.dev

Yes. It's here https://github.com/fluid-cloudnative/fluid/blob/master/GOVERNANCE.md

> Artwork: Ensure logos present on https://github.com/cncf/artwork

Yes. Our logo PR has been merged. It's here https://github.com/cncf/artwork/pull/247

**Comment by RongGu** [comment]
Hey @amye , the following are the updates for two tasks.
> Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements

I have signed the agreement, and sent it to you by email. Please check it.

> GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership

We find that both 'thelinuxfoundation' and  'caniszczyk' have accepted our owner inivitations already. Whould you please also verify that. Thanks.

**Comment by amye** [comment]
We are complete here!
