### ISSUE TITLE
[SANDBOX PROJECT ONBOARDING] Antrea

### ISSUE THREAD

**Issue by amye** [cncf/toc#650]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project. 
We would like to complete onboarding within one month of acceptance. 

From the project side, please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
- [x] Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/ 
- [x] Has your project adopted open governance already? see http://opengovernance.dev
- [x] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? 
- [x] Is your project in its own separate neutral github organization? 
- [x] Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io

Things that CNCF will need from the project: 
- [x] Owners file: Please add a link to your owners file to this issue, this is used to be able to create your maintainers mailing list. 
- [x] Create maintainer list + added to aggregated https://maintainers.cncf.io list
- [x] Domain: transfer domain to the CNCF - please send a transfer code to amye@linuxfoundation.org
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [x] Artwork: Ensure logos present on https://github.com/cncf/artwork
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices) followed
- [x] Website: Analytics transferred to amye@linuxfoundation.org
- [x] Adopt a license scanning tool, like FOSSA or Snyk
- [x] CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en

Things that the CNCF will do or help the project to do: 
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access, welcome email has monthly project sync details
- [x] Create space for meetings/events on community.cncf.io, e.g., https://community.cncf.io/pravega-community/

**Comment by amye** [comment]
Tracking owners file from https://github.com/vmware-tanzu/antrea/blob/main/MAINTAINERS.md

**Comment by amye** [comment]
@antoninbas, let me know when you have this in its own repo. :)

**Comment by antoninbas** [comment]
@amye we are having a vote in our K8s Slack channel to decide the name of the new Github organization (we have reserved antrea-io and projectantrea). We will close the vote by end of week and move the repo.

**Comment by amye** [comment]
Oh, lovely! What good timing!

**Comment by lukaszgryglicki** [comment]
DevStats [test](https://antrea.teststats.cncf.io) page added, will add `prod` one soon.

**Comment by lukaszgryglicki** [comment]
The [prod](https://antrea.devstats.cncf.io) page added as well.

**Comment by lukaszgryglicki** [comment]
All new 6 Sandbox projects added to [All CNCF](https://all.devstats.cncf.io) page, also added all of them in [Projects health](https://all.devstats.cncf.io/d/53/projects-health-table?orgId=1).

**Comment by amye** [comment]
Checking in here, new name of things? We can get started from there.

**Comment by amye** [comment]
No changes to https://github.com/vmware-tanzu/antrea/blob/main/MAINTAINERS.md as part of this, right? 
(If so, we can move ahead on getting you all access.)

**Comment by antoninbas** [comment]
@amye No change to the maintainers list and everyone already has access. Do we need to add anyone on the CNCF side?

**Comment by amye** [comment]
Nope, this is getting you all on the public maintainers lists :)

**Comment by poconnor1** [comment]
Hi @antoninbas 
I've recently joined CNCF to help with project onboarding. Nice to meet you!
I wanted to check where we stand on these items below:

- Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction
-  Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
-  Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
-  Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
-  Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/
-  Has your project adopted open governance already? see http://opengovernance.dev
-  Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack?
-  Is your project in its own separate neutral github organization?
-  Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io

as well as:

- Domain: transfer domain to the CNCF - please send a transfer code to amye@linuxfoundation.org
-  Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
-  GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
-  GitHub: ensure DCO or CLA are enabled for all GitHub repositories of the project
-  Artwork: Ensure logos present on https://github.com/cncf/artwork
-  Website: ensure LF footer is there and website guidelines followed
-  Website: Analytics transferred to amye@linuxfoundation.org
-  Adopt a license scanning tool, like FOSSA or Snyk
-  CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en

Thank you for the help! Reach out with any questions.

**Comment by antoninbas** [comment]
@poconnor1 

> Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack?

We have been using the `#antrea` channel on the Kubernetes Slack pretty much since the inception of the Antrea project

> Is your project in its own separate neutral github organization?

Yes, we just completed the transfer to https://github.com/antrea-io/antrea

> GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership

I just sent them invitations to join the antrea-io organization as owners.


I will follow up on. the other items as we complete / verify them.

@lukaszgryglicki just letting you know that Antrea was transferred to https://github.com/antrea-io/antrea, in case it changes anything for DevStats.

**Comment by antoninbas** [comment]
@poconnor1 05/13/2021 update:
* we have enabled DCO
* we have enabled the FOSSA scanning tool

**Comment by amye** [comment]
@antoninbas: Excellent! Anything that I can help explain?

**Comment by antoninbas** [comment]
@amye No thanks, we are working on the Website items and we will update the status here later.

BTW, we have a passing CII best practices badge for Antrea: https://bestpractices.coreinfrastructure.org/en/projects/4173. We have had it for a while, but I went over the form today to make sure all links were up-to-date.

**Comment by antoninbas** [comment]
@amye I just sent the transfer code for the antrea.io domain to amye@linuxfoundation.org

**Comment by amye** [comment]
Caught! IT-22108 is open with our IT team to transfer.

**Comment by amye** [comment]
Marking trademarks as complete!

**Comment by amye** [comment]
Marking Domain off!
Checking back in on :  
* GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
* Artwork: Ensure logos present on https://github.com/cncf/artwork
* Website: ensure LF footer is there and website guidelines followed
* Website: Analytics transferred to amye@linuxfoundation.org
* Adopt a license scanning tool, like FOSSA or Snyk
* CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en

**Comment by antoninbas** [comment]
Hi @amye

* GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership - **done**, see https://github.com/cncf/toc/issues/650#issuecomment-840052739
* Artwork: Ensure logos present on https://github.com/cncf/artwork - **done**, see https://github.com/cncf/artwork/commit/f4067655cc649f006c71506c82acc5f7cc321eaa
* Website: ensure LF footer is there and website guidelines followed - **in progress**, should be done within 1-2 weeks
* Website: Analytics transferred to amye@linuxfoundation.org - **N/A**; we do not have analytics enabled in netlify as it is an extra charge ($9 a month); are analytics a requirement?
* Adopt a license scanning tool, like FOSSA or Snyk - **done**, FOSSA was added; see https://app.fossa.com/projects/git%2Bgithub.com%2Fantrea-io%2Fantrea?ref=badge_large
* CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en - **done**, see https://github.com/cncf/toc/issues/650#issuecomment-841511168

**Comment by antoninbas** [comment]
@amye in addition to the items above, I also updated the CNCF entry in cncf/landscape to reflect the acceptance into Sandbox: https://github.com/cncf/landscape/pull/2126

**Comment by amye** [comment]
Re: Website: Analytics transferred to amye@linuxfoundation.org - N/A; we do not have analytics enabled in netlify as it is an extra charge ($9 a month); are analytics a requirement?

Marking off, no need!

**Comment by amye** [comment]
@antoninbas: 
* Checking back in on https://antrea.io/'s footer
* Do you also want a space on community.cncf.io for meetings? 

Other project specific things!

-  Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction
-  Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
-  Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
-  Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
-  Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/
-  Has your project adopted open governance already? see http://opengovernance.dev

**Comment by antoninbas** [comment]
@amye we have updated the footer of the https://antrea.io/ website according to the [guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md).

I don't think there are any leftover items that need to be taken care of on our side. Please let me know what's required to add our community meeting to community.cncf.io.

**Comment by jittra201** [comment]
[](url)

**Comment by amye** [comment]
https://community.cncf.io/antrea-community/ is up and running, @antoninbas  - ping me with who needs to be added.
