### ISSUE TITLE
Sandbox followup for Service Mesh Performance and Meshery

### ISSUE THREAD

**Issue by amye** [cncf/toc#652]
The @cncf/toc had some questions regarding Service Mesh Performance and  Meshery which are being contributed to sandbox: https://github.com/layer5io/service-mesh-performance, https://github.com/layer5io/meshery  

Both Service Mesh Performance and Meshery are similar projects, and the TOC would like to have a followup proposal for either combining the two, or aligning these projects with the existing Service Mesh Interface project. 

Adding @leecalcote for awareness.

**Comment by miacycle** [comment]
> The @cncf/toc had some questions regarding Service Mesh Performance and Meshery which are being contributed to sandbox: https://github.com/layer5io/service-mesh-performance, https://github.com/layer5io/meshery
> 
> Both Service Mesh Performance and Meshery are similar projects, and the TOC would like to have a followup proposal for either combining the two, or aligning these projects with the existing Service Mesh Interface project.
> 
> Adding [@leecalcote](https://github.com/leecalcote) for awareness.

e exploring the community and projects, I have a favor to ask of you. Will you consider asking your friends to star the Meshery repo (https://github.com/meshery/meshery)? We're hoping for a big jump this month and need all the help that we can get. Do you think that you can make an impact on the project in this way?
