### ISSUE TITLE
Proposed Updates to Graduation Process   - June 15th TOC Meeting

### ISSUE THREAD

**Issue by amye** [cncf/toc#667]
The goal is to give projects more clarity and provide a framework for giving a project feedback on what the TOC would want them to address before graduation. We'll be reviewing at the June 15th meeting for community feedback. 

Incubation to Graduation proposal: 
- PR template that projects submit to the TOC
-- checkboxes for the things that are objective and need to be met
-- one page narrative around impact of project in Cloud Native landscape showing real life use, at scale, and trusted in production
- Projects nominate themselves
- Initial review in private, TOC sponsor volunteers at that point, feedback to project in the pull request 
- TOC reviews in a public meeting (2 a year scheduled) and provides feedback

Public review:
June 15
Confirmed process:
July 1

Proposed One Page Template: https://hackmd.io/@XYdYH0X5SYC3DUYFF5Wylg/Sy29x0qFO

**Comment by lizrice** [comment]
From TOC discussion today: 

* Initial TOC review should happen at the next closed TOC meeting (since the goal is to give projects quick feedback and unblock the graduation process). When we update the process documentation to reflect this new process, we should ask the project to add a link to the PR into the TOC Working Doc as a proposed agenda item, so we know it needs discussion. 

* Feedback goes onto the PR in public. If the project disagrees with the feedback or wants to bring it up at a public TOC meeting they can add it as an agenda item to the TOC Working Doc, and we should schedule it as soon as feasible. No need to limit these discussions to two per year.

**Comment by jberkus** [comment]
It seems odd to have the TAGs have zero involvement in the Graduation process. Shouldn't they review the application and comment, or something?

**Comment by mrbobbytables** [comment]
> It seems odd to have the TAGs have zero involvement in the Graduation process. Shouldn't they review the application and comment, or something?

I agree. The current graduation docs do specify that the TAGs may weigh in at the same time as end users during [step 2 of the graduation process](https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#graduation-process), but it may be worth at least a cursory check with the TAG before the initial private review to  follow up with the project.  They may know about potential issues that should be addressed that are not known to the TOC.

> Initial review in private, TOC sponsor volunteers at that point, feedback to project in the pull request.

A few small asks with this:
- Establish a timeframe for review, e.g. within 1 month, to not leave a project requesting review with an indeterminate amount of time before receiving feedback on the PR. 
- codify TOC volunteer in a similar way to the [TOC Incubation Sponsor](https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#incubation-process) in Step 2 of the graduation process (can't link directly  to the step -_-)

> TOC reviews in a public meeting (2 a year scheduled) and provides feedback

This seems like quite a long period between sessions to provide feedback, is there a reason for this vs adhoc like incubation? Ideally the incubation -> graduation phase should have less DD with more of the work being put at the sandbox -> graduation phase.

**Comment by amye** [comment]
Resolved, as of 9/17!
