### ISSUE TITLE
[SANDBOX PROJECT ONBOARDING] Service Mesh Performance

### ISSUE THREAD

**Issue by amye** [cncf/toc#676]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project. 
We would like to complete onboarding within one month of acceptance. 

From the project side, please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
- [x] Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/ 
- [x] Has your project adopted open governance already? see http://opengovernance.dev
- [x] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? 
- [x] Is your project in its own separate neutral github organization? 
- [x] Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io

Things that CNCF will need from the project: 
- [x] Owners file: Please add a link to your owners file to this issue, this is used to be able to create your maintainers mailing list. 
- [x] Create maintainer list + added to aggregated https://maintainers.cncf.io list
- [x] Domain: transfer domain to the CNCF - please send a transfer code to project-onboarding@cncf.io
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [x] Artwork: Ensure logos present on https://github.com/cncf/artwork
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices) followed
- [ ] Website: Analytics transferred to amye@linuxfoundation.org
- [x] Adopt a license scanning tool, like FOSSA or Snyk
- [x] CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en

Things that the CNCF will do or help the project to do: 
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access, welcome email has monthly project sync details
- [x] Create space for meetings/events on community.cncf.io, e.g., https://community.cncf.io/pravega-community/

**Comment by amye** [comment]
@leecalcote: is there an owners file for https://github.com/layer5io/service-mesh-performance? 
Thanks!

**Comment by lukaszgryglicki** [comment]
DevStats [page](https://servicemeshperformance.devstats.cncf.io) added, not completely added to [All CNCF](https://all.devstats.cncf.io) yet (it tracks new projects but doesn't have the past data yet (mean data from before today). 

The artwork is also missing, so it uses CNCF icons as a stub.

**Comment by lukaszgryglicki** [comment]
Please ping me when moved to a separate org.

**Comment by leecalcote** [comment]
> @leecalcote: is there an owners file for https://github.com/layer5io/service-mesh-performance?
> Thanks!

Here we are - https://github.com/layer5io/service-mesh-performance/blob/master/MAINTAINERS.md

**Comment by navendu-pottekkat** [comment]
@amye Thank you for adding the artwork for Meshery. https://github.com/cncf/artwork/pull/272

The Service Mesh Performance project artworks can also be found here- https://layer5.io/company/brand

[Download smp-brand-kit.zip](https://layer5.io/brand/smp-brand-kit.zip)

**Comment by navendu-pottekkat** [comment]
@amye @lukaszgryglicki I have opened up a PR to add Service Mesh Performance to the CNCF landscape: https://github.com/cncf/landscape/pull/2190

**Comment by navendu-pottekkat** [comment]
@lukaszgryglicki We have moved the project to a new org- https://github.com/service-mesh-performance/service-mesh-performance

**Comment by lukaszgryglicki** [comment]
Thanks for the info @navendu-pottekkat , I'm on PTO now, will update once I'm back.

**Comment by navendu-pottekkat** [comment]
We have migrated the Slack channel to CNCF: https://cloud-native.slack.com/messages/service-mesh-performance

**Comment by amye** [comment]
@navendu-pottekkat: Marking that off. Can you confirm any others?

**Comment by navendu-pottekkat** [comment]
These are also done:

Is your project in its own separate neutral github organization? - https://github.com/service-mesh-performance/service-mesh-performance

Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io - PR merged https://github.com/cncf/landscape/pull/2190

GitHub: ensure DCO or CLA are enabled for all GitHub repositories of the project

**Comment by amye** [comment]
Awesome, marking those off too.

**Comment by navendu-pottekkat** [comment]
@amye You can also mark off these:

 Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction

Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/

Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
 
Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/

**Comment by leecalcote** [comment]
Does this task have the correct link? "Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices) followed"

Are project maintainers empowered to manage their maintainers mailing list?

**Comment by amye** [comment]
(1) That's accurate, it's the copyright notice in the footer
(2) CNCF staff manages this for projects, and they're limited to who is on the OWNERS file for the project

**Comment by navendu-pottekkat** [comment]
@amye Here is an open PR to add SMP artwork: https://github.com/cncf/artwork/pull/273

**Comment by amye** [comment]
Marking artwork off!

**Comment by leecalcote** [comment]
Domain transfer code sent to project-onboarding@cncf.io. How do projects make updates to the domain once transferred?

**Comment by amye** [comment]
You'll still manage DNS, so shouldn't be an issue.

**Comment by amye** [comment]
Transfer in progess!

**Comment by leecalcote** [comment]
Thank you, @amye. Will a new mechanism to manage DNS be provided? The smp-spec.io domain is no longer visible/accessible using the original registrar's tooling (namecheap.com).

**Comment by navendu-pottekkat** [comment]
@amye I have opened a PR to update the maintainers: https://github.com/cncf/foundation/pull/170

I have also sent an email to add the maintainers to the mailing lists and Service Desk as well.

**Comment by amye** [comment]
Checking in here: 
 Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
 GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
Website: ensure LF footer is there and website guidelines followed
 Website: Analytics transferred to amye@linuxfoundation.org
 Adopt a license scanning tool, like FOSSA or Snyk
 CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en

**Comment by navendu-pottekkat** [comment]
**Done** : Website: ensure LF footer is there and website guidelines followed
**Done** : Adopt a license scanning tool, like FOSSA or Snyk

@leecalcote Could you chime in on the other items?

**Comment by amye** [comment]
> **Done** : Website: ensure LF footer is there and website guidelines followed **Done** : Adopt a license scanning tool, like FOSSA or Snyk
> 
> @leecalcote Could you chime in on the other items?

Marked off! 
Happy to help!

**Comment by amye** [comment]
> > **Done** : Website: ensure LF footer is there and website guidelines followed **Done** : Adopt a license scanning tool, like FOSSA or Snyk
> > @leecalcote Could you chime in on the other items?
> 
> Marked off! Happy to help!

@leecalcote  - your assistance here?

**Comment by amye** [comment]
Welcome onboard!
