### ISSUE TITLE
[SANDBOX PROJECT ONBOARDING] KubeVela

### ISSUE THREAD

**Issue by amye** [cncf/toc#677]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project. 
We would like to complete onboarding within one month of acceptance. 

From the project side, please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
- [x] Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/ 
- [x] Has your project adopted open governance already? see http://opengovernance.dev
- [x] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? 
- [x] Is your project in its own separate neutral github organization? 
- [x] Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io

Things that CNCF will need from the project: 
- [x] Owners file: Please add a link to your owners file to this issue, this is used to be able to create your maintainers mailing list. 
- [x] Create maintainer list + added to aggregated https://maintainers.cncf.io list
- [x] Domain: transfer domain to the CNCF - please send a transfer code to project-onboarding@cncf.io
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [x] Artwork: Ensure logos present on https://github.com/cncf/artwork
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices) followed
- [x] Website: Analytics transferred to amye@linuxfoundation.org
- [x] Adopt a license scanning tool, like FOSSA or Snyk
- [x] CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en

Things that the CNCF will do or help the project to do: 
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access, welcome email has monthly project sync details
- [x] Create space for meetings/events on community.cncf.io, e.g., https://community.cncf.io/pravega-community/

**Comment by amye** [comment]
Found https://github.com/oam-dev/kubevela/blob/master/OWNERS_ALIASES, marking owners off.

**Comment by lukaszgryglicki** [comment]
DevStats [page](https://kubevela.devstats.cncf.io) added, not completely added to [All CNCF](https://all.devstats.cncf.io) yet (it tracks new projects but doesn't have the past data yet (mean data from before today). 

The artwork is also missing, so it uses CNCF icons as a stub.

**Comment by BinaryHB0916** [comment]
hi Amye and Lukasz, I'm helping KubeVela to finish the rest process.

_Website: ensure LF footer is there and website guidelines followed_
Done. Please visit KubeVela.io to reconfirm.

I'll update once other actions accomplished.

**Comment by amye** [comment]
Marking that off! 
Artwork is the next helpful item. :)

**Comment by BinaryHB0916** [comment]
Sure thing. Created a PR to upload artwork: https://github.com/cncf/artwork/pull/277

**Comment by amye** [comment]
@BinaryHB0916: checking back in here!

- Domain: transfer domain to the CNCF - please send a transfer code to project-onboarding@cncf.io
-  Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
-  GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
-  GitHub: ensure DCO or CLA are enabled for all GitHub repositories of the project

**Comment by BinaryHB0916** [comment]
Thanks for the reminder. On going with all these Actions and they will be signed off starting next week.

**Comment by BinaryHB0916** [comment]
Updates：

- GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- Website: Analytics transferred to amye@linuxfoundation.org
Both have sent invitation emails accordingly. Please have a look.

- Domain: transfer domain to the CNCF - please send a transfer code to project-onboarding@cncf.io
- Trademarks: transfer any trademark and logo mark assets over to the LF - - -https://github.com/cncf/foundation/tree/master/agreements has agreements
These two require internal review process and it would take a little while.

**Comment by amye** [comment]
Great! Marking those two off, let me know if you need assistance.

**Comment by amye** [comment]
@BinaryHB0916:
Checking back in here, we have quite a few open issues!

**Comment by BinaryHB0916** [comment]
@amye thanks for the reminder. I'm on it:

- Domain transferring code is requesting and expecting to have it in a few days
- Trademark agreement is in progress for legal, it may takes months
- The rest actions will be done within a month

**Comment by amye** [comment]
> @amye thanks for the reminder. I'm on it:
> 
> * Domain transferring code is requesting and expecting to have it in a few days
> * Trademark agreement is in progress for legal, it may takes months
> * The rest actions will be done within a month

Checking back in here, we'd like to get all onboarding projects closed out by December 15th. Thanks!

**Comment by BinaryHB0916** [comment]
Hi Amye,

DONE:
- GitHub: ensure DCO or CLA are enabled for all GitHub repositories of the project
DCO has been intalled to the project of KubeVela.
- CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en
Had Configurated. It'll be showing after [this PR](https://github.com/oam-dev/kubevela/pull/2843) merged.
- Adopt a license scanning tool, like FOSSA or Snyk
Adopted Snyk

ONGOING:
- Domain transferring code is requesting and expecting to have it in a few days
Emailed you with the code, I assume that CNCF IT is taking care of this?
- Trademark agreement is in progress for legal, it may takes months
Our legal is on progress, I'll update the email thread once it updates.

Thanks very much.

**Comment by amye** [comment]
Responded! Process changed to submitting the code into LFIT!

**Comment by amye** [comment]
Quick check in here: 

- Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction
- Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
- Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/
- Has your project adopted open governance already? see http://opengovernance.dev

**Comment by BinaryHB0916** [comment]
KubeVela had meet all these checks.

Also, Internal process of trademark reviewing expects to end within a month and then agreement will be sent to you.

Thanks for all the assistances.

**Comment by amye** [comment]
Optional: Create space for meetings/events on community.cncf.io, e.g., https://community.cncf.io/pravega-community/

**Comment by amye** [comment]
Trademarks are with our Legal for review!

**Comment by amye** [comment]
Hi all, 
Just checking back in on domain transfer: https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63 is the best place to do that.

**Comment by BinaryHB0916** [comment]
@amye thanks for checking back. I'm a bit confused, do you mean kubevela.io in terms of domain transfer?

If so, that was sent to you via email before in the thread. I assume that now I need to do it again in https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63 as well?

**Comment by amye** [comment]
> @amye thanks for checking back. I'm a bit confused, do you mean kubevela.io in terms of domain transfer?
> 
> If so, that was sent to you via email before in the thread. I assume that now I need to do it again in https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63 as well?

Jira is the better path here

**Comment by BinaryHB0916** [comment]
@amye hi Amye, the domain transfer had been approved in Jira. I assume this one can be signed off now?

Other than that, does the trademark transfer go well?

**Comment by amye** [comment]
So! Yes on domain transfer, I need additional review on trademark.

**Comment by BinaryHB0916** [comment]
@amye thanks, may I ask how long would it take? KubeVela is about to propose for Incubation stage.
