### ISSUE TITLE
[SANDBOX PROJECT ONBOARDING] Krator

### ISSUE THREAD

**Issue by amye** [cncf/toc#691]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project. 
We would like to complete onboarding within one month of acceptance. 

From the project side, please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
- [x] Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/ 
- [x] Has your project adopted open governance already? see http://opengovernance.dev
- [x] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? 
- [x] Is your project in its own separate neutral github organization? 
- [x] Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io

Things that CNCF will need from the project: 
- [x] Owners file: Please add a link to your owners file to this issue, this is used to be able to create your maintainers mailing list. 
- [x] Create maintainer list + added to aggregated https://maintainers.cncf.io list
- [x] Domain: transfer domain to the CNCF - please send a transfer code to project-onboarding@cncf.io
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [x] Artwork: Ensure logos present on https://github.com/cncf/artwork
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices) followed
- [x] Website: Analytics transferred to amye@linuxfoundation.org
- [x] Adopt a license scanning tool, like FOSSA or Snyk
- [x] CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en

Things that the CNCF will do or help the project to do: 
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access, welcome email has monthly project sync details
- [ ] Create space for meetings/events on community.cncf.io, e.g., https://community.cncf.io/pravega-community/

**Comment by thomastaylor312** [comment]
We'll start working on these steps shortly! cc @kflansburg

**Comment by kfox1111** [comment]
@amye General workflow request. Could the template for new issues like this one be amended to include the current website for the project? Would help some of us that watch for toc issues but don't follow too closely to find information about new projects quicker.

**Comment by amye** [comment]
@kfox1111: Those are all available in the public sandbox application form, they're not required for onboarding. 
Feel free to look in: 
 https://docs.google.com/spreadsheets/d/1Nnh_usr0tSZxaUpxTusqeIqKxMmvuEViRkyO9e_Do40/edit#gid=1398510353

**Comment by amye** [comment]
> We'll start working on these steps shortly! cc @kflansburg

Owners file would be helpful! https://github.com/krator-rs/krator does not have one?

**Comment by thomastaylor312** [comment]
Yep, we'll take care of that first!

**Comment by kflansburg** [comment]
@amye We are tracking this work here https://github.com/krator-rs/krator/milestone/3.
Do you need me to keep the checklist here up to date in some fashion?

**Comment by amye** [comment]
> @amye We are tracking this work here https://github.com/krator-rs/krator/milestone/3.
> Do you need me to keep the checklist here up to date in some fashion?

As you complete work, dropping a comment in here so that I (and the team) can keep track would be super.

**Comment by lukaszgryglicki** [comment]
Devstats [instance](https://krator.devstats.cncf.io/d/8/dashboards) created.

**Comment by thomastaylor312** [comment]
Code owners added: https://github.com/krator-rs/krator/pull/37

**Comment by thomastaylor312** [comment]
What do we need to do for the maintainers list step? We can't edit the spreadsheet so is that something you'd like through email?

**Comment by kflansburg** [comment]
@amye Regarding the aggregated maintainer list, I do not work for Microsoft.

**Comment by kflansburg** [comment]
@amye Krator does not currently have a website, so the domain, footer, and analytics are not applicable.

**Comment by kflansburg** [comment]
@amye Krator does not own any trademarks and does not have a logo / artwork, so those items are not applicable.

**Comment by kflansburg** [comment]
'thelinuxfoundation' and 'caniszczyk' have been added as owners of krator-rs organization.

**Comment by kflansburg** [comment]
I have have installed the DCO bot in `krator-rs/krator`.

**Comment by caniszczyk** [comment]
@kflansburg we can create a logo for you, @amye can help, we prefer our projects to have a logo at least, any design inspiration?

**Comment by kflansburg** [comment]
> @kflansburg we can create a logo for you, @amye can help, we prefer our projects to have a logo at least, any design inspiration?

Awesome, I was planning to ask about that and do have some ideas. Thanks!

**Comment by amye** [comment]
> > @kflansburg we can create a logo for you, @amye can help, we prefer our projects to have a logo at least, any design inspiration?
> 
> Awesome, I was planning to ask about that and do have some ideas. Thanks!

Drop me an email with ideas: amye@linuxfoundation.org

**Comment by kflansburg** [comment]
@caniszczyk We are looking in to setting up FOSSA. I created a new org, but it sounds like there is a CNCF org we should be using. Can we be invited to that org and set up a krator project within it?

**Comment by caniszczyk** [comment]
Hey @idvoretskyi can you help here :)?

**Comment by idvoretskyi** [comment]
@kflansburg my suggestion will be to use Snyk for this (FOSSA’s support of Rust is in Alpha), which we are happy to set it up once we’ll figure out some final details on our end regarding Snyk.

**Comment by kflansburg** [comment]
> @kflansburg my suggestion will be to use Snyk for this (FOSSA’s support of Rust is in Alpha), which we are happy to set it up once we’ll figure out some final details on our end regarding Snyk.

Ok, sounds good. I will make a note to follow up.

**Comment by amye** [comment]
> @amye Krator does not own any trademarks

You should use the non-registered trademarks agreement!

**Comment by thomastaylor312** [comment]
We don't own any logos either. Do we still need the agreement?

**Comment by amye** [comment]
Yes, I think if you review https://github.com/cncf/foundation/blob/master/agreements/CNCF%20Trademark%20and%20Account%20Assignment%20Agreement%20(2020%20-%20no%20reg%20trademarks).pdf, it will make more sense.

**Comment by thomastaylor312** [comment]
Oh yeah, I should have figured that out on my own as I already read through it multiple times today for Krustlet. Gotta transfer those domains

**Comment by amye** [comment]
I figured that a nudge towards the paperwork might help, this should be easy.

**Comment by thomastaylor312** [comment]
Trademark agreement has been signed!

**Comment by amye** [comment]
> Trademark agreement has been signed!

Should I be looking in my inbox?

**Comment by thomastaylor312** [comment]
@caniszczyk Signed it. I can forward you a copy of the signed doc if you'd like!

**Comment by amye** [comment]
Please, a copy for records is always helpful. :)

**Comment by amye** [comment]
[krator-logos-v1.pdf](https://github.com/cncf/toc/files/6908604/krator-logos-v1.pdf)
Logo options are in!

**Comment by ddl-kevin** [comment]
> [krator-logos-v1.pdf](https://github.com/cncf/toc/files/6908604/krator-logos-v1.pdf)
> Logo options are in!

Awesome! I really like Ferris in the upper left. Could that be combined with the moon from the upper right? 

Thoughts @thomastaylor312 ?

**Comment by kflansburg** [comment]
> [krator-logos-v1.pdf](https://github.com/cncf/toc/files/6908604/krator-logos-v1.pdf)
> Logo options are in!

Awesome! I really like Ferris in the upper left. Could that be combined with the moon from the upper right?

Thoughts @thomastaylor312 ?

**Comment by thomastaylor312** [comment]
My favorite would be the top row, third from the left, but with ferris in front of the moon like the one on the upper right. I think the deeper grey with the red ferris color is really nice together. The combination one @kflansburg suggested would be my 2nd place choice

**Comment by amye** [comment]
@thomastaylor312, @kflansburg: can you meet and tell me what the path forward here is? Thanks!

**Comment by kflansburg** [comment]
> @thomastaylor312, @kflansburg: can you meet and tell me what the path forward here is? Thanks!

Thanks for following up! We discussed and settled on the one Taylor liked (top, third from the left), with Ferris in front of the moon if possible. Thanks!

**Comment by kflansburg** [comment]
@amye Thanks for the update. It looks like there may have been some miscommunication, our final selection was the top row, third from the left (with grey moon and bronze helmet), with Ferris moved in front of the moon.

Also, once we have a final version, will it be possible to get a vector graphic? 

Thanks!

**Comment by amye** [comment]
I see what happened, "Awesome! I really like Ferris in the upper left. Could that be combined with the moon from the upper right?" was communicated. 
We'll recalibrate!

**Comment by amye** [comment]
[krator-logos-v3.pdf](https://github.com/cncf/toc/files/7307227/krator-logos-v3.pdf)
Let me know if this suits.

**Comment by amye** [comment]
@kflansburg. @thomastaylor312: Checking in again, we'd like to get all project onboarding closed out by December 15th. Thanks!

**Comment by thomastaylor312** [comment]
I think everything in the "Things that CNCF will need from the project:" section are done. The license checker we are using is the same we are using in Krustlet, so we should be good there

**Comment by amye** [comment]
> I think everything in the "Things that CNCF will need from the project:" section are done. The license checker we are using is the same we are using in Krustlet, so we should be good there

Do I have a 'no registered trademark' agreement from you?

**Comment by thomastaylor312** [comment]
I am pretty sure we did an agreement for Krator when I was at Microsoft. @squillace could you by chance double check?

**Comment by amye** [comment]
No, you're right, July 28th says 'signed', let me go hunt on my side.

**Comment by amye** [comment]
The domain is actually missing on our end, we can do a ticket through LFIT: https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63 

amye@linuxfoundation.org is your LF contact, you'll want to choose 'Cloud Native Computing Foundation' for the project.

**Comment by squillace** [comment]
I'm out until after next week, but if I need to do something I can try when not intoxicated. Promise.

**Comment by thomastaylor312** [comment]
@amye I don't think we have a domain for krator

**Comment by amye** [comment]
That would do it!

**Comment by caniszczyk** [comment]
@thomastaylor312 I picked up krator.dev for all y'all then

**Comment by kflansburg** [comment]
Hey @amye the following are complete:
* Understand the project proposal process
* Understand the services available
* Review the online programs guidelines
* Understand the trademark guidelines
* Set up `#krator` channel in Kubernetes Slack 
* Neutral GitHub organization


* 'thelinuxfoundation' and 'caniszczyk' have been invited as org owners
* I've completed the CII Badge [here](https://bestpractices.coreinfrastructure.org/en/projects/5066).
* We use a Rust-specific license scanning tool, [cargo-deny](https://github.com/EmbarkStudios/cargo-deny). 


Regarding adding artwork to the CNCF artwork repo, do you have the original logo assets like a vector graphic, or is the PDF what I should submit?

**Comment by ddl-kevin** [comment]
> Re: artwork - we'll want SVG + PNG files, see https://github.com/cncf/artwork/tree/master/projects
> Thanks!

Hey @amye, I did not create our logo, a team from the CNCF did (see above in this thread). Can you reach out to them about this?

**Comment by kflansburg** [comment]
> Re: artwork - we'll want SVG + PNG files, see https://github.com/cncf/artwork/tree/master/projects 
> 
> Thanks!

Hey @amye, I did not create our logo, a team from the CNCF did (see above in this thread). Can you reach out to them about this?

**Comment by amye** [comment]
I've dropped a note over to @alexcontini to make sure they get in. All will be well!

**Comment by kflansburg** [comment]
> I've dropped a note over to @alexcontini to make sure they get in. All will be well!

Thanks!

**Comment by alexcontini** [comment]
@amye @kflansburg  logos have been added! https://github.com/cncf/artwork/tree/master/projects/krator 

let me know if there are any problems

**Comment by kflansburg** [comment]
> @amye @kflansburg logos have been added! https://github.com/cncf/artwork/tree/master/projects/krator
> 
> let me know if there are any problems

Looks great, thanks @alexcontini !

@amye Looks like artwork done!

**Comment by amye** [comment]
Dropping in here again! 
We're really close!
Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
Has your project adopted open governance already? see http://opengovernance.dev

Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io  -- https://github.com/cncf/landscape/pull/2432 should resolve this.

**Comment by amye** [comment]
One thing that you might want to be aware of as you look at the IP policy: https://www.linuxfoundation.org/telemetry-data-policy/

**Comment by kflansburg** [comment]
@squillace Does your comment relate to `krator`? I'm not aware of any license issues. 

@amye I may need some help to determine our compliance with IP policy:

* CNCF produced logo / artwork, so I believe that is no issue. 
* We use DCO for all submissions which I believe functions as a CLA. 
* Krator itself is Apache 2.0 and we do scan the licenses of dependencies.


Regarding open governance, I'm also a little unsure of the criteria here. Is there a standard template GOVERNANCE document that we can start from?

**Comment by squillace** [comment]
oh, whoops! thanks @kflansburg , no -- wrong project!!! "nevermind". :-|

**Comment by amye** [comment]
As long as you've considered open governance, that's fine. It's a requirement for incubating. :)

**Comment by kflansburg** [comment]
@amye It sounds like these tasks may be complete then. Thanks!

**Comment by amye** [comment]
Marking those off, welcome onboard!
