### ISSUE TITLE
[SANDBOX PROJECT ONBOARDING] wasmCloud

### ISSUE THREAD

**Issue by amye** [cncf/toc#693]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project. 
We would like to complete onboarding within one month of acceptance. 

From the project side, please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
- [x] Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/ 
- [x] Has your project adopted open governance already? see http://opengovernance.dev
- [x] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? 
- [x] Is your project in its own separate neutral github organization? 
- [x] Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io

Things that CNCF will need from the project: 
- [x] Owners file: Please add a link to your owners file to this issue, this is used to be able to create your maintainers mailing list. 
- [x] Create maintainer list + added to aggregated https://maintainers.cncf.io list
- [x] Domain: transfer domain to the CNCF - please send a transfer code to project-onboarding@cncf.io
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [x] Artwork: Ensure logos present on https://github.com/cncf/artwork
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices) followed
- [x] Website: Analytics transferred to amye@linuxfoundation.org
- [x] Adopt a license scanning tool, like FOSSA or Snyk
- [x] CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en

Things that the CNCF will do or help the project to do: 
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access, welcome email has monthly project sync details
- [x] Create space for meetings/events on community.cncf.io, e.g., https://community.cncf.io/pravega-community/

**Comment by amye** [comment]
@liamrandall & @autodidaddict: is there a good OWNERS file for this project?

**Comment by autodidaddict** [comment]
This is the file we have currently, but it points to a Github team rather than individual people. https://github.com/wasmCloud/wasmCloud/blob/main/.github/CODEOWNERS  Let me know if you'd like me to create an `OWNERS` file in the root of key repos with individuals.

**Comment by amye** [comment]
> This is the file we have currently, but it points to a Github team rather than individual people. https://github.com/wasmCloud/wasmCloud/blob/main/.github/CODEOWNERS Let me know if you'd like me to create an `OWNERS` file in the root of key repos with individuals.

The 2nd is much preferred, we use it to populate maintainers.cncf.io

**Comment by autodidaddict** [comment]
Here is one of the new `OWNERS` files: https://github.com/wasmCloud/wasmcloud-otp/blob/main/OWNERS

**Comment by LiamRandall** [comment]
Artwork: https://github.com/cncf/artwork/pull/279

**Comment by lukaszgryglicki** [comment]
Requested small changes on artwork PR.

**Comment by LiamRandall** [comment]
@lukaszgryglicki  closed the old pull request and added a new one:
https://github.com/cncf/artwork/pull/280

**Comment by lukaszgryglicki** [comment]
Devstats [instance](https://wasmcloud.devstats.cncf.io/d/8/dashboards) created.

**Comment by amye** [comment]
@idvoretskyi: There's a question about getting access to Snyk or FOSSA, can you help?

**Comment by idvoretskyi** [comment]
My suggestion will be to evaluate Snyk for this, but let’s put this on hold a bit -we’re working on the better integration with Snyk these days.

I’ll keep this issue posted!

**Comment by amye** [comment]
@LiamRandall: Checking back in here: 

- Domain: transfer domain to the CNCF - please send a transfer code to project-onboarding@cncf.io
-  Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
-  GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
-  GitHub: ensure DCO or CLA are enabled for all GitHub repositories of the project

**Comment by autodidaddict** [comment]
DCO has been enabled throughout the organization.

**Comment by amye** [comment]
Marked off!

**Comment by amye** [comment]
@autodidaddict: Checking back in here, anything else that can be checked off?

**Comment by autodidaddict** [comment]
@amye it was my understanding that everything had been taken care of and we were all set. @LiamRandall ?

**Comment by amye** [comment]
> @amye it was my understanding that everything had been taken care of and we were all set. @LiamRandall ?


I have these currently unmarked, 
 Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction
 Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
 Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
 Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
 Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/
 Has your project adopted open governance already? see http://opengovernance.dev
 Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack?
 Is your project in its own separate neutral github organization?
 Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io

**Comment by amye** [comment]
@LiamRandall @autodidaddict: Checking in again, we'd like to get all project onboarding closed out by December 15th. Thanks!

**Comment by autodidaddict** [comment]
Pinging @LiamRandall

**Comment by LiamRandall** [comment]
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
- [x] Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/
- [ ] Has your project adopted open governance already? see http://opengovernance.dev
(will review with the team tomorrow)
- [x] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack?
- [x] Is your project in its own separate neutral github organization?
- [ ] Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io
(in flight, determining category)

**Comment by idvoretskyi** [comment]
Thanks, @LiamRandall! Checked them for you.

Do you need assistance with anything else? Eg. license scanning.

**Comment by brooksmtownsend** [comment]
Landscape PR merged now, that can be checked off 🙂

**Comment by amye** [comment]
Analytics is caught!

**Comment by LiamRandall** [comment]
@amye  @idvoretskyi  License scanning is complete and just emailed over the CNCF Trademark and Account Assignment Agreememnt.

I think we are done!

**Comment by idvoretskyi** [comment]
@LiamRandall there are a few non-marked items here - https://github.com/cncf/toc/issues/693#issue-943674781, can you check their statuses please?

**Comment by amye** [comment]
Checking back in here: 
*  Has your project adopted open governance already? see http://opengovernance.dev 
* Domain: transfer domain to the CNCF - https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63 is best!
*  Website: ensure LF footer is there and website guidelines followed
* CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en
* [optional] Create space for meetings/events on community.cncf.io, e.g., https://community.cncf.io/pravega-community/

**Comment by LiamRandall** [comment]
- Has your project adopted open governance already? see http://opengovernance.dev
We have not published a GOVERNANCE document, but we do use an open process, host weekly community meetings ( https://youtube.com/wasmCloud ), maintain a decision log, and implement an RFC process on our github.

- Domain: transfer domain to the CNCF - https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63 is best!
I thought I had submitted this already; just dropped a new Jira ticket

- Website: ensure LF footer is there and website guidelines followed
Completed

- CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en
Started

[optional] Create space for meetings/events on community.cncf.io, e.g., https://community.cncf.io/pravega-community/

I think we're good?

**Comment by amye** [comment]
> * Has your project adopted open governance already? see http://opengovernance.dev
>   We have not published a GOVERNANCE document, but we do use an open process, host weekly community meetings ( https://youtube.com/wasmCloud ), maintain a decision log, and implement an RFC process on our github.
> * Domain: transfer domain to the CNCF - https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63 is best!
>   I thought I had submitted this already; just dropped a new Jira ticket
> * Website: ensure LF footer is there and website guidelines followed
>   Completed
> * CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en
>   Started
> 
> [optional] Create space for meetings/events on community.cncf.io, e.g., https://community.cncf.io/pravega-community/
> 
> I think we're good?

Rock and roll! We are, in fact, good here! 
I'll leave this open a bit as I chase down where that domain transfer might have landed, but welcome onboard!!

**Comment by amye** [comment]
Domain is complete, welcome onboard!
