### ISSUE TITLE
[SANDBOX PROJECT ONBOARDING] MetalLB

### ISSUE THREAD

**Issue by amye** [cncf/toc#720]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project. 
We would like to complete onboarding within one month of acceptance. 

From the project side, please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
- [x] Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/ 
- [ ] Understand the license allowlist: https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist
- [x] Has your project adopted open governance already? see http://opengovernance.dev
- [x] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? 
- [x] Is your project in its own separate neutral github organization? 
- [x] Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io
- [x] Create maintainer list + add to aggregated https://maintainers.cncf.io list by submitting a PR to it
- [x] Have added your project to https://github.com/cncf/contribute 
- [x] Artwork: Submit a pull request to https://github.com/cncf/artwork with your artwork

Things that CNCF will need from the project: 
- [x] Provide emails for the maintainers added to https://maintainers.cncf.io in order to get access to the maintainers mailing list and ServiceDesk
- [x] Domain: transfer domain to the CNCF - please send a transfer code to project-onboarding@cncf.io
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices) followed
- [x] Website: Analytics transferred to amye@linuxfoundation.org
- [x] CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en

Things that the CNCF will do or help the project to do: 
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access, welcome email has monthly project sync details
- [x] Create space for meetings/events on https://community.cncf.io, e.g., https://community.cncf.io/pravega-community/ -  (https://github.com/cncf/communitygroups/blob/main/README.md#cncf-projects)
- [x] Adopt a license scanning tool, like FOSSA or Snyk

**Comment by amye** [comment]
Hi @daxmc99 @johananl @rata @russellb -- https://github.com/metallb/metallb/blob/main/CODEOWNERS looks right for all of you?

**Comment by johananl** [comment]
> Hi @daxmc99 @johananl @rata @russellb -- https://github.com/metallb/metallb/blob/main/CODEOWNERS looks right for all of you?

@amye looks good to me.

**Comment by amye** [comment]
@johananl - fantastic! I've sent invites to the maintainers lists and to ServiceDesk for you all, next big things are submitting a PR to maintainers.cncf.io and a PR to artwork!

**Comment by lukaszgryglicki** [comment]
DevStats uses MetalLB since it switched to Kubernetes a long time ago, see [this](https://github.com/cncf/devstats-helm/blob/master/README.md#domain-dns-and-ingress).

**Comment by rata** [comment]
@amye 

> Hi @daxmc99 @johananl @rata @russellb -- https://github.com/metallb/metallb/blob/main/CODEOWNERS looks right for all of you?

Yes.

> @johananl - fantastic! I've sent invites to the maintainers lists and to ServiceDesk for you all, next big things are submitting a PR to maintainers.cncf.io and a PR to artwork!

@amye no, I didn't receive any email. Can you resend to rodrigocc@gmail.com? I've checked all my address that are associated with github and all work related accounts too, just in case, but didn't find anything).

**Comment by danderson** [comment]
Howdy @amye. I'm the current owner of three domains for this project (metallb.org, metallb.com, metallb.net). Should I wait until more initial setup stuff has been done before sending over the transfer codes, or can that happen in parallel with other things?

There are no registered trademarks or logo marks that I'm aware of, so I think that checklist item is a no-op.

I think those are the only two items that are relevant to me as opposed to the current maintainers, but I'll keep an eye out if you need anything else from me.

**Comment by amye** [comment]
(1) Transfer codes can happen now! 
You can start those transfers here: https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63  

(2) We do have 'no registered trademarks' version, so we will still need that: https://github.com/cncf/foundation/tree/master/agreements

**Comment by danderson** [comment]
Understood, I'll kick off domain transfers.

The no-trademarks agreement looks generally fine, except that I'm not a corporation, so the wording of the first paragraph isn't quite right for that.

I started MetalLB and open-sourced it while I was a Google employee (I no longer am), so part of the source code IP still lies with Google, I think? IANAL. Google authorized the release of the code under its current open-source license, and generally never expressed any interest in MetalLB as a company, but per Google's open-sourcing policies, they still own some of the copyright.

I'm happy to sign something along the lines of https://github.com/cncf/foundation/tree/master/agreements as myself, and I'm happy to cooperate with whatever y'all decide you need from Google. But I don't know what that might be :). If LF would like to discuss more privately, I'm at dave@natulte.net.

**Comment by amye** [comment]
@danderson: Ok, that is more complicated. I'll review, we usually just transfer trademarks and assets, not copyright.

**Comment by lukaszgryglicki** [comment]
DevStats [page](https://metallb.devstats.cncf.io) added.

**Comment by danderson** [comment]
Re: domain transfers, the jira portal isn't yet aware of MetalLB as a project. I'll check in periodically and will file the transfer requests once it's in there.

**Comment by amye** [comment]
> Re: domain transfers, the jira portal isn't yet aware of MetalLB as a project. I'll check in periodically and will file the transfer requests once it's in there.

Ah, you'll want to put that under 'Cloud Native Computing Foundation' instead.

**Comment by danderson** [comment]
Thanks. Domain transfer request filed: https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/IT-22909

**Comment by rata** [comment]
Hi, I've received the emails now (a few minutes after posting here, thanks!). I've been doing my homework also (didn't finish yet). Here is an update.

I ensure I understand: 
 - [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction
 - [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
 - [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
 - [x]  Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
 - [x] Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/
 - [ ] Understand the license allowlist: https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist
 - [ ] Has your project adopted open governance already? see http://opengovernance.dev
 - [x] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? --> Yes, on k8s slack
 - [x] Is your project in its own separate neutral github organization? --> Yes
 - [ ] Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io --> Already there, we might want to update some info, though
 - [x] Create maintainer list + add to aggregated https://maintainers.cncf.io list by submitting a PR to it --> Done, see https://github.com/cncf/foundation/pull/199
 - [x] Have added your project to https://github.com/cncf/contribute --> Yes, see https://github.com/cncf/contribute/pull/72
 - [ ] Artwork: Submit a pull request to https://github.com/cncf/artwork with your artwork

Things that CNCF will need from the project:
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership --> Added them as members. Do they need to be owners?
 - [x] GitHub: ensure DCO or CLA are enabled for all GitHub repositories of the project --> yes, we do

**Comment by amye** [comment]
Fantastic! Artwork is the next big step.

**Comment by vbatts** [comment]
> Thanks. Domain transfer request filed: https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/IT-22909

Kinvolk (now Microsoft) is ready to transfer metallb.io as well. I don't have access to this Jira.
What steps do I need to take?

**Comment by vbatts** [comment]
ah, missed `please send a transfer code to project-onboarding@cncf.io` up above. One moment.

**Comment by amye** [comment]
> > Thanks. Domain transfer request filed: https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/IT-22909
> 
> Kinvolk (now Microsoft) is ready to transfer metallb.io as well. I don't have access to this Jira.
> What steps do I need to take?

Try here:  https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63 --  https://sso.linuxfoundation.org/ will let you in!

**Comment by vbatts** [comment]
@amye thanks. Are you the LF stakeholder?

**Comment by amye** [comment]
> @amye thanks. Are you the LF stakeholder?

Yep, put me down and I can help as needed

**Comment by vbatts** [comment]
metallb.io transfer submitted! https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/IT-22957

**Comment by russellb** [comment]
I believe you can check off using open governance.

MetalLB does all development in the open using github, slack, and weekly video chat meetings.  There is a clear set of maintainers (4 maintainers from 3 different companies), and a documented procedure for how maintainers get added.  Other items are being resolved by joining CNCF, like moving ownership of project assets (domains) to a neutral party.

**Comment by amye** [comment]
> I believe you can check off using open governance.
> 
> MetalLB does all development in the open using github, slack, and weekly video chat meetings. There is a clear set of maintainers (4 maintainers from 3 different companies), and a documented procedure for how maintainers get added. Other items are being resolved by joining CNCF, like moving ownership of project assets (domains) to a neutral party.

Marking that off! 
Artwork is the next big one.

**Comment by danderson** [comment]
The only artwork MetalLB has is artwork that was created by CNCF for inclusion in the CNCF landscape. We have copies in the MetalLB repo at https://github.com/metallb/metallb/tree/main/website/static/images/logo , but I'm thinking CNCF might already have everything, since y'all made it in the first place?

**Comment by amye** [comment]
@danderson: I can get a ticket in with design for better artwork, that's fine. 
I know we've got license questions outstanding with legal, anything else that I can check off?

**Comment by amye** [comment]
@russellb: Checking in again, we'd like to get all project onboarding closed out by December 15th. Thanks!

**Comment by russellb** [comment]
> @russellb: Checking in again, we'd like to get all project onboarding closed out by December 15th. Thanks!

I'm sorry, I've lost track?  What are we missing?  I had an open ticket with legal that I think is waiting on their response?  I'm really not worried about it as I'm *pretty* sure it's fine, but some other community members wanted to clarify.

**Comment by amye** [comment]
Here's what I see outstanding: 
Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
 Website: Analytics transferred to amye@linuxfoundation.org
 CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en
Adopt a license scanning tool, like FOSSA or Snyk

**Comment by danderson** [comment]
For trademarks, my last reply still applies:

> The no-trademarks agreement looks generally fine, except that I'm not a corporation, so the wording of the first paragraph isn't quite right for that.
> 
> I started MetalLB and open-sourced it while I was a Google employee (I no longer am), so part of the source code IP still lies with Google, I think? IANAL. Google authorized the release of the code under its current open-source license, and generally never expressed any interest in MetalLB, but per Google's open-sourcing policies, they still own some of the copyright.
> 
> I'm happy to sign something along the lines of https://github.com/cncf/foundation/tree/master/agreements as myself, and I'm happy to cooperate with whatever y'all decide you need from Google. But I don't know what that might be :). If LF would like to discuss more privately, I'm at dave@natulte.net.

Last I head we were waiting on CNCF legal to indicate what needs to happen.

**Comment by russellb** [comment]
> Website: Analytics transferred to [amye@linuxfoundation.org](mailto:amye@linuxfoundation.org) 

I don't think we have any analytics to transfer, so you can close this one.

> CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en 
> Adopt a license scanning tool, like FOSSA or Snyk

OK, we'll look into these soon.  cc @rata @johananl @fedepaol

**Comment by idvoretskyi** [comment]
@russellb on the scanning tool, we have FOSSA and Snyk tools available for free for the projects, so let me know if you'll decide on one of them - I'll help you with setting them up.

**Comment by russellb** [comment]
> @russellb on the scanning tool, we have FOSSA and Snyk tools available for free for the projects, so let me know if you'll decide on one of them - I'll help you with setting them up.

Any preference or recommendation from your end?  It's a golang project, if that helps.  Hopefully it can be run as CI against the github repo and report against PRs or something like that?

**Comment by fedepaol** [comment]
> @russellb on the scanning tool, we have FOSSA and Snyk tools available for free for the projects, so let me know if you'll decide on one of them - I'll help you with setting them up.

I don't think we have a strong preference. MetalLB uses circleCI, having some example to set one of them would be super helpful.

**Comment by idvoretskyi** [comment]
@russellb you can use this GitHub Action for FOSSA, this might be the simplest solution - https://github.com/marketplace/actions/fossa-action.

Snyk is more feature-rich, so you can use it not only for license scanning but for other purposes as well (eg. vulnerability scanning). Golang is well-supported there - https://docs.snyk.io/products/snyk-open-source/language-and-package-manager-support/snyk-for-golang. CNCF is under the Enterprise plan, so anything that Snyk can offer, it's included there.

**Comment by idvoretskyi** [comment]
@fedepaol both work with CircleCI - https://docs.fossa.com/docs/circleci and https://docs.snyk.io/features/integrations/ci-cd-integrations/circleci-integration-overview; however we encourage projects to use GitHub Actions if possible.

**Comment by fedepaol** [comment]
> @fedepaol both work with CircleCI - https://docs.fossa.com/docs/circleci and https://docs.snyk.io/features/integrations/ci-cd-integrations/circleci-integration-overview; however we encourage projects to use GitHub Actions if possible.

That's reasonable. CircleCI was in place since a while now, migrating to gh actions is definitely doable but it will require a bit of time :-).

**Comment by russellb** [comment]
@idvoretskyi We have fossa running via a github action.  Can we get on the cncf plan somehow?  The way I have it set up so far it looks like I can't add other maintainers so they can help resolve the warnings.

**Comment by fedepaol** [comment]
> @idvoretskyi We have fossa running via a github action. Can we get on the cncf plan somehow? The way I have it set up so far it looks like I can't add other maintainers so they can help resolve the warnings.

via circleci*

**Comment by russellb** [comment]
> 



> > @idvoretskyi We have fossa running via a github action. Can we get on the cncf plan somehow? The way I have it set up so far it looks like I can't add other maintainers so they can help resolve the warnings.
> 
> via circleci*

github action?  https://github.com/metallb/metallb/blob/main/.github/workflows/fossa.yaml

@idvoretskyi can you also help us with access to Snyk?  The initial report from fossa is a bit of a nightmare of false positives, so I'd like to see if Snyk provides a better starting point.

**Comment by idvoretskyi** [comment]
@russellb I've created a Snyk org for you and added you as an org Admin! You are able to add other folks (or let me know if you want me to help with this).

**Comment by amye** [comment]
Circling back in here, only two things outstanding! (Trademarks are with legal) 
Understand the license allowlist: https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist 
CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en

**Comment by russellb** [comment]
> Circling back in here, only two things outstanding! (Trademarks are with legal) 
> Understand the license allowlist: https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist 

I opened CNCFSD-945 back in October for our one outstanding question about this.  Otherwise, I think we're fine.

> CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en

@fedepaol was working on this one.  It's tracked here: https://github.com/metallb/metallb/issues/1059

**Comment by rata** [comment]
The CII best practices badge should be done already, please mark it as done! :)

@amye Also, another question. We would like to use zoom for our community video calls, how should I request that? I think opening a generic issue in the CNCF service desk is probably not the way to go, but unsure what is the way to go. Can you please point me in the right direction? :)

**Comment by rata** [comment]
Oh, sorry then. Will do that! :)

**Comment by amye** [comment]
You are just fine :)

**Comment by ahrkrak** [comment]
Is this still waiting on CNCF Legal to indicate what needs to happen? (Seems like this is the only remaining item from the thread above...) Not sure where I'd go to check status of "CNCFSD-945" mentioned by @russellb above.
Would like to understand if there's anything we can do to push this to the next step. Seems like a shame to leave this hanging, given how widespread MetalLB usage is in the cloud native community.

**Comment by dims** [comment]
@ahrkrak that would be https://github.com/cncf/servicedesk

**Comment by fedepaol** [comment]
CNCFSD-945 is still marked as "waiting on legal", I left a ping on the issue.

**Comment by fedepaol** [comment]
And I agree with @ahrkrak , please let us know if there's something we can help with to move it forward.

**Comment by fedepaol** [comment]
@amye any reason why this is still open?

**Comment by fedepaol** [comment]
> Trademarks

oh, will try to move this forward

**Comment by danderson** [comment]
To repeat the comment I posted almost two years ago:

> The no-trademarks agreement looks generally fine, except that I'm not a corporation, so the wording of the first paragraph isn't quite right for that.
>
> I started MetalLB and open-sourced it while I was a Google employee (I no longer am), so part of the source code IP still lies with Google, I think? IANAL. Google authorized the release of the code under its current open-source license, and generally never expressed any interest in MetalLB, but per Google's open-sourcing policies, they still own some of the copyright.
>
> I'm happy to sign something along the lines of https://github.com/cncf/foundation/tree/master/agreements as myself, and I'm happy to cooperate with whatever y'all decide you need from Google. But I don't know what that might be :). If LF would like to discuss more privately, I'm at [dave@natulte.net](mailto:dave@natulte.net).

At this time I no longer have contacts at Google, so if you need anything from them, that's now on you. I'm effectively ignoring this thread until someone gives me specific instructions.

**Comment by amye** [comment]
Responded by email. Thanks for the ping!

**Comment by amye** [comment]
Closing as complete
