### ISSUE TITLE
[SANDBOX PROJECT ONBOARDING] karmada

### ISSUE THREAD

**Issue by amye** [cncf/toc#721]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project. 
We would like to complete onboarding within one month of acceptance. 

From the project side, please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
- [x] Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/ 
- [x] Understand the license allowlist: https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist
- [x] Has your project adopted open governance already? see http://opengovernance.dev
- [x] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? 
- [x] Is your project in its own separate neutral github organization? 
- [x] Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io
- [x] Create maintainer list + add to aggregated https://maintainers.cncf.io list by submitting a PR to it
- [x] Have added your project to https://github.com/cncf/contribute 
- [x] Artwork: Submit a pull request to https://github.com/cncf/artwork with your artwork

Things that CNCF will need from the project: 
- [x] Provide emails for the maintainers added to https://maintainers.cncf.io in order to get access to the maintainers mailing list and ServiceDesk
- [x] Domain: transfer domain to the CNCF - please send a transfer code to project-onboarding@cncf.io
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices) followed
- [x] Website: Analytics transferred to amye@linuxfoundation.org
- [x] CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en

Things that the CNCF will do or help the project to do: 
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access, welcome email has monthly project sync details
- [x] Create space for meetings/events on https://community.cncf.io, e.g., https://community.cncf.io/pravega-community/ -  (https://github.com/cncf/communitygroups/blob/main/README.md#cncf-projects)
- [x] Adopt a license scanning tool, like FOSSA or Snyk

**Comment by lukaszgryglicki** [comment]
DevStats [page](https://karmada.devstats.cncf.io) added.

**Comment by amye** [comment]
@kevin-wangzefeng: Ping over here too, we'd like to get you onboarded!

**Comment by RainbowMango** [comment]
Hi @amye These steps can be checked off:
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
>  Note: The invitation has been sent, waiting for @thelinuxfoundation and @caniszczyk to confirm.
- [x] GitHub: ensure DCO or CLA are enabled for all GitHub repositories of the project
- [x] CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en

**Comment by amye** [comment]
Lovely! 
Next big thing:  
Provide emails for the maintainers added to https://maintainers.cncf.io in order to get access to the maintainers mailing list and ServiceDesk

**Comment by RainbowMango** [comment]
You can get the maintainer's email from [MAINTAINERS.md](https://github.com/karmada-io/karmada/blob/master/MAINTAINERS.md) which is referenced by https://maintainers.cncf.io.

**Comment by RainbowMango** [comment]
@amye 
- Artwork: Submit a pull request to https://github.com/cncf/artwork with your artwork
It Will be done by https://github.com/cncf/artwork/pull/297.

**Comment by RainbowMango** [comment]
Hi @amye , these steps can be checked off:

> From the project side, please ensure that you:

- Understand the project proposal process and reqs:
- Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- Ensure your project meets the CNCF IP Policy:
- Review the online programs guidelines: 
- Understand the trademark guidelines:
- Understand the license allowlist:
- Has your project adopted open governance already? see http://opengovernance.dev
   A: in progress
- Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack?
   A: No.
- Is your project in its own separate neutral github organization?
   A: Yes.
- Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io
   This will be done by https://github.com/cncf/landscape/pull/2321

> Things that CNCF will need from the project:

- Domain: transfer domain to the CNCF - please send a transfer code to project-onboarding@cncf.io
   A: @kevin-wangzefeng has sent it.
- Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
   A: N/A.

**Comment by amye** [comment]
Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack?
A: No. 
@idvoretskyi can help with this. Do you already have slack channels?

Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
 -- No, we have a 'no registered trademarks agreement', please look again.

**Comment by RainbowMango** [comment]
Hi Amye,

> Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack?

We have Slack at https://karmada-io.slack.com and have two channels `general`/`karmada-dev`. Can we create a new channel in Kubernetes and CNCF Slack?

> Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements

Do we mean we need to sign the [CNCF Trademark and Account Assignment Agreement(for use with no registered trademarks)](https://github.com/cncf/foundation/blob/master/agreements/CNCF%20Trademark%20and%20Account%20Assignment%20Agreement%20(2020%20-%20no%20reg%20trademarks).pdf)? And send an email to project-onboarding@cncf.io?

**Comment by RainbowMango** [comment]
Hi @idvoretskyi  @amye 

> Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack?

I don't quite understand the rule. Does it mandatory for projects to create channels in CNCF slack(or Kubernetes)? Can we keep the slack [we are using now](https://join.slack.com/t/karmada-io/shared_invite/zt-omhy1wfa-LmAkCLfpDMnBjVXp3_U~0w)?

**Comment by amye** [comment]
> Hi @idvoretskyi @amye
> 
> > Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack?
> 
> I don't quite understand the rule. Does it mandatory for projects to create channels in CNCF slack(or Kubernetes)? Can we keep the slack [we are using now](https://join.slack.com/t/karmada-io/shared_invite/zt-omhy1wfa-LmAkCLfpDMnBjVXp3_U~0w)?

Only the CNCF + Kubernetes slack will keep history, that's why we are really encouraging projects to migrate to either one.

**Comment by amye** [comment]
@RainbowMango: Checking in again, we'd like to get all project onboarding closed out by December 15th. Thanks!

**Comment by RainbowMango** [comment]
Sure Amye. 
We are in the progress of migrating slack now.
And who can help with this task?
> Create space for meetings/events on https://community.cncf.io,

**Comment by idvoretskyi** [comment]
@RainbowMango I'll assist you with both tasks.

- for Slack migration, please follow the steps described here - https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another and provide me with an archival dump from your existing Slack (you can email or DM me on CNCF Slack).

- for community.cncf.io, I've created a chapter for you - https://community.cncf.io/karmada-community/. To be granted admin access to it, please create an account on community.cncf.io (top right corner), and I'll invite you as an admin after that.

**Comment by RainbowMango** [comment]
@amye @idvoretskyi 
The slack archival dump has been sent to @idvoretskyi , and the https://community.cncf.io/karmada-community/ also has been created.

**Comment by amye** [comment]
> @amye @idvoretskyi The slack archival dump has been sent to @idvoretskyi , and the https://community.cncf.io/karmada-community/ also has been created.

Should I mark that off for you?

**Comment by idvoretskyi** [comment]
FYI, Slack import is completed, let’s mark this off :)

**Comment by amye** [comment]
Marking off.
Trademarks seems the last big thing!

**Comment by RainbowMango** [comment]
Yes, @amye, we are on it.

> Create space for meetings/events on https://community.cncf.io

We can mark this off now I guess.

**Comment by amye** [comment]
Trademarks are in, marking this closed! Welcome onboard!
