### ISSUE TITLE
[SANDBOX PROJECT ONBOARDING] Inclavare Containers

### ISSUE THREAD

**Issue by amye** [cncf/toc#722]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project. 
We would like to complete onboarding within one month of acceptance. 

From the project side, please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
- [x] Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/ 
- [x] Understand the license allowlist: https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist
- [x] Has your project adopted open governance already? see http://opengovernance.dev
- [x] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? 
- [x] Is your project in its own separate neutral github organization? 
- [x] Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io
- [x] Create maintainer list + add to aggregated https://maintainers.cncf.io list by submitting a PR to it
- [x] Have added your project to https://github.com/cncf/contribute 
- [x] Artwork: Submit a pull request to https://github.com/cncf/artwork with your artwork

Things that CNCF will need from the project: 
- [x] Provide emails for the maintainers added to https://maintainers.cncf.io in order to get access to the maintainers mailing list and ServiceDesk
- [x] Domain: transfer domain to the CNCF - please send a transfer code to project-onboarding@cncf.io
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices) followed
- [x] Website: Analytics transferred to amye@linuxfoundation.org
- [x] CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en

Things that the CNCF will do or help the project to do: 
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Insights: add to LFX Insights <https://insights.v3.lfx.linuxfoundation.org/>
- [x] Marketing: update relevant intro + slide decks
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access, welcome email has monthly project sync details
- [x] Create space for meetings/events on https://community.cncf.io, e.g., https://community.cncf.io/pravega-community/ -  (https://github.com/cncf/communitygroups/blob/main/README.md#cncf-projects)
- [x] Adopt a license scanning tool, like FOSSA or Snyk

**Comment by lukaszgryglicki** [comment]
DevStats [page](https://inclavarecontainers.devstats.cncf.io) added.

**Comment by haosanzi** [comment]
LF footer is added in [Website](https://inclavare-containers.io/en/).

**Comment by amye** [comment]
@haosanzi: Excellent! Artwork is the next big thing.

**Comment by haosanzi** [comment]
The progress of the two tasks needs to be updated
> 1. Website: Analytics transferred to amye@linuxfoundation.org

Sorry, we don't have analytics currently. Are analytics a requirement?

> 2. Artwork: Submit a pull request to https://github.com/cncf/artwork with your artwork

Has added inclavare artwork to  `cncf/artwork`.  Please see [the link](https://github.com/cncf/artwork/blob/master/examples/sandbox.md#inclavare-containers-logos) for the detailed information.

**Comment by amye** [comment]
I will mark both of these off! 
Trademarks comes next, we have paperwork for registered and non registered.

**Comment by amye** [comment]
@haosanzi: 
checking in here, anything I can help with?

**Comment by haosanzi** [comment]
Hi, here is an update. 

I ensure I understand:

- Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction
-  Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
-  Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
-  Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
-  Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/
-  Understand the license allowlist: https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist
-  Create maintainer list + add to aggregated [https://maintainers.cncf.io](https://maintainers.cncf.io/) list by submitting a PR to it --> Done, see [Add Inclavare Containers as Sandbox](https://github.com/cncf/foundation/pull/201)

Things that CNCF will need from the project:

-  GitHub: ensure DCO or CLA are enabled for all GitHub repositories of the project --> yes, we do:  https://github.com/alibaba/inclavare-containers/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by YangLiang3** [comment]
@amye Thanks! please help on this.

**Comment by haosanzi** [comment]
@amye Hi, about to `Create space for meetings/events on community.cncf.io, e.g., https://community.cncf.io/pravega-community/`. We need one to interact with the community to engage more users and developers. 

I make a request as followed, but I am not sure whether it can meet the demand. Could you give us some help?
![image](https://user-images.githubusercontent.com/26923638/137440479-28430c59-906a-42ae-a599-1394577931c1.png)

**Comment by haosanzi** [comment]
The transfer code has been sent project-onboarding@cncf.io

**Comment by amye** [comment]
> Hi, here is the update.
> 
> > Domain: transfer domain to the CNCF - please send a transfer code to [project-onboarding@cncf.io](mailto:project-onboarding@cncf.io)
> 
> The transfer code has been sent [project-onboarding@cncf.io](mailto:project-onboarding@cncf.io)

Yep! Following up from email - process has shifted a bit, you can do this through Linux Foundation's IT portal: https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63

**Comment by haosanzi** [comment]
Hi, the request is submitted. https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/IT-23461

**Comment by haosanzi** [comment]
Hi, amye.

About `Trademarks: transfer any trademark and logo mark assets over to the LF`. I have sent the CNCF Trademark and Account Assignment Agreement file to your [email](amye@linuxfoundation.org).

**Comment by haosanzi** [comment]
Hi, here is the update.
According to https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/IT-23461, `inclavare-containers.io` domain has been successfully transferred

**Comment by amye** [comment]
Currently outstanding:  
 Is your project in its own separate neutral github organization? (I know it's live, but nothing's in there yet)
GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership

**Comment by haosanzi** [comment]
Hi, here is the update.

> Is your project in its own separate neutral github organization?

yes, please see https://github.com/inclavare-containers/inclavare-containers for more detail.

> GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership

The invitation has been sent, waiting for @thelinuxfoundation and @caniszczyk to confirm.

**Comment by amye** [comment]
Excellent! The last thing waiting is Trademarks, and that's on our team.
Thanks!

**Comment by haosanzi** [comment]
@amye Hi, how long this trademark transfer take? Thank you very much!

**Comment by amye** [comment]
I've responded in email on this, this is still with Legal.

**Comment by krook** [comment]
[Added to LFX Insights](https://insights.lfx.linuxfoundation.org/foundation/cncf/overview?project=inclavarecontainers)

- [Insights documentation](https://docs.linuxfoundation.org/lfx/insights/v3-beta-version-current)
- [Insights support](https://jira.linuxfoundation.org/plugins/servlet/desk/portal/4?requestGroup=54)
- [Insights feedback](https://community.lfx.dev/t/lfx-insights-v3-feedback/2430)

**Comment by Cmierly** [comment]
Trademark paperwork has been tracked down and the task has been marked off
Inclavare Containers has completed onboarding!
