### ISSUE TITLE
Sandbox Project - Boomerang Flow - Guidance Needed

### ISSUE THREAD

**Issue by tlawrie** [cncf/toc#727]
Hi CNCF TOC.

Thanks for reviewing our proposal for Boomerang Flow. I see that it was listed as "reapply in 6 months with a more clear roadmap" as part of the Sandbox Inclusion Review -> https://docs.google.com/document/d/1jpoKT12jf2jTf-2EJSAl4iTdA7Aoj_uiI19qIaECNFc/edit#

We currently have a [roadmap repo](https://github.com/boomerang-io/roadmap) and all of our roadmap and releases are in GitHub + ZenHub. Along with a fully documented backlog. And we have open public sessions every two weeks for anyone to join.

I am hoping/wondering if we could get some guidance or mentoring in what is needed to implement so that we can submit and pass the review? Myself or any of the other maintainers are all willing to meet or talk with anyone.

**Comment by amye** [comment]
So from the application, the link to the roadmap was https://app.zenhub.com/workspaces/boomerang-flow-5f9600754a5aa9001521ccc1/board, which kicks directly to a login page. It's confusing to be able to see where the project is going, what your next plans are, and how new contributors can get involved. 

I've moved your application to the Previous Application [tab](https://docs.google.com/spreadsheets/d/1Nnh_usr0tSZxaUpxTusqeIqKxMmvuEViRkyO9e_Do40/edit#gid=1302262409) so that you can reference that on re-application.

**Comment by tlawrie** [comment]
Thanks for the quick response, @amye. 

Indeed that is strange that it asks for a login, it should be open to anyone to view as a public ZenHub board. I think ZenHub requires you to sign in to GitHub but then you can view any public boards. Ill look into it though.

Are we able to get some guidance on whether everything at https://github.com/boomerang-io/roadmap is what was being looked for? The only reason I posted the ZenHub link is that it has all our releases and tasks etc. It is public (albeit that ZenHub login) Is there a better way to display the directional roadmap that CNCF is looking for?

I also added those updates I had via the sheets comments from our discussion here https://github.com/cncf/toc/issues/682 where I put them as comments on each cell.

The maintainers are all very excited to get into Sandbox and happy for any guidance on providing a clearer / better accessible roadmap / stop using ZenHub (we are currently on the waitlist for [GitHub Projects](https://github.com/features/issues) Beta)

With reapplying, based on this thread, do we need to wait the 6 months? It seems its mainly around ZenHub forcing a login.

**Comment by tlawrie** [comment]
FYI @marcusdroy / @morarucostel

**Comment by tlawrie** [comment]
Hi @amye checking in on the above and whether we can get some guidance. Thanks!
