### ISSUE TITLE
[SANDBOX PROJECT ONBOARDING] Open Cluster Management 

### ISSUE THREAD

**Issue by amye** [cncf/toc#744]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project.
We would like to complete onboarding within one month of acceptance.

From the project side, please ensure that you:

- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
- [x] Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/
- [x] Understand the license allowlist: https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist
- [x] Has your project adopted open governance already? see http://opengovernance.dev
- [x] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? (see https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another for more details)
- [x] Is your project in its own separate neutral github organization?
- [x] Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io
- [x] Create maintainer list + add to aggregated https://maintainers.cncf.io list by submitting a PR to it
- [x] Have added your project to https://github.com/cncf/contribute
- [x] Artwork: Submit a pull request to https://github.com/cncf/artwork with your artwork
- [x] -Domain: transfer domain to the CNCF - https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63

Things that CNCF will need from the project:

- [x] Provide emails for the maintainers added to https://maintainers.cncf.io in order to get access to the maintainers mailing list and ServiceDesk
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed
- [x] Website: Analytics transferred to amye@linuxfoundation.org
- [x] CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en

Things that the CNCF will do or help the project to do:

- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access, welcome email has monthly project sync details
- [x] Create space for meetings/events on https://community.cncf.io, e.g., https://community.cncf.io/pravega-community/ - (https://github.com/cncf/communitygroups/blob/main/README.md#cncf-projects)
- [x] Adopt a license scanning tool, like FOSSA or Snyk

**Comment by amye** [comment]
Welcome  @mdelder, @deads2k, @qiujian16 and @mikeshng! 
Running off of https://github.com/open-cluster-management-io/community/blob/main/OWNERS, is this the file you want for your owners file?

**Comment by mikeshng** [comment]
Thank you @amye for welcoming us.

Yes, please use the updated https://github.com/open-cluster-management-io/community/blob/main/OWNERS file.

**Comment by mikeshng** [comment]
Hi @amye These steps can be checked off:

- Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction
- Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
 - Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
-  Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack?
-  Is your project in its own separate neutral github organization?
- GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
> Note: The invitation has been sent, waiting for @thelinuxfoundation and @caniszczyk to confirm.

**Comment by mikeshng** [comment]
@amye please see below for the following:
> Provide emails for the maintainers added to https://maintainers.cncf.io in order to get access to the maintainers mailing list and ServiceDesk
```
Name,Company,GitHubID,Email
------------------------------------------------------
Qiu Jian,Red Hat,qiujian16,jqiu@redhat.com
Joshua Packer,Red Hat,jnpacker,jpacker@redhat.com
David Eads,Red Hat,deads2k,deads@redhat.com
Mike Ng,Red Hat,mikeshng,ming@redhat.com
Min Kim,Ant Group,yue9944882,yue9944882@gmail.com
Yong Feng,Alibaba,luckyfengyong,lujing.fy@antgroup.com
```

**Comment by mikeshng** [comment]
Hi @amye the following steps are done:
- Create maintainer list + add to aggregated https://maintainers.cncf.io list by submitting a PR to it
- Have added your project to https://github.com/cncf/contribute
- GitHub: ensure DCO or CLA are enabled for all GitHub repositories of the project

Thanks.

**Comment by amye** [comment]
I just saw artwork come through, marking that off too!

**Comment by mikeshng** [comment]
Hi @amye we have a few questions, please see below

1. `Understand the license allowlist` 
OCM repos all use Apache2 Licenses and we understand the license allowlist. Do we have to make sure all our 3rd party usage is supposed to follow the same guideline as well? 
2. `Has your project adopted open governance already?`
We understand and have started to adopt open governance. Could you mark this as done if we have the PR already? Please see https://github.com/open-cluster-management-io/community/pull/72
3. `Website: Analytics transferred to amye@linuxfoundation.org` We used to have analytics but it has been disabled for some time now. Is there any point of transferring the legacy data or can we mark this as done since we don't have analytics anymore?

**Comment by amye** [comment]
You should be good with your OCM repos. I'll mark the rest of these off.

**Comment by mikeshng** [comment]
Hi @amye , we completed the following items:

- `Website: ensure LF footer is there and website guidelines followed` see https://open-cluster-management.io
- `CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en` see https://github.com/open-cluster-management-io/OCM/pull/9

**Comment by lukaszgryglicki** [comment]
DevStats [page](https://openclustermanagement.devstats.cncf.io) added.

**Comment by mikeshng** [comment]
Hi @amye we have a few questions again:
- `GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners` 
The invitation has been sent, but it seems like @thelinuxfoundation hasn't accepted yet. Is there anything we need to do on our side ie should we send another invite?
- `Domain: transfer domain to the CNCF`
What should the `LF stakeholder email?` be? Is it `amye@linuxfoundation.org` ?
For the `Community Stakeholder email` can we use our public mailing list email `open-cluster-management@googlegroups.com` or we should use a more private email in case there are sensitive information?
For the `Project ITX URL`, we are not sure what this is.

**Comment by mikeshng** [comment]
Hi @amye we have completed the following items:
- `Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io`
- `Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/`

**Comment by amye** [comment]
Domain: transfer domain to the CNCF
What should the LF stakeholder email? be? Is it amye@linuxfoundation.org ?  -- That's totally fine! 
For the Community Stakeholder email can we use our public mailing list email open-cluster-management@googlegroups.com or we should use a more private email in case there are sensitive information?
For the Project ITX URL, we are not sure what this is.

ITX is optional, but you can use your maintainers list for this!

**Comment by mikeshng** [comment]
Thanks @amye . For the following items, are there anything we need to do on our side to complete them?

- `Create space for meetings/events on https://community.cncf.io,`
Could you please help us create the Open Cluster Management space? When I tried the https://servicedesk.cncf.io URL to request the space, it asks for login that I don't have.

- `Adopt a license scanning tool, like FOSSA or Snyk`
We can use the https://github.com/fossas/fossa-action GitHub action to scan license, but how do we acquire the API key? Is it provided by CNCF?

**Comment by amye** [comment]
Resent invites to Servicedesk! @idvoretskyi can help with this. :)

**Comment by idvoretskyi** [comment]
> but how do we acquire the API key? Is it provided by CNCF?

@mikeshng yes! Please file a ServiceDesk ticket, I'll share one with you. And yes, please use that FOSSA Action for this.

**Comment by mikeshng** [comment]
> > but how do we acquire the API key? Is it provided by CNCF?
> 
> @mikeshng yes! Please file a ServiceDesk ticket, I'll share one with you. And yes, please use that FOSSA Action for this.

Thanks @idvoretskyi I just created a ticket for the API key.

As for `Create space for meetings/events on https://community.cncf.io`
I don't see a right category in the ServiceDesk to request a space. Is this something that you can help us with? ie: a space like `https://community.cncf.io/open-cluster-management-community`

**Comment by idvoretskyi** [comment]
> I don't see a right category in the ServiceDesk to request a space. Is this something that you can help us with? ie: a space like https://community.cncf.io/open-cluster-management-community

@mikeshng yes, I can help you ask well -  feel free to select any related category, eg. Program Management there.

**Comment by amye** [comment]
> Hi @amye for the item `Trademarks: transfer any trademark and logo mark assets over to the LF`
> 
> Could you please send us the agreement for us to sign? You can send it to any of the emails in [#744 (comment)](https://github.com/cncf/toc/issues/744#issuecomment-966603288) but preferably my email. Thanks.

Taken care of!

**Comment by idvoretskyi** [comment]
@mikeshng quick check on the remaining items :)

**Comment by mikeshng** [comment]
Hi @idvoretskyi thanks for checking. We are working on the following 2 items:
- `Ensure your project meets the CNCF IP Policy`
- `Trademarks: transfer any trademark and logo mark assets over to the LF`

For:
- `Domain: transfer domain to the CNCF` We have the ticket generated and its in progress. We don't anticipate there will be any issues: https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/IT-23376
- `GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners` We have sent the GitHub invitation to `thelinuxfoundation` but it hasn't accept the invitation yet. `caniszczyk` has been added as org owner. Could you help us with this item and see what is the issue with the `thelinuxfoundation` user? Thanks.

**Comment by mikeshng** [comment]
`Domain: transfer domain to the CNCF` is now completed. Ref: https://jira.linuxfoundation.org/servicedesk/customer/portal/2/IT-23376

**Comment by lukaszgryglicki** [comment]
I will work on this today, thanks for reporting.

**Comment by lukaszgryglicki** [comment]
This will do the job:
```
create temp table repos as (select id, name from gha_repos where org_login = 'open-cluster-management');
delete from gha_branches where repo_id in (select id from repos);
delete from gha_teams_repositories where repository_id in (select id from repos);
delete from gha_pull_requests_assignees where event_id in (select id from gha_events where dup_repo_name in (select name from repos));
delete from gha_pull_requests_requested_reviewers where event_id in (select id from gha_events where dup_repo_name in (select name from repos));
delete from gha_issues_assignees where event_id in (select id from gha_events where dup_repo_name in (select name from repos));
delete from gha_releases_assets where event_id in (select id from gha_events where dup_repo_name in (select name from repos));
delete from gha_commits_files where sha in (select sha from gha_commits where dup_repo_name in (select name from repos));
delete from gha_skip_commits where sha in (select sha from gha_commits where dup_repo_name in (select name from repos));
delete from gha_repos where name in (select name from repos);
delete from gha_events where dup_repo_name in (select name from repos);
delete from gha_repos_langs where repo_name in (select name from repos);
delete from gha_payloads where dup_repo_name in (select name from repos);
delete from gha_commits where dup_repo_name in (select name from repos);
delete from gha_pages where dup_repo_name in (select name from repos);
delete from gha_comments where dup_repo_name in (select name from repos);
delete from gha_issues where dup_repo_name in (select name from repos);
delete from gha_milestones where dup_repo_name in (select name from repos);
delete from gha_issues_labels where dup_repo_name in (select name from repos);
delete from gha_forkees where dup_repo_name in (select name from repos);
delete from gha_releases where dup_repo_name in (select name from repos);
delete from gha_assets where dup_repo_name in (select name from repos);
delete from gha_pull_requests where dup_repo_name in (select name from repos);
delete from gha_teams where dup_repo_name in (select name from repos);
delete from gha_events_commits_files where dup_repo_name in (select name from repos);
delete from gha_texts where repo_name in (select name from repos);
delete from gha_issues_events_labels where repo_name in (select name from repos);
delete from gha_issues_pull_requests where repo_name in (select name from repos);
```
I will also update all configurations to no longer track that `org`.

**Comment by lukaszgryglicki** [comment]
Done, dropped data, updated configs and regenerated all dashboards on both `test` and `prod` envs.

**Comment by mikeshng** [comment]
Hi @amye OCM is currently under the orchestration category in landscape: https://landscape.cncf.io/card-mode?category=scheduling-orchestration&grouping=category Can OCM be placed under the security compliance category as well? https://landscape.cncf.io/card-mode?category=security-compliance&grouping=category So it will be in both categories.

**Comment by amye** [comment]
> Hi @amye OCM is currently under the orchestration category in landscape: https://landscape.cncf.io/card-mode?category=scheduling-orchestration&grouping=category Can OCM be placed under the security compliance category as well? https://landscape.cncf.io/card-mode?category=security-compliance&grouping=category So it will be in both categories.

Unfortunately, you'll have to choose one. Sorry!

**Comment by mikeshng** [comment]
> Unfortunately, you'll have to choose one. Sorry!

Thank you for your quick response @amye 

We completed the following:
- `Domain: transfer domain to the CNCF`
ref: https://jira.linuxfoundation.org/servicedesk/customer/portal/2/IT-23376
- `GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners`
![image](https://user-images.githubusercontent.com/58747157/149530711-2d5b09ef-a8f8-4262-b652-5cf3363ae534.png)
![image](https://user-images.githubusercontent.com/58747157/149530839-014cca1e-670e-474a-af8e-49a7e23467ac.png)

**Comment by amye** [comment]
Marking off domain and GH ownership as complete. 
Looks like Trademarks and IP policy are left!
Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy

**Comment by mikeshng** [comment]
Hi @Cmierly  , thank you for your help.

We have an email thread about the last item regarding Trademarks and IP policy.
Could you please let us know your email so we can inform you our current status? 
My email address is `ming@redhat.com` , if you wish to let us know privately. 

It seems like we are current waiting for a docusign so authority can sign off on our side.

Thanks.

**Comment by amye** [comment]
Drop a note to project-onboarding@cncf.io to connect with the onboarding team!

**Comment by mikeshng** [comment]
> Marking trademarks complete. Any reason that IP policy wouldn't be met?
>  [] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy

Hi @amye , could you please check off on this item? The project does meets the CNCF IP Policy. Thanks.
