### ISSUE TITLE
[SANDBOX PROJECT ONBOARDING] K8up

### ISSUE THREAD

**Issue by amye** [cncf/toc#753]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project.
We would like to complete onboarding within one month of acceptance.

From the project side, please ensure that you:

- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
- [x] Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/
- [x] Understand the license allowlist: https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist
- [x] Has your project adopted open governance already? see http://opengovernance.dev
- [x] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? (see https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another for more details)
- [x] Is your project in its own separate neutral github organization?
- [x] Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io
- [x] Create maintainer list + add to aggregated https://maintainers.cncf.io list by submitting a PR to it
- [x] Have added your project to https://github.com/cncf/contribute
- [x] Artwork: Submit a pull request to https://github.com/cncf/artwork with your artwork
- [x] -Domain: transfer domain to the CNCF - https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63

Things that CNCF will need from the project:

- [x] Provide emails for the maintainers added to https://maintainers.cncf.io in order to get access to the maintainers mailing list and ServiceDesk
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed
- [x] Website: Analytics transferred to amye@linuxfoundation.org
- [x] CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en

Things that the CNCF will do or help the project to do:

- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access, welcome email has monthly project sync details
- [ ] Create space for meetings/events on https://community.cncf.io, e.g., https://community.cncf.io/pravega-community/ - (https://github.com/cncf/communitygroups/blob/main/README.md#cncf-projects)
- [ ] Adopt a license scanning tool, like FOSSA or Snyk

**Comment by tobru** [comment]
I'll help with the onboarding from K8up's side :+1:

**Comment by lukaszgryglicki** [comment]
DevStats [page](https://k8up.devstats.cncf.io) added.

**Comment by tobru** [comment]
I did read through the various pages provided:

- [X] Understand the project proposal process and reqs
- [X] Understand the services available for your project at CNCF
- [X] Ensure your project meets the CNCF IP Policy
- [X] Review the online programs guidelines
- [X] Understand the trademark guidelines
- [X] Understand the license allowlist

Some other information asked:

* _Has your project adopted open governance already?_ No, we do not have that yet, but we strongly consider implementing it.
* _Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack?_ We do not use Slack as of today.
* _Is your project in its own separate neutral github organization?_ Yes, it has it's home under https://github.com/k8up-io
* _Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements_ Afaik we do not have any trademarks we have to transfer

And the following PRs are opened:

- [X] Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io
- [X] Have added your project to https://github.com/cncf/contribute
- [X] Artwork: Submit a pull request to https://github.com/cncf/artwork with your artwork

Also done:

- [X] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [X] GitHub: ensure DCO or CLA are enabled for all GitHub repositories of the project

Questions to @amye :

* I'm unsure what to do about the licensing: K8up is currently licensed under BSD-3-Clause. Does the inclusion into CNCF Sandbox mean we have to change the license to Apache-2?
* _Website: Analytics transferred to amye@linuxfoundation.org_ How can I do that?

Other open points will be worked on later.

**Comment by tobru** [comment]
More work conducted:

- [X] Create maintainer list + add to aggregated https://maintainers.cncf.io list by submitting a PR to it
- [X] Provide emails for the maintainers added to https://maintainers.cncf.io in order to get access to the maintainers mailing list and ServiceDesk
- [X] CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en

E-Mail addresses of maintainers:

* tobru: tobias.brunner@vshn.ch
* Kidswiss: simon.beck@vshn.ch
* ccremer: christian.cremer@vshn.ch
* corvus-ch: christian.haeusler@vshn.ch

Ongoing work:

* _Website: ensure LF footer is there and website guidelines followed_: https://github.com/k8up-io/antora-ui-default/issues/3
* _Domain: transfer domain to the CNCF_: Ticket created IT-23283

**Comment by tobru** [comment]
- [X] Website: Analytics transferred to amye@linuxfoundation.org

**Comment by amye** [comment]
Thanks for this! 
 Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements 

There's also a 'no registered trademarks', you'll want that.

**Comment by amye** [comment]
Other things: 
_I'm unsure what to do about the licensing: K8up is currently licensed under BSD-3-Clause. Does the inclusion into CNCF Sandbox mean we have to change the license to Apache-2?_ 

Yes. 

Analytics: you should be able to invite me as an owner?

**Comment by tobru** [comment]
> Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements

Is there an editable version of these PDFs around? Would make it a bit easier :see_no_evil: 

> Does the inclusion into CNCF Sandbox mean we have to change the license to Apache-2? Yes

Do you happen to know what steps we have to take to change to license? Can we just replace the LICENSE file with the Apache-2 license and we're good?

> Analytics: you should be able to invite me as an owner?

That should have already happened

> Website: ensure LF footer is there and website guidelines followed

We prepared a merge request to update the K8up website at https://github.com/k8up-io/antora-ui-default/issues/3. We're unsure if we can keep the Hubspot tracking integrated, can we?

> Has your project adopted open governance already? see http://opengovernance.dev

What do you need from us to have a tick here? We'll be doing more work on that over the next weeks, so this is on our plate. Is this enough to get this ticked off?

> -Domain: transfer domain to the CNCF

IMHO that is done

> GitHub: ensure DCO or CLA are enabled for all GitHub repositories of the project

This is done

**Comment by tobru** [comment]
> Do you happen to know what steps we have to take to change to license? Can we just replace the LICENSE file with the Apache-2 license and we're good?

Ok, license is changed.

**Comment by tobru** [comment]
@amye I think we're nearly there, I just need some answers from your side to be able to finish the last steps. Would you mind having a look at my questions?

**Comment by amye** [comment]
It looks like the only thing you're looking for is an editable version of the agreement? 

Having a governance file will help mark off open governance. 

Do you want a space on community.cncf.io for your project?

**Comment by tobru** [comment]
@amye

> It looks like the only thing you're looking for is an editable version of the agreement?

That's not the only thing, here's a summary what I need:

* Editable version of the agreement
* We prepared a merge request to update the K8up website at k8up-io/antora-ui-default#3. We're unsure if we can keep the Hubspot tracking integrated, can we?
* Tick at "-Domain: transfer domain to the CNCF", this is done

> Having a governance file will help mark off open governance.

PR will come in the next days :+1: 

> Do you want a space on community.cncf.io for your project?

We're mostly present at https://community.cncf.io/cloud-native-computing-switzerland/, so I don't think we currently need a new space at this stage of the project.

**Comment by amye** [comment]
We're all set here!
