### ISSUE TITLE
[SANDBOX PROJECT ONBOARDING] sealer

### ISSUE THREAD

**Issue by fanux** [cncf/toc#769]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project.
We would like to complete onboarding within one month of acceptance.

From the project side, please ensure that you:

- [x] Understand the project proposal process and reqs: <https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction>
- [x] Understand the services available for your project at CNCF <https://www.cncf.io/services-for-projects/>
- [x] Ensure your project meets the CNCF IP Policy: <https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy>
- [x] Review the online programs guidelines: <https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md>
- [x] Understand the trademark guidelines: <https://www.linuxfoundation.org/en/trademark-usage/>
- [x] Understand the license allowlist: <https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist>
- [x] Is your project working on written, open governance? see <https://contribute.cncf.io/maintainers/governance/>
- [ ] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? (see <https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another> for more details)
- [ ] Is your project in its own separate neutral github organization?
- [ ] Submitted a Pull request to add your project as a sandbox project to <https://landscape.cncf.io>
- [ ] Create maintainer list + add to aggregated <https://maintainers.cncf.io> list by submitting a PR to it
- [ ] Have added your project to <https://github.com/cncf/contribute>
- [ ] Artwork: Submit a pull request to <https://github.com/cncf/artwork> with your artwork
- [ ] Domain: transfer domain to the CNCF - <https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63>

Things that CNCF will need from the project:

- [ ] Provide emails for the maintainers added to <https://maintainers.cncf.io> in order to get access to the maintainers mailing list and ServiceDesk
- [ ] Trademarks: transfer any trademark and logo mark assets over to the LF - <https://github.com/cncf/foundation/tree/master/agreements> has agreements
- [ ] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [ ] GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [ ] GitHub: ensure that hat the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub
- [ ] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines to the README file of your project on GitHub).
- [ ] Website: Analytics transferred to amye@linuxfoundation.org
- [ ] CII: Start on a CII best practices badge <https://bestpractices.coreinfrastructure.org/en>

Things that the CNCF will do or help the project to do:

- [ ] Devstats: add to devstats <https://devstats.cncf.io/>
- [ ] Marketing: update relevant intro + slide decks
- [ ] Events: update CFP + Registration + CFP Area forms
- [ ] ServiceDesk: confirm maintainers have read <https://www.cncf.io/services-for-projects/>
- [ ] CNCF Welcome Email Sent to confirm maintainer list access, welcome email has monthly project sync details
- [ ] Create space for meetings/events on <https://community.cncf.io>, e.g., <https://community.cncf.io/pravega-community/> - (<https://github.com/cncf/communitygroups/blob/main/README.md#cncf-projects>)
- [ ] Adopt a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/)

**Comment by amye** [comment]
Next Sandbox review meeting is January 11th, I will open tickets for accepted projects at that time.

**Comment by fanux** [comment]
@amye How do I know if sealer has been accepted or not?

**Comment by amye** [comment]
sandbox.cncf.io will always show you what has and hasn't been reviewed.

**Comment by fanux** [comment]
https://github.com/cncf/toc/issues/831 @amye I don't have issue 831 edit promission, how can I update the todo list?

**Comment by amye** [comment]
Drop us notes in #831, we'll respond in there 😄
