### ISSUE TITLE
Present REX-Ray to TOC

### ISSUE THREAD

**Issue by clintkitson** [cncf/toc#80]
Hello team,

Last year we did a presentation to the TOC about REX-Ray/libStorage. At the time the relevance of storage to cloud native was less clear and the SWG was asked to discuss this topic. Since then CSI was formed and the industry is rallying around this new interop API. With the introduction of storage projects like Rook and Vitess, it feels like the right time to readdress this important project.

Is the TOC open to get some time on the calendar to discuss REX-Ray again as a possible CNCF project?

REX's focus moving forward is to support the CSI eco-system. It is focused on a simple and common user experience across many cloud and storage platforms. Architecturally it packages any CSI plugin implementations to provide value universally beyond the current scope of the CSI specification.

**Comment by monadic** [comment]
I am open to this.

**Comment by monadic** [comment]
Would love to hear from Storage experts in the TOC and community, but seems fair to invite them back.

**Comment by clintkitson** [comment]
Ok sounds good, Feb 20th it is.
