### ISSUE TITLE
TOC Chair Election, March 2022

### ISSUE THREAD

**Issue by amye** [cncf/toc#810]
Now that we have a fully formed TOC, a TOC chair needs to be selected.

We will leave nominations open through next Tuesday, March 29th at noon Pacific.

Please comment here if you're interested in standing for chair.

**Comment by dzolotusky** [comment]
I know that it says "comment here if you're interested in standing for chair.", but I'd like to use this space to nominate instead.

I'd like to nominate @dims for the role of TOC chair.

**Comment by dims** [comment]
@dzolotusky thanks for the nomination! Yes, i would love to stand for the chair role.

fyi, We talked about this in the closed toc meeting as well. @RichiH and @cdavisafc could not make it, we should wait for them to chime in as well.

**Comment by amye** [comment]
As @dims is running unopposed, I will close this.
Welcome @dims as TOC chair!
