### ISSUE TITLE
Document the Annual Review Process and expectations for sandbox projects

### ISSUE THREAD

**Issue by dims** [cncf/toc#815]
This year we had a public Annual Review process:
- The TOC self-organized to assign one TOC member for each Annual Review
- The assigned member, went through the filed PRs and also took a look at community health
- On the private TOC channel, before the meeting we started a thread for each project
- On the thread, assigned shepherds gave and gathered feedback, everyone else chimed in
- We invited the projects to show up in the public meeting. No Biggie if they could not make it.
- During the meeting, each assigned member gave a readout and asked some leading questions to the project representative (if they made it)
- Brief discussion about things that went well, some thoughts on how to do better for each project
- Projects could voice their concerns and requests for help
- At the end of the public call, the TOC took a vote to approve all the annual reviews in one shot. If there were concerns, we would have picked a smaller subset and voted on that (and separate vote on the projects of concern)

We need to write this down somewhere @amye :)

cc @rochaporto @dzolotusky @erinaboyd @TheFoxAtWork as they had thoughts/ideas on how to tune this further.

**Comment by dzolotusky** [comment]
I agree with what's been here so far, so I wont bother duplicating my notes on the content.
Though, one point that I think that we should emphasize clarifying is
- We invited the projects to show up in the public meeting. No Biggie if they could not make it.

I think that we need to be very clear on the "No biggie" part, and really focus on making sure that projects don't feel really pressured to show up.

On the other hand, I like the idea of giving the maintainers that do show up a bit of time on the TOC call to speak about their project, the annual review, and any asks of the CNCF. I feel like letting the maintainers speak and the assigned TOC member clarifying or asking questions is a better way to do this than having the assigned TOC member just speak on behalf of the project.

We should come to consensus on how we feel about both of these points and then make sure that's well documented and doesn't cause confusion for projects joining (or not joining) the annual review call.

**Comment by amye** [comment]
#816  resolves
