### ISSUE TITLE
Question about the Status of Standbox Project Application

### ISSUE THREAD

**Issue by brant-ruan** [cncf/toc#818]
Hello, 

We planned to contribute our project [Metarget](https://github.com/Metarget/metarget) to CNCF as sandbox project. We have followed the [project proposal process](https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#sandbox-process) and finished the application last year, but haven't received any reply yet. Could you please tell me where or how I can know the TOC review process about our project and the application status?

Thanks!

**Comment by amye** [comment]
[sandbox.cncf.io. ](http://sandbox.cncf.io/) has the list of applications and you'll be able to find yourself in the queue.
Our next Sandbox review meeting is listed on [https://docs.google.com/document/d/1jpoKT12jf2jTf-2EJSAl4iTdA7Aoj_uiI19qIaECNFc/edit](Public TOC Meeting Notes) as April 26, 2022.

**Comment by brant-ruan** [comment]
Thank you : )
