### ISSUE TITLE
Add Hindi translation to DEFINITION.md

### ISSUE THREAD

**Issue by devsachinsharma** [cncf/toc#875]
I saw all the different types of languages present in definition.md but Hindi was missing. So I really wanted to add it.

**Comment by dims** [comment]
@devsachinsharma please feel free to open a PR. thanks!

**Comment by devsachinsharma** [comment]
@dims https://github.com/cncf/toc/pull/878

**Comment by dims** [comment]
Marking as done. #878 has merged.
