### ISSUE TITLE
Typo in keptn.adoc

### ISSUE THREAD

**Issue by bishal7679** [cncf/toc#892]
There are two typos in this file `brige` and `supporte`

![Screenshot (256)](https://user-images.githubusercontent.com/70086051/183090939-7a119f51-2a3a-4d91-a1d9-6bb93f850e73.png)

![Screenshot (257)](https://user-images.githubusercontent.com/70086051/183090945-18798fd1-cfde-42a6-8f35-4a640d0e3f2a.png)

**Comment by dims** [comment]
@bishal7679 these docs we do not touch as they are not living docs.
