### ISSUE TITLE
Health of Brigade project

### ISSUE THREAD

**Issue by dims** [cncf/toc#900]
In the last annual review of Brigade, the maintainers requested either for some new folks to step up or archive the project:
https://github.com/cncf/toc/pull/845/files#diff-f60234e8ebf42cf703af9378082fd419b6c7cf03a8764af6a58f2ff6a180fde6R137-R139

At that point, some new folks stepped up, but the transition was not complete and the new folks have requested archival as well:
https://github.com/cncf/toc/pull/845#issuecomment-1216061204

cc @krancour @jorgearteiro

**Comment by bridgetkromhout** [comment]
Hi, @dims! Thanks for following up. As you correctly noted, the annual report mentioned that new maintainers would be needed or the project would need to be archived; all the active maintainers had transitioned to other projects and weren't able to continue with this project. While there was some interest, in the end it wasn't feasible for a new maintainer to take over. We all agree at this juncture that archiving the Brigade project is the best approach. Please let me and @karenhchu how we can assist with the archival process - thanks!

**Comment by jorgearteiro** [comment]
Agree with @bridgetkromhout. I haven't started anything as maintainer. I just tried to help a project that i really believe, in my free time.

**Comment by aantn** [comment]
Hi all, sorry to see the news on this. I love the concept behind Brigade and it's nice to see a code-based approach and not just more YAML.

I work on https://github.com/robusta-dev/robusta which also does code-based automation [1], but is more narrowly focused on alerting and SRE use cases. We're not a CNCF project (yet?) but if there is anything we can do to help then we are happy to do so. E.g. if you have a use case that isn't covered but should be, we're open to adding support.

[1] Don't let the homepage trick you - automations only *look* like they're written in YAML on first glance, but everything is Python under the hood and the YAML only provides parameters to that Python. Here is a [Kubernetes automation example in Python](https://docs.robusta.dev/master/#writing-your-own-automations).

**Comment by dims** [comment]
thanks everyone for the discussion in https://github.com/cncf/toc/pull/845 and here. Will leave this open for two weeks (Aug 31st) and we can wrap this up at that time.

**Comment by krancour** [comment]
Just commenting that I hope no one has lost track of this. August 31 is just two days away and still no one has communicated the intention to archive Brigade to its community. The Brigade Slack channel is semi-active and people are trying/using Brigade and asking question about it and being met with silence. It would be better for the community, small as it may be, to hear sooner rather than later that they should be exploring alternatives instead of wasting their time on Brigade.

**Comment by bridgetkromhout** [comment]
@krancour based on https://github.com/cncf/toc/blob/main/process/archiving.md I believe that the TOC (of which @dims is a member) informs the community; perhaps a link to this issue is needed in that channel, so I'll add it there.

**Comment by krancour** [comment]
@amye it was proposed in #845, which was merged. I apologize, for I didn't know there was a dedicated process for proposing archival.

Now that I understand that... whose responsibility is it to PR that?

**Comment by bridgetkromhout** [comment]
Thanks, @amye. @krancour I've carried out the required proposal step in https://github.com/cncf/toc/pull/915. @karenhchu and I will take care of any remaining tasks. Thanks!

**Comment by krancour** [comment]
Thanks, @bridgetkromhout!

**Comment by craigbox** [comment]
Looks like #915 closes this.

**Comment by caniszczyk** [comment]
archived

**Comment by dims** [comment]
thanks a ton everyone! 

thanks @caniszczyk !
