### ISSUE TITLE
Review list of Sandbox Questions

### ISSUE THREAD

**Issue by jberkus** [cncf/toc#901]
With #884, the Sandbox Application Process is changing.  As such, we should revisit what questions we're asking of potential new sandbox projects.  The current list of questions hasn't been reviewed in two years, and isn't necessarily 100% what the TOC needs to know.

Please offer your suggestions on which questions should be added, and which removed, and why.

## Current list of questions

* Email
* Project Name
* Project Description
* Code Repository (URL)
* Website (URL)
* Project Roadmap (URL)
* Why do you want to contribute your project to the CNCF? What would you like to get out of being part of the CNCF?
* Code of Conduct (URL)
* I understand that if accepted, the project will be required to follow the CNCF IP Policy (https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy)
* I understand that I am donating all project trademarks and accounts to the CNCF 
* Please explain how your project is aligned with the cloud native computing ecosystem.
* Please list similar projects in the CNCF or elsewhere
* Guidelines/help for project contributors (URL) 
* Explanation of alignment/overlap with existing CNCF projects (optional)
* Existing project overview presentation (optional)
* Maintainers file (optional)
* Link to project artwork: (optional)

attn: @TheFoxAtWork

**Comment by jberkus** [comment]
Here's my suggestions based on experience as a sandbox submitter.  It changes the questions in a few ways:

1. It reorders the questions to put the URL and yes/no questions at the top, and the "essay" questions at the bottom, as well as grouping closely related questions together.
2. It splits some questions that currently ask for two different things into two different questions.
3. It adds questions around important project information (like organizational sponsors) that we don't currently have and often end up asking for.

Here's the updated questions:

* Email(s) *CHANGE: should accept up to three email addresses, so that there is coverage in case the original submitter is unavailable when the submission is actually reviewed*
* Project Name
* *ADD*: Project Summary (100 chars or less) 
* Project Description *ADD instruction:* (100-300 word explanation of the project, what it does, and why it's needed)
* *Move Up* Existing project overview presentation (optional)
* ~~Code Repository (URL)~~ *REPLACE QUESTION WITH 2 BELOW*
* *ADD* GitHub or Gitlab Organization (URL):
* *ADD* Primary code repository (URL):
* Website (URL)
* Project Roadmap (URL)
* *Move Up* Guidelines/help for project contributors (URL) 
* *ADD*: Explanation of project roadmap (Optional) (Add any details of the roadmap you might feel are required for clarity)
* *ADD*: List of Project Adopters (URL) (Optional)
* *ADD*: List of Contributing/Sponsoring Organizations (URL) (Optional)
* *Move up* Code of Conduct (URL)
* *Move Up, change to requried* Maintainers file ~~(optional)~~
* *Move Up* Link to project artwork: (optional)
* *Move Up* I understand that if accepted, the project will be required to follow the CNCF IP Policy (https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy)
* *Move Up* I understand that I am donating all project trademarks and accounts to the CNCF 
* Why do you want to contribute your project to the CNCF? What would you like to get out of being part of the CNCF?
* *ADD* How will adding your project benefit the CNCF ecosystem?
* ~~Please explain how your project is aligned with the cloud native computing ecosystem.~~ *Change question text*: Please explain where you see your project "fitting" in the Cloud Native ecosystem. 
* Please list similar projects in the CNCF or elsewhere
* *REPLACE question with below 2 questions*: ~~Explanation of alignment/overlap with existing CNCF projects (optional)~~
* What CNCF projects does this project complement or depend on, and how?
* What CNCF projects does this project overlap with, and how?
* *ADD* If this project is closely related to one or more products for the sponsoring organization(s), how do you plan to separate this project from any products in terms of organization and development? (if it is not related to a product, just say so)
* *ADD* Has your project been presented to any TAG? If so, please link meeting notes and/or recordings as applicable. (optional)
* *ADD* Please list any people who are part of CNCF leadership (TOC, TAGS, etc.) who can endorse or answer questions about your project (optional)
* *ADD* Any additional information you would like the TOC to consider when evaluating your project? (optional)

**Comment by jberkus** [comment]
Removed "link to project artwork" per Amye above.

However, I think it's very useful for the TOC to be able to see a list of maintainers; that tells you a LOT about a project.

**Comment by TheFoxAtWork** [comment]
@jberkus Since we've modify the sandbox process to reflect this questions, would you concur this issue is resolved?

**Comment by jberkus** [comment]
Yes.  Great work!
