### ISSUE TITLE
`toc/FAQ.md` might need to be updated for consistency with `foundation/dco-guidelines.md` about "pseudonyms"

### ISSUE THREAD

**Issue by AkihiroSuda** [cncf/toc#906]
I'm not really sure about the definition of "pseudonyms" but the latest `foundation/dco-guidelines.md` seems to allow using pseudonyms while `toc/FAQ.md` prohibits that.
Any chance to get `toc/FAQ.md` updated for consistency and clarity?

#### `foundation/dco-guidelines.md`: `DCO and Real Names`
https://github.com/cncf/foundation/blob/e0060f51/dco-guidelines.md

>The DCO requires the use of a real name that can be used to identify someone in case there is an issue about a contribution they made. 
>
>**A real name does not require a legal name, nor a birth name, nor any name that appears on an official ID (e.g. a passport). Your real name is the name you convey to people in the community for them to use to identify you as you. The key concern is that your identification is sufficient enough to contact you if an issue were to arise in the future about your contribution.**
>
>Your real name should not be an anonymous id or false name that misrepresents who you are.

#### `toc/FAQ.md`: `Do I have to use my real name when contributing via DCO/CLA?`
https://github.com/cncf/toc/blob/cd39aa602/FAQ.md#do-i-have-to-use-my-real-name-when-contributing-via-dcocla

>Yes, no pseudonyms or anonymous contributions. The CNCF follows the same tried and true policy in the Linux Kernel and other LF projects. They have proven strong enough to defend the Linux kernel against legal attacks to date
>
>* https://github.com/torvalds/linux/blob/master/Documentation/process/submitting-patches.rst#developers-certificate-of-origin-11

**Comment by amye** [comment]
It's probably best to just link to the /foundation repo, keeps information in one place.

**Comment by caniszczyk** [comment]
fixed https://github.com/cncf/toc/commit/aac8c46d5d397637c84036be0a14448b60735de0
