### ISSUE TITLE
[SANDBOX PROJECT ONBOARDING] Kured

### ISSUE THREAD

**Issue by amye** [cncf/toc#922]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project.
We would like to complete onboarding within one month of acceptance.

From the project side, please ensure that you:

- [x] Understand the project proposal process and reqs: <https://github.com/cncf/toc/blob/main/process/project_proposals.md#introduction>
- [x] Understand the services available for your project at CNCF <https://www.cncf.io/services-for-projects/>
- [x] Ensure your project meets the CNCF IP Policy: <https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy>
- [x] Review the online programs guidelines: <https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md>
- [x] Understand the trademark guidelines: <https://www.linuxfoundation.org/en/trademark-usage/>
- [x] Understand the license allowlist: <https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist>
- [x] Is your project working on written, open governance? see <https://contribute.cncf.io/maintainers/governance/>
- [x] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? (see <https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another> for more details)
- [x] Is your project in its own separate neutral github organization?
- [x] Submitted a Pull request to add your project as a sandbox project to <https://landscape.cncf.io>
- [x] Create maintainer list + add to aggregated <https://maintainers.cncf.io> list by submitting a PR to it
- [x] Have added your project to <https://github.com/cncf/contribute>
- [x] Artwork: Submit a pull request to <https://github.com/cncf/artwork> with your artwork
- [x] Domain: transfer domain to the CNCF - <https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63>

Things that CNCF will need from the project:

- [x] Provide emails for the maintainers added to <https://maintainers.cncf.io> in order to get access to the maintainers mailing list and ServiceDesk
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF - <https://github.com/cncf/foundation/tree/master/agreements> has agreements
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [x] GitHub: ensure that hat the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines to the README file of your project on GitHub).
- [x] Website: Analytics transferred to projects@cncf.io
- [x] CII: Start on a CII best practices badge <https://bestpractices.coreinfrastructure.org/en>

Things that the CNCF will do or help the project to do:

- [x] Devstats: add to devstats <https://devstats.cncf.io/>
- [x] Insights: add to LFX Insights <https://insights.v3.lfx.linuxfoundation.org/>
- [x] Marketing: update relevant intro + slide decks
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read <https://www.cncf.io/services-for-projects/>
- [x] CNCF Welcome Email Sent to confirm maintainer list access, welcome email has monthly project sync details
- [x] Create space for meetings/events on <https://community.cncf.io>, e.g., <https://community.cncf.io/pravega-community/> - (<https://github.com/cncf/communitygroups/blob/main/README.md#cncf-projects>)
- [x] Adopt a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/)

**Comment by dholbach** [comment]
- [x] CNCF Slack channel is created and advertised in our main README - we will keep the old channel around for some time to transition
- [x] Maintainers added to `maintainer.cncf.io`
- [x] PR against `cncf/artwork` is filed
- [x] GitHub org `kubereboot` (`kured` was already taken) is created and has Chris A and `linuxfoundation` as owners
- [x] Ticket to create `kubereboot` Docker Hub org is filed: CNCFSD-1405
- [x] N/A: no domain for a website yet
- [x] Emails of project maintainers have been submitted to Service Desk: CNCFSD-1405
- [ ] Move to independent `kubereboot` org is in progress, cf weaveworks/kured#633

**Comment by lukaszgryglicki** [comment]
DevStats [page](https://kured.devstats.cncf.io) added.

**Comment by dholbach** [comment]
Everything aside from CNCF Landscape (need to find somebody to create SVG for us) and governance guidelines (TBD at our next meetings(s)) should be done or N/A.

ServiceDesk request to add everyone to ServiceDesk is CNCFSD-1404.

**Comment by dholbach** [comment]
We are all on ServiceDesk now. We are using 1password, we moved our meeting videos to a shared youtube brand account. And will look into building a website next.

So even if while some things are still WIP, we feel we are very well onboarded already. :-)

**Comment by dholbach** [comment]
Website is up at https://kured.dev, we are on the landscape and governance has just been merged as well.

**Comment by dholbach** [comment]
AFAICT We are done with all the things!

**Comment by dholbach** [comment]
> Have you transferred any trademark and logo assets to the LF? If you don't have any, there is an agreement that also needs to be signed located here: https://github.com/cncf/foundation/tree/master/agreements

@evrardjp @ckotzbauer @jackfrancis Do you remember anything we did here?

**Comment by jackfrancis** [comment]
@dholbach does kured have any trademarks or logos associated with the project?

**Comment by dholbach** [comment]
We got all our logos added to https://github.com/cncf/artwork/blob/master/examples/sandbox.md#kured-logos (some done by CNCF Designers) but there are no trademarks in the kured project.

Do you remember if we ever signed any document?

**Comment by jackfrancis** [comment]
I don't recall adding my signature to any doc. Lemme know if I can help.

**Comment by amye** [comment]
For trademarks, you'll want to review https://github.com/cncf/foundation/tree/master/agreements
There are two agreements, one for registered and one for non-registered trademarks.
It's likely that you don't have a registered trademark, but https://docs.google.com/spreadsheets/d/1Nnh_usr0tSZxaUpxTusqeIqKxMmvuEViRkyO9e_Do40/edit#gid=1136111842 has your application data for who submitted this. 
Usually, someone from the submitting organization can sign for this.

**Comment by dholbach** [comment]
There are no registered trademarks. 

@monadic Do you know who could help us get https://github.com/cncf/foundation/blob/main/agreements/CNCF%20Trademark%20and%20Account%20Assignment%20Agreement%20(2020%20-%20no%20reg%20trademarks).pdf signed for the transfer of Kured?

**Comment by krook** [comment]
[Added to LFX Insights](https://insights.lfx.linuxfoundation.org/foundation/cncf/overview?project=kured)

- [Insights documentation](https://docs.linuxfoundation.org/lfx/insights/v3-beta-version-current)
- [Insights support](https://jira.linuxfoundation.org/plugins/servlet/desk/portal/4?requestGroup=54)
- [Insights feedback](https://community.lfx.dev/t/lfx-insights-v3-feedback/2430)

**Comment by dholbach** [comment]
I'm not sure how we are going to resolve the trademark situation with https://www.linkedin.com/posts/richardsonalexis_hi-everyone-i-am-very-sad-to-announce-activity-7160295096825860096-ZS67

**Comment by amye** [comment]
> I'm not sure how we are going to resolve the trademark situation with https://www.linkedin.com/posts/richardsonalexis_hi-everyone-i-am-very-sad-to-announce-activity-7160295096825860096-ZS67

We can probably work quickly on this, just let us know who to send this to.

**Comment by monadic** [comment]
There are no registered trademarks!  How can I help?   @amye feel free to email me on my gmail!

**Comment by Cmierly** [comment]
@monadic we can send the unregistered trademark agreement to your email if that works for you?

**Comment by monadic** [comment]
Yep

**Comment by dholbach** [comment]
Thanks @monadic and @Cmierly

**Comment by dholbach** [comment]
According to @monadic this is resolved now!

**Comment by evrardjp** [comment]
What are the next steps?

**Comment by dholbach** [comment]
@Cmierly @amye do you know if there is more to do?

**Comment by krook** [comment]
@Cmierly can you please reconcile the checklist with the latest updates to see if there are more steps before onboarding is complete?

**Comment by dholbach** [comment]
Can we mark this as resolved now?

**Comment by Cmierly** [comment]
Hi! Here's the ones that we absolutely need from your team/confirmation of completion:

- [ ] Is your project in its own separate neutral github organization?

- [ ] GitHub: ensure DCO or CLA are enabled for all GitHub repositories of the project
- [ ] GitHub: ensure that hat the CNCF Code of Conduct (or your adopted version of it) are explicitly referenced at the project's README on GitHub

- [ ]  Website: Analytics transferred to projects@cncf.io
- [ ] CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en

**Comment by dholbach** [comment]
>     * [ ]  Is your project in its own separate neutral github organization?

All code, docs, website, charts have been under https://github.com/kubereboot since September '22


>     * [ ]  GitHub: ensure DCO or CLA are enabled for all GitHub repositories of the project

Same


>     * [ ]  GitHub: ensure that hat the CNCF Code of Conduct (or your adopted version of it) are explicitly referenced at the project's README on GitHub

Same

>     * [ ]   Website: Analytics transferred to [projects@cncf.io](mailto:projects@cncf.io)

Our website does not use Analytics.


>     * [ ]  CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en

We started work on https://www.bestpractices.dev/en/projects/8867


> we also need to get you added to FOSSA or Snyk

We do use FOSSA.


Thanks.

**Comment by dholbach** [comment]
@evrardjp @ckotzbauer @jackfrancis Can you confirm?

**Comment by ckotzbauer** [comment]
Confirm!

**Comment by krook** [comment]
@Cmierly @idvoretskyi  I updated the checklist at the top. Looks like this one is now complete?

**Comment by Cmierly** [comment]
Kured is now fully on boarded!
