### ISSUE TITLE
[INCUBATING PROJECT ONBOARDING] Istio

### ISSUE THREAD

**Issue by amye** [cncf/toc#935]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project.
We would like to complete onboarding within one month of acceptance.

From the project side, please ensure that you:

- [x] Understand the project proposal process and reqs: <https://github.com/cncf/toc/blob/main/process/project_proposals.md#introduction>
- [x] Understand the services available for your project at CNCF <https://www.cncf.io/services-for-projects/>
- [x] Ensure your project meets the CNCF IP Policy: <https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy>
- [x] Review the online programs guidelines: <https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md>
- [x] Understand the trademark guidelines: <https://www.linuxfoundation.org/en/trademark-usage/>
- [x] Understand the license allowlist: <https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist>
- [x] Is your project working on written, open governance? see <https://contribute.cncf.io/maintainers/governance/>
- [x] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? (see <https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another> for more details)
- [x] Is your project in its own separate neutral github organization?
- [x] Submitted a Pull request to add your project as a sandbox project to <https://landscape.cncf.io>
- [x] Create maintainer list + add to aggregated <https://maintainers.cncf.io> list by submitting a PR to it
- [x] Have added your project to <https://github.com/cncf/contribute>
- [x] Artwork: Submit a pull request to <https://github.com/cncf/artwork> with your artwork
- [x] Domain: transfer domain to the CNCF - <https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63>

Things that CNCF will need from the project:

- [x] Provide emails for the maintainers added to <https://maintainers.cncf.io> in order to get access to the maintainers mailing list and ServiceDesk
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF - <https://github.com/cncf/foundation/tree/master/agreements> has agreements
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [x] GitHub: ensure that hat the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines to the README file of your project on GitHub).
- [ ] Website: Analytics transferred to projects@cncf.io
- [x] CII: Start on a CII best practices badge <https://bestpractices.coreinfrastructure.org/en>

Things that the CNCF will do or help the project to do:

- [x] Devstats: add to devstats <https://devstats.cncf.io/>
- [x] Marketing: update relevant intro + slide decks
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read <https://www.cncf.io/services-for-projects/>
- [x] CNCF Welcome Email Sent to confirm maintainer list access, welcome email has monthly project sync details
- [x] Create space for meetings/events on <https://community.cncf.io>, e.g., <https://community.cncf.io/pravega-community/> - (<https://github.com/cncf/communitygroups/blob/main/README.md#cncf-projects>)
- [x] Adopt a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/)

**Comment by amye** [comment]
@craigbox - maintainers emails are the biggest thing to help here!

**Comment by craigbox** [comment]
Who does one normally list as a maintainer? We have ~87 listed [here](https://eng.istio.io/maintainers). Kubernetes seems to only have listed its Steering members.

**Comment by amye** [comment]
Correct, these are the people who should be added to your maintainer list + they get voting rights in an election.

**Comment by craigbox** [comment]
...is it OK to have 87 be listed for voting purposes? Not all will need service desk access.

**Comment by amye** [comment]
No, establishing a steering committee is probably your best move.

**Comment by dims** [comment]
LOL no to 87 :)

**Comment by lukaszgryglicki** [comment]
DevStats [page](https://istio.devstats.cncf.io) added.

**Comment by lukaszgryglicki** [comment]
Added [Istio](https://istio.devstats.cncf.io) DevStats instance, and added Istion in [All CNCF](https://all.devstats.cncf.io) - those are [Project Health](https://all.devstats.cncf.io/d/54/project-health-table?orgId=1&var-repogroup_name=Istio) & [Projects Health](https://all.devstats.cncf.io/d/53/projects-health-table?orgId=1) dashboards that include Istio.

**Comment by craigbox** [comment]
Some I can tick off immediately; feel free to give me access to edit the first page if you prefer.

> * [X]  Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.md#introduction
> * [X]  Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
> * [X]  Is your project working on written, open governance? see https://contribute.cncf.io/maintainers/governance/
> * [X]  Is your project in its own separate neutral github organization?
> * [X]  Submitted a Pull request to add your project to https://landscape.cncf.io
> * [X]  Provide emails for the maintainers added to https://maintainers.cncf.io in order to get access to the maintainers mailing list and ServiceDesk
> * [X]  CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en

**Comment by therealmitchconnors** [comment]
Maintainer list submitted at https://github.com/cncf/foundation/pull/468

**Comment by therealmitchconnors** [comment]
FWIW, I'm struggling to clearly see what on the task list has been completed and what remains.  I don't have access to modify the checklist.  Can the access be opened, or can someone with access mark off the completed tasks?

**Comment by therealmitchconnors** [comment]
Status Update: I've hit a few snags in slack migration, and am waiting on support here: https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-1522

**Comment by kfaseela** [comment]
https://github.com/istio/istio/pull/42795

**Comment by kfaseela** [comment]
Add link to the CNCF Code of Conduct: https://github.com/istio/community/pull/944

**Comment by craigbox** [comment]
We believe this issue is ready to close. We have been maintaining our [own copy of the checklist](https://github.com/cncf/toc/issues/935#issuecomment-1273063329) which you are welcome to copy.

Remaining issues:

- The Google CLA is enabled on all repos; we have a plan to flip over to the LF CLA (largely the same process Kubernetes followed) after the next release.
- I'm told we can't add projects@cncf.io as an admin to Google Analytics since it's a group, and not a person. We're raising a service desk ticket for that.

**Comment by amye** [comment]
Best to have direct confirmation in here for items that are closed! 

Invite nwaddington@linuxfoundation.org in the alternative, projects@cncf.io is an account.

**Comment by craigbox** [comment]
Did you click the link for "own copy of the checklist?"  It's to a comment further up this thread, as we never got access to edit the actual checklist ourselves. 😊

**Comment by amye** [comment]
I'm checking in on Trademarks as it's marked above. 
FOSSA/Synk? 
Any desire for a space in community.cncf.io?

**Comment by craigbox** [comment]
We will raise a ticket for community.cncf.io at a later date, and I believe we already have a solution for linting for licenses.

**Comment by craigbox** [comment]
@amye Did you get what you needed re. trademarks?

<img width="1189" alt="Screenshot 2023-02-22 at 7 44 43 PM" src="https://user-images.githubusercontent.com/132510/220543585-8b9741d8-dd17-44b5-99c0-3e329eeabf69.png">

**Comment by amye** [comment]
> We will raise a ticket for community.cncf.io at a later date, and I believe we already have a solution for linting for licenses.

Yes, just waiting to hear on Slack.

**Comment by craigbox** [comment]
Can we leave the decisiona s "We are sticking with Istio Slack" for now , and then revisit options at a later date?

**Comment by amye** [comment]
> Can we leave the decisiona s "We are sticking with Istio Slack" for now , and then revisit options at a later date?

Sure! Did we resolve Google Analytics? projects@cncf.io is an account that can accept invites.

**Comment by craigbox** [comment]
For access to our analytics dashboard, please go to https://eng.istio.io/webanalytics.
If you see "Can't access this report", you will need to join [the istio-team-drive-access group](https://groups.google.com/g/istio-team-drive-access), which is a public group.

We can't transfer the Google Analytics account today, because it was created within Google and it can't be shared with non-Google.com addresses.  Longer term we will solve this problem — either by finding a way to transfer the account to an external domain, or by creating a brand new account and using it going forward — but we hope that this dashboard is enough to meet the requirement and close the onboarding issue!

**Comment by amye** [comment]
> For access to our analytics dashboard, please go to https://eng.istio.io/webanalytics. If you see "Can't access this report", you will need to join [the istio-team-drive-access group](https://groups.google.com/g/istio-team-drive-access), which is a public group.
> 
> We can't transfer the Google Analytics account today, because it was created within Google and it can't be shared with non-Google.com addresses. Longer term we will solve this problem — either by finding a way to transfer the account to an external domain, or by creating a brand new account and using it going forward — but we hope that this dashboard is enough to meet the requirement and close the onboarding issue!

We should likely finish this, you'll end up with incomplete project reporting without it.

**Comment by craigbox** [comment]
We will definitely finish this, but the quick method will not give us the
history we would probably like to keep. We don't want to hold up closing
this issue based on the intention to do the right thing, which is the slow
method!

(Francis is researching if a team at Google can move the account from
Google-internal to public.)

**Comment by Xunzhuo** [comment]
Hey @amye, I did not recieve any ServiceDesk invitation even if we have submitted https://github.com/cncf/foundation/pull/468#issuecomment-1334688593

Can you help a check on it?

**Comment by craigbox** [comment]
Hi @Xunzhuo; we have listed all Istio maintainers [in the CSV](https://github.com/cncf/foundation/blob/main/project-maintainers.csv) but access to the CNCF service desk is limited to Steering Committee members.  Thanks!
