### ISSUE TITLE
Ideas to Improve the CNCF TAG formation process

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/toc#936]
Hey all, I would like to take this opportunity to share some ideas that I have been thinking about while helping form the TAG Environmental Sustainability over the past few months. I believe there are some opportunities to improve the TAG formation process in the future. I hope that this will first lead to further discussion and then to improvements in the program.

I'll keep it as short as possible and get directly over to the ideas/feedback (in no particular order):

1. **Organizational Introduction to TAGs and WG**: We have discussed a lot about the outline of CNCF WG and later a CNCF TAG, especially the differences between the two. We discovered a bit late the [toc/cncf-tags.md](https://github.com/cncf/toc/blob/main/tags/cncf-tags.md) which gives a good introduction to CNCF TAGs - perhaps highlighting this more + a section that sets working groups and TAGs apart would be beneficial here. 
2. **TAG Template Repository**: We started off with a blank repository and saw ourselves coping a lot of structure and files over from other TAGs. During this process, we also started to discuss things like code of conduct and others, which we sorted out (more or less quickly) but this distracted us on our main goals. Setting up a template repository could improve this by agreeing on a best practices structure. 
3. **Roadmap for the creation of a TAG** Just a bit of structure as reference would be useful; example: `1. Bring your idea to create a TAG to the community and begin drafting a TAG proposal (see example X) - make sure this becomes a community effort 2. set up meetings to discuss the proposal and allow sufficient time for review and discussion before finalizing the proposal. 3. …`.
4. **Document lessons learned from other TAGs** Depending on the amount and quality of ‘lessons learned’ this would be helpful: example: `For TAG-X, the rule of thumb is that meetings are cancelled if there is nothing on the agenda one hour before the meeting`. 
5. **TAG Bootstrap Mentor; support from an experienced community member who has already formed a TAG**: Having a sort of referee in smaller conflicts which also shares some “wisdom” about open-source community building from time to time would have helped us in the beginning. We got a ToC liaison a little later because we became an WG first and then a TAG; so maybe this problem would not happen again. But maybe this could be another role (reduce ToC load)?

cc @erinaboyd @dims (+ I will share this in the Environmental Sustainability Slack group to get more feedback)

**Comment by cdeliaRH** [comment]
Thanks for sharing this @leonardpahlke. Let's add to our agenda for discussion during next meeting on Wed Oct 5.

**Comment by TheFoxAtWork** [comment]
@leonardpahlke would you be amenable to closing this issue in favor of the more robust and action-oriented outline? We wont lose the content from this issue since it is mentioned in the new one and can be linked as a source reference for final deliverables. I want to ensure individuals interested in this are focused on the actionable issue.
