### ISSUE TITLE
Kuberhealthy as a sandbox CNCF project

### ISSUE THREAD

**Issue by integrii** [cncf/toc#94]
Hey guys,

I have a tool that I would like to see become a Kubernetes sandbox project, but I am not sure exactly where to pitch it.  Currently, the code lives within the corporation I work for, but we are looking to open source it (and hand the rights to the name over to the CNCF).  The corporation is a member of the CNCF.

The project is still immature and likely should be considered alpha, but it is used in production by our team and should soon have a beta version.

Project Description:

Kuberhealthy is a monitoring system for Kubernetes that exposes an endpoint that indicates cluster health.  Cluster health is determined through several synthetic checks, such as:

- Deploying and tearing down a daemonset
- Checking if pods are restarting too often
- Checking if all workloads in the kube-system namespace are healthy

This project was born from the need to monitor production Kubernetes clusters better.  Metrics and status checks are often not enough to guarantee that a deployment or rolling update can occur properly.  Over time, more checks will be added to Kuberhealthy in a modular and tunable way so that the tool is an easy and generic drop-in for any Kubernetes cluster.

Thanks for any information you can provide!

**Comment by caniszczyk** [comment]
@integrii I'll get back you in a week or so, the sandbox process isn't approved yet but will be soon

I'd advise you to open source the code first under ALv2 under your corporate open source home first before bringing it into CNCF. I'd also advise you to present to the kubernetes community first too which you can sign up here: https://docs.google.com/document/d/1VQDIAB0OqiSjIHI8AWMvSdceWhnz56jNpZrLs6o7NJY/edit#heading=h.en8cy6hno0c6

**Comment by twilfong** [comment]
It sounds like this may be the right approach. @integrii and I could get this open sourced under a different name at our corporate open source home, then potentially rename and migrate to CNCF sandbox if we make it though the approval process.

**Comment by integrii** [comment]
I've requested a presentation slot for 3/8 (this week)

**Comment by integrii** [comment]
I will be doing a quick presentation on Kuberhealthy in the community meeting on the 15th of this month.

**Comment by caniszczyk** [comment]
closing this, please come back with a request once the project has been open sourced

**Comment by integrii** [comment]
Hey @caniszczyk - Kuberhealthy is now open sourced and gaining traction!  Is it possible to look at getting Kuberhealthy into the CNCF incubator program?

**Comment by ant31** [comment]
This project seems to have a small scope and would probably better fit into the kubernetes community.  Have you presented it to the sig-instrumentation from kubernetes  ?

**Comment by integrii** [comment]
We did awhile back, and I agree that is a better fit.  I will revisit that path.

Thanks for your feedback on the project!
