### ISSUE TITLE
Sustainable Sandbox and project maturity growth 

### ISSUE THREAD

**Issue by TheFoxAtWork** [cncf/toc#961]
This issue is to capture some initial discussion items from the TOC and TAGs and invite the community to comment and provide additional suggestions, improvements based on their experience.

**Problem:**
Sandbox is a rapidly growing cluster of early maturity projects in the ecosystem. When Sandbox was initiated, one core element  was to provide an experimental, vendor neutral area to determine the viability of a project in the ecosystem. Projects within the sandbox are reasonably expected to move onto incubation and eventually graduation or to have been determined as not viable due to lack of market interest, low/no progress, etc. either of these is perfectly natural and acceptable outcome. Currently the TOC's only documented check-in with sandbox projects after acceptance is through the annual reviews. Our sandbox process does not introduce milestones to guide projects to maturity or to evaluate their maturity progress.

The TAGs are often called upon to assist the TOC in posturing projects for success. This may include and is not limited to a review of the project (which varies from TAG to TAG), a presentation (with no clearly defined end goal by the TOC to the project or TAG as to why), or a discussion without a define return value to the TOC. Previously, TAGS (then SIGs) were heavily relied upon but there was significant variance from TAG to TAG on the depth and nature of review/support projects received.

**Goal:**
Assist sandbox projects to incubation, define an exit path for non-viable sandbox projects, create more meaningful engagements with TAGs, provide consistent or well-defined expectations for TAG/Project interactions at sandbox.

**Ideas from the discussion for improving this (in no order):**
* _Define Sandbox exit criteria_ - this should be criteria that determine a sandbox project is no longer viable in the sandbox and is not expected to move to incubation. What kinds of criteria should there be if any? A missed Annual Review, perhaps two? what characteristics define an unhealthy sandbox project? When is it no longer experimental? What is the likelihood the project can graduate and how could that be measured given the information we have about a project? How is this different from archive?
* _Project progress map_ - A map of key points projects should undertake if they are not meeting expected milestones on the path to incubation. What should this look like to first evaluate projects as "inbetween" incubation and exit but not making progress in one direction or the other? and then what are the actions to bring projects back onto a path toward incubation, to set them up to hit maturity milestones? How long can projects expect to be following a map before re-evaluated?
* _Milestones to incubation_ - What milestones may be defined to provide sandbox projects a clearer path to incubation? Should milestones be cumulative - building upon each other? Should some be parallel? If so what are these? Should we consider a listing of milestones knowing that not all milestones apply to all projects? What is the minimum core set that describes fundamental success regardless of the nature of a project?
  * Would milestones better assist TAGs in supporting projects consistently? Are there certain TAGs or TAG functions that apply across all projects regardless of domain that should be considered as a fundamental milestone? 

This issue is related to #907 .

**Comment by TheFoxAtWork** [comment]
related: https://github.com/cncf/toc/pull/997

**Comment by leecalcote** [comment]
Addressed by https://github.com/cncf/toc/pull/997

**Comment by TheFoxAtWork** [comment]
Per discussion on today's TOC/TAG Call here is a google doc of the primary changes for better discussion/facilitation of this Issue and its PR: https://docs.google.com/document/d/1aL0mxInyz-qtRT2QM7kdr9riM36uihILtgM4TR35cPQ/edit?usp=sharing
