### ISSUE TITLE
Add a formal Govenance review to Graduating DD

### ISSUE THREAD

**Issue by jberkus** [cncf/toc#963]
TOC,

One of the requirements for a project reaching graduated is for it to be employer-neutral.  As such, the Governance WG of TAG-Contributor-Strategy frequently gets asked either by the TOC or by a project lead, informally, to review project governance.  

Given this, it would make sense to simply add a statutory requirement that all Graduated applications need to include a review and signoff from TAG-Contributor Strategy that the project has open and neutral governance.  This would be similar to the security review that TAG-Security does.  Since this is something we're already informally doing, TAG-CS can staff this.

**Comment by RichiH** [comment]
I won't be able to make today's call. Sounds good to me, though.

**Comment by cathyhongzhang** [comment]
Looks good to me.

**Comment by jberkus** [comment]
@mattfarina have you taken a look at the governance documentation we already have at contribute.cncf.io?  What do you feel is missing?  We have one template document that's still pending ... what else do we need?

**Comment by ahrkrak** [comment]
@xmulligan I would suggest there should be reviews at both incubation and graduated, reflecting the different expectations for each level. My reading (admittedly somewhat between the lines in places) is that for incubation there should be solid governance process in place, but a project can still be de facto controlled by a single vendor, e.g. the majority of maintainers come from one company; whereas, for graduation, you should be in a position where any single vendor could drop out, but the project itself would continue (I am not sure all currently graduated projects would pass that test).

**Comment by angellk** [comment]
Thanks @xmulligan - the new graduation/incubation templates do capture this - DD's can be augmented by TAG C-S reviews as the TAG has resources and TOC reviewers request further governance review.
