### ISSUE TITLE
[SANDBOX PROJECT ONBOARDING] Merbridge

### ISSUE THREAD

**Issue by amye** [cncf/toc#969]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project.
We would like to complete onboarding within one month of acceptance.

From the project side, please ensure that you:

- [x] Understand the project proposal process and reqs: <https://github.com/cncf/toc/blob/main/process/project_proposals.md#introduction>
- [x] Understand the services available for your project at CNCF <https://www.cncf.io/services-for-projects/>
- [x] Ensure your project meets the CNCF IP Policy: <https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy>
- [x] Review the online programs guidelines: <https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md>
- [x] Understand the trademark guidelines: <https://www.linuxfoundation.org/en/trademark-usage/>
- [x] Understand the license allowlist: <https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist>
- [x] Is your project working on written, open governance? see <https://contribute.cncf.io/maintainers/governance/>
- [x] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? (see <https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another> for more details)
- [x] Is your project in its own separate neutral github organization?
- [x] Submitted a Pull request to add your project as a sandbox project to <https://landscape.cncf.io>
- [x] Create maintainer list + add to aggregated <https://maintainers.cncf.io> list by submitting a PR to it
- [x] Have added your project to <https://github.com/cncf/contribute>
- [x] Artwork: Submit a pull request to <https://github.com/cncf/artwork> with your artwork
- [x] Domain: transfer domain to the CNCF - <https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63>

Things that CNCF will need from the project:

- [x] Provide emails for the maintainers added to <https://maintainers.cncf.io> in order to get access to the maintainers mailing list and ServiceDesk
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF - <https://github.com/cncf/foundation/tree/master/agreements> has agreements
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [x] GitHub: ensure that hat the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines to the README file of your project on GitHub).
- [x] Website: Analytics transferred to projects@cncf.io
- [x] CII: Start on a CII best practices badge <https://bestpractices.coreinfrastructure.org/en>

Things that the CNCF will do or help the project to do:

- [x] Devstats: add to devstats <https://devstats.cncf.io/>
- [x] Insights: add to LFX Insights <https://insights.v3.lfx.linuxfoundation.org/>
- [x] Marketing: update relevant intro + slide decks
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read <https://www.cncf.io/services-for-projects/>
- [x] CNCF Welcome Email Sent to confirm maintainer list access, welcome email has monthly project sync details
- [x] Create space for meetings/events on <https://community.cncf.io>, e.g., <https://community.cncf.io/pravega-community/> - (<https://github.com/cncf/communitygroups/blob/main/README.md#cncf-projects>)
- [x] Adopt a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/)

**Comment by lukaszgryglicki** [comment]
DevStats page [added](https://merbridge.devstats.cncf.io).

**Comment by kebe7jun** [comment]
- [X] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.md#introduction
- [X] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [ ] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [X] Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
- [X Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/
- [X] Understand the license allowlist: https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist
- [ ] Is your project working on written, open governance? see https://contribute.cncf.io/maintainers/governance/
- [ ] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? (see https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another for more details)
- [X] Is your project in its own separate neutral github organization?
- [X] Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io/
- [X] Create maintainer list + add to aggregated https://maintainers.cncf.io/ list by submitting a PR to it
- [ ] Have added your project to https://github.com/cncf/contribute
- [X] Artwork: Submit a pull request to https://github.com/cncf/artwork with your artwork
- [ ] Domain: transfer domain to the CNCF - https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63

**Comment by kebe7jun** [comment]
Same doubts as https://github.com/cncf/toc/issues/973#issuecomment-1369357341, can you guide me?

**Comment by amye** [comment]
Biggest next thing: getting emails to us so that we can add you to the maintainers email lists and servicedesk
Domains: You can set me as the LF contact, amye@linuxfoundation.org is fine

**Comment by kebe7jun** [comment]
> Biggest next thing: getting emails to us so that we can add you to the maintainers email lists and servicedesk Domains: You can set me as the LF contact, [amye@linuxfoundation.org](mailto:amye@linuxfoundation.org) is fine

@amye  Maintainers' email list is here: https://github.com/merbridge/merbridge/blob/main/MAINTAINERS.md
Is this ok?

**Comment by kebe7jun** [comment]
> 

@amye is this ok?

**Comment by kebe7jun** [comment]
@amye My side of things should be almost finished, how can I cooperate with you next?

**Comment by Xunzhuo** [comment]
Hey @amye: 
<img width="568" alt="image" src="https://user-images.githubusercontent.com/48784001/225947729-b95a88a7-af55-4e2b-a638-80bc1a0eb05c.png">

Can I get some help to reinvite me for timeout expired?

**Comment by amye** [comment]
Ah, I see this: 
Trademarks: transfer any trademark and logo mark assets over to the LF -https://github.com/cncf/foundation/tree/master/agreements has agreements 

You'll want to use the 'nonregistered trademarks' if you haven't filed.

**Comment by kebe7jun** [comment]
> Ah, I see this: Trademarks: transfer any trademark and logo mark assets over to the LF -https://github.com/cncf/foundation/tree/master/agreements has agreements
> 
> You'll want to use the 'nonregistered trademarks' if you haven't filed.

Hi, @amye  sorry to bother you, but now that Merbridge has applied for a trademark in China and has obtained it, how do we fill out the trademark agreement and get it to you?

I'm sorry I didn't find similar instructions for the process.

**Comment by amye** [comment]
> > Ah, I see this: Trademarks: transfer any trademark and logo mark assets over to the LF -https://github.com/cncf/foundation/tree/master/agreements has agreements
> > You'll want to use the 'nonregistered trademarks' if you haven't filed.
> 
> Hi, @amye sorry to bother you, but now that Merbridge has applied for a trademark in China and has obtained it, how do we fill out the trademark agreement and get it to you?
> 
> I'm sorry I didn't find similar instructions for the process.

Oh cool! We've got a registered trademark agreement in that folder! How neat!

**Comment by kebe7jun** [comment]
Hi @amye , trademark transfer agreement has sent to you~

**Comment by amye** [comment]
Marking trademarks off, one thing that would be helpful: 
Provide emails for the maintainers added to https://maintainers.cncf.io/ in order to get access to the maintainers mailing list and ServiceDesk

**Comment by kebe7jun** [comment]
Mail list:

Kebe Liu | kebe7jun | mail@kebe7jun.com
-- | -- | --
Wenqing Dai | dddddai | dddwq@foxmail.com
Xunzhuo Liu | Xunzhuo | mixdeers@gmail.com
Xiaopeng Han | hanxiaop | hanxiaop8@outlook.com
Bart Smykla | bartsmykla |  
Kay Yan | yankay | kay.yan@daocloud.io
Michael Yao | windsonsea | haifeng.yao@daocloud.io
Nicole Li | nicole-lihui | nicole.li@daocloud.io


> Marking trademarks off, one thing that would be helpful: Provide emails for the maintainers added to https://maintainers.cncf.io/ in order to get access to the maintainers mailing list and ServiceDesk

**Comment by kebe7jun** [comment]
> Hi @kebe7jun ! My name is Crystal and I am the new project coordinator in charge of onboarding sandbox projects!
> 
> Have you and your team had the chance to review/complete any tasks? There are only a few left to go and I would be more than happy to help in any way I can! If you have any questions or concerns, please don't hesitate to reach out!

Hi @Cmierly ,

Thank you very much for helping us complete the remaining tasks.

For `Ensure your project meets the CNCF IP Policy`, I believe we have already done it. I don't know why it hasn't been completed?
For `Domain: transfer domain to the CNCF`,  I have already transferred the domain to CNCF.
For `Adopt a license scanning tool `, we have added: https://app.fossa.com/projects/git%2Bgithub.com%2Fmerbridge%2Fmerbridge?ref=badge_shield

**Comment by krook** [comment]
[Added to LFX Insights](https://insights.lfx.linuxfoundation.org/foundation/cncf/overview?project=merbridge)

- [Insights documentation](https://docs.linuxfoundation.org/lfx/insights/v3-beta-version-current)
- [Insights support](https://jira.linuxfoundation.org/plugins/servlet/desk/portal/4?requestGroup=54)
- [Insights feedback](https://community.lfx.dev/t/lfx-insights-v3-feedback/2430)

**Comment by vielmetti** [comment]
Merbridge progress has slowed considerably since going into the sandbox, with the last commit registered at https://landscape.cncf.io/?selected=merbridge&item=orchestration-management--service-mesh--merbridge in October 2023.

**Comment by kebe7jun** [comment]
> Merbridge progress has slowed considerably since going into the sandbox, with the last commit registered at https://landscape.cncf.io/?selected=merbridge&item=orchestration-management--service-mesh--merbridge in October 2023.

Most of the tasks I have completed, can you guide me through what needs to be done next? Thanks.

**Comment by amye** [comment]
I see slack as currently outstanding, I see governance, I can check on if we've got your emails (I'm pretty sure we do), and do you have any analytics?

**Comment by kebe7jun** [comment]
slack channel https://cloud-native.slack.com/archives/C04GGRWLDLG
The email address has already been sent in October 2023.

**Comment by windsonsea** [comment]
Hi @Cmierly, just wanted to confirm the remaining two tasks:
 
- [x] Is your project working on written, open governance? see https://contribute.cncf.io/maintainers/governance/
  Yes, Merbridge has its [open governance policy](https://github.com/merbridge/merbridge/blob/main/governance.md) now.
- [x] Website: Analytics transferred to [projects@cncf.io](mailto:projects@cncf.io)
  [merbridge.io](https://merbridge.io/) does not currently have any analytics in place.

**Comment by Cmierly** [comment]
Thank y ou for the update, @windsonsea !
Merbridge is now done with onboarding! Congratulations!
