### ISSUE TITLE
[SANDBOX PROJECT ONBOARDING] Carina

### ISSUE THREAD

**Issue by amye** [cncf/toc#974]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project.
We would like to complete onboarding within one month of acceptance.

From the project side, please ensure that you:

- [x] #1346
- [x] Understand the services available for your project at CNCF <https://www.cncf.io/services-for-projects/>
- [x] Ensure your project meets the CNCF IP Policy: <https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy>
- [x] Review the online programs guidelines: <https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md>
- [x] Understand the trademark guidelines: <https://www.linuxfoundation.org/en/trademark-usage/>
- [x] Understand the license allowlist: <https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist>
- [x] Is your project working on written, open governance? see <https://contribute.cncf.io/maintainers/governance/>
- [x] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? (see <https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another> for more details)
- [x] Is your project in its own separate neutral github organization?
- [x] Submitted a Pull request to add your project as a sandbox project to <https://landscape.cncf.io>
- [x] Create maintainer list + add to aggregated <https://maintainers.cncf.io> list by submitting a PR to it
- [x] Have added your project to <https://github.com/cncf/contribute>
- [x] Artwork: Submit a pull request to <https://github.com/cncf/artwork> with your artwork
- [x] Domain: transfer domain to the CNCF - <https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63>

Things that CNCF will need from the project:

- [x] Provide emails for the maintainers added to <https://maintainers.cncf.io> in order to get access to the maintainers mailing list and ServiceDesk
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF - <https://github.com/cncf/foundation/tree/master/agreements> has agreements
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [x] GitHub: ensure that hat the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines to the README file of your project on GitHub).
- [x] Website: Analytics transferred to projects@cncf.io
- [x] CII: Start on a CII best practices badge <https://bestpractices.coreinfrastructure.org/en>

Things that the CNCF will do or help the project to do:

- [x] Devstats: add to devstats <https://devstats.cncf.io/>
- [x] Insights: add to LFX Insights <https://insights.v3.lfx.linuxfoundation.org/>
- [x] Marketing: update relevant intro + slide decks
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read <https://www.cncf.io/services-for-projects/>
- [x] CNCF Welcome Email Sent to confirm maintainer list access, welcome email has monthly project sync details
- [x] Create space for meetings/events on <https://community.cncf.io>, e.g., <https://community.cncf.io/pravega-community/> - (<https://github.com/cncf/communitygroups/blob/main/README.md#cncf-projects>)
- [x] Adopt a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/)

**Comment by lukaszgryglicki** [comment]
DevStats page [added](https://carina.devstats.cncf.io).

**Comment by hwdef** [comment]
@caniszczyk @thelinuxfoundation 

Hello, we have invited you to enter the carina-io organization, please check your email.

**Comment by hwdef** [comment]
@amye 
Hi, we don't currently have a slack channel, Can a Carina slack channel be created directly in CNCF slack?

**Comment by hwdef** [comment]
@amye Do you know how to enable CLA checking bot?

**Comment by amye** [comment]
> @amye Do you know how to enable CLA checking bot?


> @amye Hi, we don't currently have a slack channel, Can a Carina slack channel be created directly in CNCF slack?

You should be able to make one yourself, I don't believe it's locked down.

**Comment by amye** [comment]
> @amye Do you know how to enable CLA checking bot?



> @amye Do you know how to enable CLA checking bot?

You'll want to choose between Synk or FOSSA, we'll be able to help with this in January.

**Comment by hwdef** [comment]
> > @amye Hi, we don't currently have a slack channel, Can a Carina slack channel be created directly in CNCF slack?
> 
> You should be able to make one yourself, I don't believe it's locked down.

ok, I will create a channel for carina , and transfer it to cncf

**Comment by hwdef** [comment]
@amye 
Hey, I have submitted an application to transfer the carina domain name to cncf on the [website]( https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63)
The serial number is IT-24998

**Comment by hwdef** [comment]
@amye 
I have sent you the trademark assignment letter of carina by email.

**Comment by hwdef** [comment]
I create a channel for Carina in CNCF slack

https://cloud-native.slack.com/archives/C04H2EXP801

**Comment by hwdef** [comment]
>  CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en

I've tried many times, but every time I submit, I get this error

![image](https://user-images.githubusercontent.com/13084946/211699146-8c1e392f-8bdb-4aa5-8612-eced4d908b56.png)

**Comment by amye** [comment]
Trademarks marked as complete!

**Comment by hwdef** [comment]
Carina official website has added LF footer.
http://www.opencarina.com/

**Comment by hwdef** [comment]
@amye 
Hi, I think all the work we need to do has been done. is there anything else we need to add.

**Comment by amye** [comment]
Just two things! 
(1) GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project 
and 
(2) do you want a space on community.cncf.io?

**Comment by hwdef** [comment]
I have enabled DCO for carina repositories, but I don't understand how to enable CLA for repo.can you give me some guidance.
Yes, I want a space on community.cncf.io

**Comment by amye** [comment]
> I have enabled DCO for carina repositories, but I don't understand how to enable CLA for repo.can you give me some guidance. Yes, I want a space on community.cncf.io

Only one is needed! 
We can create a space for you on community.cncf.io

**Comment by hwdef** [comment]
> Only one is needed!

Thank you! I see.

**Comment by hwdef** [comment]
@amye 
![image](https://user-images.githubusercontent.com/13084946/219308863-0ce43948-a5a5-4548-a7cb-79053986ec03.png)

I already enable DCO for all repositories in carina org

**Comment by amye** [comment]
> > I have enabled DCO for carina repositories, but I don't understand how to enable CLA for repo.can you give me some guidance. Yes, I want a space on community.cncf.io
> 
> Only one is needed! We can create a space for you on community.cncf.io

Let me know who to invite to manage that space!

**Comment by hwdef** [comment]
@zhangzhenhua @antmoveh and me

**Comment by hwdef** [comment]
@amye 
Hi, I saw a domain name transfer request in the background of the domain name management website, but the request failed. Is this operated by cncf?

**Comment by amye** [comment]
> @amye Hi, I saw a domain name transfer request in the background of the domain name management website, but the request failed. Is this operated by cncf?

LFIT handles that, you should work with them through https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63

**Comment by hwdef** [comment]
I think I've filled out this form.

https://github.com/cncf/toc/issues/974#issuecomment-1364822467

**Comment by hwdef** [comment]
Sorry, the information I just provided is wrong, the domain name has been transferred out

**Comment by hwdef** [comment]
@Cmierly 
Thank you for your response, I would like to know what else I need to do in order to complete the last two tasks.

**Comment by hwdef** [comment]
I remembered that I had sent emails related to the trademarks, please check it. 
https://github.com/cncf/toc/issues/974#issuecomment-1365010021

**Comment by hwdef** [comment]
Thanks!
Is there anything else I need to do, or do I just need to wait?

**Comment by amye** [comment]
You are good! @RobertKielty will help you get a license scanning tool set up, and adding you to Insights is also pretty easy!
Nothing to do from the project side.

**Comment by krook** [comment]
> Insights: add to LFX Insights https://insights.v3.lfx.linuxfoundation.org/
> This is a new task that we will be handling on our end. Please keep an eye out for more information regarding this cool new feature!

LFX Insights provides projects with more visibility into their community dynamics around contributors, organizations, issues, and pull request metrics. It v3 uses [crowd.dev](https://www.crowd.dev/) under the hood to gather data about certain repositories in a GitHub organization.

The way it does this is through an app installed (similar to the DCO bot) at the organization level. This is then connected to one or more public repos under the organization. You can see [technical details here](https://docs.crowd.dev/docs/github-integration).

The LFX team will install it on behalf of your project using the [Linux Foundation id](https://github.com/thelinuxfoundation) GitHub id you granted access to earlier, so no action is needed on the project maintainer side. Once your project is onboarded, you'll see data flowing into the dashboards at the [LFX Insights v3 site](https://insights.v3.lfx.linuxfoundation.org/).

**Comment by hwdef** [comment]
Thank you very much!

**Comment by krook** [comment]
@hwdef can you please double check that `thelinuxfoundation` is set as an Owner of the https://github.com/carina-io organization?

**Comment by hwdef** [comment]
> @hwdef can you please double check that `thelinuxfoundation` is set as an Owner of the https://github.com/carina-io organization?

I don't think `thelinuxfoundation` is in the carina-io organization, I would invite this account. Please accept it.

<img width="996" alt="image" src="https://github.com/cncf/toc/assets/13084946/6bb15ef5-8760-4c63-8e4f-9c2384ad27de">

**Comment by krook** [comment]
[Added to LFX Insights](https://insights.lfx.linuxfoundation.org/foundation/cncf/overview?project=carina)

- [Insights documentation](https://docs.linuxfoundation.org/lfx/insights/v3-beta-version-current)
- [Insights support](https://jira.linuxfoundation.org/plugins/servlet/desk/portal/4?requestGroup=54)
- [Insights feedback](https://community.lfx.dev/t/lfx-insights-v3-feedback/2430)

**Comment by krook** [comment]
> I don't think `thelinuxfoundation` is in the carina-io organization, I would invite this account. Please accept it.

Confirmed that Carina is in our GHE instance and `thelinuxfoundation` has access.

**Comment by hwdef** [comment]
@krook Thanks for your work! I noticed that we only have one last task left. is there anything I need to do about it?

**Comment by amye** [comment]
Yes! Your last piece is "Adopt a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/)" which @RobertKielty can assist with! 
Do you have a preference?

**Comment by hwdef** [comment]
> Yes! Your last piece is "Adopt a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/)" which @RobertKielty can assist with! Do you have a preference?

I think FOSSA is better.

**Comment by RobertKielty** [comment]
I can set up both. I'll do that next week.

**Comment by RobertKielty** [comment]
The Carina Team on FOSSA has been created and I have invited a user on FOSSA using the Carina maintainer list email address. 

I have one or more steps to carry out to configure the team and I will share credentials and next steps then.

**Comment by RobertKielty** [comment]
I have sent invites out to the maintainers to join the cncf-carina-maintainers list. Please check your emails.

**Comment by hwdef** [comment]
@RobertKielty 
Thank you for everything! 
Do you know the specific email address? I checked my email and did not receive it. It may have been sent to the email addresses of other colleagues of mine

**Comment by RobertKielty** [comment]
@hwdef not sure what happened those invites to join the mailing list.

I have sent them out again just now.

Look out for cncf-carina-maintainers and lists.cncf.io

**Comment by RobertKielty** [comment]
Hi @hwdef 

The 2 invites for cncf-carina-maintainers are still pending. 

DM me on CNCF Slack if you need help accepting the invites  (we can troubleshoot the invites more easily there)

**Comment by hwdef** [comment]
@RobertKielty 
I will notify my colleagues to check their emails, thanks for the reminder

**Comment by antmoveh** [comment]
@RobertKielty 
Hello, I am the invitee. Sorry, Just now I checked my email and it seems that I have not received the invitation email. My email address is shen.ren.love@163.com

**Comment by antmoveh** [comment]
@RobertKielty 
sorry, I have been busy with other things recently. When I see the invitation email and click on it, it reminds me that the fossa invitation token has expired, please send the invitation again. I will check the email every day

**Comment by RobertKielty** [comment]
@antmoveh I will need to look in to the Slack registration issue. I will get to that next week.

I have sent you an email about FOSSA.

**Comment by antmoveh** [comment]
Ok, I have successfully logged into FOSSA using cncf-carina-maintainers@lists.cncf.io. What should I do next

**Comment by RobertKielty** [comment]
@antmoveh after logging into FOSSA you can do a Quick Import of the projects repos' that need to be license checked.

**Comment by antmoveh** [comment]
@RobertKielty 
I have imported the carina project and completed the license check

**Comment by krook** [comment]
@RobertKielty is this one fully set up for license scanning? Can we mark that complete?

**Comment by RobertKielty** [comment]
@krook @Cmierly 

The Onboarding Task list now correctly reflects that the Carina project used FOSSA to statisfy the CNCF license policy compliance scan.

Here's the latest FOSSA scan 

[carina - Projects | FOSSA](https://app.fossa.com/projects/git%2Bgithub.com%2Fcarina-io%2Fcarina/refs/branch/main/59521d1f15efeb92e4e9a30980385499c4d86171 )

And @antmoveh has added [a status badgs](https://github.com/carina-io/carina?tab=readme-ov-file#license) to the README on the carina-io/carina repo.

**Comment by Cmierly** [comment]
That's great!
Carina is now finished with onboarding!

**Comment by hwdef** [comment]
@Cmierly @RobertKielty @krook @amye 
Hi,all
I'm sorry to bother you.
I would like to know if it is possible to use github copilot provided by this organization for free. I followed the github prompts and added four members. It seemed that I successfully enabled copilot, but I didn't know who paid the bill. Can you give me an answer?

![image](https://github.com/cncf/toc/assets/13084946/d2f9e762-ca84-4d2e-b945-457a97935171)

**Comment by krook** [comment]
@hwdef Yes, these are handled in GHE. 

[The number of seats available to projects is documented in the March 2024 Maintainer Newsletter](https://contribute.cncf.io/resources/newsletters/2024-03-14-projectnewsletter/#github-copilot-availability). 

As a Sandbox project, you are good with up to 10 seats!

**Comment by hwdef** [comment]
@krook
I understand, thank you!
