### ISSUE TITLE
Provide CNCF-hosted Google workspace for DD docs

### ISSUE THREAD

**Issue by tomkerkhove** [cncf/toc#980]
As of today, when writing DD docs they are created in the person's personal workspace who starts writing the doc and it stays there forever.

However, that means that person has full control and if relationships become bad or that person passes away the document gets lost.

Are there plans to provide a CNCF-hosted Google workspace for DD docs?

**Comment by xmulligan** [comment]
+1 we can't find some docs from the Cilium Incubation DD and it would be great if there was a place to host them.

https://github.com/cncf/toc/pull/952#issuecomment-1318706847

**Comment by cathyhongzhang** [comment]
It is a valid concern. Like the idea of a CNCF-hosted place for DD docs

**Comment by angellk** [comment]
+1 fantastic idea

**Comment by tomkerkhove** [comment]
@caniszczyk What is the typical process for these kind of suggestions?

**Comment by RichiH** [comment]
There's one process I am aware of, but that's for graduated projects and needs-based. For Prometheus, we have a Google Workspace for all team members. We keep our design docs, conference planning, and public calls there. This also gives us the ability to record and have arbitrarily long public calls.

This comes with obvious cost overhead, and scaling it out to all CNCF project members down to sandbox seems unfeasible.

Maybe we can have an automation where project maintainers can request doc creation, and a doc is created in the appropriate public (or sometimes private?) GDrive structure under a role account, with the requester being made editor?

**Comment by tomkerkhove** [comment]
That is fine for me.

Just to be clear - The suggestion is only to host DD docs wrt TOC interactions, not for running the projects itself which would be massive impact as you mention.

**Comment by RichiH** [comment]
I would be concerned if we gatekeep the creation of documents on manual TOC action; it seems like a toil-intensive process. Some automation and self-checkout would be good. E.g. we could have a repo/issue tag which triggers the creation of said document.

And added benefit of triggering this through GitHub would be a public overview & paper trail of all documents created.

My medium term concern is sprawl and consistency, something also easily solved if working through e.g. GH issues.

**Comment by lizrice** [comment]
Documents could be created wherever as they are today, and moved to the CNCF workspace when the incubation / graduation process completes? IIRC changing the ownership of a doc doesn't break links to it (though I stand to be corrected on that)

**Comment by tomkerkhove** [comment]
I think that's the best approach indeed - Nice and simple

**Comment by dims** [comment]
@amye @jeefy could we please mint a new google workspace for TOC use?

We could get into the habit of copying the doc over to this shared directory for example before we send a doc for public comment period. (and send that new link out for public comment)

**Comment by RichiH** [comment]
> IIRC changing the ownership of a doc doesn't break links to it 

I just verified the worst case: Private & secret GDoc moved into the Prometheus GSuite in a public Gdrive directory. There seem to be a bunch of redirects happening, but the URL is stable in the end.

I don't know if the redirect spree will subside once the document "settles" in the new location, but that's more of academic interest than real-world impact.

**Comment by amye** [comment]
We have this now, drop a note into servicedesk if you need this. It's tied into the CNCF.io workspace.

**Comment by dims** [comment]
@amye let's make sure that toc folks have access (since they are the one sending out public comment emails https://github.com/cncf/toc/issues/980#issuecomment-1382908689)

**Comment by tomkerkhove** [comment]
Thanks for the testing @RichiH !

**Comment by amye** [comment]
Marking this one as closed, a project can drop into servicedesk and request this. 👍

**Comment by tomkerkhove** [comment]
Thanks @amye !
