### ISSUE TITLE
Project proposal: Telepresence for CNCF Sandbox

### ISSUE THREAD

**Issue by richarddli** [cncf/toc#99]
Telepresence is a developer tool for Kubernetes. Telepresence lets developers code their Kubernetes services locally, while creating a bi-direction network proxy to a remote Kubernetes cluster. This lets developers who are working on multi-service apps to get the benefits of both local development (fast feedback cycle, IDE, debugger, etc.) and cloud development (unlimited compute/network resources, realistic environment).

GitHub: https://github.com/datawire/telepresence
Website: https://www.telepresence.io
License: Apache 2.0

Alignment to CNCF:

1. Makes Kubernetes easier to use for app devs (and anyone else, really).
2. The broader CNCF/Kubernetes community is actively exploring how to improve the application developer experience. Adding more projects for the app dev is a natural evolution of these efforts.

Some public end users:

* Bitnami (https://kccnceu18.sched.com/event/Dqug -- presenting on this at KubeCon)
* Verloop (https://www.telepresence.io/case-studies/verloop)
* Sight Machine (https://www.telepresence.io/case-studies/sight-machine)

I've spoken with Brian Grant and Alexis Richardson both of whom are supportive of Sandbox.

What do we want to get out of submitting to the CNCF?

1. Expanding the contributor base (the vast majority of contributors have been Datawire-related folks). We'd love to get others to contribute.
2. Expanding the visibility of Telepresence to improve both the project and the Kubernetes app dev experience as a whole.

**Comment by caniszczyk** [comment]
Hey @richardli thanks for reaching out! (did you forget number three?)

Does April 17 work for you to present to the @cncf/toc community meeting (April 3rd will be taken for another topic I plan to announce soon)? That has to be done before we ask for TOC sponsors.

**Comment by richarddli** [comment]
Oops, that was a typo. Deleted the #3. Yes, 4/17 works.

**Comment by caniszczyk** [comment]
you're scheduled to present for 4/17
